### ISSUE TITLE
Deauth all AP in range 

### ISSUE THREAD

**Issue by doge27** [spacehuhn/esp8266_deauther#10]
There is a repo in GitHub to death all AP in range, but it is written in python. Is it possible to implement on C?

**Comment by spacehuhn** [comment]
Maybe but that's not the point of this project. Feel free to fork it.

**Comment by budwig** [comment]
You can do that with Kali linux (jam the whole WiFi router, or single devices)
https://www.youtube.com/watch?v=O6rJeqKqaJE
