### ISSUE TITLE
I keep getting an error when i try to upload to my ESP8266. (PLEASE HELP)

### ISSUE THREAD

**Issue by xwhd12** [spacehuhn/esp8266_deauther#1002]
so it says this 

Arduino: 1.8.8 (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

In file included from sketch\CLI.h:18:0,

                 from sketch\CLI.cpp:1:

DisplayUI.h:71:9: error: 'Button' does not name a type

         Button* up   = NULL;

         ^

DisplayUI.h:72:9: error: 'Button' does not name a type

         Button* down = NULL;

         ^

In file included from sketch\CLI.h:11:0,

                 from sketch\CLI.cpp:1:

A_config.h:66:26: error: 'SSD1306Wire' does not name a type

 #define DEAUTHER_DISPLAY SSD1306Wire display = SSD1306Wire(0x3c, 5, 4); // for 0.96" OLED

                          ^

sketch\DisplayUI.h:76:9: note: in expansion of macro 'DEAUTHER_DISPLAY'

         DEAUTHER_DISPLAY // see config.h

         ^

sketch\Settings.cpp: In member function 'void Settings::load()':

Settings.cpp:17:15: error: 'data' was not declared in this scope

     version = data.get<String>("version");

               ^

Settings.cpp:17:30: error: expected primary-expression before '>' token

     version = data.get<String>("version");

                              ^

Settings.cpp:20:67: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_SSID))) setSSID(data.get<String>(keyword(S_SSID)));

                                                                   ^

Settings.cpp:21:75: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_PASSWORD))) setPassword(data.get<String>(keyword(S_PASSWORD)));

                                                                           ^

Settings.cpp:22:74: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_CHANNEL))) setChannel(data.get<uint8_t>(keyword(S_CHANNEL)));

                                                                          ^

In file included from C:\Users\Leo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/Arduino.h:29:0,

                 from sketch\Settings.h:4,

                 from sketch\Settings.cpp:1:

Settings.cpp:23:65: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_HIDDEN))) setHidden(data.get<bool>(keyword(S_HIDDEN)));

                                                                 ^

Settings.cpp:24:79: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_CAPTIVEPORTAL))) setCaptivePortal(data.get<bool>(keyword(S_CAPTIVEPORTAL)));

                                                                               ^

Settings.cpp:27:67: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_LANG))) setLang(data.get<String>(keyword(S_LANG)));

                                                                   ^

In file included from C:\Users\Leo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/Arduino.h:29:0,

                 from sketch\Settings.h:4,

                 from sketch\Settings.cpp:1:

Settings.cpp:28:85: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_DISPLAYINTERFACE))) setDisplayInterface(data.get<bool>(keyword(S_DISPLAYINTERFACE)));

                                                                                     ^

Settings.cpp:29:90: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_DISPLAY_TIMEOUT))) setDisplayTimeout(data.get<uint32_t>(keyword(S_DISPLAY_TIMEOUT)));

                                                                                          ^

In file included from C:\Users\Leo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/Arduino.h:29:0,

                 from sketch\Settings.h:4,

                 from sketch\Settings.cpp:1:

Settings.cpp:30:71: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_SERIALINTERFACE))) setCLI(data.get<bool>(keyword(S_SERIALINTERFACE)));

                                                                       ^

Settings.cpp:31:74: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_SERIAL_ECHO))) setSerialEcho(data.get<bool>(keyword(S_SERIAL_ECHO)));

                                                                          ^

Settings.cpp:32:77: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_WEBINTERFACE))) setWebInterface(data.get<bool>(keyword(S_WEBINTERFACE)));

                                                                             ^

Settings.cpp:33:72: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_WEB_SPIFFS))) setWebSpiffs(data.get<bool>(keyword(S_WEB_SPIFFS)));

                                                                        ^

Settings.cpp:34:73: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_LEDENABLED))) setLedEnabled(data.get<bool>(keyword(S_LEDENABLED)));

                                                                         ^

Settings.cpp:35:69: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_MACAP))) setMacAP(data.get<String>(keyword(S_MACAP)));

                                                                     ^

Settings.cpp:36:69: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_MACST))) setMacSt(data.get<String>(keyword(S_MACST)));

                                                                     ^

Settings.cpp:39:73: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_CHTIME))) setChTime(data.get<uint16_t>(keyword(S_CHTIME)));

                                                                         ^

Settings.cpp:40:82: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_MIN_DEAUTHS))) setMinDeauths(data.get<uint16_t>(keyword(S_MIN_DEAUTHS)));

                                                                                  ^

Settings.cpp:43:87: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_ATTACKTIMEOUT))) setAttackTimeout(data.get<uint32_t>(keyword(S_ATTACKTIMEOUT)));

                                                                                       ^

Settings.cpp:44:84: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_FORCEPACKETS))) setForcePackets(data.get<uint8_t>(keyword(S_FORCEPACKETS)));

                                                                                    ^

Settings.cpp:45:93: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_DEAUTHSPERTARGET))) setDeauthsPerTarget(data.get<uint16_t>(keyword(

                                                                                             ^

Settings.cpp:48:84: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_DEAUTHREASON))) setDeauthReason(data.get<uint8_t>(keyword(S_DEAUTHREASON)));

                                                                                    ^

In file included from C:\Users\Leo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/Arduino.h:29:0,

                 from sketch\Settings.h:4,

                 from sketch\Settings.cpp:1:

Settings.cpp:49:79: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_BEACONCHANNEL))) setBeaconChannel(data.get<bool>(keyword(S_BEACONCHANNEL)));

                                                                               ^

Settings.cpp:50:81: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_BEACONINTERVAL))) setBeaconInterval(data.get<bool>(keyword(S_BEACONINTERVAL)));

                                                                                 ^

Settings.cpp:51:69: error: expected primary-expression before 'bool'

     if (data.containsKey(keyword(S_RANDOMTX))) setRandomTX(data.get<bool>(keyword(S_RANDOMTX)));

                                                                     ^

Settings.cpp:52:86: error: expected primary-expression before '>' token

     if (data.containsKey(keyword(S_PROBESPERSSID))) setProbesPerSSID(data.get<uint8_t>(keyword(S_PROBESPERSSID)));

                                                                                      ^

sketch\Settings.cpp: In member function 'String Settings::getJsonStr()':

Settings.cpp:129:5: error: expected primary-expression before '.' token

     .set(keyword(S_PASSWORD), password);

     ^

Settings.cpp:130:35: error: no matching function for call to 'Settings::set(String, uint8_t&)'

    set(keyword(S_CHANNEL), channel);

                                   ^

sketch\Settings.cpp:130:35: note: candidate is:

In file included from sketch\Settings.cpp:1:0:

sketch\Settings.h:37:14: note: void Settings::set(const char*, String)

         void set(const char* str, String value);

              ^

sketch\Settings.h:37:14: note:   no known conversion for argument 1 from 'String' to 'const char*'

Settings.cpp:131:33: error: no matching function for call to 'Settings::set(String, bool&)'

    set(keyword(S_HIDDEN), hidden);

                                 ^

sketch\Settings.cpp:131:33: note: candidate is:

In file included from sketch\Settings.cpp:1:0:

sketch\Settings.h:37:14: note: void Settings::set(const char*, String)

         void set(const char* str, String value);

              ^

sketch\Settings.h:37:14: note:   no known conversion for argument 1 from 'String' to 'const char*'

Settings.cpp:132:47: error: no matching function for call to 'Settings::set(String, bool&)'

    set(keyword(S_CAPTIVEPORTAL), captivePortal);

                                               ^

sketch\Settings.cpp:132:47: note: candidate is:

In file included from sketch\Settings.cpp:1:0:

sketch\Settings.h:37:14: note: void Settings::set(const char*, String)

         void set(const char* str, String value);

              ^

sketch\Settings.h:37:14: note:   no known conversion for argument 1 from 'String' to 'const char*'

Settings.cpp:135:30: error: no matching function for call to 'Settings::set(String, String&)'

     set(keyword(S_LANG), lang);

                              ^

sketch\Settings.cpp:135:30: note: candidate is:

In file included from sketch\Settings.cpp:1:0:

sketch\Settings.h:37:14: note: void Settings::set(const char*, String)

         void set(const char* str, String value);

              ^

sketch\Settings.h:37:14: note:   no known conversion for argument 1 from 'String' to 'const char*'

Settings.cpp:136:5: error: 'data' was not declared in this scope

     data.set(keyword(S_AUTOSAVE), autosave);

     ^

In file included from sketch\DisplayUI.cpp:1:0:

DisplayUI.h:71:9: error: 'Button' does not name a type

         Button* up   = NULL;

         ^

DisplayUI.h:72:9: error: 'Button' does not name a type

         Button* down = NULL;

         ^

In file included from sketch\DisplayUI.h:5:0,

                 from sketch\DisplayUI.cpp:1:

A_config.h:66:26: error: 'SSD1306Wire' does not name a type

 #define DEAUTHER_DISPLAY SSD1306Wire display = SSD1306Wire(0x3c, 5, 4); // for 0.96" OLED

                          ^

sketch\DisplayUI.h:76:9: note: in expansion of macro 'DEAUTHER_DISPLAY'

         DEAUTHER_DISPLAY // see config.h

         ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::configInit()':

DisplayUI.cpp:6:5: error: 'display' was not declared in this scope

     display.init();

     ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::configOn()':

DisplayUI.cpp:26:5: error: 'display' was not declared in this scope

     display.displayOn();

     ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::configOff()':

DisplayUI.cpp:30:5: error: 'display' was not declared in this scope

     display.displayOff();

     ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::updatePrefix()':

DisplayUI.cpp:34:5: error: 'display' was not declared in this scope

     display.clear();

     ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::updateSuffix()':

DisplayUI.cpp:38:5: error: 'display' was not declared in this scope

     display.display();

     ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::drawString(int, int, String)':

DisplayUI.cpp:42:5: error: 'display' was not declared in this scope

     display.drawString(x, y, replaceUtf8(str, String(QUESTIONMARK)));

     ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::drawLine(int, int, int, int)':

DisplayUI.cpp:50:5: error: 'display' was not declared in this scope

     display.drawLine(x1, y1, x2, y2);

     ^

sketch\DisplayUI.cpp: In lambda function:

DisplayUI.cpp:83:13: error: 'display' was not declared in this scope

             display.setFont(ArialMT_Plain_24);

             ^

DisplayUI.cpp:83:29: error: 'ArialMT_Plain_24' was not declared in this scope

             display.setFont(ArialMT_Plain_24);

                             ^

DisplayUI.cpp:84:38: error: 'TEXT_ALIGN_CENTER' was not declared in this scope

             display.setTextAlignment(TEXT_ALIGN_CENTER);

                                      ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::update()':

DisplayUI.cpp:459:5: error: 'up' was not declared in this scope

     up->update();

     ^

DisplayUI.cpp:460:5: error: 'down' was not declared in this scope

     down->update();

     ^

DisplayUI.cpp:461:5: error: 'a' was not declared in this scope

     a->update();

     ^

DisplayUI.cpp:462:5: error: 'b' was not declared in this scope

     b->update();

     ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::setupButtons()':

DisplayUI.cpp:499:5: error: 'up' was not declared in this scope

     up   = new ButtonPullup(BUTTON_UP);

     ^

DisplayUI.cpp:499:16: error: expected type-specifier before 'ButtonPullup'

     up   = new ButtonPullup(BUTTON_UP);

                ^

DisplayUI.cpp:499:16: error: expected ';' before 'ButtonPullup'

DisplayUI.cpp:500:5: error: 'down' was not declared in this scope

     down = new ButtonPullup(BUTTON_DOWN);

     ^

DisplayUI.cpp:500:16: error: expected type-specifier before 'ButtonPullup'

     down = new ButtonPullup(BUTTON_DOWN);

                ^

DisplayUI.cpp:500:16: error: expected ';' before 'ButtonPullup'

DisplayUI.cpp:501:5: error: 'a' was not declared in this scope

     a    = new ButtonPullup(BUTTON_A);

     ^

DisplayUI.cpp:501:16: error: expected type-specifier before 'ButtonPullup'

     a    = new ButtonPullup(BUTTON_A);

                ^

DisplayUI.cpp:501:16: error: expected ';' before 'ButtonPullup'

DisplayUI.cpp:502:5: error: 'b' was not declared in this scope

     b    = new ButtonPullup(BUTTON_B);

     ^

DisplayUI.cpp:502:16: error: expected type-specifier before 'ButtonPullup'

     b    = new ButtonPullup(BUTTON_B);

                ^

DisplayUI.cpp:502:16: error: expected ';' before 'ButtonPullup'

sketch\DisplayUI.cpp: In lambda function:

DisplayUI.cpp:595:17: error: 'display' was not declared in this scope

                 display.setFont(DejaVu_Sans_Mono_12);

                 ^

DisplayUI.cpp:596:42: error: 'TEXT_ALIGN_LEFT' was not declared in this scope

                 display.setTextAlignment(TEXT_ALIGN_LEFT);

                                          ^

sketch\DisplayUI.cpp: In lambda function:

DisplayUI.cpp:634:17: error: 'display' was not declared in this scope

                 display.setFont(DejaVu_Sans_Mono_12);

                 ^

DisplayUI.cpp:635:42: error: 'TEXT_ALIGN_LEFT' was not declared in this scope

                 display.setTextAlignment(TEXT_ALIGN_LEFT);

                                          ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::drawButtonTest()':

DisplayUI.cpp:693:35: error: 'up' was not declared in this scope

     drawString(0, str(D_UP) + b2s(up->read()));

                                   ^

DisplayUI.cpp:694:37: error: 'down' was not declared in this scope

     drawString(1, str(D_DOWN) + b2s(down->read()));

                                     ^

DisplayUI.cpp:695:34: error: 'a' was not declared in this scope

     drawString(2, str(D_A) + b2s(a->read()));

                                  ^

DisplayUI.cpp:696:34: error: 'b' was not declared in this scope

     drawString(3, str(D_B) + b2s(b->read()));

                                  ^

sketch\DisplayUI.cpp: In member function 'void DisplayUI::drawClock()':

DisplayUI.cpp:789:5: error: 'display' was not declared in this scope

     display.drawString(64, 20, clockTime);

     ^

exit status 1
In file included from sketch\CLI.h:18:0,

                 from C:\Users\Leo\Desktop\esp8266_deauther-2.1.0\esp8266_deauther\esp8266_deauther.ino:32:

DisplayUI.h:71:9: error: 'Button' does not name a type

         Button* up   = NULL;

         ^

DisplayUI.h:72:9: error: 'Button' does not name a type

         Button* down = NULL;

         ^

In file included from sketch\Settings.h:11:0,

                 from C:\Users\Leo\Desktop\esp8266_deauther-2.1.0\esp8266_deauther\esp8266_deauther.ino:27:

A_config.h:66:26: error: 'SSD1306Wire' does not name a type

 #define DEAUTHER_DISPLAY SSD1306Wire display = SSD1306Wire(0x3c, 5, 4); // for 0.96" OLED

                          ^

sketch\DisplayUI.h:76:9: note: in expansion of macro 'DEAUTHER_DISPLAY'

         DEAUTHER_DISPLAY // see config.h

         ^

'Button' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by davedarko** [comment]
have you followed the library steps in the wiki? https://github.com/spacehuhn/esp8266_deauther/wiki/Installation

**Comment by xwhd12** [comment]
yes if im not wrong but if u could help me find out whats wrong i would like ur help u could help me tru discord or something else idk but i would like to fix this problem

**Comment by MartieTheSmartie** [comment]
You selected Node MCU 0.9, try 1.0 it's a more common device, having issues with compiling aswell..

**Comment by xwhd12** [comment]
i did still says it

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
