### ISSUE TITLE
Spi screen bugged

### ISSUE THREAD

**Issue by AnnonZerp** [spacehuhn/esp8266_deauther#1005]
I followed the instructions from the wiki to get a screen working and it shows that weird dot pattern with clock cut off in the middle
![img_20181210_2240031](https://user-images.githubusercontent.com/17935575/49777959-b4b5a380-fcd0-11e8-8976-3efcda2568c8.jpg)

**Comment by marvinborner** [comment]
This probably happened due to a wrongly configured code. You have to compile it yourself and change the screen parameter in the A_config.h file to your corresponding screen type (In this case you should uncomment the bottom display line for a 1.3" OLED SPI screen I guess).

**Comment by tobozo** [comment]
problem with init sequence, typically wrong driver selection

you can try to invert the drivers e.g. if you're using sh1106, try ssd1306 instead

also make sure the pins aren't used by another functionality such as led or button

**Comment by AnnonZerp** [comment]
Thanks I mixed up the board type
