### ISSUE TITLE
Green Light Not On Anymore

### ISSUE THREAD

**Issue by caspertheghost1337** [spacehuhn/esp8266_deauther#1012]
The green light that used to indicate that it was on, is not on anymore after updating from v.2.0.5 (iirc) to the latest v2.1.0. There used to be a green light on an old version, but now it doesn't have a light anymore. I have turned on LED in the serial monitor. Also, the web panel is good but then in a different location, it is all buggy all of a sudden, files not loading and other errors. Other than that, it works great in some locations.

**Comment by commanderHR1** [comment]
Could be a corrupted update. Have you tried re-updating? Reverting to the old version again? Any error messages to examine?

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
