### ISSUE TITLE
Can the node mcu overheat/frie himself ?

### ISSUE THREAD

**Issue by TheD0ge** [spacehuhn/esp8266_deauther#1018]
I am interested of making an box with an hole on top where i attach a fan that blows on it is it necessary ?

**Comment by kai9987kai** [comment]
He can overheat himself if you run intensive tasks for a computer of that size and spec.
A solution would be for a [tiny heatsink](https://www.robotshop.com/uk/self-adhesive-pure-copper-heat-sink-raspberry-pi.html?gclid=Cj0KCQiA05zhBRCMARIsACKDWjfkFd57OcyLLPyGaJi0cR3DFjho_Gpd2mbcX5FbgtvXjL_PbukxQRsaAruGEALw_wcB) you can get these for as little as 94p

**Comment by lMartin3** [comment]
Please close this issue
