### ISSUE TITLE
Enhancement request - extra features

### ISSUE THREAD

**Issue by Mera-balou** [spacehuhn/esp8266_deauther#1020]
Hi Stefan,

I've just buying a DSTIKE Deauther Wristband V2 from @lspoplove, can't wait to try it.
I 've few suggestions for extra features:
- grab WPA handshakes and PMKID hashes of target
- collect client/AP MAC Address and geoloc if possible, like wardriving app. Maybe geolocate AP throught smartphone location connected with esp8286 (google API for arduino), or specific GPS hardware module.
  
Thanks for your work anyway.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
