### ISSUE TITLE
Why deauthantication process stop some time later ???

### ISSUE THREAD

**Issue by aponfurious** [spacehuhn/esp8266_deauther#1021]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```inside these 3 quotes/grave accents```
(Delete this text when you've read it)
I am useing esp8266 module .. and .bin file v2.1
all thing work fine but the deauthentication process stop automatically (blue light stop) after 8-10 mins later ...  

<details>
  <summary> Compile log (...)</summary>

  

</details>
<br><br><br>

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#attack-stops-after-a-while
