### ISSUE TITLE
Plese send the bin file...

### ISSUE THREAD

**Issue by aponfurious** [spacehuhn/esp8266_deauther#1024]
Please send me the bin file of esp8266 board jammer which attacktimeout=0 need it urgent...  please help me... please please please
if it possible then send it through gmail .. mail:aponfurious@gmail.com

**Comment by forseenink3238** [comment]
Where should we send it?

**Comment by sro2** [comment]
I can give but in this bin file i also get a problem. When i attack 3or4
device the deauther wifi connection lost but attack running background. If
you want i can send you bin file. Or you can also give me the Bin file, i
will modify it for you. Thanks

**Comment by sro2** [comment]
In mail

**Comment by sro2** [comment]
Send dude in gmail

**Comment by sro2** [comment]
Which version bin file you are using. And where you live

**Comment by aponfurious** [comment]
sorry, I am new user so I don't see the attacktimeout value in setting option..  but now I saw it and solved the problem. thank you everyone

**Comment by aponfurious** [comment]
thank you sro2
