### ISSUE TITLE
Why my connection lost when i attack 4or5 device

### ISSUE THREAD

**Issue by sro2** [spacehuhn/esp8266_deauther#1026]
I flash it by nodmcu flasher. But when i attack 4or 5 device my pown nework connection lost but attack still running background. When i power off my board and plugged again the i can connect pown . Plz give me solution plz.......

**Comment by sro2** [comment]
Please help me

**Comment by spacehuhn** [comment]
sir bro plz read manual
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#timeout-error
u loose connection when u attack is normal, say it in web interface too where u click

**Comment by sro2** [comment]
Sir its happened also web view. Help

**Comment by sro2** [comment]
Link

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
