### ISSUE TITLE
Deauthentication frames are not sent after re-flashing the ESP12 module in the Arduino IDE.

### ISSUE THREAD

**Issue by AlexandreVN** [spacehuhn/esp8266_deauther#1028]
I compiled the project in Arduino IDE for ESP12 module. Everything worked fine, but after a couple of months I decided to show my friends how to do *.bin file. After re-flashing, the module does not send deauthentication frames. In the port monitor, the following: 
[Pkt/s] All:    0 | Deauths:   0/40  | Beacons:   0/0   | Probes:   0/0
I tried different modules, different firmwares. It's useless. What could be the reason? The reset command, and the format also did not help.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
