### ISSUE TITLE
"Run <file> -c <time>" doesn't work

### ISSUE THREAD

**Issue by laurentbourassa** [spacehuhn/esp8266_deauther#1032]
Hello, I'm playing around a bit with the scripts and for some reason the continuous mode (-c) doesn't seem to be working. I assume it should work the same way as it does for the continuous scan mode. Am I just dumb?

Edit : Forgot to mention I am using the Arduino Monitor to send commands to the ESP8266.

**Comment by Esp8266Alfa** [comment]
Did you find a way to fix it?

**Comment by DeMaska** [comment]
@Esp8266Alfa Haven't got the time to look into it right now, so no I didn't fix it.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
