### ISSUE TITLE
I can't set Chinese

### ISSUE THREAD

**Issue by clementatt** [spacehuhn/esp8266_deauther#1034]
Hello, I can't set Chinese, the version is V2.1.0

**Comment by 18119702253** [comment]
emmm，我也是

**Comment by clementatt** [comment]
> emmm，我也是

我知道怎么设置了，先设置语言，然后清除浏览器cookie就可以了

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
