### ISSUE TITLE
My computer cannot detect my NodeMCU

### ISSUE THREAD

**Issue by dzp0wer** [spacehuhn/esp8266_deauther#1036]
I have an ESP8266 Nodemcu 1.0. I flashed it with Deauther 2.1, but now i want to reset my board, but my pc cant detect the board. I reinstalled driver, i changed the cable, i used an other pc, ...How can i fix this??

**Comment by ohno-o** [comment]
You probably have to install a driver. I had this problem to

**Comment by dzp0wer** [comment]
what did you do ? Do you have a solution to the problem ? What's the driver ?

**Comment by ohno-o** [comment]
I downloaded the driver. But I don't remember.
I'll try to find it

**Comment by ohno-o** [comment]
https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by dzp0wer** [comment]
Thank u, I'll try it

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
