### ISSUE TITLE
not work with Nodemcu v3 ch-12e esp-8266

### ISSUE THREAD

**Issue by sebk95** [spacehuhn/esp8266_deauther#1037]
not work with this board. Version 1.5 worked.
iussue:
-slow reload page when search access point and it not show access point until i reload the page.
-not switch on led( on board led- unique led ) when i attack with deauther tecnique and other
-not change the language 
-not  show packets in real time when i attack but i must reload page.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
