### ISSUE TITLE
Cant flash esp8266, failed sending bytes

### ISSUE THREAD

**Issue by v3n0mou5** [spacehuhn/esp8266_deauther#1038]
Tried multiple usb cables,
multiple usb ports,
got the right drivers,
tried multiple board settings
googled alot, tried holding down the buttons,

nothing works, any ideas? or is the board dead?

Build options changed, rebuilding all
Archiving built core (caching) in: C:\Users\race_\AppData\Local\Temp\arduino_cache_531236\core\core_deauther_esp8266_nodemcuv2_CpuFrequency_160,UploadTool_esptool,FlashFreq_80,FlashMode_dio,UploadSpeed_9600,FlashSize_1M256_a6090ebb234c974a0cd9e5be7c5f28d3.a
Sketch uses 704758 bytes (92%) of program storage space. Maximum is 761840 bytes.
Global variables use 42772 bytes (52%) of dynamic memory, leaving 39148 bytes for local variables. Maximum is 81920 bytes.
Uploading 708912 bytes from C:\Users\race_\AppData\Local\Temp\arduino_build_502920/esp8266_deauther.ino.bin to flash at 0x00000000
error: failed sending 1070 bytes
.error: failed sending 1044 bytes
.error: failed sending 1040 bytes
.error: failed sending 1040 bytes
.error: failed sending 1082 bytes
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
warning: espcomm_send_command: wrong direction/command: 0x01 0x03, expected 0x01 0x04
the selected serial port warning: espcomm_send_command: wrong direction/command: 0x01 0x03, expected 0x01 0x04
 does not exist or your board is not connected

**Comment by tobozo** [comment]
Closing this issue as OS/cable related, feel free to reopen if necessary.
