### ISSUE TITLE
Cannot connect to device using cellphone, tablets and pc

### ISSUE THREAD

**Issue by Invy55** [spacehuhn/esp8266_deauther#1039]
I cannot connect to device from any device. 
I used esp8266-01 and the ultimate version of the deauther.
When i connect it disconnect me and it seems the device restart (blue led turns on and off).
I have flashed it with nodemcu programmer.

**Comment by elliot-holley** [comment]
good question.

it's probably something to do with power management, although this is just a guess

**Comment by tobozo** [comment]
Closing this issue as power related, feel free to reopen if necessary.
