### ISSUE TITLE
OLED Screen doesn't boot up (or briefly)

### ISSUE THREAD

**Issue by Lglaplante** [spacehuhn/esp8266_deauther#1043]
Since 2.1.0, on Maltronics OLED Deauthers, the OLED screen doesn'T boot up (or boots up briefly)
This only occurs with this update. I tried flashing other firmwares to see if it was actually a board problem, and with the 2.0.5 it doesn't happens

in the Serial Monitor, no errors are showing up

**Comment by KmanOz** [comment]
It seems that if DisplayTimeout is set to 0 (don't turn the display off) the display turns off. The only way to turn the display on is to set a value and reboot. Not sure if this is related to your issue.

**Comment by Sponge3** [comment]
Me too

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
