### ISSUE TITLE
*.ino file for setup with buttons and OLED

### ISSUE THREAD

**Issue by kenai2019** [spacehuhn/esp8266_deauther#1044]
Hi there,
are there anywhere the *.ino files of the advanced setups with OLED and buttons? I tried to change the default deauther.ino but the display did not boot up. I would like to learn whats the difference is between the universal code and the precompiled *.bin.

thanks kenai2019

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
