### ISSUE TITLE
why i cant deauth a pc connected via lan cable

### ISSUE THREAD

**Issue by WeenDive** [spacehuhn/esp8266_deauther#1046]
i tried deauthing my pc but it doesn't work
prob because its on a wired connection
it does work for my iphone, and basically anything connected wirelessly.

**Comment by jLynx** [comment]
Please read the FAQ

**Comment by tobozo** [comment]
what about this ? :grin:  https://github.com/spacehuhn/ArduinoARPspoof

**Comment by WeenDive** [comment]
you have to be connected to the wifi tho
