### ISSUE TITLE
How to deauther a mesh network with more than one node?

### ISSUE THREAD

**Issue by jggg77** [spacehuhn/esp8266_deauther#1048]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```inside these 3 quotes/grave accents```
(Delete this text when you've read it)

<details>
  <summary> Compile log (...)</summary>

  

</details>
<br><br><br>

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
