### ISSUE TITLE
does this real works ?

### ISSUE THREAD

**Issue by minanagehsalalma** [spacehuhn/esp8266_deauther#1049]
it would be great if you made a video about it !
https://github.com/senorblasto/fluxion-esp8266

**Comment by 29G** [comment]
Wow that's really cool, i did not know of that project before. But you need to know that spacehuhn does not like "illegal" (even though it's impossible to get caught lol) things like that.

**Comment by minanagehsalalma** [comment]
@29G ... lol ... this isn't much different than the wifi deauther

**Comment by tobozo** [comment]
Closing this issue as yes, feel free to reopen if necessary.
