### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Marekkon5** [spacehuhn/esp8266_deauther#105]
I flashed the 1MB file to my NodeMCU and when I connected it, it made wifi ap called AI-THINKER-some number. When I connect to it, it disconnects me after 3 seconds. The 500KB bin file doesnt do anything. Thanks

**Comment by spacehuhn** [comment]
Have you tried to turn it off and on again (reset button)? And yes I'm serious you need to do that after you flashed it(, if you flashed it correct and  successful).

**Comment by Marekkon5** [comment]
I did that.

**Comment by Marekkon5** [comment]
I was using NodeMCU-Flasher for windows. I tried esptool and It worked. Sorry for ur time

**Comment by spacehuhn** [comment]
great 👍 have fun with the deauther :)
