### ISSUE TITLE
oui.h: no such file in directory

### ISSUE THREAD

**Issue by pelikan4001** [spacehuhn/esp8266_deauther#1050]
esp8266_deauther:24:17: error: oui.h: No such file or directory

 #include "oui.h"

                 ^

compilation terminated.

exit status 1
oui.h: No such file or directory

**Comment by pelikan4001** [comment]
@spacehuhn Is there a solution for that, I looked for in my documents and in the project file there is nothing like "oui" nor any of the files described in the lines 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 37.

**Comment by pelikan4001** [comment]
@spacehuhn Is there a solution for that, I looked for in my documents and in the project file there is nothing like "oui" nor any of the files described in the lines 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 37

**Comment by groovenreuven** [comment]
You have to download the .tar file instead of the .Zip source code. That works

**Comment by tytower** [comment]
> You have to download the .tar file instead of the .Zip source code. That works

This is rubbish  . disregard . In fact you have the files in the zip file but your compile IDE is not finding the file . In Arduino IDE Open the file from the sketchbook or examples , wherever you find it and it will compile.
