### ISSUE TITLE
Invalid version found: version 2013-07-07-17:51

### ISSUE THREAD

**Issue by xXPawnedXx** [spacehuhn/esp8266_deauther#1051]
Hey, Im sorta new to deauth and ESP8266 boards. Every time I try to upload the current version of the code to my board it reads : (Invalid version found: version 2013-07-07-17:51) 

Now, My port is resisted and my board has power
I installed the driver CH341SER_WINDOWS.zip as linked on the install page for the ESP8266 NodeMCU board
I commented out the #error line in the current code for ArduinoJSON version 5 

 As Far as I know, Im doing everything right. But apparently not. 
Sorry If this is just a really easy thing to solve. I lack experience with this program and board.

Thank you for your time.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
