### ISSUE TITLE
missing file directory

### ISSUE THREAD

**Issue by mzarzecki** [spacehuhn/esp8266_deauther#1053]
i've gone through the steps a few times now, but i keep having issues with this part of the code,  image below

![capture](https://user-images.githubusercontent.com/47264190/52158922-8a96b700-266b-11e9-9a22-ce48a968c2a0.JPG)

**Comment by xhdix** [comment]
OLED library 

 Search "sh1106" in: 
 Sketch -> Include Library -> Library Manager 

**However, it should be noted in the installation documentation.**

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
