### ISSUE TITLE
"Write" serial command removes necessary quotation marks

### ISSUE THREAD

**Issue by 29G** [spacehuhn/esp8266_deauther#1054]
I want to write to autostart.txt:

deselect -ap "R Hen"

But it writes it as:

deselect -ap R Hen

Because of that the deselection command will not work. The AP has a space in its name and needs quotation marks.

I tried giving that AP a custom name and deselecting the custom name, but it doesn't work.

Also at the [Write command page](https://github.com/spacehuhn/esp8266_deauther/blob/master/serialcommands.md#write) it says that there is a "tutorials.md" file somewhere but i can't find it.

**Comment by spacehuhn** [comment]
try `deselect -ap \"R Hen\"`

**Comment by 29G** [comment]
It worked, thank you :)
