### ISSUE TITLE
Simple Web File Manager?

### ISSUE THREAD

**Issue by testufo** [spacehuhn/esp8266_deauther#1058]

**Comment by DeMaska** [comment]
Can't help you if you don't give any information.

**Comment by KmanOz** [comment]
I am assuming he means access to the files that are created by scanning for stations AP's etc via a Web interface. So for example you could upload a saved set of stations and AP's when you arrive at a particular location for "TESTING" rather than having to scan again.

**Comment by usergyhh** [comment]
Yes.
10.02.2019 4:07 пользователь "KmanOz" <notifications@github.com> написал:

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
