### ISSUE TITLE
You must read

### ISSUE THREAD

**Issue by Michaelmeissner1997** [spacehuhn/esp8266_deauther#1061]
https://www.youtube.com/watch?v=N5JVQ-m5Kd0&feature=youtu.be

Hey This person is Avertising this as Jammer and USing your files without permission.

**Comment by beicnet** [comment]
@Michaelmeissner1997 I think it's open source and it's free too, right?! ;)

**Comment by DeMaska** [comment]
Here's the thing about Github : If a code is here, everyone can take it.

**Comment by tobozo** [comment]
Closing this issue as you-must-close, feel free to reopen if necessary.
