### ISSUE TITLE
If I use a wifi extender on the deauther network will it extend its range??

### ISSUE THREAD

**Issue by kai9987kai** [spacehuhn/esp8266_deauther#1062]
If I use a wifi extender on the deauther network will it extend its range??

**Comment by 29G** [comment]
Do you mean the AP that it creates to access the website interface (pwned)? If so, yes.

But obviously you can't use a repeater for deauthentications, beacons and problem requests.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
