### ISSUE TITLE
ESP 8266 reset itself

### ISSUE THREAD

**Issue by Section25** [spacehuhn/esp8266_deauther#1063]
Something strange just happened to one of my ESP8266s, when I connected power to it, its SSID was reset to pwned and password to deauth. After scratching my head for a while, I wondered if I had accidentally pushed the reset button but I can't find anything which says exactly what happens if the reset button is pressed - none of the reset instruction mention it - and I have tried to replicate the action but haven't been able to do so.

Are there any physical actions which could do this?

**Comment by sro2** [comment]
I also have this problem but i dont get any solution.....

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
