### ISSUE TITLE
changes in webfiles possible?

### ISSUE THREAD

**Issue by kenai2011** [spacehuhn/esp8266_deauther#1064]
Hi there,
i just played around withe the code and tried to change some of the webfiles. 
Workflow: Go into data subfolder - extract index.html from .gz  - changed anything in the file - put it back to the gz -uploaded spiffs via ESP8266 data upload plugin - restartet ESP and log in to the webinterface

But nothing was changed on the web interface. Is there any cheat to do changes?

Thanks in advance
kenai2011

**Comment by tobozo** [comment]
https://github.com/spacehuhn/esp8266_deauther/blob/master/settings.md#web-spiffs

**Comment by kenai2011** [comment]
Oh, wow! 
thank you tobozo, will check it soon.

greetz
kenai2011

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
