### ISSUE TITLE
Can't connect to pwned "authentication problem"

### ISSUE THREAD

**Issue by ohno-o** [spacehuhn/esp8266_deauther#1066]
When I try to connect to pwned I get the text autentiecatieprobleem Dutch for authentication problem. I've been connected two times.
I don't know how to fix it.

P.S. I have a android phone

**Comment by ohno-o** [comment]
Update: I have reflashed the code. But it still doesn't work

**Comment by NeverFen** [comment]
what is pwned password？

**Comment by jLynx** [comment]
Read the FAQ NeverFen

**Comment by ohno-o** [comment]
Ok

**Comment by ohno-o** [comment]
The password is deauther

**Comment by a-wip0** [comment]
Close this issue if the problem already solved.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
