### ISSUE TITLE
does it support ap channel change so it can start the jamming  attack automatic  after channel change ????   ﻿   

### ISSUE THREAD

**Issue by minanagehsalalma** [spacehuhn/esp8266_deauther#107]

**Comment by N0vaPixel** [comment]
Channel change is for the AP created by the esp.

**Comment by minanagehsalalma** [comment]
@N0vaPixel no channel change is for the first wifi router...  and i meant if the script support channels hopping

**Comment by spacehuhn** [comment]
Next time please ask your question clearly with a short title and a understandable description, thanks.

If the AP changes the channel while you're attacking it, you'd have to scan again to get the new channel (there's no other way).
If you have selected multiple APs which run on different channels it will automatically switch through them.

**Comment by minanagehsalalma** [comment]
@spacehuhn    (
If you have selected multiple APs which run on different channels it will automatically switch through them.)  even if one of the APs changed has channel

**Comment by spacehuhn** [comment]
no. you have to scan to get the new channel.

**Comment by minanagehsalalma** [comment]
@spacehuhn  can mdk3 run on esp8266 nodemcu ????

**Comment by anudeepND** [comment]
Nope.

**Comment by minanagehsalalma** [comment]
@anudeepND  why not   ??

**Comment by anudeepND** [comment]
Considering the memory and storage availability on esp it is not possible. And this project has all the best features. If you are looking to install mdk3 and other wireless tools out there, a $5 raspi zero is your best option.

**Comment by minanagehsalalma** [comment]
@anudeepND can this version of mdk3  https://github.com/wi-fi-analyzer/mdk3-master run on the $5 raspi zero ???  do you have a video link about  how to use it ??

**Comment by tpmodding** [comment]
yes
http://bit.ly/2ncxXBy

**Comment by minanagehsalalma** [comment]
@tpmodding i didn't find a video !!!!!

**Comment by N0vaPixel** [comment]
Impossible to run an os based programs (like mdk3) on the esp's microcontroller.
Aircrack is a dangerous tool for other users. So if you didn't know how it basicly works and how properly install it, you didn't deserve to use it, because your purpose will only be to annoy others. So please don't be like all these "script kiddies".
Mdk3 and many tools can run on the $5 raspi zero.

**I lock this issue.**
