### ISSUE TITLE
Library Issues

### ISSUE THREAD

**Issue by thoshall** [spacehuhn/esp8266_deauther#1071]
I keep getting this error when trying to upload the code to an MCU through IDE.  I verified my files are in the correct folder.  Any help would be appreciated.

  <Sketch uses 703132 bytes (92%) of program storage space. Maximum is 761840 bytes.
Global variables use 42402 bytes (51%) of dynamic memory, leaving 39518 bytes for local variables. Maximum is 81920 bytes.
Uploading 707280 bytes from /var/folders/kv/dxlkw_ls1bg_kpflfdx2lmkw0000gn/T/arduino_build_550199/esp8266_deauther.ino.bin to flash at 0x00000000
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Invalid library found in /Users/jessehoshall/Documents/Arduino/libraries/esp8266_deauther-2.1.0: no headers files (.h) found in /Users/jessehoshall/Documents/Arduino/libraries/esp8266_deauther-2.1.0
Invalid library found in /Users/jessehoshall/Documents/Arduino/libraries/esp8266_deauther-2.1.0: no headers files (.h) found in /Users/jessehoshall/Documents/Arduino/libraries/esp8266_deauther-2.1.0
>

</details>
<br><br><br>

**Comment by tobozo** [comment]
just move the folder ` /Users/jessehoshall/Documents/Arduino/libraries/esp8266_deauther-2.1.0` on your desktop or somewhere else and the IDE will stop to complain about it

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
