### ISSUE TITLE
Using arduino-cli tutorial please

### ISSUE THREAD

**Issue by ghost** [spacehuhn/esp8266_deauther#1072]
I am very new to using arduino-cli. Im using it because I run Linux distribution only. I could not find a way to install the IDE version that was for any of the the distro bases. I had some success on the arduino-cli github. Looking through there commands and actually reproducing them. But as I said, Im kinda new at this. Any extra tutorial may help the next person as well. So I have no errors to report. Thanks for making this project happen.

**Comment by tobozo** [comment]
Please have a look at the [Travis CI yml test file](https://github.com/spacehuhn/esp8266_deauther/blob/travis-ci-tests/.travis.yml) near [this line](https://github.com/spacehuhn/esp8266_deauther/blob/travis-ci-tests/.travis.yml#L60) to get clues on how to setup the environment, but be aware this hasn't been maintained for a long time.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
