### ISSUE TITLE
Maltronics Deauther

### ISSUE THREAD

**Issue by caspertheghost1337** [spacehuhn/esp8266_deauther#1075]
I bought one, and it worked, but I saw there was an update, so I reflashed it or what the term is, I don't know. Now, the LED only turns on when scanning, and deauth + beacon doesn't even work. After beacon attack runs for a bit, only one SSID pops up. Any troubleshooting tips? Thanks!

**Comment by Sourin-Mitra** [comment]
I also facing same problem...developer please help us... Please help us... Thanks u

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
