### ISSUE TITLE
I bought one, and it worked, but ...

### ISSUE THREAD

**Issue by Sourin-Mitra** [spacehuhn/esp8266_deauther#1076]
I bought one, and it worked, but I saw there was an update, so I reflashed it or what the term is, I don't know. Now, the LED only turns on when scanning, and deauth + beacon doesn't even work. After beacon attack runs for a bit, only one SSID pops up. Any troubleshooting tips? Thanks

**Comment by digmorepaka** [comment]
As far as i know this is intended behavior.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
