### ISSUE TITLE
Access Point

### ISSUE THREAD

**Issue by 10newolf** [spacehuhn/esp8266_deauther#1078]
Can I use the access point created by nodemcu for headless setup for Raspberry Pi

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.

**Comment by spacehuhn** [comment]
Not sure what headless setup means, but the ESP8266 creates an access point without the functionality of a router. So talking to the raspi through a wifi network made by the ESP8266 is not possible. At least not just like that. You'd have to program the ESP to create some sort of bridge.
