### ISSUE TITLE
Arduino: 1.8.9 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 160 MHz, Serial, 80MHz, DIO, 115200, 1M (256K SPIFFS)"  esp8266_deauther:16:17: error: oui.h: No such file or directory  Multiple libraries were found for "ArduinoJson.h"  #include "oui.h"   Used: C:\Users\Jason\Documents\Arduino\libraries\ArduinoJson                  ^   Not used: C:\Users\Jason\AppData\Local\Arduino15\packages\deauther\hardware\esp8266\2.0.0-deauther\libraries\ArduinoJson compilation terminated.  exit status 1 oui.h: No such file or directory  This report would have more information with "Show verbose output during compilation" option enabled in File -> Preferences.

### ISSUE THREAD

**Issue by fdkjgudogh** [spacehuhn/esp8266_deauther#1083]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```inside these 3 quotes/grave accents```
(Delete this text when you've read it)

<details>
  <summary> Compile log (...)</summary>

  

</details>
<br><br><br>

**Comment by tytower** [comment]
This is because Arduino is not finding the files it needs for some reason .Close the sketch you have open now . The files are there ! just try in the menu to find the file in examples rather than the sketch you were using.
