### ISSUE TITLE
Cant install it to ESP8285

### ISSUE THREAD

**Issue by x0r3n** [spacehuhn/esp8266_deauther#1085]
Hello

When I try to Upload it to ESP8285 (selected from above ESP8266 Deauther Modules) I got this error :/

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Generic ESP8285 Module.

**Comment by x0r3n** [comment]
I have upload successful to ESP8285 , but not working, cant find the ssid pwned, hidden option is off (`bool hidden = false`  )

**Comment by tobozo** [comment]
Closing this issue as solved, feel free to reopen if necessary.
