### ISSUE TITLE
can we use the led as indicator?

### ISSUE THREAD

**Issue by WardanaID** [spacehuhn/esp8266_deauther#1086]
hello, I have an ESP8266 NodeMCU that has firmware v2.1.0 installed
Is there a way to use the LED lights as an indicator when attacking, like a blinking when attacking?

**Comment by teco13** [comment]
In previous versions, the blue internal led of the nodemcu was lit in attacks. Now compiling my own version, I managed to turn it on, but only on scan. Is it possible to turn on in attack?

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
