### ISSUE TITLE
Web doesn't work for me.

### ISSUE THREAD

**Issue by Dex25** [spacehuhn/esp8266_deauther#1092]
Hi, I followed all the steps and I connected to pwned but I can't load the web 192.168.4.1 it says error 504 timeout.

**Comment by cab19** [comment]
I've noticed on my Android (LineageOS) I had a similar experience, there was a dialog pop up about staying connected to the network as there's no internet, once I clicked okay on that it worked.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
