### ISSUE TITLE
NO WARRANTY from Travis Lim for faulty boards

### ISSUE THREAD

**Issue by KmanOz** [spacehuhn/esp8266_deauther#1094]
So I contacted Travis Lim with an issue that developed with my DSTIKE v4 board that was purchased through the official DSTIKE store on AliExpress. Everything was fine and it was charging (I had battery installed) during the day. It was plugged into a USB hub that was plugged into my Mac. I turned off the computer overnight BUT DID NOT unplug it from the hub. In the morning I tried to turn on the board but it would no longer turn on. The LED lights for the battery level would come on but board would not boot and within 1 second the battery level LEDS would go out. Tried removing battery and it wouldn't power at all.

I contacted Travis and basically THERE IS NO WARRANTY. All he offers is a 20% discount on another board.

PLEASE DO NOT DELETE THIS. PEOPLE NEED TO KNOW THE LEVEL OF SERVICE IS NEXT TO NOTHING for a fault I did not create from Travis.

**Comment by jLynx** [comment]
This is not an issue with the software, so this is going to be closed.
