### ISSUE TITLE
deauther_2.1.0_1mb.bin upload failed

### ISSUE THREAD

**Issue by r4adi0GaX2** [spacehuhn/esp8266_deauther#1095]
Hey, I'm on Mac and I'm getting this error message when I try to upload deauther_2.1.0_1mb.bin on my ESP8266...

"warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed"

![Captura de Pantalla 2019-05-13 a les 14 37 59](https://user-images.githubusercontent.com/50443359/57622360-b4764880-758d-11e9-879d-b56b831ebe03.png)

The WiFI connection "pwned" does not appear either.
The Arduino program uploads itself correctly on the NodeMCU.

**Comment by r4adi0GaX2** [comment]
I pressed the flash button until the program startsto upload. Now "pwned" appears on the WiFi list but only on my Mac and not on my Android phone ...

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
