### ISSUE TITLE
can you add channel  hopping ??? 

### ISSUE THREAD

**Issue by minanagehsalalma** [spacehuhn/esp8266_deauther#110]
@spacehuhn i want the script to hop channels like mdk3..  cause of ap channel change...  can you do this  ??? please

**Comment by spacehuhn** [comment]
there you go: 25a9dfe73c847b2585b407241a56c7b78f0ad3a9

**Comment by minanagehsalalma** [comment]
@spacehuhn  does it hops all the 13 channels ????

**Comment by N0vaPixel** [comment]
@minanagehsalalma  Look at the code, if channel hopping is enabled, the esp will send deauth packet for specified client/AP to all channels. Only channels 1 to 11 (USA band)

**Comment by minanagehsalalma** [comment]
@N0vaPixel @spacehuhn  can you add channels 12 &  13 cause i am not from usa ??  please

**Comment by N0vaPixel** [comment]
Me too i live in EU
I plan to add this feature, in settings you'll be able to choose your location.
USA (channel 1 to 11)
EU (1 to 13)
Japan (1 to 14)
I don't know the others

**Comment by minanagehsalalma** [comment]
@N0vaPixel great..  add this option ..  the others are  not important ..

**Comment by spacehuhn** [comment]
@minanagehsalalma how about doing it yourself? You don't need this feature anyway in 99% of the time.

**Comment by N0vaPixel** [comment]
@minanagehsalalma  This is not my priority. All the wifi equipements in EU are limited to USA channels.

**Comment by spacehuhn** [comment]
@N0vaPixel no need to add this. If someone really needs this, it can be easily changed by going into the code and replacing the 11 int the for loop with a 13 or 14. Like you said, most devices are limited to the USA channels anyway and the ESP's memory is limited!

**Comment by minanagehsalalma** [comment]
@spacehuhn  which one   ???

**Comment by minanagehsalalma** [comment]
@spacehuhn @N0vaPixel  in which code file

**Comment by minanagehsalalma** [comment]
@spacehuhn @N0vaPixel I don't have the skills to do that...  can you explain more ??
