### ISSUE TITLE
nodemcu has been programmed but the wifi is not showing up

### ISSUE THREAD

**Issue by koko5888** [spacehuhn/esp8266_deauther#1102]
I just got a  nodemcu and have flashed this project two times once with the Arduino and once with the Node2Deauther they both said it successfully finished but when I check my wifi list the wifi does not show up. 

also, what does it mean when you set GPIO0 to LOW because it said to do that with the NODEMCU firmware but I didn't know how to do that.

**Comment by SentinelMKX** [comment]
Are you sure you have the correct nodemcu?

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
