### ISSUE TITLE
I need help. 

### ISSUE THREAD

**Issue by MichalNemecek** [spacehuhn/esp8266_deauther#1103]
I tried looking through all the issues and didn't find anything that matches this. I hit upload and got this:

In file included from sketch\LED.h:6:0,

                 from sketch\LED.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

In file included from sketch\Accesspoints.h:7:0,

                 from sketch\Accesspoints.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

In file included from sketch\Names.h:8:0,

                 from sketch\Names.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

In file included from sketch\Settings.h:7:0,

                 from sketch\DisplayUI.h:6,

                 from sketch\DisplayUI.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

In file included from sketch\Stations.h:6:0,

                 from sketch\Stations.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

In file included from sketch\Attack.h:7:0,

                 from sketch\Attack.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

exit status 1
In file included from sketch\CLI.h:8:0,

                 from sketch\CLI.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

In file included from sketch\Accesspoints.h:7:0,

                 from sketch\Scan.h:5,

                 from sketch\Scan.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

In file included from C:\Users\nemec\Desktop\esp8266_deauther-master\esp8266_deauther\esp8266_deauther.ino:12:0:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

sketch\Attack.cpp: In member function 'bool Attack::sendPacket(uint8_t*, uint16_t, uint8_t, uint16_t)':

Attack.cpp:412:60: error: cannot convert 'uint8_t* {aka unsigned char*}' to 'uint8** {aka unsigned char**}' for argument '1' to 'int wifi_send_pkt_freedom(uint8**, int, bool)'

     bool sent = wifi_send_pkt_freedom(packet, packetSize, 0) == 0;

                                                            ^

Attack.cpp:415:96: error: cannot convert 'uint8_t* {aka unsigned char*}' to 'uint8** {aka unsigned char**}' for argument '1' to 'int wifi_send_pkt_freedom(uint8**, int, bool)'

     for (int i = 0; i < tries && !sent; i++) sent = wifi_send_pkt_freedom(packet, packetSize, 0) == 0;

                                                                                                ^

In file included from sketch\SSIDs.h:8:0,

                 from sketch\SSIDs.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

sketch\Scan.cpp: In member function 'void Scan::start(uint8_t, uint32_t, uint8_t, uint32_t, bool, uint8_t)':

Scan.cpp:81:37: error: no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool)'

         WiFi.scanNetworks(true, true);

                                     ^

sketch\Scan.cpp:81:37: note: candidate is:

In file included from sketch\Accesspoints.h:5:0,

                 from sketch\Scan.h:5,

                 from sketch\Scan.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note: int8_t ESP8266WiFiClass::scanNetworks(bool)

     int8_t scanNetworks(bool async = false);

            ^

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note:   candidate expects 1 argument, 2 provided

In file included from sketch\Settings.h:7:0,

                 from sketch\Settings.cpp:1:

C:\Users\nemec\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

cannot convert 'uint8_t* {aka unsigned char*}' to 'uint8** {aka unsigned char**}' for argument '1' to 'int wifi_send_pkt_freedom(uint8**, int, bool)'

**Comment by SentinelMKX** [comment]
I recommend making everything again by the wiki/tutorial
it looks like some of the files are corrupted or you choosed somewhere the wrong option or set wrong settings
check everything

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
