### ISSUE TITLE
No network found

### ISSUE THREAD

**Issue by Danielr19** [spacehuhn/esp8266_deauther#1105]
//Found an issue with a similar problem but found no solutions

Hi, I really liked your project and I think that what you are doing is great and spiring, at least for me. I tried installing the 2.0.5 version on a board I´ve got, everything seemed fine, I was even able to upload the code. The wifi network "pwned" won't appear, settings are as shown in the first picture. I'll try with another version but I wanted to know if the problem is due to the version I used. I'll post some pictures showing the board I own.

The last 3 pictures are basically what is being shown in the serial port, it shows that and then loops and shows it again for an unlimited amount of times.

![image](https://user-images.githubusercontent.com/51176392/58589029-99ab0180-8226-11e9-813b-75d8b34d883e.png)

![image](https://user-images.githubusercontent.com/51176392/58588503-6b78f200-8225-11e9-9779-b223612091e4.png)

![image](https://user-images.githubusercontent.com/51176392/58588519-73389680-8225-11e9-9830-e2f3511c1684.png)

**Serial:**

![image](https://user-images.githubusercontent.com/51176392/58589871-85680400-8228-11e9-832a-6481d3eb66f8.png)
![image](https://user-images.githubusercontent.com/51176392/58589884-8a2cb800-8228-11e9-9abf-55c3c21a2a28.png)
![image](https://user-images.githubusercontent.com/51176392/58589891-90229900-8228-11e9-8c68-36534809590b.png)

**Comment by Danielr19** [comment]
Update: Tried it with the easter version and I had the same problem

**Comment by SentinelMKX** [comment]
umm, I think you have wrong development board, I don't see network chip on your board

**Comment by jLynx** [comment]
@SentinelMKX, I do. It's the bottom chip

**Comment by Danielr19** [comment]
It has a wifi chip, I've used this board in other projects small projects involving wifi, but I don't know why I cant get it working for this one.
btw thx for trying to help, I really want to able to show this project to my friends.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
