### ISSUE TITLE
Can't de-authenticate  when selecting only AP

### ISSUE THREAD

**Issue by pijo2004** [spacehuhn/esp8266_deauther#1106]
Hello, 
I flashed with esp8266_deauther-2.1.0. It worked,
but i have very strange issue.
Let say I have a laptop and a phone connected to my AP
laptop wifi card: intel n7260
Phone Samsung something :)
So there are 2 situation 
1)Selecting only the AP
 result : phone->disconnected
            laptop-> not disconnected
2) selecting the AP and the client (my intel wifi card)
 result : phone->disconnected
            laptop->disconnected
I try the same thing with 2 different AP, the result was the same.
now i'm wondering is this a bug or something with this wifi card or i did something wrong.
Please advised
If you need more information: chip dump or something please tell me
Thank you for your time you put in this project.

**Comment by blokerun** [comment]
I have the same problem!! What can Ido?

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
