### ISSUE TITLE
No "Clients" Tab on deauthing a network.

### ISSUE THREAD

**Issue by ITCMD** [spacehuhn/esp8266_deauther#1110]
When I select a network to deauth it does not provide me with a clients tab so I can select specific devices on said network. The network is password protected so I assume I need to connect to it first or something like that, but I see no option to do this.

**Comment by ITCMD** [comment]
Figured that the "Clients" tab was renamed "Stations" and is now under the APs list.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
