### ISSUE TITLE
Can't find "arduino-esp8266-deauther" in the library manager

### ISSUE THREAD

**Issue by ytzlax** [spacehuhn/esp8266_deauther#1114]
Can't find "arduino-esp8266-deauther" in the library manager

**Comment by AxelLuch** [comment]
Same problem. Maybe it was deleted?

**Comment by tobozo** [comment]
it's not in the library manager but in the boards manager

**Comment by kryptohavoc** [comment]
even if i include "https://raw.githubusercontent.com/wiki/tobozo/Arduino/package_deauther_index.json" to the arduino preferences. i still can't find "arduino-esp8266-deauther" in the board manager
![2020-07-14 (1)](https://user-images.githubusercontent.com/68241285/87328478-1bafd400-c568-11ea-8c14-a639db959f78.png)

**Comment by spacehuhn** [comment]
Your screenshots indicates that you have already installed it
