### ISSUE TITLE
ERRORS :c

### ISSUE THREAD

**Issue by wiktor000** [spacehuhn/esp8266_deauther#1118]
I have a problem, it works for me once and not once. Once I have some errors once I do not how to solve it? I installed all versions

**Comment by wiktor000** [comment]
My error "Response error ClientScan. Json"

**Comment by Waviestballoonx9** [comment]
I can't do anything when I'm connected to the browser GUI just throws back errors.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
