### ISSUE TITLE
Cannot reset password!

### ISSUE THREAD

**Issue by Hhrthrwrwt** [spacehuhn/esp8266_deauther#1119]
I changed my password,and now I can't connect. I read the FAQ and nothing helped. After I download the reset firmware then the old firmware is returned. I don't know what to do. Please help. Again,I read the FAQ and nothing helped.

**Comment by Hhrthrwrwt** [comment]
I just forgot password

**Comment by SentinelMKX** [comment]
Flash there the empty bin and then flash the deauther, it should delete all data on it

**Comment by Hhrthrwrwt** [comment]
Thank you,but lol now when I install the firmware,the SSID does not appear ( maybe the firmware is not installed,or the problem in the SSID)

**Comment by Hhrthrwrwt** [comment]
I just changed COM port
