### ISSUE TITLE
ESP8266 scans but does not attack

### ISSUE THREAD

**Issue by ciclo2000** [spacehuhn/esp8266_deauther#1123]
Hiho,

I managed to flash an ESP266 and everything seems to work. 

The only problem I have is that an deauther attack does notinfluence my wlan at all. I looked up the specs of the wlan in windows10 and it says it is 2.4Ghz... so no multi frequency ..

When reviewing some instructions for installations I recognized, that I have not installed the 2.0.0 version in Arduino, but somewhat higher...around 2.4.1 or so... 

Can this be the cause of the problem? 

On the other hand, I did not change the user_interface.h like it is described in some installation guides. Is the manipulation of this files necessary for attacking? 

Thx for your help in advance.

Ciclo

<details>
  <summary> Compile log (...)</summary>

  

</details>
<br><br><br>

**Comment by tobozo** [comment]
Thanks for notifying us that this application actually does not work when you don't follow the [instructions](https://github.com/spacehuhn/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide).

Closing this issue as resolved.
