### ISSUE TITLE
Code got Compiled But Showing Erreor About Serial Port Not Selected

### ISSUE THREAD

**Issue by Ddeadpool** [spacehuhn/esp8266_deauther#1127]
Arduino: 1.8.8 (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Serial, 80MHz, DIO, 115200, 1M (256K SPIFFS)"

Build options changed, rebuilding all
Sketch uses 704686 bytes (92%) of program storage space. Maximum is 761840 bytes.
Global variables use 42788 bytes (52%) of dynamic memory, leaving 39132 bytes for local variables. Maximum is 81920 bytes.
Serial port not selected.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by tobozo** [comment]
Closing this issue as Serial port not selected, feel free to reopen if necessary.
