### ISSUE TITLE
Code Gets Compile And Upload But Showing Error Message Of Serial Port Not Selected And Also The The Wifi Created by Esp8266 Can't Connect To Server Of By Default Gateway 192.168.4.1 I Tried To Falsh And Reset Bur Nothing Is Working Please Solve Problem ASAP

### ISSUE THREAD

**Issue by Ddeadpool** [spacehuhn/esp8266_deauther#1129]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also, have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```inside these 3 quotes/grave accents```
(Delete this text when you've read it)

<details>
  <summary>
Code Gets Compile And Upload But Showing Error Message Of Serial Port Not Selected And Also The The Wifi Created by Esp8266 Can't Connect To Server Of By Default Gateway 192.168.4.1
</summary>

  

</details>
<br><br><br>

**Comment by tobozo** [comment]
![image](https://user-images.githubusercontent.com/1893754/62012869-ead66380-b18b-11e9-874d-cd42a712fb19.png)
