### ISSUE TITLE
USB deauthor

### ISSUE THREAD

**Issue by itzguno** [spacehuhn/esp8266_deauther#1131]
It works fine picking up ap and deauthing them but my school WiFi won't get picked up by the USB deauthor like I get every single ap around me like hotspots and other networks but my school WiFi won't show?

**Comment by projectb-temp** [comment]
Maybe the school Wifi works on 5GHz (following IEEE 802.11n or 802.11ac standards)?
The ESP8266 operates on 2.4GHz and therefore can only deauther (and scan) networks using this frequency.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
