### ISSUE TITLE
EPS8266

### ISSUE THREAD

**Issue by nitin9411166** [spacehuhn/esp8266_deauther#1135]
Tried to deauth a network. It was working fine. But when network restart/reboot deauth command automatically deleted for that network. Its not retrying to same thing

**Comment by projectb-temp** [comment]
Hi there.
Please try setting a better topic for your issue.
Just "EPS8266" (has even a typo in it, as the MCU is called "ESP8266") is too generic and so maybe none of the contributors will get interested in helping you out.
Also please try to give more information:
- Include version numbers and information about the software/hardware you are using.
- What exactly did you do?
- What expected you to happen and what was the result that did happen?
- What error messages or codes did you get?
- etc.

Thank you.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
