### ISSUE TITLE
Unable to connect to pwned network on iPad and Mac

### ISSUE THREAD

**Issue by VincentLeChef** [spacehuhn/esp8266_deauther#1138]
So I bought a USB WiFi deauther from maltronics, i plugged it in my mac, when i connected to the network on my mac, it automatically disconnected me from the network. I tried conencting to the network on my Ipad and when I put the password "deauther" it kept saying incorrect password.

**Comment by VincentLeChef** [comment]
now that im trying to connect to it again, there is no pwned network at all

**Comment by projectb-temp** [comment]
Did you tried to reset the device to defaults or maybe tried to re-flash a new .bin file?
What about other (non Apple) devices you could try to connect to the AP - do they work?

**Comment by VincentLeChef** [comment]
how can i reset the device? I have tried connecting it to my android phone but once it's connected it automatically disconects

**Comment by projectb-temp** [comment]
Please see the project's Wiki for this: https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#how-to-do-a-reset

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
