### ISSUE TITLE
#1149 by tytower was closed yesterday 

### ISSUE THREAD

**Issue by tytower** [spacehuhn/esp8266_deauther#1151]
```Can you please refrain from closing issues on a whim just because you seem unable to comprehend them```

**Comment by jLynx** [comment]
Please dont create issues if there are none. You just end up wasting our time

**Comment by tytower** [comment]
If you insist on closing them I will keep opening them because you are not giving them a fair go mate.!

**Comment by jLynx** [comment]
If that is the case then I will end up banning you.
