### ISSUE TITLE
Accidentally made the hotspot hidden

### ISSUE THREAD

**Issue by ulerlagopodous** [spacehuhn/esp8266_deauther#1156]
I was tweaking the settings of the deauther and I accidentally clicked save after clicking the "hidden" feature of the web page. now i am unable to go onto the hotspot because of my mistake.

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#how-to-do-a-reset

**Comment by ulerlagopodous** [comment]
does this also work for the oled deatuher mini?

**Comment by ulerlagopodous** [comment]
> https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#how-to-do-a-reset

Does this also work for the oled deatuher mini? I forgot to specify which device, i'm having the issue with.

**Comment by tobozo** [comment]
please tell us if it does
