### ISSUE TITLE
how to translate language?

### ISSUE THREAD

**Issue by ErfanDL** [spacehuhn/esp8266_deauther#116]
Hi. how can I translate web ui to other languages ? I trying edit html files but translation not changes when uploading to esp

thanks

**Comment by N0vaPixel** [comment]
You need to convert into bytes the html files and update data.h
All informations are included in the data.h file

**Comment by ErfanDL** [comment]
thanks for replay. can you tell me a example ? Im noob :D

**Comment by N0vaPixel** [comment]
Edit your html file, copy/past the content into the minifier (minifier.html), click on button "minify + byte-ify", get the result and past it into the appropriate PROGMEM variable in data.h.

**Comment by ErfanDL** [comment]
thanks for replay. is minifier.html program? or online tools ?

**Comment by N0vaPixel** [comment]
Both, you can use any online tool that convert text into bytes.

**Comment by spacehuhn** [comment]
@ErfanDL everything is in the htmlfiles folder, including a readme.

**Comment by poslogic** [comment]
Open the minified.html file that is in the html folder of this code.

Then paste your version of new html into the top part.

Then click minify + bitify.

Then copy the bottom part into the data.h file between the {} brackets of the page you are changing.

Then save data.h

Then compile and flash to ESP8266

**Comment by N0vaPixel** [comment]
Everything has been explained, i close this issue.

**Comment by ErfanDL** [comment]
thanks very much. my problem solved
