### ISSUE TITLE
CHANCE TO REVIEW YOUR FOOLISHNESS.

### ISSUE THREAD

**Issue by leonierocks** [spacehuhn/esp8266_deauther#1160]
CHANCE TO REVIEW YOUR FOOLISHNESS.

You are not getting it right .
Issues on github are for the discussion of problems by likeminded individuals over the same software to try to work out what is happening..
You don't just close an issue because you think it does not concern you ?
"I have looked at it and determined it must be something you did" ??

You don't just stick a label on it and forget it.

What a stupid approach to solving a problem. ...NOT solving it.
**Who's got control of you clowns. Who is overseeing the project? NO-ONE IT SEEMS !**

I have selected the only board in the deauther section that meets the description.
The ESP8266 device has ESP WROOM 32 marked on the front of it .
Which board should I be selecting at least ?

**Comment by spacehuhn** [comment]
wow

**Comment by underwoodblog** [comment]
Lol, 1bjames1 creating only a new account to post her again. What a madlad!

**Comment by tobozo** [comment]
confusing the effects of a locked post with a banned account totally corroborates the fact that frustration can obfuscate neural paths.

**Comment by digmorepaka** [comment]
I have looked at this issue, and determined it's a waste of time for both the developers, maintainers, and you. If you don't like how the issues section meant for *Bug reports* is handled,  no one forces you to make a post or read the others.

**Comment by lbussy** [comment]
Clearly, the gentleman deserves a refund?   Twice what he paid for all of his troubles!

**Comment by tobozo** [comment]
@digmorepaka I'll do you one better: "...it's a waste of time for *throth* the developers, maintainers, and you"

**Comment by PwnKitteh** [comment]
I think I deserve a refund for my time for reading this stupid ass post

**Comment by f0wl** [comment]
That's like buying an iPhone and complaining that it doesn't run Android

**Comment by jasonjpeters** [comment]
> That's like buying an iPhone and complaining that it doesn't run Android

I'll do ya'll one even more better -- why is Android.

**Comment by astonge** [comment]
You win. I quit.

**Comment by jLynx** [comment]
Closed as OP seems to be off his meds.
