### ISSUE TITLE
no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool)' 

### ISSUE THREAD

**Issue by dxsakthisundar1** [spacehuhn/esp8266_deauther#1162]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```inside these 3 quotes/grave accents```
(Delete this text when you've read it)

<details>
  <summary> Compile log (...)</summary>

  

</details>
<br><br><br>

**Comment by tobozo** [comment]
just follow all the steps in the [wiki](https://github.com/spacehuhn/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide) and your problem will be solved
