### ISSUE TITLE
Both Master And Testing File not working

### ISSUE THREAD

**Issue by DevShekhawat7** [spacehuhn/esp8266_deauther#118]
So I have used previous version(code), everything was working as mentioned.
but now I am unable to scan my network(pwned) on any of my devices. And when I re-upload the previous code it starts working again.

**Comment by N0vaPixel** [comment]
The "hide AP" feature seems to be enabled. Open the arduino monitor and look at the settings when the esp starts.

**Comment by DevShekhawat7** [comment]
it worked! apparently my ssid was hidden by default. thanks!
