### ISSUE TITLE
no matching function for call to 'ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(int)'

### ISSUE THREAD

**Issue by the-mcnaveen** [spacehuhn/esp8266_deauther#1180]
<details>
  <summary> no matching function for call to 'ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(int)'</summary>

Arduino: 1.8.10 (Linux), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Serial, 80MHz, DIO, 115200, 1M (256K SPIFFS)"

sketch/Names.cpp: In member function 'void Names::load()':
Names.cpp:10:38: error: no matching function for call to 'ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(int)'
     DynamicJsonBuffer jsonBuffer(4000);
                                      ^
sketch/Names.cpp:10:38: note: candidates are:
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:7:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/Names.h:10,
                 from sketch/Names.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note: ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer()
   DynamicJsonBuffer();
   ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note:   candidate expects 0 arguments, 1 provided
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note: constexpr ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(const ArduinoJson::DynamicJsonBuffer&)
 class DynamicJsonBuffer : public JsonBuffer {
       ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note:   no known conversion for argument 1 from 'int' to 'const ArduinoJson::DynamicJsonBuffer&'
sketch/Settings.cpp: In member function 'void Settings::load()':
Settings.cpp:9:38: error: no matching function for call to 'ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(int)'
     DynamicJsonBuffer jsonBuffer(4000);
                                      ^
sketch/Settings.cpp:9:38: note: candidates are:
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:7:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/Settings.h:9,
                 from sketch/Settings.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note: ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer()
   DynamicJsonBuffer();
   ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note:   candidate expects 0 arguments, 1 provided
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note: constexpr ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(const ArduinoJson::DynamicJsonBuffer&)
 class DynamicJsonBuffer : public JsonBuffer {
       ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note:   no known conversion for argument 1 from 'int' to 'const ArduinoJson::DynamicJsonBuffer&'
sketch/Settings.cpp: In member function 'String Settings::getJsonStr()':
Settings.cpp:124:38: error: no matching function for call to 'ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(int)'
     DynamicJsonBuffer jsonBuffer(4000);
                                      ^
sketch/Settings.cpp:124:38: note: candidates are:
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:7:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/Settings.h:9,
                 from sketch/Settings.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note: ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer()
   DynamicJsonBuffer();
   ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note:   candidate expects 0 arguments, 1 provided
sketch/SSIDs.cpp: In member function 'void SSIDs::load()':
SSIDs.cpp:9:38: error: no matching function for call to 'ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(int)'
     DynamicJsonBuffer jsonBuffer(4000);

                                      ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note: constexpr ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(const ArduinoJson::DynamicJsonBuffer&)
 class DynamicJsonBuffer : public JsonBuffer {
       ^
sketch/SSIDs.cpp:9:38: note: candidates are:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note:   no known conversion for argument 1 from 'int' to 'const ArduinoJson::DynamicJsonBuffer&'
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:7:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/SSIDs.h:10,
                 from sketch/SSIDs.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note: ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer()
   DynamicJsonBuffer();
   ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:25:3: note:   candidate expects 0 arguments, 1 provided
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note: constexpr ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(const ArduinoJson::DynamicJsonBuffer&)
 class DynamicJsonBuffer : public JsonBuffer {
       ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/DynamicJsonBuffer.hpp:23:7: note:   no known conversion for argument 1 from 'int' to 'const ArduinoJson::DynamicJsonBuffer&'
SSIDs.cpp:13:60: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonArray&' from an rvalue of type 'ArduinoJson::JsonArray'
     JsonArray & arr = obj.get<JsonArray>(str(SS_JSON_SSIDS));

                                                            ^
Settings.cpp:166:21: error: no matching function for call to 'ArduinoJson::JsonObject::printTo(String&)'
     data.printTo(buf);
                     ^
sketch/Settings.cpp:166:21: note: candidates are:
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonArray.hpp:10:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:8,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/Settings.h:9,
                 from sketch/Settings.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/Internals/JsonPrintable.hpp:25:10: note: size_t ArduinoJson::Internals::JsonPrintable<T>::printTo(Print&) const [with T = ArduinoJson::JsonObject; size_t = unsigned int]
   size_t printTo(Print &print) const {
          ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/Internals/JsonPrintable.hpp:25:10: note:   no known conversion for argument 1 from 'String' to 'Print&'
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/Internals/JsonPrintable.hpp:31:10: note: size_t ArduinoJson::Internals::JsonPrintable<T>::printTo(char*, size_t) const [with T = ArduinoJson::JsonObject; size_t = unsigned int]
   size_t printTo(char *buffer, size_t bufferSize) const {
          ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/Internals/JsonPrintable.hpp:31:10: note:   candidate expects 2 arguments, 1 provided
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonObject.hpp:98:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:9,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/SSIDs.h:10,
                 from sketch/SSIDs.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonObject.ipp: In instantiation of 'T ArduinoJson::JsonObject::get(ArduinoJson::JsonObjectKey) const [with T = ArduinoJson::JsonArray]':
sketch/SSIDs.cpp:13:60:   required from here
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonObject.ipp:22:71: error: use of deleted function 'ArduinoJson::JsonArray::JsonArray(ArduinoJson::JsonArray&&)'
   return node ? node->content.value.as<T>() : JsonVariant::invalid<T>();
                                                                       ^
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:8:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/SSIDs.h:10,
                 from sketch/SSIDs.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonArray.hpp:33:7: note: 'ArduinoJson::JsonArray::JsonArray(ArduinoJson::JsonArray&&)' is implicitly deleted because the default definition would be ill-formed:
 class JsonArray : public Internals::JsonPrintable<JsonArray>,
       ^
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonArray.hpp:12:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:8,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/SSIDs.h:10,
                 from sketch/SSIDs.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/Internals/ReferenceType.hpp:28:3: error: 'ArduinoJson::Internals::ReferenceType::ReferenceType(const ArduinoJson::Internals::ReferenceType&)' is private
   ReferenceType(const ReferenceType&);
   ^
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:8:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/SSIDs.h:10,
                 from sketch/SSIDs.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonArray.hpp:33:7: error: within this context
 class JsonArray : public Internals::JsonPrintable<JsonArray>,
       ^
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonVariant.hpp:102:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonArray.hpp:13,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:8,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/SSIDs.h:10,
                 from sketch/SSIDs.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonVariant.ipp: In instantiation of 'T ArduinoJson::JsonVariant::as() const [with T = ArduinoJson::JsonArray]':
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonObject.ipp:22:15:   required from 'T ArduinoJson::JsonObject::get(ArduinoJson::JsonObjectKey) const [with T = ArduinoJson::JsonArray]'
sketch/SSIDs.cpp:13:60:   required from here
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonVariant.ipp:92:50: error: use of deleted function 'ArduinoJson::JsonArray::JsonArray(ArduinoJson::JsonArray&&)'
   return is<T>() ? _content.as<T>() : invalid<T>();
                                                  ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonVariant.ipp: In instantiation of 'static T ArduinoJson::JsonVariant::invalid() [with T = ArduinoJson::JsonArray]':
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonObject.ipp:22:71:   required from 'T ArduinoJson::JsonObject::get(ArduinoJson::JsonObjectKey) const [with T = ArduinoJson::JsonArray]'
sketch/SSIDs.cpp:13:60:   required from here
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonVariant.ipp:97:12: error: no matching function for call to 'ArduinoJson::JsonArray::JsonArray()'
   return T();
            ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonVariant.ipp:97:12: note: candidate is:
In file included from /home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson.h:8:0,
                 from /home/ninja/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:13,
                 from sketch/SSIDs.h:10,
                 from sketch/SSIDs.cpp:1:
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonArray.hpp:41:12: note: ArduinoJson::JsonArray::JsonArray(ArduinoJson::JsonBuffer*)
   explicit JsonArray(JsonBuffer *buffer)
            ^
/home/ninja/Arduino/libraries/ArduinoJson/src/../include/ArduinoJson/JsonArray.hpp:41:12: note:   candidate expects 1 argument, 0 provided
Multiple libraries were found for "Adafruit_NeoPixel.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/Adafruit_NeoPixel-1.1.6
Multiple libraries were found for "ESP8266WebServer.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/ESP8266WebServer
Multiple libraries were found for "DNSServer.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/DNSServer
Multiple libraries were found for "EEPROM.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/EEPROM
Multiple libraries were found for "ArduinoJson.h"
 Used: /home/ninja/Arduino/libraries/ArduinoJson
 Not used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/ArduinoJson
Multiple libraries were found for "SH1106Wire.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/esp8266-oled-ssd1306-4.0.0
Multiple libraries were found for "SimpleButton.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/SimpleButton
Multiple libraries were found for "ESP8266mDNS.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/ESP8266mDNS
Multiple libraries were found for "Wire.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/Wire
Multiple libraries were found for "SPI.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/SPI
Multiple libraries were found for "ESP8266WiFi.h"
 Used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/ESP8266WiFi
exit status 1
no matching function for call to 'ArduinoJson::DynamicJsonBuffer::DynamicJsonBuffer(int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

</details>
<br><br><br>

**Comment by tobozo** [comment]
Used: /home/ninja/Arduino/libraries/ArduinoJson
   Not used: /home/ninja/.arduino15/packages/deauther/hardware/esp8266/2.0.0-deauther/libraries/ArduinoJson

delete the "Used" folder (`/home/ninja/Arduino/libraries/ArduinoJson`) and it'll use the other one from the deauther sdk

**Comment by the-mcnaveen** [comment]
Thanks man, It worked.

**Comment by ryaneditraj** [comment]
bro, what about Mac ?
