### ISSUE TITLE
Problem uploading code to the ESP8266 ! 

### ISSUE THREAD

**Issue by cristi091** [spacehuhn/esp8266_deauther#1182]
I cannot upload the code to the board because : 
Multiple libraries were found for "EEPROM.h"
esp8266_deauther:16:25: error: ArduinoJson.h: No such file or directory

Multiple libraries were found for "SPI.h"
In file included from sketch\Settings.h:11:0,

 Used: C:\Users\cri$ti\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\SPI
Multiple libraries were found for "EEPROM.h"
                 from C:\Users\cri$ti\Documents\esp8266_deauther-master\esp8266_deauther\esp8266_deauther.ino:27:

 Used: C:\Users\cri$ti\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\EEPROM
A_config.h:7:24: error: SH1106Wire.h: No such file or directory

Multiple libraries were found for "ArduinoJson.h"
 #include "SH1106Wire.h"

 Used: C:\Users\cri$ti\Documents\Arduino\libraries\ArduinoJson
                        ^

Multiple libraries were found for "Wire.h"
compilation terminated.

 Used: C:\Users\cri$ti\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\Wire
exit status 1
SH1106Wire.h: No such file or directory

<details>
  <summary> Compile log (...)</summary>

  

</details>
<br><br><br>

**Comment by altimmons** [comment]
So fix your libraries...

Try using platform io in vs code. 

In your platform.ini file specify each library under lib_deps=

**Comment by itsmemohit** [comment]
- Delete all libraries named EEPROM.h
Download library from below given link: 
https://github.com/PaulStoffregen/EEPROMand locate the library from this link

Multiple libraries were found for "ArduinoJson.h"
SIMILARLY Delete libraries naming ArduinoJson.h and download the lobrary from here :https://github.com/bblanchon/ArduinoJson
 and locate in your system

**Comment by jLynx** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki
