### ISSUE TITLE
Error message when trying to upload in arduino

### ISSUE THREAD

**Issue by lesquieshia** [spacehuhn/esp8266_deauther#1191]
'''Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Uno"

esp8266_deauther:12:12: error: user_interface.h: No such file or directory

   #include "user_interface.h"

            ^~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1
user_interface.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.'''

**Comment by beckerichmika** [comment]
First install the esp8266-specific board configs and select it as upload target because you selected the Arduino UNO instead of the esp8266 which can lead to such errors. Then try again

**Comment by jLynx** [comment]
RTFM https://github.com/spacehuhn/esp8266_deauther/wiki
