### ISSUE TITLE
QUESTION - What's That probe option?

### ISSUE THREAD

**Issue by FrostyModz** [spacehuhn/esp8266_deauther#120]
I'm on v1.1 and I am wondering, what's that probe option under attacks menu. So. What is it. How do I use it. And what can it be used for

**Comment by poslogic** [comment]
Hi,

It is related to this feature request.

https://github.com/spacehuhn/esp8266_deauther/issues/102

**Comment by tobozo** [comment]
It performs the [Evil Twin](http://www.kalitutorials.net/2014/07/evil-twin-tutorial.html) attack (or is it [KARMA](https://insights.sei.cmu.edu/cert/2015/08/instant-karma-might-still-get-you.html)?),

**Comment by spacehuhn** [comment]
> It performs the Evil Twin attack (or is it KARMA?),

not really. It just asks for non existing networks from a non existing MAC adress. WiFi trackers search for these packets and will think there are dozents of clients nearby.

**Comment by scarfasss** [comment]
Is there a practical way to see this probe request spam? My wifi tracker is not picking up any of it when turned on.

Thanks!

**Comment by spacehuhn** [comment]
You could use airodump-ng to or any other advanced scanner which picks up client packets.
