### ISSUE TITLE
Dstike Wristband V2 White Led Code

### ISSUE THREAD

**Issue by gorkalombar** [spacehuhn/esp8266_deauther#1203]
Hello y'all!

I'm newbie in this world, and that's why I'm asking for help here.
Yes, I have done a long research through the Internet and the open o closed previous issues, but I didn't found anything about this.

**Descripton**
I recently got the Dstike Wristband V2 (with an RTC on it). I'm really happy with it, really good board for starting into arduino. The problem is that when it arrived, on the main menu there was an option under all the other things which was an option to enable a white led that is on the left side of the watch. And I wanted to make some changes in the code, just for customising a little bit the board (the blue led indicator, the boot message, buttons speed... small little things that I can understand just reading the code), and I did it, and uploaded to the board by the Arduino IDLE.
But now, the option in the menu to activate the white LED is not longer available, and I don't have any idea about how to code it, and where to do it. And I can´t find anywhere the original specific code for this watch.
Is there anyone who knows how to do this? It would be great if someone has the complete code, so I can have a look at it.

Thank you!!!

![IMG_20200114_092608](https://user-images.githubusercontent.com/38617497/72327375-3f758880-36b1-11ea-8678-67131b78dc7e.jpg)

**Comment by mattyams** [comment]
Add this line to your A_config file, compile and upload. 

#define HIGHLIGHT_LED 16 (or whatever GPIO pin the LED is on)
