### ISSUE TITLE
[question] Would xcluma CH340 USB to ESP8266 work?

### ISSUE THREAD

**Issue by sayem314** [spacehuhn/esp8266_deauther#1205]
here is the amazon link, it's cheap so!
https://www.amazon.in/xcluma-ESP8266-Wireless-Development-Microcontroller/dp/B07CSMDS76/ref=sr_1_5?keywords=esp8266&qid=1579248223&sr=8-5#customerReviews

**Comment by yippiez** [comment]
@sayem314 Work for what? it is a board for programming your [esp8266](https://www.amazon.com/DIYmall-ESP8266-ESP-01S-Serial-Transceiver-x/dp/B00O34AGSU). it is not one itself.Have you misunderstood it for an esp8266 board like [this](https://www.amazon.com/Makerfocus-NodeMcu-Development-ESP8266-Compatible/dp/B01N3P763C)?

**Comment by sayem314** [comment]
@yippiez yeah I think I misunderstood. Thanks for pointing out :)
