### ISSUE TITLE
Downloading 'DSTIKE Deauther OLED Mini' bin file from https://github.com/spacehuhn/esp8266_deauther/releases downloads wristband bin file instead.

### ISSUE THREAD

**Issue by Booooozo** [spacehuhn/esp8266_deauther#1211]
Downloading 'DSTIKE Deauther OLED Mini' bin file from https://github.com/spacehuhn/esp8266_deauther/releases downloads wristband bin file instead.

**Comment by bfgelectronics** [comment]
It's the same file , i tryed to flash on my deauther mini and it works just fine

**Comment by jLynx** [comment]
Closed as there was no issue described here.
