### ISSUE TITLE
Removed SSID then saved after making network hidden, can't connect.

### ISSUE THREAD

**Issue by cc1279** [spacehuhn/esp8266_deauther#1215]
So I made the network hidden in settings then saved it, can't connect to the network because of unknown SSID. Using WeMos D1 Mini

**Comment by cc1279** [comment]
I can remember that it automatically filled the text box with something but i can't remember what that was.

**Comment by jLynx** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#how-to-do-a-reset
