### ISSUE TITLE
serialcommands.md page 404!

### ISSUE THREAD

**Issue by shuimoshusheng** [spacehuhn/esp8266_deauther#1239]

**Comment by shuimoshusheng** [comment]
Wiki's Serial Commands link page 404.
when I click on it, jump to this page [https://github.com/SpacehuhnTech/esp8266_deauther/blob/master/serialcommands.md](url)

**Comment by spacehuhn** [comment]
Thank you, I fixed the link. It's 
https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/serialcommands.md
