### ISSUE TITLE
WiFiEventHandler does not name a type

### ISSUE THREAD

**Issue by scargill** [spacehuhn/esp8266_deauther#124]
Hi

Copied the instructions - before realising I had to overwrite 2 files it compiled fine - over-wrote the two files and now (this is version 2.30 - reasonably current)

error - WiFiEventHandler does not name a type

(gives that error twice..)

**Comment by spacehuhn** [comment]
You need to use v.2.0.0 of the SDK and follow every installation step carefully.

**Comment by N0vaPixel** [comment]
This is not the expressif SDK
[https://github.com/esp8266/Arduino](url)

Follow the readme.md file

**Comment by rajatpunkstaa** [comment]
I am using official Arduino IDE and esp version 2.3.0 and getting the same error:
Arduino: 1.8.1 (Linux), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from xxx/yyy/Downloads/esp8266_deauther-master/esp8266_deauther/esp8266_deauther.ino:5:0:
/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266mDNS/ESP8266mDNS.h:117:3: error: 'WiFiEventHandler' does not name a type
   WiFiEventHandler _disconnectedHandler;
   ^
/xxx/yyy/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266mDNS/ESP8266mDNS.h:118:3: error: 'WiFiEventHandler' does not name a type
   WiFiEventHandler _gotIPHandler;
   ^
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Any suggestions ??

**Comment by Fireflaker** [comment]
try upload ver1.1 bin file instead of ver1.0 arduino file
Rajat Gupta <notifications@github.com>于2017年3月29日 周三下午2:36写道：

**Comment by Fireflaker** [comment]
By  the way, i have not successfully flash this board at 115200 baud EVER!
It prints "flash at 9600 baud” on the other side of board. Try so and you
might be amazed.
NodeMCU 1.0,9600,80MHz,4M(does not matter), works for me and is relatively
stable.



wzd leo <leowzd@gmail.com>于2017年3月29日 周三下午2:38写道：

**Comment by Fireflaker** [comment]
Choose the right compiler.
The compiler is not the default compiler for arduino uno 
I am not exactly sure but it should be called Arduino IDE
