### ISSUE TITLE
www.msftconnecttest.com window shows up instead of evil twin wifi login page

### ISSUE THREAD

**Issue by dreamshape** [spacehuhn/esp8266_deauther#1241]
Sorry in advance if this isn't the good place to ask for that but I recently managed to make the deauther running on my nodeMCU and everything works fine but when I try to test airgeddon on my computer instead of opening chrome with the fake login page it instead redirect me to the deauther user interface, any way to fix that?

**Comment by M1z23R** [comment]
Go to the deauther user interaface - settings - disable captive portal (disables fake dns server that's redirecting all traffic to the user interface)
