### ISSUE TITLE
configs folder missing

### ISSUE THREAD

**Issue by gd21584** [spacehuhn/esp8266_deauther#1243]
The folder for the configs gives a 404. Any idea where I could find the configs now?
https://github.com/SpacehuhnTech/esp8266_deauther/tree/master/configs

**Comment by spacehuhn** [comment]
All configs are now in the [`A_config.h`](https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/esp8266_deauther/A_config.h) file directly. 
Thanks for the note, I updated the wiki.

For reference, here you can still find the old configs folder: https://github.com/SpacehuhnTech/esp8266_deauther/tree/fda01a64861f3e0e8e9379a8e8ed743cb56038f7/configs
