### ISSUE TITLE
Deauther OLED Mini. Missing power button?

### ISSUE THREAD

**Issue by Romcollector** [spacehuhn/esp8266_deauther#1248]
After changing from Deauther V5 to Deauther mini I found that the mini has no power button. Am I missing a way to turn it off without deconnecting it from its power source?

**Comment by adi17082** [comment]
they have a new model DSTIKE DeautherMiNi EVO

( https://dstike.com/products/dstike-deauthermini-evo )

**Comment by adi170-alt** [comment]
> they have a new model DSTIKE DeautherMiNi EVO
> 
> ( https://dstike.com/products/dstike-deauthermini-evo )

BROOOO, I don't even remember writing this, that what I wrote it nonsense lol
