### ISSUE TITLE
Allowing spam ssids to be actuall networks and custom passwords

### ISSUE THREAD

**Issue by OfficialEnlightGames** [spacehuhn/esp8266_deauther#125]
how can we have a code to allow spam ssids to be actual networks you can join and allow the jammer to be a tool for e.g have 1 custom ssid on the list but allow to add a password and set the type of security and it will allow to connect like a wifi repeater

Having following tabs

APs
Tools
Settings

tools that could be added...

wifi repeater
wifi hotspot for lan partys
wifi jammer
wifi checker aka ping, connected devices, block device (cliend side) etc

please can this be in the next update so i dont have to get different esp8266 boards for different tools

(EDIT) this can be a new project of you want and can we have a bootstrap theme or osmething like that please?

**Comment by spacehuhn** [comment]
![That's not how this works. That's not how any of this works.](https://cloud.githubusercontent.com/assets/3826044/24034816/29672a36-0af3-11e7-8deb-405f0405dfc1.jpg)
