### ISSUE TITLE
Newer sdk support

### ISSUE THREAD

**Issue by M1z23R** [spacehuhn/esp8266_deauther#1250]
Is it possible to enable wifi_send_pkt_freedom in newer sdk or is 2.0.0 with modified wifi/ user libs a must?

Edit:
I've done a few hour research regarding the wifi_send_pkt_freedom, apparently they didn't remove the wifi_send_pkt_freedom function (which i already knew), they've modified it to check for first 2 bytes of the packet and detect if it's management packet and return false if it is (the constant -1). I am trying to figure out how to find the source file that's using user_interface.h and remove the mgmt packet condition if possible, however I am still unable to find the correct file and I am not really sure how. I've found a lot of files that are using that header file but non of them have this.
Any help would be appreciated.

**Comment by spacehuhn** [comment]
It's in here https://github.com/esp8266/Arduino/blob/master/tools/sdk/lib/NONOSDK22x_190313/libnet80211.a 

You can donwload the file and unpack, it's an archive. Inside you will find a file `ieee80211_output.a` that's where the magic happens.

(Though they now have a multitude of different SDKs packaged into the arduino core, so there could be differences:
https://github.com/esp8266/Arduino/tree/master/tools/sdk/lib)

**Comment by M1z23R** [comment]
Thank you for your answer. Honestly, this goes beyond my skill and knowledge so I'll have to settle for 2.0.0
