### ISSUE TITLE
DOITEsp32DevKitv1 I can't find the library

### ISSUE THREAD

**Issue by wmauti** [spacehuhn/esp8266_deauther#1252]
![image](https://user-images.githubusercontent.com/42239154/83953054-9127d680-a83d-11ea-957e-9db3968ad45d.png)
I can't find on arduino ide the library I also added the following links for the board manager
(https://dl.espressif.com/dl/package_esp32_index.json
http://arduino.esp8266.com/stable/package_esp8266com_index.json)

**Comment by spacehuhn** [comment]
What is it you can't find?
Maybe the official guide will help you: https://github.com/SpacehuhnTech/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide

**Comment by spacehuhn** [comment]
Remember to look int the **boards manager** not the **library manager** in Arduino IDE.
