### ISSUE TITLE
No Deauth packets

### ISSUE THREAD

**Issue by nGErWeigHtEMI** [spacehuhn/esp8266_deauther#1257]
#https://github.com/SpacehuhnTech/esp8266_deauther/issues/1088
my case
reproduce :
-I select one or multi APs
-On attack tab
-click start

( deauth method can not send any ptks but after symbol slash have number (Deauths: 0/40)
probes and beacons method still work )
[Pkt/s] All: 0 | Deauths: 0/80  | Beacons: 0/0 | Probes: 0/0
[Pkt/s] All: 0 | Deauths: 0/80  | Beacons: 0/0 | Probes: 0/0
[Pkt/s] All: 0 | Deauths: 0/80  | Beacons: 0/0 | Probes: 0/0
[Pkt/s] All: 0 | Deauths: 0/80  | Beacons: 0/0 | Probes: 0/0
[Pkt/s] All: 0 | Deauths: 0/80  | Beacons: 0/0 | Probes: 0/0

<details>
  <summary> Serial Monitor</summary>

# sysinfo
[======== SYSTEM INFO ========]
RAM usage: 60080 bytes used [74%], 21840 bytes free [26%], 81920 bytes in total

Current WiFi channel: 9
AP MAC address: 00:18:e7:a3:8f:11
Station MAC address: 00:14:5f:56:fc:c8
SPIFFS: 4016 bytes used [0%], 953298 bytes free [99%], 957314 bytes in total
        block size 8192 bytes, page size 256 bytes
Files: 
  /settings.json 502 bytes
  /names.json 2 bytes
  /ssids.json 318 bytes
  /autostart.txt 19 bytes
  /scan.json 1178 bytes
[WiFi] Path: '/web', Mode: 'AP', SSID: 'pwned', password: 'deauther', channel: '10', hidden: false, captive-portal: true
===============================
[AP] request: /connecttest.txt# save scan
# save names
[AP] request: /scan.json  OK
[AP] request: /names.json  OK
# select ap 0
Selected access point 210DS
# select ap 1
Selected access point TaDaKe
# select ap 2
Selected access point SSSS
# select ap 3
Selected access point danielaazuaje_
# attack -d
Start attacking
[Pkt/s] All:    0 | Deauths:   0/80  | Beacons:   0/0   | Probes:   0/0  
[Pkt/s] All:    0 | Deauths:   0/80  | Beacons:   0/0   | Probes:   0/0  
[Pkt/s] All:    0 | Deauths:   0/80  | Beacons:   0/0   | Probes:   0/0  
[Pkt/s] All:    0 | Deauths:   0/80  | Beacons:   0/0   | Probes:   0/0  
[Pkt/s] All:    0 | Deauths:   0/80  | Beacons:   0/0   | Probes:   0/0  

</details>

Issue when flash with my arduino 1.8.12 ( i just config settings.h file & installed board 2.1.0 ). no error show in when upload project to module.

Please tell me anything to solve.
p/s: No issue if auto flash with n2d2 tool

<br><br><br>

**Comment by nGErWeigHtEMI** [comment]
it also can't send to detect stations

Scan results saved in /scan.json
Starting Scan for stations (client devices) - 15s
Stopped Access Point
Scanning WiFi [20%]:   0 packets/s |  0 devices |  0 deauths
Scanning WiFi [40%]:   0 packets/s |  0 devices |  0 deauths
Scanning WiFi [60%]:   0 packets/s |  0 devices |  0 deauths
Scanning WiFi [80%]:   0 packets/s |  0 devices |  0 deauths
[===== Stations =====]
Station list is empty :(

**Comment by spacehuhn** [comment]
>  installed board 2.1.0

You need 2.0.0 or rather the Deauther SDK by Tobozo
https://github.com/SpacehuhnTech/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide
