### ISSUE TITLE
Is there a way to make the deauther target one device on that network instead of all of the devices?

### ISSUE THREAD

**Issue by Skullcodz** [spacehuhn/esp8266_deauther#1259]
Is there a way to make the deauther target one device on that network instead of all of the devices?

**Comment by spacehuhn** [comment]
Yes you can scan for stations (client devices) and select one of those as a target.

**Comment by Skullcodz** [comment]
> Yes you can scan for stations (client devices) and select one of those as a target.

when i do that i click reload but the vendors section on the stations are always blank is there a way to fix this so i can see what device is which?
