### ISSUE TITLE
Attack page blanck when AP is selected

### ISSUE THREAD

**Issue by duan78** [spacehuhn/esp8266_deauther#126]
Hi, when I select an AP : the attack page return me a blanck page (if I don't select an AP, attack page work but tell me to add AP...)

What am I missing ?

**Comment by spacehuhn** [comment]
Can you test this on a computer and use the developer tools of your browser to see if it throws an error?
This sounds like some JSON parsing error.

**Comment by duan78** [comment]
I did, nothing on console (blank) & no error on network

**Comment by duan78** [comment]
Pressed the reset button : it work fine now : thx for this great PoF
