### ISSUE TITLE
after compiling does not allow to connect to pwned

### ISSUE THREAD

**Issue by mac3d0** [spacehuhn/esp8266_deauther#1264]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

After I compiled the new version of the deauther by Arduino, it presents an error, it doesn't let me connect to the pwned wif-fi and its led is flashing and not fixed.
The old version I did not have this problem.

Error/Compile/Output Log

**Comment by spacehuhn** [comment]
> I compiled the new version

Which version are youb referring to?
If you're talking about [v3](https://github.com/SpacehuhnTech/esp8266_deauther/tree/v3), it's cleary stated that there is **no web interface available** yet. You must use the serial command line.
