### ISSUE TITLE
How to Use "captive Portal" in Settings WebUI

### ISSUE THREAD

**Issue by revanthshiva** [spacehuhn/esp8266_deauther#1268]
in Web UI settings a feature called captive portal how to use  it

**Comment by ghost** [comment]
Captive Portal is a feature where any HTTP request (that isn't secure) is redirected to the deauther page and pops up that 'Sign in to WiFi' message you might see in Coffee shops.

**Comment by revanthshiva** [comment]
> Captive Portal is a feature where any HTTP request (that isn't secure) is redirected to the deauther page and pops up that 'Sign in to WiFi' message you might see in Coffee shops.

How i can use the both Feature  as "deauther and captive portal" in ESP8266 +oled bro 



How to use the captive portal in deauther

**Comment by ghost** [comment]
If you're using OLED, just use the display! 😂
Captive Portal just allows easier access to the web interface on another device.

To use captive potal, enable it and restart the deauther. Then connect to it via WiFi ``pwned:deauther`` and you should see a popup on your phone / tablet. Captive Portal doesn't work well on computers (Idk, maybe just me) so if you don't see a popup, open a web browser to ``192.168.4.1``
