### ISSUE TITLE
Deauther v3/nightly Deauther

### ISSUE THREAD

**Issue by cpu2020** [spacehuhn/esp8266_deauther#1269]
Hi,

i am using the nightly deauther on my esp8266 node mcu chip it works good i use the cli.
Is There a web interface for this version or is that not a thing

Thanks,
Cpu

**Comment by ghost** [comment]
This version does not currently have the web interface. The web interface will be added in future releases.

**Comment by cpu2020** [comment]
Hi,


Ah ok thank you i wasnt sure if it was or not.


Thanks



Cpu
