### ISSUE TITLE
Getting 'espcomm_sync failed' error when uploading

### ISSUE THREAD

**Issue by Spencer008** [spacehuhn/esp8266_deauther#127]
I understand that this problem may have been addressed, but the solutions listed are not fixing my issue. I keep getting these errors

warning: espcomm_sync failed
error: espcomm_open failed

I've read all the suggestions but none of them have worked. I appreciate any and all help, hope it fixes my problem.

**Comment by spacehuhn** [comment]
All information we can possible provide you is in the readme (see FAQ).

this isn't related to the project, but you may wanna go to the arduino or esp8266 forum. There are a lot of forum threads about this exact error.
