### ISSUE TITLE
Won't turn on (red LED and three battery LEDs)

### ISSUE THREAD

**Issue by turkeyphant** [spacehuhn/esp8266_deauther#1272]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**
Charged via USB.
During charging third battery LED (from the top) went off.
Now won't turn on.

One power press makes the three battery LEDs shine green:

ON
ON
OFF
ON

And a red LED above the chip (second from left).

The main RGB LED doesn't even flicker and the display is blank.

It turns off after about 15 seconds.

Turning off with double press of power switch also works.

**Expected behavior**
Works normally. Turns on and off. Menu and features work,

**Screenshots**

**Environment (please complete the following information):**
 - Hardware DSTIKE v3.5

**Comment by lspoplove** [comment]
-----Original Message-----

**Comment by turkeyphant** [comment]
Still stuck in this mode and won't turn on.

**Comment by turkeyphant** [comment]
![2020-08-15 16 29 55](https://user-images.githubusercontent.com/8129583/90315685-38e41380-df15-11ea-8b20-22e63dd1f95e.jpg)

**Comment by Bommlon** [comment]
Have you tried re-flashing the board? If this doesn't help it could be a problem with the board. Try contacting DSTIKE if that's the case.

**Comment by turkeyphant** [comment]
I have tried reflashing the board but neither of the two recommended software work (have tried on a Windows 10 PC and a macOS laptop).

esptool can't connect to it in both instances for some reason.
