### ISSUE TITLE
about captive portal

### ISSUE THREAD

**Issue by iaemonbd** [spacehuhn/esp8266_deauther#1275]
at first Thank you spacehuhntech for giving us such an awesome game changing tool.
My question is how to use captive portal? . It's really work.?
When daughter version 3 will come?
Please answer my question soon as possible

**Comment by Bommlon** [comment]
Your question about the captive portal was already answered in [this thread](https://github.com/SpacehuhnTech/esp8266_deauther/issues/1234).

**Comment by Bommlon** [comment]
Deauther v3 is still in development
