### ISSUE TITLE
The liitle chip infront off the micro usb port gets really hot.

### ISSUE THREAD

**Issue by christianzee2002** [spacehuhn/esp8266_deauther#128]
# General
the board chip gets really hot the second i give it power. I have the old verson loaded but i cant upload any new code to it. Ideas?

**Comment by christianzee2002** [comment]
my computer also doesnt recognize it anymore. It used to

**Comment by spacehuhn** [comment]
sounds like a defective USB serial chip. 

But this isn't related to this project!
