### ISSUE TITLE
Deauth device on startup without scan

### ISSUE THREAD

**Issue by chinswain** [spacehuhn/esp8266_deauther#1284]
Is there a way to attack a device on boot by mac address without selecting it from a scan?

I've tried adding this to autostart (after saving the device name):

write autostart.txt scan -t 5s
write autostart.txt select name mydevice
write autostart.txt attack -d

But the attack does not work. Is it possible to attack without a scan and via the mac address?

**Comment by vovanhau** [comment]
help
