### ISSUE TITLE
Hidden ssid

### ISSUE THREAD

**Issue by mhenos** [spacehuhn/esp8266_deauther#1286]
como faço para buscar ssid oculto?

**Comment by vexxrs** [comment]
Se um ssid oculto estiver ao alcance, e usando 2,4GHz. 
Será mostrado na lista como *HIDDEN*

**Comment by spacehuhn** [comment]
está certo

**Comment by mhenos** [comment]
ok obrigado

Em seg., 26 de out. de 2020 às 07:11, Stefan Kremser <
notifications@github.com> escreveu:
