### ISSUE TITLE
Please add Korean.

### ISSUE THREAD

**Issue by Renyu106** [spacehuhn/esp8266_deauther#1293]
I think it would be good to add Korean.
So I made a Korean language file.

https://drive.google.com/file/d/1_iDu95ZQk9aTtyM2tyZX06olTMO4CzVr/view?usp=sharing

**Comment by spacehuhn** [comment]
Thank you, I added it.

**Comment by Pen-Spinner** [comment]
2021-01-15 0:19 GMT+03:00, Stefan Kremser <notifications@github.com>:
