### ISSUE TITLE
Buttons no longer function + display is upside down

### ISSUE THREAD

**Issue by JxmesW** [spacehuhn/esp8266_deauther#1296]
I have flashed 2.5 to my board - updating from 2.1.0.
Everything was functional until upgrading; now the display is upside down and the buttons do not do anything when pushed.

What could be causing this?

**Comment by Bommlon** [comment]
Maybe you've selected the wrong board when flashing.

**Comment by VIS-WA** [comment]
find this line in A_config.h file
#define FLIP_DIPLAY false
change fit to  #define FLIP_DISPLAY true
