### ISSUE TITLE
Help with Oled, Buttons and Neopixel

### ISSUE THREAD

**Issue by Nikakz** [spacehuhn/esp8266_deauther#1297]
Hello, I managed to make the web interface work well, but I could not configure the oled screen, the neopixel led and the buttons, as I am a beginner I did not understand where to enable everything in the code, I am using a node mcu v1.0, could someone help me ? Oled using pins: GND GND
VCC / VDD VCC / 3.3V
SCL / CLK / SCK GPIO 4 (D2)
SDA GPIO 5 (D1), buttons:
GPIO Button
UP GPIO 14 (D5)
Down GPIO 12 (D6)
GPIO 13 (D7)
NEOPIXEL LED GPIO
GND GND
VCC VCC / 3.3V
DIN GPIO 16 (D0)

**Comment by spacehuhn** [comment]
For reference, this is the page you want to be reading: https://github.com/SpacehuhnTech/esp8266_deauther/wiki/Setup-Display-&-Buttons
