### ISSUE TITLE
Include client's signal strength

### ISSUE THREAD

**Issue by doge27** [spacehuhn/esp8266_deauther#13]
Please add clients signal strength as it is in AP.

**Comment by spacehuhn** [comment]
This is not possible sorry. There is no way to get the signal strength from user packets with the SDK functions.
http://bbs.espressif.com/viewtopic.php?t=683

**Comment by doge27** [comment]
Is it possible to increase deauth packets? Any advantage from increasing it?

**Comment by spacehuhn** [comment]
Yes is possible but no won't give you any advantage.

**Comment by doge27** [comment]
What I noticed that is the clients which are far from the access point are not getting disconnected. Can you please explain why is that?

**Comment by spacehuhn** [comment]
Because they probably don't get the deauth packets. This is a tiny >$2 chip you can't assume it has the same transmition power than a computers Wi-Fi card.

**Comment by doge27** [comment]
But I have found that transmit power of esp8266 is set to low to consume minimum current. Is it possible to increase transmit power using setOutputPower?

**Comment by spacehuhn** [comment]
just try it out then.

**Comment by doge27** [comment]
How?

**Comment by doge27** [comment]
Where to define it?

**Comment by tpmodding** [comment]
gibt schon penetrante leute

**Comment by doge27** [comment]
After setting max TX power, the signal strength increased from -73 to -65
