### ISSUE TITLE
Deauthuer 2.5 Users not showing

### ISSUE THREAD

**Issue by PumpP** [spacehuhn/esp8266_deauther#1301]
Hello all, I'm new to this and I have tested my first projet which is the deauther version 2.5, all seems to work okay but I cannot see users connected to my network, I have seen a screenshot of this same program that had a user tab at the top next to scan.
Have I missed something?

**Comment by ghost** [comment]
Try installing this version v2. 1. 0
https://github.com/SpacehuhnTech/esp8266_deauther/releases/tag/v2.1.0
Your version V. 2. 5 is a beta version and therefore there are bugs, but before flashing to version 2.1.0, you need to flash https://github.com/SpacehuhnTech/esp8266_deauther/wiki/FAQ#how-to-do-a-reset to avoid unnecessary problems;) And after flashing, I recommend restarting esp8266 several times

**Comment by PumpP** [comment]
Many thanks.

Kind regards.

Pete.

The information contained in this e-mail is confidential and may be legally privileged, except where expressly indicated, it may not necessarily represent my views.
This e-mail is intended solely for the addressee(s) and I ask that any unauthorised recipient advise the sender immediately. If you are not the intended recipient any disclosure, copying, distribution or any other action taken in reliance on it is prohibited and may be unlawful.

**Comment by ghost** [comment]
always happy to help

**Comment by vovanhau** [comment]
> luôn sẵn lòng giúp đỡ

Is there a way to attack a device on boot by mac address without selecting it from a scan?

**Comment by ghost** [comment]
After the first scan, you can save your device or wi-fi network to esp8266, and after rebooting, you can immediately select the device you saved! You can also change the AutoSave time in the settings:)

**Comment by vovanhau** [comment]
https://www.youtube.com/watch?v=HWZrBoIKacw
Is it possible to do so on 8266 mcu modems or not

**Comment by ghost** [comment]
theoretically esp8266 can attack everyone at once, but the current firmware does not have such a function.  As for a MAC attack without an initial scan, I'm not sure if this can be done.  If you need to disable everyone at once, that is, mdk4 on github;)

**Comment by Letschat44** [comment]
Stop email me

**Comment by Bommlon** [comment]
@Letschat44 just unsubscribe

**Comment by Letschat44** [comment]
How do I unsubscribe so I don't get 400 emails ￼at ?
