### ISSUE TITLE
What file is the boot text located in Arduino IDE esp8266 wifi deauther wristband

### ISSUE THREAD

**Issue by Thman558** [spacehuhn/esp8266_deauther#1303]
In Arduino ide what folder is the boot text located in? I have looked through most but I cant find it?
I have a Wi-Fi deauther wristband (its the text that says "ESP8266 Deauther and then the credits and then the software version

**Comment by ghost** [comment]
Hi! I'm from Russia and that's why I read your text through a translator, and because of this, I may have misunderstood you! Here is a possible solution https://github.com/SpacehuhnTech/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide

**Comment by Thman558** [comment]
Спасибо большое!

**Comment by ghost** [comment]
Всегда Пожалуйста :)
