### ISSUE TITLE
Deauth Attack will not Deauth device from network, Beacon & Prob working fine

### ISSUE THREAD

**Issue by jamiek2k8** [spacehuhn/esp8266_deauther#1306]
Hi All,

I have been looking on the forum for an answer to my question without success.

I got my NodeMCU V3 today and flashed the device using the bin followed by Arduino process.

The issue I am having is when I try to Deauth Attack my own network it has zero effect and everything runs as normal however, when i try to Becon and Probe its fine, can anyone give any advice around this?

> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki).

**Comment by ghost** [comment]
1) I think that it is possible if you have two wifi ranges in your router (2.4 and 5ghz), then when esp8266 starts attacking the 2.4 ghz network, and it can only attack this frequency, then your devices switch to the 5GHz frequency.
2) Either your devices work on the 802.11 w Protocol (https://en.wikipedia.org/wiki/IEEE_802.11w-2009#Protected_frames). This Protocol is protected from a deauthorization attack.
3) Or you have a bug in the firmware
4) or maybe changing the number of packets sent in deauntification mode for each client will help you. These settings are available in esp8266
