### ISSUE TITLE
Failed to connect to esp8266 board with arudino IDE

### ISSUE THREAD

**Issue by ghost** [spacehuhn/esp8266_deauther#1307]
I attempted to connect my board with the arudino IDE, apon flashing I got this on the terminal

```
esptool.py v2.8
Serial port /dev/ttyS0
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "/root/.arduino15/packages/deauther/hardware/esp8266/2.7.2/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "/root/.arduino15/packages/deauther/hardware/esp8266/2.7.2/tools/esptool/esptool.py", line 2890, in main
    esp.connect(args.before)
  File "/root/.arduino15/packages/deauther/hardware/esp8266/2.7.2/tools/esptool/esptool.py", line 483, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
```

Any clue on how to fix this? Im not sure how im supposed to connect it!

**Comment by ghost** [comment]
I had the same problem, you need to hold down the FLASH button on esp8266 attach the Board to the Arduino and start compiling and downloading, and as soon as the firmware percentages go in the Arduino download window, you can release the FLASH button, but you can't release the button until the firmware has

**Comment by satan666000** [comment]
if what you are looking for is to flash the .bin with an android phone it is very easy

**Comment by ghost** [comment]
I have no flash button, I don't see it atleast

**Comment by ghost** [comment]
If you don't have this button, I don't know what else can help you! Try to find out which output this button was connected to and make your own (short-circuit to ground),
![ESP8266-NodeMCU-Hardware-Specifications-Reset-Flash-Buttons-LED-Indicators](https://user-images.githubusercontent.com/40857994/94794683-911c9980-041f-11eb-84da-834b13ddb06c.jpg)
![1_vdyA7ASUgPbQNzCg0L6shQ png f25807cca397a56b3685e4d8464d2ae5](https://user-images.githubusercontent.com/40857994/94794688-924dc680-041f-11eb-96b0-836f7e838f54.png)
