### ISSUE TITLE
#define NAME_MAX_LENGTH 17

### ISSUE THREAD

**Issue by lelguea** [spacehuhn/esp8266_deauther#1309]
**Describe the bug**
NAME_MAX_LENGTH id defined as 16, but the correc number es 17   6*2+5 (5 separators)

**To Reproduce**
Capture Mac
Open Serial Windows
See error

**Comment by spacehuhn** [comment]
https://github.com/SpacehuhnTech/esp8266_deauther/commit/33e0cd22504a186504c91a3faa0468a8be6e74b6
