### ISSUE TITLE
Adafruit_NeoPixel error during compilation

### ISSUE THREAD

**Issue by Cyb3rn0id** [spacehuhn/esp8266_deauther#1310]
During compilation an _'Adafruit_NeoPixel' does not name a type_ error comes out in the _LED.h_ module even if you've the Adafruit neopixel library installed.

Maybe this issue is due to the fact that _#include <Adafruit_NeoPixel.h>_ statement does not include the requested library since is only included _#if defined(NEOPIXEL_LED)_ and the NEOPIXEL_LED is not present in the _A_config.h_ module.

So I've changed _#if defined(NEOPIXEL_LED)_ to _#if defined(LED_NEOPIXEL_NUM)_ and works

**Comment by spacehuhn** [comment]
This should be fixed :)
