### ISSUE TITLE
Deauther esp32

### ISSUE THREAD

**Issue by Edo-Bat** [spacehuhn/esp8266_deauther#1313]
Hi, can i use the code for esp8266 deauther also on esp32?
I would like to use it from my phone only, so I wouldn't need to attach it to a display.

**Comment by ghost** [comment]
The ESP32 is not supported this firmware!
![Screenshot_25](https://user-images.githubusercontent.com/40857994/94380025-26493500-0177-11eb-8921-7adc4b561934.png)

**Comment by Edo-Bat** [comment]
Ok : (  How could I use the same program on the 32?

**Comment by ghost** [comment]
I don't know, but I think you need to rewrite the code to esp32. You may need to use libraries for esp32 in your code.

**Comment by spacehuhn** [comment]
Hi! There are many issues on this repo about ESP32 support, so I published a blog post to bring some clarity to this topic: https://blog.spacehuhn.com/esp32-deauther/ 
TL;DR: It's made for the ESP8266, and I have no plans to port this application to the ESP32. But it's open-source, so you're free to do it yourself if you want. I appreciate your understanding.
