### ISSUE TITLE
Error compiling for board NodeMCU 1.0 (ESP-12E Module). Help me with this please! 

### ISSUE THREAD

**Issue by ldq1709** [spacehuhn/esp8266_deauther#1316]
Arduino: 1.8.14 Hourly Build 2020/06/24 01:33 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, Basic SSL ciphers (lower ROM use), 4M (2M SPIFFS), v2 Lower Memory, Disabled, None, Sketch + WiFi Settings, 115200"

In file included from c:\programdata\matlab\supportpackages\r2017b\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-3-20ed2b9\xtensa-lx106-elf\include\c++\4.8.2\algorithm:60:0,

                 from C:\ProgramData\MATLAB\SupportPackages\R2017b\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266/Arduino.h:257,

                 from sketch\esp.ino.cpp:1:

c:\programdata\matlab\supportpackages\r2017b\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-3-20ed2b9\xtensa-lx106-elf\include\c++\4.8.2\utility:68:28: fatal error: bits/c++config.h: No such file or directory

 #include <bits/c++config.h>

                            ^

compilation terminated.

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ghost** [comment]
Try this https://forum.arduino.cc/index.php?topic=540292.msg3705349#msg3705349
