### ISSUE TITLE
Can this be used to help me pentest WiFi passwords?

### ISSUE THREAD

**Issue by Thman558** [spacehuhn/esp8266_deauther#1319]
Hello, I was wondering if this could be used with my computer while it is packet capturing and I deauth someone with it will my computer catch the 2 way handshake? Thanks

**Comment by ghost** [comment]
this device sends deauthentication packets that disconnect a particular client from the network! And you can't know exactly how many packets she sent. Using esp8266 to capture a handshake is inconvenient!
It will be easier to use special programs for this purpose (wifite, airmon-ng, mdk4)

**Comment by Thman558** [comment]
I know I normally use aircraft-ng just thought this would be a cool tool to use on the side

**Comment by ghost** [comment]
esp8266 perfectly replaces mdk4! You can use it for these purposes!
But my opinion is that it is better to use special programs, because if you send too many deauntification packets, the device will stop trying to connect to the network again! Thinking that it is unavailable!
