### ISSUE TITLE
Led Serial Command Not Found

### ISSUE THREAD

**Issue by Thman558** [spacehuhn/esp8266_deauther#1323]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**
A clear and concise description of what the problem is.
What do you think causes it?

When I open serial connection and type in led g  it says led not found if I type in led disable is says not found
Error/Compile/Output Log

ERROR: command "led disable" not found :(

**To Reproduce**
1. Go to Serial
2. Type In led disable'
3. See error

**Expected behavior**
Led To Turn Off Or Change Color

**Environment (please complete the following information):**
 - OS: Osx
 - Browser: Not Using Web Interface but its google chrome
 - Version 2.5
 - Hardware: Deauther Wristband DSTIKE

**Attempts**
Changing uppercase lowercase different spelling

**Comment by spacehuhn** [comment]
Thank you and sorry for the late response, I'm pushing a fix now.
