### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LmfaoHax** [spacehuhn/esp8266_deauther#1326]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**

when i upload it i get nothing so i tried monitoring the serial but it only shows something in 74880 :

```

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

ets_main.c 

```

**Environment (please complete the following information):**
 - OS: Windows 10\
 - Version deauther v2.2
 - Hardware Heltec Wifi kit 8

**Comment by Bommlon** [comment]
In order to be able to help you we would need more information.
If you didn't already, take a look at [the installation page in the wiki](https://spacehuhn.wiki/deauther/installation/).
