### ISSUE TITLE
WiFi 5Ghz deauther support ？

### ISSUE THREAD

**Issue by ghost** [spacehuhn/esp8266_deauther#1327]
Can you increase 5Ghz support by using other WiFi soc like rtl8720dn?

**Comment by Dayron-Cyber** [comment]
> Can you increase 5Ghz support by using WiFi soc like rtl8720dn?

I would also like to know if it is possible.

**Comment by forseenink3238** [comment]
No it won't be because esp8266 doesn't support 5 ghz

**Comment by tienanh996tn** [comment]
Có hỗ trợ cho esp07 không

**Comment by Bommlon** [comment]
no

**Comment by minanagehsalalma** [comment]
@spacehuhn So it's a Yes or a no ? 
That chipset mentioned here isn't even that Expensive so...
