### ISSUE TITLE
Disconnects upon deauth

### ISSUE THREAD

**Issue by Clon3d** [spacehuhn/esp8266_deauther#133]
Please read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) 
and the [readme](https://github.com/spacehuhn/esp8266_deauther/blob/master/README.md)
before posting a new issue. Thanks!

Hello, using version 1.1 bin.   whenever I try to death it says starting then loses all connection causing me to have to do a full reboot and does not work against the wifi networks.  I tried version 2.0 but will not compile correctly following your exact instructions. please reply or PM me for details. thanks

**Comment by Giuseppe2018** [comment]
i have the same issue...

**Comment by spacehuhn** [comment]
What does it say in the serial monitor?


>  I tried version 2.0 but will not compile correctly following your exact instructions.

You need the SDK version 2.0.0. If you get an error than that's an other issue.

**Comment by RMOA789** [comment]
Same issue. For some APs it's working well without disconnecting, but for other APs, I get an unavailable webpage. Already tried with different monitors/smartphones.

Flashing with the bin file from the git.

**Comment by elliot12** [comment]
Also the same issue. I can deauth an entire network but when scanning for devices on the network to deauth individually the esp8266 restarts. Other than that though, its working 100%. Thanks for the great work @spacehuhn 👍

**Comment by jLynx** [comment]
I also have this issue

**Comment by jLynx** [comment]
I have noticed, if im connected to the deauther on my computer it works fine, but if I try it on my phone it does exactly what the problem describes. But im not sure, it could just be a coincidence

**Comment by spacehuhn** [comment]
> but when scanning for devices on the network to deauth individually the esp8266 restarts.

Your problem is that it's getting disconnected when scanning for clients?

**Comment by elliot12** [comment]
Correct. It won't let me see individual devices on a given AP. It just
disconnects and comes on again about 10-15 seconds after but still doesn't
show me the clients. I used the bin file btw.

**Comment by spacehuhn** [comment]
It's normal that it disconnects, it has to do that in order to scan for devices.
To find devices they have to send packets while you are scanning, so make sure you generate some traffic in this network (by loading a site for example).
Also note that if your network has 2.4 and 5Ghz it will only find the devices which are using the 2.4Ghz connection.

**Comment by Fireflaker** [comment]
Would it be possible to develop it based on ESP32? It is just as cheap and
has 2x 160MHz cores with both bluetooth and wifi. The dual core should make
coding a lot easier.
Stefan Kremser <notifications@github.com>于2017年3月31日 周五上午11:04写道：

**Comment by spacehuhn** [comment]
The ESP32 isn't able to inject packets, so no :(

**Comment by jLynx** [comment]
This is the problem I am having https://imgur.com/iSISaNa

It gets to starting then times out the page when it try to reload. But it does stay connected to the device, as per the WiFi icon in the notification bar. But I cannot access any page from it now until I reset the power

**Comment by spacehuhn** [comment]
Yeah... I still need the serial log from you guys.

**Comment by jLynx** [comment]
Oops sorry didn't see that message 

ok..typical... it works this time. Anyway here is my log https://pastebin.com/qWd5MFZw

**Comment by spacehuhn** [comment]
thank you. The device isn't crashing and doesn't throw any other error.

**Comment by jLynx** [comment]
I have tested it 2 other times since that post and both have timed out, no error messages or anything out of the ordinary.

**Comment by spacehuhn** [comment]
Sorry I didn't want to close it! (stupid phones..)
Anyway...
can you access the website with another device?

**Comment by jLynx** [comment]
Yes on my desktop I have no problems. Just tried again and and it worked perfectly like it should and instantly started deauthing, where before in that log I sent it took at least 30 seconds or more before it started working (Website showing up anyway)

**Comment by spacehuhn** [comment]
OK yes that's really weird. It's not like that the ESP8266 doesn't send the website or something, because then it also wouldn't work with your PC.

**Comment by jLynx** [comment]
Could it be a way Android's Chrome handles the requests or something?

**Comment by jLynx** [comment]
Ok it just happened again while logging, and there is no crashes just the constant running deauth attack message. no matter what I did on my phone I could not access it. I tried disconnecting and reconnecting and that didn't work, but on my desktop I connected to the point and I can see the attack still running and then stop it with no problems.

Now i'm getting timeout (took too long to respond) with a 504 error on my phone trying to load the site, but no errors in the logs in console

**Comment by spacehuhn** [comment]
I maybe found a solution.
Scan for the network you want to deauth. Look what channel it uses and then go to settings and set the channel to the same value.
Then restart your ESP8266 and try to deauth that network.

I shouldn't loose the connection then.

**Comment by jLynx** [comment]
That seems to fix the problem! Thanks @spacehuhn 

Now do you think it's possible to fix this in software or is it just a problem we will have to live with?

**Comment by jLynx** [comment]
@spacehuhn can this issue be closed now?
