### ISSUE TITLE
pwned Network not showing up

### ISSUE THREAD

**Issue by Nipeno** [spacehuhn/esp8266_deauther#1345]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**
A clear and concise description of what the problem is.
What do you think causes it?

I just got the Deauther OLED V6, worked fine earlier, then I changed the name of the network from pwned to something different, now it just doesn't show up on my Wi-Fi. I already flashed the software, still no luck, please help.

**Expected behavior**
Wifi network should show up

**Environment (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Hardware DSTIKE
 - Deauther Version 2.5.0

**Attempts**
Flashing, using another phone to try to connect (didn't show up)

**Comment by oldrox** [comment]
The problem is that you have hidden the web interface, not the SSID.
I had this problem. I solved it with the latest firmware via esptool. Do not forget to hold down the flash button on the board before starting the firmware process.

**Comment by sircarti** [comment]
> > Have you searched for existing (open and closed) issues describing the same problem?
> 
> Yes
> 
> **Describe the error**
> A clear and concise description of what the problem is.
> What do you think causes it?
> 
> I just got the Deauther OLED V6, worked fine earlier, then I changed the name of the network from pwned to something different, now it just doesn't show up on my Wi-Fi. I already flashed the software, still no luck, please help.
> 
> **Expected behavior**
> Wifi network should show up
> 
> **Environment (please complete the following information):**
> 
> * OS: iOS
> * Browser Safari
> * Hardware DSTIKE
> * Deauther Version 2.5.0
> 
> **Attempts**
> Flashing, using another phone to try to connect (didn't show up)

Nothing realated to that my bad. But I also have a DSTIKE running that version does the attack function work for you? For me it hasn’t really. kind of a bummer.

**Comment by spacehuhn** [comment]
You can try resetting the settings: https://github.com/SpacehuhnTech/esp8266_deauther/wiki/FAQ#how-to-do-a-reset
