### ISSUE TITLE
5 GHz Router can be attacked?

### ISSUE THREAD

**Issue by helplessThor** [spacehuhn/esp8266_deauther#1348]
Can this deauthentication attack will work for 5 Ghz ?
Also, I want to run this in two of my NodeMCU boards, so for distinguishing, how to change the ssid name created by the ESP8266 board?

**Comment by vexxrs** [comment]
`5Ghz`
nope.
NodeMCU board doesn't support and also the code.

`"change the ssid"`
Do you mean the SSID of ESP wifi ? 
Or the ssid's for beacon attack ?

For both cases I recommend you to use version 2.0 ou 2.5
They are more "complete" and straight to action. 

V3.0 (the version where you are) is currenctly in development and may present issues
