### ISSUE TITLE
How to comment out mac vendor list

### ISSUE THREAD

**Issue by tnj86** [spacehuhn/esp8266_deauther#135]
Note: If you use a 512kb version of the ESP8266, you need to comment out a part of the mac vendor list in data.h.

I think I use a 512kb version of the esp8266.
Could you please elaborate how to comment out the mac vendor list in data.h.
I am so new to all this.thanks in advance.

**Comment by N0vaPixel** [comment]
Change in data.h   `const static uint8_t data_vendors[] PROGMEM = {///*`  to  `const static uint8_t data_vendors[] PROGMEM = {/*`
