### ISSUE TITLE
SSD1306 display problem and arduino not working problem after compiling

### ISSUE THREAD

**Issue by LuckyFishGeek** [spacehuhn/esp8266_deauther#1353]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

I have this board https://www.banggood.com/Wemos-D1-Esp-Wroom-02-Motherboard-ESP8266-Mini-WiFi-NodeMCU-Module-p-1224577.html 

**Describe the error**
A clear and concise description of what the problem is.
What do you think causes it?

I directly flashed the firmware esp8266_deauther_2.5.0-rc2_DSTIKE_DEAUTHER_OLED_V3_5.bin and it works normally

But after compiling with arduino, it does not work
I read the instructions on the wiki, modified the content of the A_config.h file, and uncommented #define DEAUTHER_OLED_V3_5

SSD1306 monitor does not display after arduino compilationError

**To Reproduce**
![Snipaste_2020-11-17_15-05-17](https://user-images.githubusercontent.com/29472751/99357291-a32a9c80-28e6-11eb-8e19-a56dbbfe7271.png)
![Snipaste_2020-11-17_15-07-16](https://user-images.githubusercontent.com/29472751/99357296-a58cf680-28e6-11eb-850a-9a3401f1c56e.png)
![Snipaste_2020-11-17_15-11-01](https://user-images.githubusercontent.com/29472751/99357601-23e99880-28e7-11eb-8f59-a0bbeb8d08b3.png)

After flashing the firmware, the screen does not display, and the PWNED hotspot cannot be connected

**Environment (please complete the following information):**
 - OS: windows7 64bit
 - Browser   chrome
 - Version  85.0.4183.121
 - Hardware https://www.banggood.com/Wemos-D1-Esp-Wroom-02-Motherboard-ESP8266-Mini-WiFi-NodeMCU-Module-p-1224577.html 

**Attempts**
 already tried and didn't work out.

Thanks friends for your help

**Comment by d1qqn** [comment]
i have the same board and my problem is, that the display is not clear.

![display](https://user-images.githubusercontent.com/74415153/99892483-9060f080-2c75-11eb-9279-546f97aa6ebb.jpg)

does anyone know what to do here?

**Comment by LuckyFishGeek** [comment]
@d1qqn   Brother, how do you deal with the display problem?

**Comment by fish-hue** [comment]
I have two deauthors, different versions, and if I could get my money back I would (sorry to my old deauthors). They work, but reset from time to time.

For $20 and a SD card, consider making your own pwnagotchi, more useful in my opinion and more for your money.

If you get a screen be sure to get a board with a header already soldered.

*My apologies as this is not related directly to your question, but if you have a chance I suggest going to the pwnagotchi.ai website and you can see what I am talking about.

**Comment by RChadwick7** [comment]
It looks like you have a cracked or damaged display. All the connections come in the bottom, and if a corner is cracked (Very easy to do), you can get the effect where every other line is off. The solution is to solder a new display on the PCB.

**Comment by d1qqn** [comment]
> @LuckyFishGeek

I use the web interface 


> @fish-hue 

thanks for the recommendation, but I already have a pwnagotchi and I'm very happy with this little toy ...
i can recommend it, too ;)


> @RChadwick7

It seems you are right. .. My display has broken off a bit in the lower right corner... 

But I've already read on the Internet that someone had the same problem.
his solution was to comment out
#define SSD1306_128_64
instead of 
#define SSD1306_128_32
in the "Adafruit_SSD1306.h" file

But this file doesn't exist in this project, right?
