### ISSUE TITLE
Stuck with the blue LED

### ISSUE THREAD

**Issue by satya-root** [spacehuhn/esp8266_deauther#1354]
I am using nodemcu esp8266 and after flashing the bin file, it worked fine and web page loaded on the ip. But when I disconnected it from power source and plugged it again, I am stuck with the blue LED constantly on. Although I am getting connected to ip but the webpage at the ip won't come saying webpage taking too long to respond.
Help me to fix this plz

**Comment by ghost** [comment]
I see that this old issue is still open. Is the problem fixed? 
To answer you question: can you try to reflash the bin file to the ESP8266.
