### ISSUE TITLE
Question: Were is the pic with the new project 

### ISSUE THREAD

**Issue by H1ghTech** [spacehuhn/esp8266_deauther#136]
I know you sent a pic with a new project lol.
Is it already open for alpha testing?

**Comment by spacehuhn** [comment]
you will find out soon ;)

**Comment by H1ghTech** [comment]
xD

**Comment by spacehuhn** [comment]
(sometime this week, but don't tell anyone 😶🤐 )

**Comment by H1ghTech** [comment]
Oki =]
