### ISSUE TITLE
Add one feature

### ISSUE THREAD

**Issue by me-najrudin** [spacehuhn/esp8266_deauther#1364]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki).  

I want to access internet when esp8266 connect to Router
Esp8266 work like wifi repeater and deauth on same bin file.
Please make bin file and send me on my email. Please, sir

My Email ID :- najrudin1ansari@gmail.com

**Comment by me-najrudin** [comment]
4

**Comment by spacehuhn** [comment]
Thank you for your interest bro sir, but I have to decline. Have a fabulous day. 💃
