### ISSUE TITLE
How can i add this code on esp32?

### ISSUE THREAD

**Issue by Maestro-ops** [spacehuhn/esp8266_deauther#1370]
How can i add this code on esp32?

**Comment by Bommlon** [comment]
The ESP32 does not support deauthing. So you can't use this code on the ESP32.

**Comment by ghost** [comment]
@Maestro-ops this project does not support the ESP32. That means that you can not flash (add the code) onto the ESP32, it will not work. Please close the issue.

**Comment by spacehuhn** [comment]
Hi! There are many issues on this repo about ESP32 support, so I published a blog post to bring some clarity to this topic: https://blog.spacehuhn.com/esp32-deauther/ 
TL;DR: It's made for the ESP8266, and I have no plans to port this application to the ESP32. But it's open-source, so you're free to do it yourself if you want. I appreciate your understanding.
