### ISSUE TITLE
Adafruit 2821 Feather Huzzah with ESP8266 Wi-Fi

### ISSUE THREAD

**Issue by DOKGMC** [spacehuhn/esp8266_deauther#1372]
I am using bin 2.1.0 source, Works great. I am wondering if i can flash it to the latest version 2.5.0* and which bin should i use for my model if possible. I am using a Adafruit 2821 Feather Huzzah with ESP8266 Wi-Fi.

Thank you.

**Comment by spacehuhn** [comment]
The NodeMCU bin file should work just fine :)
