### ISSUE TITLE
Make access point visible again

### ISSUE THREAD

**Issue by pioterjestem** [spacehuhn/esp8266_deauther#1373]
Hi guys !

I disabled the "pwned" access point via the website. What do I have to do to turn it on?

P.S. Sorry for my english. I'm Polish ;)

**Comment by pioterjestem** [comment]
I have DSTIKE mini oled deauther

**Comment by spacehuhn** [comment]
You can try a settings reset [How to do a reset](https://github.com/SpacehuhnTech/esp8266_deauther/wiki/FAQ#how-to-do-a-reset) or (re)install the latest firmware [Installation](https://github.com/SpacehuhnTech/esp8266_deauther/wiki/Installation)
