### ISSUE TITLE
Unable to connect to pwned

### ISSUE THREAD

**Issue by aaronreilly17** [spacehuhn/esp8266_deauther#1374]
what is the pass word?

**Comment by marco-porto** [comment]
Hello @aaronreilly17, password for the wifi hotspot is `deauther`😀

**Comment by aaronreilly17** [comment]
> Hello @aaronreilly17, password for the wifi hotspot is `deauther`😀

hi mate it doesnt work for me keeps saying unable to connect u know what i could try do to fix?

**Comment by spacehuhn** [comment]
You can try a settings reset [How to do a reset](https://github.com/SpacehuhnTech/esp8266_deauther/wiki/FAQ#how-to-do-a-reset) or (re)install the latest firmware [Installation](https://github.com/SpacehuhnTech/esp8266_deauther/wiki/Installation)
