### ISSUE TITLE
Changing SSID and password

### ISSUE THREAD

**Issue by zak1975** [spacehuhn/esp8266_deauther#138]
Hello,
I am using Version 1.1.bin. Everything was ok since I tried to change the ssid from pwned to another name. In the same step I also changed the wifi Password and clicked "save".
After that the new ssid is displayed, but when i try to connect, the new password is not accepted. I was very carefully when changing the password and i am sure that i wrote it correctly.
Also the old password "deauther" doesnt work.
I flashed the esp8266 again, hoping that would set everything to default, but after that it Shows the new given ssid again and no Login possible.
Any ideas?

**Comment by poslogic** [comment]
Erase your ESP first then flash again, Google "esp8266 erase eeprom"

**Comment by zak1975** [comment]
This worked, thank you.
I erased it with esptool.py and then flashed again. Now it is default ssid again.

**Comment by poslogic** [comment]
Glad to hear that you got it solved.

Please close this issue 👍

**Comment by zak1975** [comment]
I tried again to change ssid and password. This time it worked properly, so the problem is not reproducable for me.
Issue closed.

**Comment by cfa999** [comment]
How do you change the SSID and the password?

**Comment by developerfromjokela** [comment]
You should go to settings and change SSID and Password settings.

**Comment by saintofinternet** [comment]
mostly it is the timeout error that bugs the process. 

anyways i can change the timeout settings when changing the password or ssid etc?

**Comment by AN0NIT** [comment]
> How do you change the SSID and the password?

esp8266_deauther/A_config.h, edit the 'AP_SSID', 'AP_PASSWD'

**Comment by Chesterphillip** [comment]
Can I just purchase one complete

**Comment by datunadav2** [comment]
> > How do you change the SSID and the password?
> 
> esp8266_deauther/A_config.h, edit the 'AP_SSID', 'AP_PASSWD'

I changed the name once and then it didn't work. I changed it in the code but it didn't work.
