### ISSUE TITLE
Disconnect error 

### ISSUE THREAD

**Issue by Giuseppe2018** [spacehuhn/esp8266_deauther#139]
When i click on deauth he loses the connection

**Comment by poslogic** [comment]
This is normal.
It should reconnect, tell your device to forget your local/home connection so that the ESP will automatically reconnect.

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/issues/133

**Comment by Giuseppe2018** [comment]
The webpage become unaviable until i reboot the esp
