### ISSUE TITLE
Setting SSID and Password 

### ISSUE THREAD

**Issue by DOKGMC** [spacehuhn/esp8266_deauther#1390]
Hi. I've seen it before and cannot find it, I am using deauther 2.0 on Node mcu ESP8266. What file can i open and set the SSID and Password in before i flash it to the ESP8226>

Thank you

**Comment by DOKGMC** [comment]
Same here, never Mind

**Comment by spacehuhn** [comment]
You can change it in `A_config.h` at `#define AP_SSID "pwned"`

https://github.com/SpacehuhnTech/esp8266_deauther/blob/d078cea46978e4313f68f9866ecfe0ef7732cf0b/esp8266_deauther/A_config.h#L413
