### ISSUE TITLE
Attack stops after a while dosen´t work

### ISSUE THREAD

**Issue by Petros626** [spacehuhn/esp8266_deauther#1392]
Hi guys,

spacehuhn said in the FAQ that you should set "attackTimeout" to 0 so that the attack runs continuously.

My question now is whether this has to be done in this code section (Attack.cpp)? I set it to 0 and noticed that no attack takes place (condition never true always false):

// each second
    if (currentTime - attackTime > 1000) {
        attackTime = currentTime; // update time
        updateCounter();

        if (output) status(); // status update
        getRandomMac(mac); // generate new random mac
    }

Thank you for your feedback

**Comment by spacehuhn** [comment]
You don't have to edit the code. There should be a `attacktimeout` setting at the settings page for this (192.168.4.1/settings.html).

**Comment by Petros626** [comment]
i mean the code on the hardware stops after a few minutes. have the deauther mini and oled v5, as soon as the attack starts it stops after the display goes off.

i changed a condition in the code to work around this problem. just didn't know what is meant by attackTimeout as i don't use the web application

**Comment by geo777535** [comment]
> You don't have to edit the code. There should be a `attacktimeout` setting at the settings page for this (192.168.4.1/settings.html).

after installing firmware 2.6 on esp8266 (nodemcu), when I choose in settings to hide ssd, earlier on a version below 2.1.0 on Windows it did not show the "hidden network" 
![hidden_wifi_3](https://user-images.githubusercontent.com/73498291/112112915-9210d580-8bcf-11eb-90fc-d223effceb08.png)
now it shows like this. I don’t want to show "hidden networks" an inscription and unmasked the module esp8266 (nodemcu).
second problem: after the settings, the LED is turned off, after the esp8266 (nodemcu) module is turned on, the blue LED is on.
