### ISSUE TITLE
ESP8266 deauther in vorhandenes WLAN einbinden

### ISSUE THREAD

**Issue by heydemar** [spacehuhn/esp8266_deauther#140]
Hi Spacehuhn, 

besteht die Möglichkeit den ESP8266 mit deinem Image in ein bestehendes WLAN zu integrieren so das man ggfs. über Portfreigabe ihn aus der Ferne steuer kann? 
In der Config angeben mit welchem WLAN und Key er sich verbinden soll und ihm noch eine staticIP vergeben (Nezwerkconfig). 
Das wäre genial. 

Gruß

**Comment by switchbyte** [comment]
+1

**Comment by spacehuhn** [comment]
Ich seh den Sinn dahinter nicht.

Macht aber nichts das kannst du ganz einfach selbst einbauen. Den esp mit wlan zu verbinden ist total einfach, Google einfach und schau dir die examples an, dann ergänze den Code.


And because this isn't in English, I'll close it.
