### ISSUE TITLE
Littlefs.h no such file or directory

### ISSUE THREAD

**Issue by iama10yearold** [spacehuhn/esp8266_deauther#1400]
Hello I need help with the deauther code because when ever I try to verify the code it keeps saying that little fs is not a file or directory please help me with this @spacehuhn

**Comment by ghost** [comment]
First of all it is rude to ping someone in a issue when they are not needed to help.
Second if you open a issue it is very helpful for the person trying to help to include the steps you did/tutorial you followed. 

Looking at you issue I think you have not followed the installation/compilation instructions carefully enough. I suggest following this interactive guide: [deauth.me](http://deauth.me/). I found the link on the [installation Github Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki/Installation) page.

**Comment by iama10yearold** [comment]
Sorry no need to be mean I just joinedOn Feb 15, 2021 6:36 AM, Tim Hobbes <notifications@github.com> wrote:
First of all it is rude to ping someone in a issue when they are not needed to help.
Second if you open a issue it is very helpful for the person trying to help to include the steps you did/tutorial you followed.
Looking at you issue I think you have not followed the installation/compilation instructions carefully enough. I suggest following this interactive guide: deauth.me. I found the link on the installation Github Wiki page.
