### ISSUE TITLE
button not working

### ISSUE THREAD

**Issue by wh1ter0z** [spacehuhn/esp8266_deauther#1403]
i flashed v2.6.0 nodemcu with nodemcu flasher and setup lcd with i2c 1306 

buttons didnt work ( d5 d6 d7) i conected gnd to d5 then not work

on v2.1.0 d5 d6 works but d7 (A) not work for me ...

how can i solve this problem ?

please help me !

**Comment by unkn0wn-wifi** [comment]
Same here can we get some guidance here @spacehuhn ive tried multiple tries, and even when running the button test they all are on false when trying to click on them, this seems to me as a coding issue can you help?

im using a i2c SSD1306 display with a node mcu, i flashed it using the arduino flasher as i had to edit some code, i even tried replacing all of the 

"  #define BUTTON_UP 13
   #define BUTTON_DOWN 14
   #define BUTTON_A 12
"
Please can you help,

ps you may know me from kody's live stream when you joined and i spoke to you, UNKNOWN

**Comment by wh1ter0z** [comment]
yes i can help you ...

but i cant join to kody's stream

give me a whatsapp or telegram or instagram id to help you 

my instagram ID is 4xtrom

**Comment by MegaAndrey** [comment]
> yes i can help you ...
> 
> but i cant join to kody's stream
> 
> give me a whatsapp or telegram or instagram id to help you
> 
> my instagram ID is 4xtrom

I would be very happy if you can help me, I have a similar problem, my telegram @Ararelos

**Comment by Nikakz** [comment]
![Esquema Eletrico Deauther_LI](https://user-images.githubusercontent.com/21699431/111246127-7c564b80-85e4-11eb-9b25-396298f423be.jpg)

**Comment by Deniskyn** [comment]
how the scheme above affects the operation of the buttons?

**Comment by FriendlyWizard23** [comment]
did you guys solve the problem?

**Comment by wh1ter0z** [comment]
i solved this if you want to come in instagram : 4xtrom

**Comment by Bommlon** [comment]
@wh1ter0z you know you could just post your solution right here, right?

**Comment by strolll395** [comment]
@wh1ter0z your instagram doesn't exist anymore, would you mind just posting the fix directly?

**Comment by wh1ter0z** [comment]
Sure, no problem.

#define BUTTON_UP 14 gpio 14 = d5 #define BUTTON_DOWN 12 gpio 12 = d6 #
define BUTTON_A 13

gpio0 = d3

---------------------
d1 d2 use for lcd

use left GND for buttons
@irh1m is my new IG
if u want more help tell me...

**Comment by wh1ter0z** [comment]
Sure, no problem.

#define BUTTON_UP 14 gpio 14 = d5 #define BUTTON_DOWN 12 gpio 12 = d6 #
define BUTTON_A 0

gpio 0 = d3

---------------------
d1 d2 use for lcd

use left GND for buttons
@irh1m is my new IG
if u want more help tell me...

**Comment by wh1ter0z** [comment]
check my   Repositories  <https://github.com/wh1ter0z?tab=repositories>

i uploaded edited project and changed something

**Comment by strolll395** [comment]
Thank you for being so nice to make this fix easily accessible. It really helps and will save a ton of time in the future. I will try it out later and report back if it works

**Comment by strolll395** [comment]
Uhm, sorry, I get the following error while compiling:
exit status 1
'USE_LED' was not declared in this scope

**Comment by strolll395** [comment]
Nevermind, I got it. I removed the RGB LED part since I dont need it anyways.

**Comment by wh1ter0z** [comment]
okay fine i will fix it

**Comment by wh1ter0z** [comment]
sorry for errors i fixed now u can update A_config.h file

**Comment by strolll395** [comment]
tested it and it works perfect now. thanks for taking your time and fixing it :)

**Comment by wh1ter0z** [comment]
You're welcome!

**Comment by ghost** [comment]
With only one esp8266, deauth + evil twin + Facebook, Google, Twitter,..
https://youtu.be/oKsRb4KXXk0
https://youtu.be/Nt-0aTfPECQ

**Comment by strolll395** [comment]
I do not understand anything in this video nor does anything make sense you posted here. Go advertise somewhere else.
