### ISSUE TITLE
Error saving and loading files on correctly mounted SPIFFS

### ISSUE THREAD

**Issue by AgentSmith0** [spacehuhn/esp8266_deauther#1408]
I have a problem when I boot the esp8266 deauther (DSTIKE OLED V4).

I uploaded the code with the following settings:
```
Board: DSTIKE Deauther
Flash Size: 4MB (FS:3MB OTA:~512KB)
Deauther Config: DSTIKE Deauther OLED V4
```
I tried already other flash sizes, but all have the same issue.

Here is the Serial output:
```
Mounting SPIFFS...OK
Formatting SPIFFS...OK
Formatting EEPROM...OK
Formatting SPIFFS...OK
Formatting EEPROM...OK
Loading settings...Invalid Hash
Settings reset to default
ERROR: saving /settings.json
ERROR couldn't open /names.json
Device names loaded from /names.json
ERROR couldn't open /ssids.json
SSIDs loaded from /ssids.json
ERROR: saving file. Try 'format' and restart - /scan.json
Serial interface enabled
Started AP
[WiFi] Path: '/web', Mode: 'AP', SSID: 'pwned', password: 'deauther', channel: '1', hidden: false, captive-portal: false
STARTED! \o/
2.6.0

```

As you can see, the SPIFFS are mounting correctly, but it can't access files on it. How can I fix this?

**Comment by Fearce1** [comment]
It's sooo funny that NO ONE fixed this yet.. seems intentional.... like the missing .h files in all of the updates, also noting that other libraries had to be installed like neopixle.
