### ISSUE TITLE
Connection Time Out trying to reach 192.168.41

### ISSUE THREAD

**Issue by ghost** [spacehuhn/esp8266_deauther#1412]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki).  
Connection Time Out trying to reach 192.168.41, suggestions?
```
PASTE YOUR ERROR/COMPILE LOGS HERE
```

**Comment by diveyez** [comment]
Try 192.168.4.1
