### ISSUE TITLE
Charged, but red LED inside watch is constantly on?

### ISSUE THREAD

**Issue by ImmortLx** [spacehuhn/esp8266_deauther#1421]
Recently flashed the deauther watch from DSTIKE, but when I charge it the internal red LED is always on. How do I know when it is fully charged?

**Comment by Bommlon** [comment]
It depends on which version you've got. V2 and V3 have 4 LEDs on the left side indicating the amount of charge left. I'd guess the internal LED only indicates that the board has power .

**Comment by lucas083** [comment]
hello I wanted to know why DSTIKE v2 watch when I put it on charge from off it turns on by itself? there is no way to be able to charge it by spending? also I would like to know when it is on in standby the battery heats up a little is this normal?
