### ISSUE TITLE
Error compilando para la tarjeta Generic ESP8266 Module.

### ISSUE THREAD

**Issue by INNOX20** [spacehuhn/esp8266_deauther#1425]
Se encontraron varias bibliotecas para "SD.h"

In file included from D:\OneDrive\Documentos\Arduino\libraries\Firebase-ESP8266-master\src/common.h:45:0,

Usado: C:\Users\stiven\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.1\libraries\SD

 No usado: D:\Archivos de programas\Arduino\libraries\SD

                 from D:\OneDrive\Documentos\Arduino\libraries\Firebase-ESP8266-master\src/Utils.h:37,

                 from D:\OneDrive\Documentos\Arduino\libraries\Firebase-ESP8266-master\src/signer/Signer.h:37,

                 from D:\OneDrive\Documentos\Arduino\libraries\Firebase-ESP8266-master\src/FirebaseESP8266.h:51,

                 from C:\Users\stiven\Desktop\UNIVERSIDAD\INTRODUCCION A LA ELECTRONICA\cafetera\codigo_listo\codigo_listo.ino:14:

D:\OneDrive\Documentos\Arduino\libraries\Firebase-ESP8266-master\src/wcs/esp8266/FB_HTTPClient.h:56:22: fatal error: LittleFS.h: No such file or directory

 #include <LittleFS.h>

                      ^

compilation terminated.

exit status 1

Error compilando para la tarjeta Generic ESP8266 Module.

Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by Bommlon** [comment]
Please provide more information about your problem (going through the provided form when creating an issue helps). Also please keep in mind that this is a international community which benefits from using English as the language of choice.
