### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by iamroyce007** [spacehuhn/esp8266_deauther#1426]
Arduino: 1.8.13 (Mac OS X), Board: "Arduino Yún"

esp8266_deauther:11:10: fatal error: ESP8266WiFi.h: No such file or directory
 #include <ESP8266WiFi.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
ESP8266WiFi.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Ferferite** [comment]
You are compiling for the Arduino Yún, this should help you out: https://github.com/spacehuhntech/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide
