### ISSUE TITLE
ESP8266 does not detect clicks from buttons.

### ISSUE THREAD

**Issue by suchencjusz** [spacehuhn/esp8266_deauther#1434]
Hello, I have a problem with esp8266 buttons.
Buttons are connected to GND and digital ports (D5-D7),
esp don't detect the clicking, also I connected buttons to VCC, it did not work.
(SSD1306 I2C OLED works fine)

I'm using nodemcu 0.9

![photo](https://i.ibb.co/wKrHWFh/IMG-20210520-141947.jpg)
(maybe useful photo)

**Comment by Torpeda0** [comment]
For me, uploading the code again helped me. It is best to set it when uploading ,,earse all data''

**Comment by suchencjusz** [comment]
co kurwa stale

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
spacehuhntech please help me, i am facing the same problame

**Comment by Torpeda0** [comment]
Have you connected the buttons to GND?

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
> Have you connected the buttons to GND?

Obviously, i have done the same procedure mentioned in the diagram. But the buttons are not working, my nodemcu and display is working fine. But the buttons are not working. If you know why then please help me. It is my office project.
