### ISSUE TITLE
Nothing happens when an attack is launched

### ISSUE THREAD

**Issue by Phunki10** [spacehuhn/esp8266_deauther#1443]
Hi guys,

I have just received my DSTIKE Deauther Monster V5. I've assembled the antenna and I've put a battery in one of the slots, though, when I scan for my network and then try to deauth it from the attack menu - nothing happens. I know this is not very concrete, but I am hoping to receive some directions about this, because otherwise the device is unusable.
Thanks in advance :)

**Comment by pramady101** [comment]
have you tired changing the reason code?

**Comment by Bommlon** [comment]
keep in mind that not every network is susceptible to deauth attacks

**Comment by pramady101** [comment]
true - a 5ghz only, wpa3 or 802.11w networks are invunerable to the deauther
