### ISSUE TITLE
Resolving MAC to vendor 

### ISSUE THREAD

**Issue by JackWilder00** [spacehuhn/esp8266_deauther#1448]
Hey,

When I am searching for stations, I got results without any information about the vendor. I have to manually lookup the MAC in a vendor database.
Is there a possibility to import a vendor database?

**Comment by jsonnet** [comment]
Hi,
take a look in the utils folder, there you'll find a vendor_list_updater which will create you an updated oui.h file.
You could of course also add to those manually, but try first just updating, resolved also my issue

Cheers Josh
