### ISSUE TITLE
Esp32 support

### ISSUE THREAD

**Issue by fcwys** [spacehuhn/esp8266_deauther#1455]
The esp32 will support 5G wifi later, so I hope to support esp32.

**Comment by HoaxParagon** [comment]
I have a couple ESP32 and ESP8266. I would be interested in helping with this port and I'm going to start looking into it. Let me know if there's real interest with this @spacehuhn.

**Comment by spacehuhn** [comment]
Hi! There are many issues on this repo about ESP32 support, so I published a blog post to bring some clarity to this topic: https://blog.spacehuhn.com/esp32-deauther/ 
TL;DR: It's made for the ESP8266, and I have no plans to port this application to the ESP32. But it's open-source, so you're free to do it yourself if you want. I appreciate your understanding.
