### ISSUE TITLE
DFRobot FireBeetle support?

### ISSUE THREAD

**Issue by Sle77en** [spacehuhn/esp8266_deauther#1457]
Hey,

i have a FireBeetle and want to run the deauther on it. I tried many options in the Arduino IDE to upload it on the board. But i cant flash it to the board. 

Which are the right settings to upload it?

**Comment by Sle77en** [comment]
I found this tutorial, but i doesnt work like in this tutorial anymore: https://www.hackster.io/akarsh98/wi-fi-jammer-from-an-esp8266-wifi-jammer-deauther-8187b8#toc-step-1--parts-1

**Comment by Bommlon** [comment]
The FireBeetle uses an ESP32 which is not supported. The Deauther is made for the ESP8266 only.

**Comment by Sle77en** [comment]
No there is also a ESP8266 version ;) I got it to work. Thanks.
