### ISSUE TITLE
user_interface.h: No such file or directory

### ISSUE THREAD

**Issue by ardiwidiyono** [spacehuhn/esp8266_deauther#1458]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki).  

```
PASTE YOUR ERROR/COMPILE LOGS HERE
```
Please help me.  I always face this problem
esp8266_deauther.ino:12:30: fatal error: user_interface.h: No such file or directory

**Comment by Bommlon** [comment]
Could you provide more information about the version you're using? Try going through the form provided when opening a new issue. The more information you provide about your problem the better we may be able to help you out.
