### ISSUE TITLE
Hackheld Vega PCB

### ISSUE THREAD

**Issue by GrafvonWolfenstein** [spacehuhn/esp8266_deauther#1472]
Hello Spacehuhn Team,

where can I buy a PCB for the Hackheld Vega, or where do you produce it so I can let it make there?

Thank you
Graf von Wolfenstein

**Comment by Bommlon** [comment]
You can either buy the PCBs directly from https://spacehuhn.com/store/
or download the files [here](https://github.com/SpacehuhnTech/Hackheld/tree/main/Hackheld_Vega_PCB) and have the manufacturer of your choice produce them for you. The ones sold in the store are made by [JLCPCB](https://jlcpcb.com/) iirc.
