### ISSUE TITLE
Don't work deauther 

### ISSUE THREAD

**Issue by Kittyskj** [spacehuhn/esp8266_deauther#1473]
when trying to deauthenticate a network that is logged in via a web application it don't deauth

**Comment by pramady101** [comment]
does it deauth without the login?

**Comment by mrace500** [comment]
I am Having the exact same problem everything else works fine like the beacon and probe but the deauther doesn't work and I'm not sure why.

**Comment by mrace500** [comment]
I am Having the exact same problem everything else works fine like the beacon and probe but the deauther doesn't work and I'm not sure why.

**Comment by Bommlon** [comment]
keep in mind that not every network is susceptible to the deauth-attack

**Comment by Europe-Connection** [comment]
Same problem for me, I had working software used last year, I flash an update today and am trying on an 802.11g network but deauther mode does not work. Something to change that would cause this malfunction? Thank you
