### ISSUE TITLE
wemos d1 mini pro

### ISSUE THREAD

**Issue by wolfyy59** [spacehuhn/esp8266_deauther#1474]
hello i would love if there's any flashable binary for the wemos d1 mini pro?, beacuse i have the wemos d1 mini and it works fine but in the wemos d1 mini pro there's an antenna which makes it better in term of reception thanks for the devs.

**Comment by jsonnet** [comment]
Hey @wolfyy59 not sure if you already tried it, but I just compiled the code myself the other day, for a D1 mini pro and used the "LOLIN (WEMOS) D1 mini" preset, so I would guess, you are perfectly fine using the precompiled binary for the D1 mini. Or clone the repo, open in Arduino (IDE) and follow the instructions to set it up (~5 mins and you are up and running).

Cheers Josh

**Comment by groomit** [comment]
On my setup with a D1 mini clone I still have no success using "LOLIN (WEMOS) D1 mini" preset. What solved the issue for me is described [here](https://github.com/SpacehuhnTech/esp8266_deauther/issues/1387#issuecomment-772698839). Maybe this is of help here too
