### ISSUE TITLE
Can i take the probes off of the back side of the esp8266 and it will still work the same?

### ISSUE THREAD

**Issue by rflinkss** [spacehuhn/esp8266_deauther#1481]
Can i cut or pull off the probes on the back side of the esp8266 and still have the functionality of everything on v2? 
![image](https://user-images.githubusercontent.com/47998991/135574568-f65d50e1-1be1-48dd-baef-096615793846.png)

**Comment by apnof** [comment]
what do you mean with 'probes'?
(Maybe you can draw where you want to cut?)
