### ISSUE TITLE
Display doesn’t work after flashing (false code)

### ISSUE THREAD

**Issue by l0ckD2wN** [spacehuhn/esp8266_deauther#1491]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**
After I followed SpacehuhnTech's tutorial "Compiling Using Arduino-IDE" V2 my screen is black when I start my Deauther DSTIKE Watch **V3**. I know it was the false version. But can anyone help me?
I'm also very new to this so if you need more information to this problem I can give you them.

```
Error/Compile/Output Log
```

**To Reproduce**
1. Downloading .zip file "Compiling using Arduino-IDE" and filled tutorial
2. Downloaded the CP210x USB to UART Bridge VCP Drivers, after which my Arduino-IDE showed a Port (COM4) which it didn't done first (I can give you further information, e.g. Upload speed, later)
3. Uploaded the script on my Deauther DSTIKE Watch V3 with the Arduino-IDE
4. Started the watch but the display was/is still black; But I can switch on the Bright LED and it also has it's normal colours (green, blue light while flashing)

**Expected behavior**
I expected that the watch will just run like it did before. I wanted to check uploading, so that I could start scripting for my watch after this little test.

**Screenshots**
I don't know which screenshots could be useful. If you need some I can send them.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: Deauther DSTIKE Watch V3
 - Hardware: Deauther DSTIKE Watch V3

**Attempts**
First thing I tried was a restart via the reset button on my Deauther DSTIKE Watch V3. It didn't work.
Next thing I tried was downloading the reset files from this GitHub but it still didn't work.
Last thing I tried after my display turned black was flashing the "Compiling using Arduino-IDE" V3 but my display just stayed black. I also tried pressing flash while uploading script but it didn't change anything. But the blue RX/FX (I guess this are their names) LED's are blinking while uploading.

**Additional context**
I don't know what else to do. If you need some further information text me here. Hope you guys can help me. Thank you all. I hop I will solve it so I can continue coding on this project as I like this project very much.

**Comment by hertzi** [comment]
Hi @l0ckD2wN,
you probably forgot to change the A_config.h file to the configuration of your watch.
Just comment out 
`#define DEFAULT_ESP8266`
and comment in
`#define DSTIKE_DEAUTHER_WATCH_V2`

Hope that helps.
