### ISSUE TITLE
Problems with web 

### ISSUE THREAD

**Issue by mchyla7** [spacehuhn/esp8266_deauther#1497]
> Have you searched for existing (open and closed) issues describing the same problem?

No

**Describe the error**
The web isn't working and I don't know why. Back about 10 hours it works and now not

**To Reproduce**
Steps to reproduce the behaviour:
1) Connect to pwned
2) Open Opera and go to 192.168.4.1
3) Agree with terms
4) Press the button for scan and nothing
5) Try to go to settings and just text 

**Expected behaviour**
Normal working web with working buttons, settings and all that stuff 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Android
 - Browser: Chrome, Opera 
 - Version: Latest
 - Hardware: **NodeMcu** CP2102 Lua WI-fi **ESP8266**

**Attempts**
I erase all settings and upload them again over Arduino software

**Additional context**
I try to power it through a power bank, and lately by PC USB 

edit:
Now its working and I don't know why :D
Now it's connected through the computer, through the same port but last time it didn't work anyway

Have anybody the same problem as me? And how did you solve it?

**Comment by captclearleft** [comment]
It looks like you were using an Apple OS.  Most current OS's do not like a wifi connection that does not have internet access.
When you press scan, the esp8266 cannot "scan" and provide the web interface at the same time.  This shows the OS that the wifi is "disconnected" (in simple terms).  If a better wifi is available the Apple device (or any device) will connect to another known working website.  When you try to connect to 192.168.4.1 - It cant be accessed either because it is unavailable on the new wifi connection or the esp8266 is currently busy "sannning".  

You need to remove the known wifi's in that area and force the connection even though there is no internet connectivity.
Hope that helps.

**Comment by P-A-Trick** [comment]
The same prob, if I connect via WLAN the connection is stable but the Webinterface fon"t reac5t...meas I can't see the settings or can do a scan via web...reset reload reboot nothing happens

**Comment by captclearleft** [comment]
Just to clarify.  In the Wiki - It states:
1. The web interface is not available during scan.
2. Remove know wifi APs in your phone that it would normally connect to.

If using android you can force the wifi connection even if no interenet.

**Comment by P-A-Trick** [comment]
I got the connection via WLAN to owned, but after accepting the rules the chapters  with menu scan attack settings and do on appears...
But the menus without function no reload reboot or reset is helping

**Comment by captclearleft** [comment]
I don't understand what issue you are having.  Please provide a picture of your setup.  What device are you using?
 
I don't understand what you are saying here -

"..but the Webinterface fon"t reac5t...meas I can't see the settings or can do a scan via web..."   **Please provide a screen shot or video of what is not working.**  

And I don't understand what you are saying here - 

"but after accepting the rules the chapters with menu scan attack settings and do on appears..."
**Please provide a screen shot or video of what is not working.**

**Comment by P-A-Trick** [comment]
![Screenshot_2021-12-15-19-05-39-458_org mozilla firefox](https://user-images.githubusercontent.com/96141031/146242226-a9753799-35b4-48b9-8b98-6f3bb19ee55d.jpg)

**Comment by P-A-Trick** [comment]
There are no options

**Comment by P-A-Trick** [comment]
Using the V2 clock

**Comment by P-A-Trick** [comment]
![Screenshot_2021-12-15-19-17-40-700_org mozilla firefox](https://user-images.githubusercontent.com/96141031/146242834-958bb721-f6cb-449c-8c38-1f2823cbec96.jpg)
![Screenshot_2021-12-15-19-17-53-082_org mozilla firefox](https://user-images.githubusercontent.com/96141031/146242845-36846aba-84dc-4b3f-9da5-93fb0bab4493.jpg)

**Comment by captclearleft** [comment]
@P-A-Trick The below image is what I am going off of.  If this is NOT what you have?  Create a new thread.

I am helping you with a NodeMCU esp8266 that you flashed with v2.6.1 as outlined in the tutorial.
Your images show that you have version 2.6.0.  I would update to the latest version.


![esp8266 help](https://user-images.githubusercontent.com/44250740/146405396-1e77ba3d-e172-4997-985c-956aab4b5ee4.PNG)

**Comment by P-A-Trick** [comment]
The version o  the V2 clock is 2.61... in the web it's 2.60 don't know why.
sorry I 'm new to this and also to the GitHub. Try to understand how
everything works here..


captclearleft ***@***.***> schrieb am Do., 16. Dez. 2021,
17:03:
