### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by gremlinflat** [spacehuhn/esp8266_deauther#150]
Can u add whitelist feature??

**Comment by spacehuhn** [comment]
please explain that

**Comment by ChaudhryAbdulAziz47** [comment]
I Think @gremlinflat means; adding a feather where we can attack other device on network and whitelist the device we don't want to attack. But what he doesn't know is that, we can scan for clients and only attack the device we want! Technically this feature is already there! :+1:  @spacehuhn

**Comment by gremlinflat** [comment]
Deauth entire network, without deauth device on list

**Comment by gremlinflat** [comment]
The simplest word is the opposite of blacklist

**Comment by spacehuhn** [comment]
That's not possible though. You can either deauth all or just specific clients (in which case you need to scan first).

**Comment by gremlinflat** [comment]
Have u ever use mdk3 or aireplay in linux?
Its like blind deauth but didnt attack mac addres that listed on whitelist
