### ISSUE TITLE
windows not detecting device

### ISSUE THREAD

**Issue by settlelol** [spacehuhn/esp8266_deauther#1502]
i got this [https://www.aliexpress.com/item/1005001952641270.html] and when i plug it into my pc the device manager doesnt detect it

i have a data cable

when i tried installing the ch34 driver it said it installed but on ports in device manager it doesnt show 
![image](https://user-images.githubusercontent.com/66353129/146643747-0fe79a15-a384-497a-a4cf-a87ea4288209.png)

**Comment by Tim2906** [comment]
Uninstall the old driver and install this one:  https://github.com/nodemcu/nodemcu-devkit/tree/master/Drivers

If it does not work, try another port or another cable, but it should work
