### ISSUE TITLE
language change

### ISSUE THREAD

**Issue by serja123** [spacehuhn/esp8266_deauther#1509]
please tell me how to change the language? I go to the settings and write ru in the language line. Then I save and reboot, but the language still remains English.

**Comment by nikita2882737** [comment]
У меня такая же тема, не переключается не на какой язык

**Comment by linyecheng** [comment]
我也遇到这个问题，可以尝试在保存了之后，打开192.168.4.1/lang/default.lang这个页面，重复刷新几次就更改成功。

**Comment by linyecheng** [comment]
> 请告诉我如何更改语言？我去设置并在语言行写。然后我保存并重新开始，但语言仍然是英语。

我也遇到了这个问题，可以尝试在保存了之后，打开 192.168.4.1/lang/default.lang，刷新一次就更改成功了。
