### ISSUE TITLE
Display on Wristband v1 does not work

### ISSUE THREAD

**Issue by loviuz** [spacehuhn/esp8266_deauther#1520]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**

After I flash the firmware **deauther_2.1.0_DSTIKE_Wristband_Mini.bin** or **esp8266_deauther_2.6.1_DSTIKE_DEAUTHER_WATCH.bin** or **esp8266_deauther_2.6.1_DSTIKE_DEAUTHER_WATCH_V2.bin**, the display does not work, it stays black. I don't know if something else works because I don't see any AP.

```
Error/Compile/Output Log
```

**esptool  -p /dev/ttyUSB0 write_flash -fm dout 0x0000 deauther_2.1.0_DSTIKE_Wristband_Mini.bin**
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting.......
Detecting chip type... ESP32
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 160MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 3c:71:bf:c1:70:a4
Enabling default SPI flash mode...
Configuring flash size...
Auto-detected Flash size: 4MB
Erasing flash...
Took 2.19s to erase flash block
Wrote 710656 bytes at 0x00000000 in 69.7 seconds (81.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**To Reproduce**
Compile, no errors in output, but the device does not work :-(

**Expected behavior**
The display should lights on.

**Screenshots**
None.

**Environment (please complete the following information):**
 - OS: Parrot Linux]
 - Hardware: DSTIKE Wristband v1

**Attempts**
I have tried many firmware as described above.

**Additional context**
Nothing to add

**Comment by huifeideteji** [comment]
![image](https://user-images.githubusercontent.com/47907651/154248876-a51bb45f-c43a-492b-8766-ce3c0e7d881d.png)
