### ISSUE TITLE
Does this work for ESP-WROOM-32

### ISSUE THREAD

**Issue by morpheuslord** [spacehuhn/esp8266_deauther#1527]
Hello,
I have a a esp32 wroom chip and I wanted to flash this onto my wroom chip will it still work???

**Comment by DamianSuess** [comment]
Duplicate of:
* #1455 
* #1370 
* #731

@morpheuslord, see wiki page [Supported-Devices](https://github.com/SpacehuhnTech/esp8266_deauther/wiki/Supported-Devices) for more information. Overall, not at this time w/ this repo.

For more info:
* https://blog.spacehuhn.com/esp32-deauther/
