### ISSUE TITLE
how do i change the default password and username of the wifi

### ISSUE THREAD

**Issue by user421921** [spacehuhn/esp8266_deauther#1532]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki).  

I want to change the default username and password for the WiFi AP, how can I do that? editing the src code?

**Comment by depthso** [comment]
When you are on it's home page viva the device's IP, click settings and scroll down a bit where it says Password: deauther.
