### ISSUE TITLE
Beacon Attack Radius

### ISSUE THREAD

**Issue by gitiliya** [spacehuhn/esp8266_deauther#1538]
Hello, I have noticed that the beacons being sent out don't have a very large radius, is it possible to connect a wifi antennae to the esp8266 to extend the radius?

**Comment by 1999AZZAR** [comment]
in my experience yes, you can definitely add an external antenna to help boosting its signal strength.
but be careful about the antenna that you want to add, you can also browse "how to add external antenna to esp" for more.
