### ISSUE TITLE
Not working display

### ISSUE THREAD

**Issue by D1st3f** [spacehuhn/esp8266_deauther#1544]
Hi, i have esp8266 and sdi oled display. I conected like wiki, but nothing work. i tried flash by Arduino IDE and by bin file. If i flash Nodems version all works, but if i flash SPI version anythink dont work, no wifi to connect and no image. 

![photo_2022-04-28_18-52-46](https://user-images.githubusercontent.com/76536480/165794314-d5455de2-d0ed-4673-809d-e07591be411a.jpg)
![photo_2022-04-28_18-52-43](https://user-images.githubusercontent.com/76536480/165794315-06f38377-3829-4695-b870-4d59ae924474.jpg)
![photo_2022-04-28_18-52-38](https://user-images.githubusercontent.com/76536480/165794310-87745b6a-20f5-45d5-a54d-889d9239abec.jpg)

I tried display demo and display work fine. 
Pls help : /
Thxs

**Comment by D1st3f** [comment]
I fixed that sht : ) In wiki you have issue, ssd1306_Spi you have double usage of same pin, same issue you have in bin file. Pls fix that. I remove double define pin and all works nice : ) 



#elif defined(DISPLAY_EXAMPLE_SPI)
   #define SSD1306_SPI

  **_#define SPI_RES 5_**
  #define SPI_DC 4
  #define SPI_CS 15

 #define FLIP_DIPLAY true

// ===== BUTTONS ===== //
  #define BUTTON_UP 0
  **_#define BUTTON_DOWN 12_**
  #define BUTTON_A 2

// ===== LED ===== //
  #define LED_NEOPIXEL_GRB
// #define LED_NEOPIXEL_RGB

  #define LED_NUM 1
  #define LED_NEOPIXEL_PIN 9
  #define LED_MODE_BRIGHTNESS 10

#elif defined(MALTRONICS)

// ===== Reset ====== //
  **_#define RESET_BUTTON 5_**

// ===== LED ===== //
  #define LED_DOTSTAR
  #define LED_NUM 1
  _**#define LED_DOTSTAR_CLK 12**_
  #define LED_DOTSTAR_DATA 13
  #define LED_MODE_BRIGHTNESS 255

**Comment by logicbreaks** [comment]
What do i have to change?
