### ISSUE TITLE
Deauth 5G

### ISSUE THREAD

**Issue by Sanityfrog502** [spacehuhn/esp8266_deauther#1546]
can the deauther and bad usb watch deauth 5G?

**Comment by bomberfish** [comment]
Do you mean 5GHz wifi or 5G cellular?
In either case, it won't work.
[https://github.com/SpacehuhnTech/esp8266_deauther/wiki/FAQ#5ghz-support](https://github.com/SpacehuhnTech/esp8266_deauther/wiki/FAQ#5ghz-support)
