### ISSUE TITLE
Deauther does not allow Windows 10 laptop to connect but allows every other device to.

### ISSUE THREAD

**Issue by iProgramIt1** [spacehuhn/esp8266_deauther#155]
I have several devices, of which run Windows [10], Android 6.1.1 and Android 5. The Android devices run smoothly when connecting to the deauther's AP. However, when I try to connect with my Windows device, it just disconnects and says it can't connect to the network. I'm not running another deauther, so I'm unsure of what is happening. Some insight would be helpful.

Thanks,
Program.

**Comment by spacehuhn** [comment]
Well that's a problem with your win10 then

**Comment by Fireflaker** [comment]
There is probably a setting saying automaticly disconnect from hotspots without internet connection. You need to disable it somehow.
