### ISSUE TITLE
ARDUINO POPS UP A ERROR AS USING ESP8266WIFI.h AND NOT USING esp8266.h 

### ISSUE THREAD

**Issue by Vaibhavland** [spacehuhn/esp8266_deauther#156]
HELPP MEE PLZZ I WANNA KNOW HOW DO I RESET MY ESP ITS NOT SHOWING ANY WIFI SIGNAL AND PLUS I CANNOT FLASH ANYTHING OF UR FILES INTO IT AND THEN I WAS TRYIN TO IT MESSED UP WITH THIS BOARD PLZ HELP ME I M A POOR BOY I CANNOT AFFORD THIS AGAIN! Plzzz 
Email-vaibhavs362@gmail.com
---

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by iProgramIt1** [comment]
You don't need to shout to get help...
