### ISSUE TITLE
I CANNOT FLASH THIS FILE PLUS HOW TO RESET THIS BOARD 

### ISSUE THREAD

**Issue by Vaibhavland** [spacehuhn/esp8266_deauther#157]
PLZZ GUYS HELP ME WITH THIS BOARD I CANNOT FLASH ANY FILE AND PLUS I CANNOT BURN THE BOOTLOADER PLZZ GIVE ME A GUIDE I M A POOR BOY I CANNOT AFFORD THIS AGIN LITREALLY AND ITS NOT SHOWING ANY WIFI SIGNALS TOO 
vaibhavs362@gmail.com
---

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by poslogic** [comment]
Stop shouting!!!!!

**Comment by poslogic** [comment]
Everything is explained here https://github.com/spacehuhn/esp8266_deauther/blob/master/README.md

If you have problems still please follow these recommendations for asking for help https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md

**Comment by Vaibhavland** [comment]
Bro i want an bin file for the compatiable esp8266 that we get in market with golden lines on top of it

**Comment by Vaibhavland** [comment]
Bro hwo to reset that too??

**Comment by poslogic** [comment]
I have no idea what ESP board that you have?
But if you follow the instructions this should work for any type (it has been tested on most)

To reset your board Google "ESP8266 erase eeprom"

If you are struggling with this information try searching YouTube for some basic videos first before attempting this project.

Good luck

**Comment by spacehuhn** [comment]
I blocked him.

**Comment by spacehuhn** [comment]
Next time don't even help such a spammer.
