### ISSUE TITLE
Change Web Interface

### ISSUE THREAD

**Issue by 2a6o1** [spacehuhn/esp8266_deauther#1584]
Hi!! i want to change the web interface, i already change the html file in the "web_interface" folder and in the "index.html.gz" winrar file and still showing the index default page, help please thnx.
![Untitled](https://user-images.githubusercontent.com/78982930/190726118-a4bbf04a-0a48-414e-bff6-adbfac620e5f.png)

**Comment by EPiCxRIOTZZ** [comment]
because your viewing his webserver...you wont be able to change anything, only huhn

**Comment by rorosin** [comment]
> because your viewing his webserver...you wont be able to change anything, only huhn

local ip bro
facepalm
