### ISSUE TITLE
where is the rtc code located

### ISSUE THREAD

**Issue by Bob-Lobalaw** [spacehuhn/esp8266_deauther#1585]
Hi, I am building my own deauther watch, and would like to include a ds1307 rtc. I have found a piece of code mentioning a ds3231 on line 68 of DisplayUI.cpp, and I am wondering where I might find the rest of it (e.g. pin assignments, initialization, and definitions), so that I might be able to change it to accommodate my rtc.
Any help would be appreciated.

**Comment by Mejkiz** [comment]
Have you found a way to connect RTC?
