### ISSUE TITLE
errors "command welcome not found " and "settings reset to default"  

### ISSUE THREAD

**Issue by freakazoidz** [spacehuhn/esp8266_deauther#1586]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes
**Describe the error**
hello, 

i used a nodemcu v3 flashed with the latest version named " esp8266_deauther_2.6.1_NODEMCU" , and after flash when i launched huhnitor 2.0 for windows ,i have errors like:
"ERROR: command "welcome" not found :("
and after i have : 
"Settings reset to default
Settings saved in /settings.json"

again and again since i disconnect the nodemcu 

i don't know how to solve this
thanks for your help 

![huhnitor prob](https://user-images.githubusercontent.com/7070096/191300499-aebb7e48-f090-4a16-9aac-524b5b88ec30.png)

**Comment by johseffer** [comment]
Same here

**Comment by TheMiner203** [comment]
same
