### ISSUE TITLE
Arduino IDE literally exploding when opening esp8266_deauther.ino

### ISSUE THREAD

**Issue by l0rnem4lv0** [spacehuhn/esp8266_deauther#1592]
When I'm going to open the esp8266_deauther.ino arduino IDE starts to open all the .h files related to the project and starts to run very slow until i cannot interact with the IDE in any way. 

I tried with a macbook M1 and a HP laptop with windows 10, both of them with really well specifications.

**Comment by Acesif** [comment]
Try using an older version of the Arduino IDE. Had the same issues so I downgraded to 1.8.1 and it works fine.
