### ISSUE TITLE
any chance of support for the  BW16 RTL8710BX

### ISSUE THREAD

**Issue by EPiCxRIOTZZ** [spacehuhn/esp8266_deauther#1594]
any chance of support for the  BW16 RTL8710BX its a dual band nodemcu dev board just like the esp8266, can be programmed the same, also supports 5ghz frequencies so can possibly deauth 5ghz.
also can help for support of testing if need be if you dont want to buy device

link to dev board if interested 

https://www.aliexpress.com/item/1005001768102716.html?spm=a2g0o.order_list.0.0.21ef18028lcr8P

**Comment by schlaf3r** [comment]
I actually interfaced it with an esp32 marauder the same way the wiki tells you to connect an esp8266 via the IC connections. it definitely has the capability to deauth at the 2.4ghz range. I've been converting the esp8266 code over to an rtl8720dn but its not anything that I'm gonna have completed anytime soon.
