### ISSUE TITLE
Error when trying to load Arduino file

### ISSUE THREAD

**Issue by markdonofrio** [spacehuhn/esp8266_deauther#1596]
Arduino: 1.8.12 (Windows 10), Board: "Generic ESP8266, NodeMCU, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, 160 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), Disabled, None, v2 Lower Memory, All Flash Contents, 115200"

Executable segment sizes:

IROM   : 796368          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 28396   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 

DATA   : 1348  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 3352  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 27432 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 829464 bytes (86%) of program storage space. Maximum is 958448 bytes.
Global variables use 32132 bytes (39%) of dynamic memory, leaving 49788 bytes for local variables. Maximum is 81920 bytes.
esptool.py v2.8
Serial port COM3
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "C:\Users\Gram\AppData\Local\Arduino15\packages\deauther\hardware\esp8266\2.7.5/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/Gram/AppData/Local/Arduino15/packages/deauther/hardware/esp8266/2.7.5/tools/esptool\esptool.py", line 2890, in main
    esp.connect(args.before)
  File "C:/Users/Gram/AppData/Local/Arduino15/packages/deauther/hardware/esp8266/2.7.5/tools/esptool\esptool.py", line 483, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
_
the selected serial port _
 does not exist or your board is not connected

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by eclipt69** [comment]
Were you able to fix it? I also have the same problem

**Comment by markdonofrio** [comment]
> Were you able to fix it? I also have the same problem

I used the old version of Arduino and it worked.  The new IDE version wouldn't work.  It's much easier to get a raspberry pi and load it with the latest Kali pi ARM image.  It can do 2.5 and 5g deauther as well as many other tools.

**Comment by q1w17** [comment]
> > Were you able to fix it? I also have the same problem
> 
> I used the old version of Arduino and it worked. The new IDE version wouldn't work. It's much easier to get a raspberry pi and load it with the latest Kali pi ARM image. It can do 2.5 and 5g deauther as well as many other tools.

Hey there! Thx for the help. I tried with the 1.8.19 version of arduinoIDE and it didn't work. Can you tell me what version worked for you? Thx :)
