### ISSUE TITLE
AP deauth works but Client deauth not

### ISSUE THREAD

**Issue by WiredLife** [spacehuhn/esp8266_deauther#160]
Hello :)
I've build and flashed the newest version to my wemos d1 mini and it works perfect except the client specific deauth.
Maybe i must set another deauth reason in settings for that?
Thanks!

**Comment by spacehuhn** [comment]
So if you deauth as broadcast (without selecting a client) it works?

**Comment by BioEnergy01** [comment]
After selecting a client on selected AP and going to the attack tab my device reboots. Deauthing an AP works just fine.

**Comment by spacehuhn** [comment]
Add any more information.
 Otherwise I will close it as invalid.

> Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

**Comment by tufaly** [comment]
I've been having the same problem it seems because could choose the client but the next day when am searching for clients and I reconnect it seems to have restarted
