### ISSUE TITLE
After deauth attack, esp8266 wifi die too

### ISSUE THREAD

**Issue by AnduinBrian** [spacehuhn/esp8266_deauther#1604]
Hello, i just down load the source, modify wifi name + pass with my visual code + platformio. After that i flash it in to my wemos d1 r1. After that, i can access the web UI, start clicking some AP to deauth. But when i use deauth, the esp's wifi lost, i cant see it in wifi list.
I made a change in A_config.h

**Comment by AnduinBrian** [comment]
fixed by compile and upload by Arduino IDE. But still dont know why

**Comment by Wannacry1234455900** [comment]
Tnx
