### ISSUE TITLE
Buttons will not work on nodemcu but work fine on a wemos mini

### ISSUE THREAD

**Issue by th3j3sus** [spacehuhn/esp8266_deauther#1605]
I cannot for the life of me seem to get the up,down and ok buttons to working with my nodemcu board. is there a step i am missing? i have this same exact setup on a d1 mini and it works flawlessly. current i have a all buttons to ground, then up is d5 down is d6 and A is d7

**Comment by Neals86** [comment]
Did you enable them in code?

**Comment by ryaneditraj** [comment]
Yea configure it in the config file.
