### ISSUE TITLE
Settings in v1.1 new SSID and hidden wifi 

### ISSUE THREAD

**Issue by John13K** [spacehuhn/esp8266_deauther#161]
Hello team,

I follow the setup tutorial Wifi 'Jammer' Device V1.1 from Seytonic and it works fine at first.
But later I change the settings with a new SSID and hidden the wifi and know I can not see the new or the old SSID of the ESP8266 in any device.
I did several times flash using the nodemcu-flasher in order to solve the issue but unsuccessfully.
It seems that the SSID is hidden and I do not know how to see it again !
Thanks for the support

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by poslogic** [comment]
You will need to set your connecting device to connect to the hidden SSID that you set on the settings page.
Look in your network connections (or Google) for connecting to a hidden SSID

**Comment by John13K** [comment]
I understand but I do not remember the hidden SSID and I want to come back to default settings.
My goal is to  change the settings in order to go back default settings i.e. no hidden SSID.
What are the exact steps that I need to do go back default settings ?

Thanks for the support

**Comment by spacehuhn** [comment]
search for erase eeprom or clear eeprom

**Comment by John13K** [comment]
OK thanks I Google erase/clear eeprom method and to be honest the is too much for me I have no knowledge for that level !
Is there a way to rename i.e. change the hidden SSID ? 
I just need to change the hidden SSID in order to allow me to connect to the hidden SSID.

Thanks team for the support

**Comment by Mcewen123** [comment]
In the Arduino go to : 
File
then select : Exemples
then EEPROM
then eeprom_clear 
then upload and you are done
![eeprom clear](https://cloud.githubusercontent.com/assets/25852304/24585678/93193f38-1790-11e7-82d2-034eafe4db97.png)

**Comment by John13K** [comment]
OK thanks, I could only install the version v1.0 but I could not install v1.1 or v.1.2.

FYI - as lessons learned all my steps:

1º I installed the v1.0 with Arduino upload file and it works 100%.
2º I installed the v1.1 with flash using the nodemcu-flasher and it works 100%.
3º In the v1.1. I change the settings put hidden SSID and I created the problem because I forgot the SSID.
4º I did several times (for the v1.1 and v.1.2) flash using the nodemcu-flasher but does not work.
5º I did several times also upload file with Arduino (for the v1.1 and v.1.2) but does not work neither.
6º I came back to previous step and I reinstalled the v1.0 with Arduino upload file and it works 100%.

It seems that after the settings change with hidden SSID we can not go back.

Once again thanks all for the support

**Comment by spacehuhn** [comment]
Yes because since v1.1 it uses the EEPROM to save the hidden-setting. So clear your EEPROM and it should be fine.

**Comment by spacehuhn** [comment]
Look in the serial monitor. The ESP8266 will print out its settings so you can see waht SSID it has.

**Comment by Fireflaker** [comment]
I had the same issue with you and solved it.

For me, the data stored was damaged for some reason. I could connect to it but it resets itself every 5 seconds. 192.168.4.1 does not respond. Reason for data loss is likely to be frequent power removal and playing with the in board keys too much.(Wrong gramma)

Solution:
1 use a paper clip to clip down "flash"key. Don't take it off during entire time.
2 plug into computer
3 press "reset" key once. If the blue led onboard flash ONLY once, you should be good. IF the led goes crazy or even stays on, check if flash key if held down.
4 flash it with settings: 9600 baud, 80MHz, 4M. MUST BE 9600 or will not work.
5 DO NOT TOUCH RESET KEY. To reset, unplug from power source, remove paper clip, and plug it in again.
6 It worked for me. Good luck. Don't touch any keys when using! Don't reset using reset key. Don't remove power when anything is going on. Or, it might be all good if you are lucky, but if it is accessing eepram, it is dead and you must flash it again.

**Comment by John13K** [comment]
problem solved closed :)
The "flash" did not work for me thanks you anyway. 
So as backup I followed the spacehuhn tip and the serial monitor printed the settings with the SSID and now it works 100%.

FYI - The ESP8266 it's a very good device because during this issue I did "thousand times" flash, resets power on/off and  the ESP8266 still working. 

thanks all for the support

**Comment by schinfo** [comment]
My tool can fix the problem too.

https://github.com/schinfo/EEPROM-Cleaner

**Comment by Vibgyorisavailable** [comment]
I am having the same problem and I couldn't flash my node mcu please 🙏 help me, I tried flashing but it did not flash, I also did searched eprom clear it gave me errors I'm using v1, reset flashing and everything just seem to be fake in themselves I forgot my ssid and password and it's just showing hidden network, serial monitor couldn't help me either, I am in pain... Help me.....

**Comment by Vibgyorisavailable** [comment]
> problem solved closed :) The "flash" did not work for me thanks you anyway. So as backup I followed the spacehuhn tip and the serial monitor printed the settings with the SSID and now it works 100%.
> 
> FYI - The ESP8266 it's a very good device because during this issue I did "thousand times" flash, resets power on/off and the ESP8266 still working.
> 
> thanks all for the support

Its just showing reverse question marks nothing more than that the serial monitor..
