### ISSUE TITLE
Question regarding internet connection 

### ISSUE THREAD

**Issue by fox-die-zero** [spacehuhn/esp8266_deauther#1615]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki).  

I bought a flashed deauther online and everything seems to be alright. Pwned shows up in wifi connections and the password works. But when I connect to pwned it says "No internet". 
Did I bought a fake or a faulty deauther? If not can I reflash it? 

Thanks for your time reading this.

**Comment by Markixo25** [comment]
Men the Pwned wifi is only a local area network to show you the page interface that it have at the 192.168.4.1 ip.
In this page you can change settings and do many things.
In this Youtube video you have a tutorial https://www.youtube.com/watch?v=YpCH9FgOR9w&ab_channel=TravisLin
