### ISSUE TITLE
Upload error with NodeMCU

### ISSUE THREAD

**Issue by pvtoari** [spacehuhn/esp8266_deauther#1667]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**
Whenever I try to upload the deauther code to my nodemcu board it just throws the same error that I show on the image

```
Traceback (most recent call last):
  File "C:\Users\ariel\AppData\Local\Arduino15\packages\deauther\hardware\esp8266\2.7.5/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/ariel/AppData/Local/Arduino15/packages/deauther/hardware/esp8266/2.7.5/tools/esptool\esptool.py", line 2890, in main
    esp.connect(args.before)
  File "C:/Users/ariel/AppData/Local/Arduino15/packages/deauther/hardware/esp8266/2.7.5/tools/esptool\esptool.py", line 483, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
Failed uploading: uploading error: exit status 1
```

**Expected behavior**
Expected to flash correctly the board :(

**Screenshots**
![imagen](https://github.com/SpacehuhnTech/esp8266_deauther/assets/43178469/e1d906ab-3b1b-43a1-ad07-8415bd0f3e80)

**Environment (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Firefox
 - Version idk (latest?)
 - Hardware DIY

**Attempts**
I tried to update every neccesary driver from NodeMCU or ArduinoIDE and nothing seems to work.

**Additional context**
I read in a forum that it might be an hardware error and my board might be defective. Help guys :[

**Comment by Karthik-Sarvan** [comment]
Open the
 ``` C:\Users\ariel\AppData\Local\Arduino15\packages ``` 
on your file explorer and delete the full deauther folder and then try to  install the  deauther in your arduino. 
And then upload the code into the esp8266
it shoud be working fine
once again check the port on which the esp8266 on.
make sure you are on it

**Comment by pvtoari** [comment]
> 

Already tried and happens the same :/

![imagen](https://github.com/SpacehuhnTech/esp8266_deauther/assets/43178469/d48bbbee-f705-4de2-a16f-02fc7abb10fc)

**Comment by pvtoari** [comment]
> Open the `C:\Users\ariel\AppData\Local\Arduino15\packages` on your file explorer and delete the full deauther folder and then try to install the deauther in your arduino. And then upload the code into the esp8266 it shoud be working fine once again check the port on which the esp8266 on. make sure you are on it

that didnt work :(
![imagen](https://github.com/SpacehuhnTech/esp8266_deauther/assets/43178469/0effb45d-a743-4396-a952-b268a8419f9d)

**Comment by pvtoari** [comment]
i closed this by error :(
