### ISSUE TITLE
Is there any way to edit the index.html?

### ISSUE THREAD

**Issue by gabenthegamer** [spacehuhn/esp8266_deauther#168]
---

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---
Ok so i want to edit the index is that possible?

**Comment by spacehuhn** [comment]
yes https://github.com/spacehuhn/esp8266_deauther/tree/master/web_server

**Comment by haxord7** [comment]
In deauth folder you will get all html files , if you want edit then edit those files and convert it hex then replace it in data.h  .
