### ISSUE TITLE
Will this work??

### ISSUE THREAD

**Issue by klgor1803** [spacehuhn/esp8266_deauther#1695]
i found this esp8266 with a oled screen, but it is connected by a flat, not by the pins, look:
![-1047777842946099016](https://github.com/SpacehuhnTech/esp8266_deauther/assets/89669610/9c4cd09f-011c-47e3-a0ee-41d3ab514f11)

**Comment by wryhode** [comment]
If the screen is connected to the usual I2C pins (they might also be remappable), then I think it should work. The only concern, then, would be the lack of buttons

**Comment by wryhode** [comment]
If the screen is connected to the usual I2C pins (they might also be remappable), then I think it should work. The only concern, then, would be the lack of buttons.
