### ISSUE TITLE
Wpa3

### ISSUE THREAD

**Issue by smoochiee** [spacehuhn/esp8266_deauther#1696]
Unable to deauth wpa3 encryptions

**Comment by wryhode** [comment]
Afaik WPA3 requires protected management frames to be used, which quite securely protects against deauth-attacks.
See: https://blog.spacehuhn.com/deauth-attack-not-working#heading-protected-management-frames

Also worth mentioning is that the ESP8266 can only use 2.4GHz networks. The access point might be 5GHz.

**Comment by smoochiee** [comment]
> Afaik WPA3 requires protected management frames to be used, which quite securely protects against deauth-attacks.
> See: https://blog.spacehuhn.com/deauth-attack-not-working#heading-protected-management-frames
> 
> Also worth mentioning is that the ESP8266 can only use 2.4GHz networks. The access point might be 5GHz.

Okay ive read that 2.4ghz with wpa3 cant be deauth...
