### ISSUE TITLE
Attack detection feature

### ISSUE THREAD

**Issue by bildos99** [spacehuhn/esp8266_deauther#171]
Hi All,

Would be nice if one of next version will include features to detect WiFi attacks.

Definitely it will be extremely useful for all of us.

Thanks!

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by spacehuhn** [comment]
It's added to the list 👍
