### ISSUE TITLE
Add OLED and web interface support to V3

### ISSUE THREAD

**Issue by AyceBenz** [spacehuhn/esp8266_deauther#1712]
I know that Deauther V3 primarily uses a CLI interface, but adding OLED and web interfaces significantly enhances its usability compared to V2. These features are probably what the majority of users are accustomed to and expect in an upgraded version.

**Comment by AyceBenz** [comment]
If it really needs the extra power, why not also disable the option for some other attack types so that atleast its still acessible

**Comment by Wannacry1234455900** [comment]
How can I help?
