### ISSUE TITLE
Fake ssid doesn't work

### ISSUE THREAD

**Issue by WorstMaster** [spacehuhn/esp8266_deauther#1735]
i cant make fake ssids im using Nodemcu esp8266 
but fake ssids doesnt shown in my phone or laptop .
have you any solutions for me?

**Comment by harvez** [comment]
#include <WiFi.h>

const char* fakeSSID = "MyFakeSSID";
const char* fakePassword = "12345678";

void setup() {
  Serial.begin(115200);

  WiFi.mode(WIFI_AP);
  WiFi.softAP(fakeSSID, fakePassword);

  Serial.println("Fake SSID created: " + String(fakeSSID));
  Serial.println("Fake password: " + String(fakePassword));
}

void loop() {
  // Do nothing in the loop
}
In this code, we use the WiFi.mode() function to set the ESP8266 to act as an access point (AP) mode. Then, we use the WiFi.softAP() function to create a fake SSID and password for the access point.

To connect to this fake SSID, you can use any WiFi-enabled device (like a smartphone or laptop) and enter the fake SSID and password. However, keep in mind that this is a simulated network and the actual data transmitted over this network will not go through the ESP8266.

Please note that creating fake SSIDs is a security risk and should be done only for educational or testing purposes. In a real-world scenario, it is not recommended to create and broadcast fake SSIDs.
