### ISSUE TITLE
Stuck at Initializing - Deauth app 

### ISSUE THREAD

**Issue by elk1007** [spacehuhn/esp8266_deauther#1743]
![Screenshot-20241003-165011](https://github.com/user-attachments/assets/055cb3e6-c449-4a9b-803f-6791ded4b654)

_________________________________________________________________________________________________________

**> Have you searched for existing (open and closed) issues describing the same problem?**
Yes

**Describe the error**
When I open the Deauth app on Flipper, it gets stuck at Initializing... 

I was able to successfully flash Deauth onto my D1 mini V4 (using flash tool QOUT method).
The module is detected, and I can even flash using ESP Flasher. 
Selecting Enter Bootloader in ESP Flasher creates the SSID pwned and I am able to connect. 

I must be overlooking something simple, as the deauth app can't go past Initializing.... 

 

```
**Error/Compile/Output Log**

Please let me know where I can find a relevant log file to this issue. I will post it. 
```

To Reproduce
1. Connect Flipper to D1 mini per provided schematic 
2. Reset Flipper (back and left)
3. Open ESP8266-Death 
4. Brief message appears to connect the module
5. Quickly changes to "Initializing..." 
6. Stays here indefinitely

Expected behavior
Screen should go past "initializing..."

Environment (please complete the following information):
-Flipper Zero
-Unleashed firmware w/preinstall and 'flipper-z-f7-full-local' firmware which shows deauth in main menu (tried both, same issue "initializing")
-D1 Mini Ver4 

Attempts
I have tried to swap TX/RX pins. 
I have tried to connect/disconnect Pin 0 to ground. This was required to flash the chip. 
I have tried reinstalling firmware and resetting flipper. 

Any input, suggestion, or guess, is appreciated.

**Comment by elk1007** [comment]
https://github.com/SequoiaSan/FlipperZero-Wifi-ESP8266-Deauther-Module/issues/10#issuecomment-2386093446

Resolved

**Comment by TickTastley** [comment]
How did you resolve it? I spent my pocket money for this, I need to know immediately, my dad will kill me :D
