### ISSUE TITLE
Hi i want to add ir blast function that blasts power off codes in display i used chatgpt and tried to debug myself but getting same errors

### ISSUE THREAD

**Issue by IDknoobcoder** [spacehuhn/esp8266_deauther#1744]
Hi i want to add ir blast function that blasts power off codes in display i used chatgpt and tried to debug myself but getting same errors
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:37:31: error: no 'void DisplayUI::setupMainMenu()' member function declared in class 'DisplayUI'
 void DisplayUI::setupMainMenu() {
                               ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:50:10: error: no matching function for call to 'DisplayUI::addMenuNode(MenuNode&, const char [21], DisplayUI::setupIRBlastMenu()::__lambda0::__lambda1)'
         });
          ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:50:10: note: candidates are:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click, std::function<void()>hold);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note:   candidate expects 4 arguments, 3 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, Menu*)
         void addMenuNode(Menu* menu, std::function<String()>getStr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note: void DisplayUI::addMenuNode(Menu*, const char*, std::function<void()>)
         void addMenuNode(Menu* menu, const char* ptr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note: void DisplayUI::addMenuNode(Menu*, const char*, Menu*)
         void addMenuNode(Menu* menu, const char* ptr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:54:32: error: no matching function for call to 'DisplayUI::changeMenu(Menu&)'
             changeMenu(mainMenu);
                                ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:54:32: note: candidate is:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:190:14: note: void DisplayUI::changeMenu(Menu*)
         void changeMenu(Menu* menu);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:190:14: note:   no known conversion for argument 1 from 'Menu' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:55:10: error: no matching function for call to 'DisplayUI::addMenuNode(MenuNode&, const char [18], DisplayUI::setupIRBlastMenu()::__lambda0::__lambda2)'
         });
          ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:55:10: note: candidates are:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click, std::function<void()>hold);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note:   candidate expects 4 arguments, 3 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, Menu*)
         void addMenuNode(Menu* menu, std::function<String()>getStr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note: void DisplayUI::addMenuNode(Menu*, const char*, std::function<void()>)
         void addMenuNode(Menu* menu, const char* ptr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note: void DisplayUI::addMenuNode(Menu*, const char*, Menu*)
         void addMenuNode(Menu* menu, const char* ptr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In member function 'void DisplayUI::setupIRBlastMenu()':
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:56:6: error: no matching function for call to 'DisplayUI::createMenu(MenuNode&, Menu&, DisplayUI::setupIRBlastMenu()::__lambda0)'
     });
      ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:56:6: note: candidate is:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:192:14: note: void DisplayUI::createMenu(Menu*, Menu*, std::function<void()>)
         void createMenu(Menu* menu, Menu* parent, std::function<void()>build);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:192:14: note:   no known conversion for argument 1 from 'MenuNode' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In constructor 'DisplayUI::DisplayUI()':
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:113:11: error: no match for 'operator=' (operand types are 'MenuNode' and 'Menu*')
   IRBlast = new Menu();
           ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:113:11: note: candidates are:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:60:8: note: MenuNode& MenuNode::operator=(const MenuNode&)
 struct MenuNode {
        ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:60:8: note:   no known conversion for argument 1 from 'Menu*' to 'const MenuNode&'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:60:8: note: MenuNode& MenuNode::operator=(MenuNode&&)
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:60:8: note:   no known conversion for argument 1 from 'Menu*' to 'MenuNode&&'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:114:14: error: no match for 'operator=' (operand types are 'Menu' and 'Menu*')
     mainMenu = new Menu();
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:114:14: note: candidates are:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:66:8: note: Menu& Menu::operator=(const Menu&)
 struct Menu {
        ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:66:8: note:   no known conversion for argument 1 from 'Menu*' to 'const Menu&'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:66:8: note: Menu& Menu::operator=(Menu&&)
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:66:8: note:   no known conversion for argument 1 from 'Menu*' to 'Menu&&'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:147:50: error: no matching function for call to 'DisplayUI::addMenuNode(Menu*, const char [7], MenuNode*)'
         addMenuNode(&mainMenu, D_ATTACK, &IRBlast);     // ATTACK
                                                  ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:147:50: note: candidates are:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click, std::function<void()>hold);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note:   candidate expects 4 arguments, 3 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note:   no known conversion for argument 2 from 'const char [7]' to 'std::function<String()>'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, Menu*)
         void addMenuNode(Menu* menu, std::function<String()>getStr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note:   no known conversion for argument 2 from 'const char [7]' to 'std::function<String()>'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note: void DisplayUI::addMenuNode(Menu*, const char*, std::function<void()>)
         void addMenuNode(Menu* menu, const char* ptr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note:   no known conversion for argument 3 from 'MenuNode*' to 'std::function<void()>'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note: void DisplayUI::addMenuNode(Menu*, const char*, Menu*)
         void addMenuNode(Menu* menu, const char* ptr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note:   no known conversion for argument 3 from 'MenuNode*' to 'Menu*'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:395:76: error: 'select' was not declared in this scope
             return stations.getSelected(selectedID) ? str(select(selectedID) : stations.select(selectedID);
                                                                            ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:395:107: error: expected ':' before ';' token
             return stations.getSelected(selectedID) ? str(select(selectedID) : stations.select(selectedID);
                                                                                                           ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:395:107: error: expected primary-expression before ';' token
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:396:10: error: no matching function for call to 'DisplayUI::addMenuNode(Menu*, DisplayUI::setup()::__lambda56::__lambda66)'
         });
          ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:396:10: note: candidates are:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click, std::function<void()>hold);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note:   candidate expects 4 arguments, 2 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note:   candidate expects 3 arguments, 2 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, Menu*)
         void addMenuNode(Menu* menu, std::function<String()>getStr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note:   candidate expects 3 arguments, 2 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note: void DisplayUI::addMenuNode(Menu*, const char*, std::function<void()>)
         void addMenuNode(Menu* menu, const char* ptr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note:   candidate expects 3 arguments, 2 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note: void DisplayUI::addMenuNode(Menu*, const char*, Menu*)
         void addMenuNode(Menu* menu, const char* ptr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note:   candidate expects 3 arguments, 2 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:399:58: error: 'struct Menu' has no member named 'sD_DESELECT'
             stationListMenu.list->remove(stationListMenu.sD_DESELECT) : str(D_SELECT); // SELECT/DESELECT
                                                          ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:399:71: error: expected ';' before ':' token
             stationListMenu.list->remove(stationListMenu.sD_DESELECT) : str(D_SELECT); // SELECT/DESELECT
                                                                       ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:401:57: error: 'class Stations' has no member named 'deelected'
             stations.getSelected(selectedID) ? stations.deelected);
                                                         ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:401:66: error: expected ':' before ')' token
             stations.getSelected(selectedID) ? stations.deelected);
                                                                  ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:401:66: error: expected primary-expression before ')' token
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:401:66: error: expected ';' before ')' token
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp: In lambda function:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:403:10: error: no matching function for call to 'DisplayUI::addMenuNode(Menu*, const char [7], DisplayUI::setup()::__lambda56::__lambda67, DisplayUI::setup()::__lambda56::__lambda68)'
         });
          ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:403:10: note: candidates are:
In file included from C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.cpp:3:0:
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click, std::function<void()>hold);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:194:14: note:   no known conversion for argument 2 from 'const char [7]' to 'std::function<String()>'
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, std::function<void()>)
         void addMenuNode(Menu* menu, std::function<String()>getStr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:195:14: note:   candidate expects 3 arguments, 4 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note: void DisplayUI::addMenuNode(Menu*, std::function<String()>, Menu*)
         void addMenuNode(Menu* menu, std::function<String()>getStr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:196:14: note:   candidate expects 3 arguments, 4 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note: void DisplayUI::addMenuNode(Menu*, const char*, std::function<void()>)
         void addMenuNode(Menu* menu, const char* ptr, std::function<void()>click);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:197:14: note:   candidate expects 3 arguments, 4 provided
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note: void DisplayUI::addMenuNode(Menu*, const char*, Menu*)
         void addMenuNode(Menu* menu, const char* ptr, Menu* next);
              ^
C:\Users\Erics\Downloads\esp8266_deauther-2 (1)\esp8266_deauther-2\esp8266_deauther\DisplayUI.h:198:14: note:   candidate expects 3 arguments, 4 provided

exit status 1

Compilation error: no 'void DisplayUI::setupMainMenu()' member function declared in class 'DisplayUI'

**Comment by wryhode** [comment]
Hey, thank you for the post! To be able to help you, you'd need to post the code ChatGPT made for you. I have to warn you, however, that LLMs aren't that good at working with large projects, and this is a quite large project, unfortunately.

**Comment by IDknoobcoder** [comment]
Bro leav

**Comment by IDknoobcoder** [comment]
Bro sorryclosed by mistake I just want to integrate a new menu on display that blasts power off ur codes could u guide how to do i m a beginner not much in coding
