### ISSUE TITLE
ESP8266 KEEPS RESSETING 

### ISSUE THREAD

**Issue by PYNX-01** [spacehuhn/esp8266_deauther#1753]
My esp8266 keeps resseting after i upload the from arduino and esp8266 flasher, the code is working but it keeps resseting, i tried it to my (3) esp8266 and still have the same issue

(-------   It show in serial ----------)

 ets Jan  8 2013,rst cause:4, boot mode:(3,4)

wdt reset

load 0x4010f000, len 3584, room 16 

tail 0

chksum 0xb0

csum 0xb0

v2843a5ac

~ld

Mounting SPIFFS...OK

Loading settings...OK

Device names loaded from /names.json

SSIDs loaded from /ssids.json

Scan results saved in /scan.json

Serial interface enabled

Started AP

[WiFi] Path: '/web', Mode: 'AP', SSID: 'pwned', password: 'deauther', channel: '1', hidden: false, captive-portal: false

STARTED! \o/

2.6.1

**Comment by PYNX-01** [comment]
The "Display Example I2C" board config is broken. Do not use it. Instead, under the "deauther config" menu, select the default "NodeMCU" at the top, and then in A_config.h, manually copy everything from the "Display Example I2C" section to the top, outside of its "#if defined" group.

**Comment by Sasank36** [comment]
Give me your discord
