### ISSUE TITLE
Packets rate 

### ISSUE THREAD

**Issue by haxord7** [spacehuhn/esp8266_deauther#178]
In version 1.2 packet rate has lilmited only 20pkts if i change this to 50 or or more its continuesly sends 20pkts . version 1.1 has no problem like this . send upto 300+ pkts ,how to do same thing in version 1.2 ,??

i face another problem when first time i plugged and start attacking page is not responding but blue led blinking like its running ok but acctually i didn't acces the attack page .after 20/22 secend its running smoothly no problem .i face this stucking issue  when i plugged esp first time ,then 20/22 secend left i got the deauth page ,how to fix it??

please look at the picture  <a href="http://imgur.com/k4RY64s"><img src="http://i.imgur.com/k4RY64s.png" title="source: imgur.com" /></a>

---

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by spacehuhn** [comment]
It's both working fine for me using the latest testing branch.

**Comment by haxord7** [comment]
thanks ,testing branch is running smoothly no problem . :+1:
