### ISSUE TITLE
No networks found

### ISSUE THREAD

**Issue by digounet** [spacehuhn/esp8266_deauther#185]
Hi, I've succesffully flashed it into my ESP-01 board but no networks are listed. Any issue with the version?

**Comment by jLynx** [comment]
I don't have this issue running  the latest version on both my boards, are you sure there are networks around you are are 2.4 ghz and not 5ghz?

**Comment by digounet** [comment]
Hello,  I don't know why but if I connect to the 8266 using my notebook no networks are listed. But if I use my iphone to connect then it works but the deauth attack isn't working (maybe my AP isn't vulnerable). Thanks

**Comment by spacehuhn** [comment]
Use an up to date version of Firefox or Chrome and the scan should work, unless there are no networks in range of course.

**Comment by WillGreen98** [comment]
Could Tor potentially work? Scan for bridges etc...
