### ISSUE TITLE
I F'ed up

### ISSUE THREAD

**Issue by djwildbill** [spacehuhn/esp8266_deauther#187]
So i messed up i changed the password is there a way to hack it back to default
---

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by poslogic** [comment]
Use the settings page to change the password.

Erase the EEPROM and re-flashing to get a clean start.

**Comment by djwildbill** [comment]
That was the issue I changed the password in the settings and my smartphone auto correct the darn thing... 

I tried refreshing it and every stated the same

**Comment by spacehuhn** [comment]
Connect your dev board, open the serial monitor in arduino and click on reset on the board.
It will print out all settings including the password.

**Comment by poslogic** [comment]
Or type the same thing into your phone again and see what it automatically corrects to?

But using serial monitor will show you the password :)

**Comment by djwildbill** [comment]
I tried but I found out what happened when I did it and do the web interface they capitalize the first letter but when I go to type in the password for the Wi-Fi it isn't capital but thank you for let me know that cereal would let me know that information

**Comment by RiccardoMax** [comment]
Hey guys, I got the same problem but when i click reset on the board it gives me this: 8P⸮t⸮⸮⸮⸮⸮Xp⸮⸮
Any Help?

**Comment by spacehuhn** [comment]
You have to set the Baudrate to 115200 in the serial monitor.

**Comment by djwildbill** [comment]
Thanks Spacehun this thing rocks

**Comment by RiccardoMax** [comment]
Thanks spacehuhn, I managed to solve this issue by reflashing the unit and then reinstalling the software.
