### ISSUE TITLE
Need ur help

### ISSUE THREAD

**Issue by J4ck02** [spacehuhn/esp8266_deauther#188]
Hey Spacehuhn

i know it´s not a real issue but i don´t know how to contact you.
I´ve build an enclosure for my ESP8266. Now i would like to ask would it be possible to connect a extern Led to light up while an attack is active i don´t want to use the build in LED.
If this is the wrong place to ask please head me over to the right one.
Help would be much appreciated.
Thanks in advance J4ck

**Comment by spacehuhn** [comment]
One way would be to connect the LED to pin 2 which is the pin for the built-in LED.
Otherwise you have to change the `Attack::refreshLed` function in `Attack.h` and change the `digitalWrite` to whatever pin you wanna use. You also have to change it in the `esp8266_deauther.ino` at `pinMode(2, OUTPUT)`.

**Comment by J4ck02** [comment]
That sounds good so pin2 equals D2 ?

**Comment by spacehuhn** [comment]
I don't know, you have to look that up for your board.

**Comment by J4ck02** [comment]
Ok i´ll do that, thanks for your fast reply :)

**Comment by spacehuhn** [comment]
Your welcome :)

**Comment by J4ck02** [comment]
Sry man ik ur busy but it´s not working :/

**Comment by poslogic** [comment]
It would help if you could identify what ESP board that you are using? 

Guessing that it's a WeMos D1 Mini?
Make sure that you use the 3.3v gpio not the 5v

Best to get a simple blink sketch working first before attempting to use with this project

**Comment by J4ck02** [comment]
I got the blink sketch working man. Im using this Board [http://www.banggood.com/de/NodeMcu-Lua-WIFI-Internet-Things-Development-Board-Based-ESP8266-CP2102-Wireless-Module-p-1097112.html?rmmds=myorder](url)

**Comment by poslogic** [comment]
The link does not work for us because it is linking into your orders from your account.

Did you get the blink sketch to work with an external led?

**Comment by poslogic** [comment]
The link does not work for us because it is linking into your orders from your account.

Did you get the blink sketch to work with an external led?

But looks like you have a Node MCU Dev board?

**Comment by J4ck02** [comment]
Yes it´s a NodeMCU sry for the corrupt link
 So i got the led kinda working but if i start the attack it turns off :D any ideas ?

**Comment by J4ck02** [comment]
Fail alarm. Got the Blink working with D0 it´s blinking but if i do likespacehuhn sad 
```
One way would be to connect the LED to pin 2 which is the pin for the built-in LED.
Otherwise you have to change the Attack::refreshLed function in Attack.h and change the digitalWrite to whatever pin you wanna use. You also have to change it in the esp8266_deauther.ino at pinMode(2, OUTPUT).
```
it won´t light up the LED

**Comment by J4ck02** [comment]
![Uploading Nodecase.jpg…]()

Works like a charm! Thank u guys ;)
