### ISSUE TITLE
I have  a Question ??

### ISSUE THREAD

**Issue by Elora393** [spacehuhn/esp8266_deauther#189]
see the picture : esp8266_deauther  can stop this red signaled wifi??

<a href="http://imgur.com/EyT2TVf"><img src="http://i.imgur.com/EyT2TVf.png" title="source: imgur.com" /></a>
---

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by poslogic** [comment]
Yes move closer to the AP's
The ESP8266 is very portable
