### ISSUE TITLE
stray '#' in program

### ISSUE THREAD

**Issue by LucasTor** [spacehuhn/esp8266_deauther#19]
Hi i'm trying to compile the code but i get this error message, does anyone knows how to fix it? thanks so much! 

Arduino: 1.8.1 (Windows 10), Placa:"Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck"

esp8266_deauther:1: error: stray '#' in program

 do#include <Arduino.h>

   ^

esp8266_deauther:1: error: expected unqualified-id before 'do'

 do#include <Arduino.h>

 ^

In file included from c:\users\lucas\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\new:40:0,

                 from c:\users\lucas\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\ext\new_allocator.h:33,

                 from c:\users\lucas\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\xtensa-lx106-elf\bits\c++allocator.h:33,

                 from c:\users\lucas\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\bits\allocator.h:46,

                 from c:\users\lucas\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\memory:63,

                 from C:\Users\Lucas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/WiFiClient.h:28,

                 from C:\Users\Lucas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:32,

                 from C:\Users\Lucas\Desktop\wifi jammer\esp8266_deauther-master\esp8266_deauther\esp8266_deauther.ino:3:

c:\users\lucas\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\exception:35:37: error: expected declaration before end of line

 #pragma GCC visibility push(default)

                                     ^

exit status 1
stray '#' in program

Este relatório teria mais informações com
"Mostrar a saida detalhada durante a compilação"
opção pode ser ativada em "Arquivo -> Preferências"

**Comment by doge27** [comment]
It seems that you have installed the libraries incorrectly. Try reinstalling it
