### ISSUE TITLE
Not an issue, just a warning

### ISSUE THREAD

**Issue by jLynx** [spacehuhn/esp8266_deauther#191]
EverythingApplePro with 3.5 million subscribers just released a video on this. So just pre warning you with the mass amount of people(kids) who are going to flood this git page with spam and stupid issues https://www.youtube.com/watch?v=xYeQvMEtyBs

You can close this when you have read it.

**Comment by SaltyViper** [comment]
Already warned spacehuhn via discord about the great skid zerg rush brewing on the horizon

**Comment by jLynx** [comment]
Discord link @SaltyViper ?

**Comment by SaltyViper** [comment]
[This](https://discord.gg/DtgAs) is the seytonic discord server, spacehuhn is asleep at the moment as its really late in germany.

**Comment by jLynx** [comment]
Thanks, I have joined the server
