### ISSUE TITLE
LCD and button wiring 

### ISSUE THREAD

**Issue by ErfanDL** [spacehuhn/esp8266_deauther#192]
Hi. I need LCD and button wiring

**Comment by spacehuhn** [comment]
````#ifdef USE_DISPLAY

#include <Wire.h>

//include the library you need
#include "SSD1306.h"
//#include "SH1106.h"

//button pins
#define upBtn D6
#define downBtn D7
#define selectBtn D5

#define buttonDelay 180 //delay in ms

//render settings
#define fontSize 8
#define rowsPerSite 8

//create display(Adr, SDA-pin, SCL-pin)
SSD1306 display(0x3c, D2, D1);
//SH1106 display(0x3c, D2, D1);

int rows = 3;
int curRow = 0;
int sites = 1;
int curSite = 1;
int lrow = 0;
#endif```

**Comment by ErfanDL** [comment]
is compiled BIN have LCD feature ?

**Comment by schinfo** [comment]
Hello ErfanDL,

please use your brain, not your keyboard

**Comment by ErfanDL** [comment]
Im wiring LCD but not worked

![photo_2017-04-18_14-25-18](https://cloud.githubusercontent.com/assets/14868771/25125141/07d46e4c-2443-11e7-86df-3df7119fbd39.jpg)

**Comment by schinfo** [comment]
Connect the white wire to 3V3 (Pin left of the red wire)

**Comment by ErfanDL** [comment]
@schinfo 
Im do it but not worked ! wiring SDA to D2 and SCL to D1 - VCC to 3.3 & GND to GND

**Comment by schinfo** [comment]
You must use the Arduino-IDE, not the BIN-File

**Comment by schinfo** [comment]
And read the hints in "esp8266_deauther.ino"

**Comment by schinfo** [comment]
Line 16:  //#define USE_DISPLAY /* <-- uncomment that if you wanna use the display */

**Comment by schinfo** [comment]
It's not enabled in the BIN-Files

**Comment by spacehuhn** [comment]
Please don't spam.
It's for advanced users, you have to use some knowlege about how to use an OLED.
I can't explain every little detail.

**Comment by ErfanDL** [comment]
Thanks. its worked with arduino ide

![photo_2017-04-18_15-05-10](https://cloud.githubusercontent.com/assets/14868771/25126769/9761bec0-2448-11e7-861d-b6d0830c2f6f.jpg)
