### ISSUE TITLE
Help i have error uploading

### ISSUE THREAD

**Issue by helpme1234432** [spacehuhn/esp8266_deauther#195]
---

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by jLynx** [comment]
Please don't post spam. If you have a problem, please format the issue correctly and ask a question

**Comment by helpme1234432** [comment]
Arduino: 1.8.2 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"  sketch\Attack.cpp: In member function 'bool Attack::send()':  Attack.cpp:102: error: 'wifi_send_pkt_freedom' was not declared in this scope     if (wifi_send_pkt_freedom(packet, packetSize, 0) == -1) {                                                    ^  exit status 1 'wifi_send_pkt_freedom' was not declared in this scope  This report would have more information with "Show verbose output during compilation" option enabled in File -> Preferences.

**Comment by helpme1234432** [comment]
The error im getting ^^^

**Comment by jLynx** [comment]
Again, please format the issue properly and give us some background, or we cannot help you and your issue will be closed

**Comment by SaltyViper** [comment]
You have not properly configured the arduino IDE as shown in [the instructions,](https://github.com/spacehuhn/esp8266_deauther/#compiling-the-source-with-arduino) Make sure you don't miss **any** steps.

**Comment by SaltyViper** [comment]
@helpme1234432

**Comment by helpme1234432** [comment]
is this video explain it right?  
https://www.youtube.com/watch?v=MOscKnm8IcY&t=261s

**Comment by helpme1234432** [comment]
ive done this whole thing 3 times, the error code is poping up, plz help
