### ISSUE TITLE
Settings won't load

### ISSUE THREAD

**Issue by Spektrumz** [spacehuhn/esp8266_deauther#202]
The settings won't load, I searched down the the issues page but I couldn't find it, If It exists can someone link it please?

**Comment by spacehuhn** [comment]
It was mentioned in other issues often. Though you still have to debug it and provide more information, as described in the [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md).

**Comment by Spektrumz** [comment]
I am kindda new, If you can help me I will be really happy. What kind of information shall I provide you with?

**Comment by Spektrumz** [comment]
At first, It was all good but It stopped functioning...

**Comment by Spektrumz** [comment]
I downloaded the 512k, It's working now.

**Comment by jLynx** [comment]
Since the problem is fixed, I will now close this issue
