### ISSUE TITLE
Compiling Source

### ISSUE THREAD

**Issue by HS8800** [spacehuhn/esp8266_deauther#203]
I got this deauther to work and it's great well done. Now I have been trying to change the password, I have found to change in Settings.ccp but I have had a bit of a problem compiling it into a .bin to be uploaded with ESP8266Flash. I'm sorry if its obvious i'm still learning.

**Comment by jLynx** [comment]
What?... All you have to do is go to the setting page on the device's webpage and you can change the password there. Why are you trying to change it in the source code?

**Comment by HS8800** [comment]
what you can do that ... thx XD
