### ISSUE TITLE
Can I modify the "web_server" html? I want to change it to Chinese. How do I upload it?

### ISSUE THREAD

**Issue by 123wbx321wbx** [spacehuhn/esp8266_deauther#205]
---

Can I modify the "web_server" html? I want to change it to Chinese. How do I upload it?

---

**Comment by jLynx** [comment]
As long as you adhere to the licence, then there is no problems with you translating it.

**Comment by 123wbx321wbx** [comment]
I know that I will keep the license.
But I would like to ask why I modified later, Use Arduino after upload but same as before.

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/blob/master/web_server/readme.md

**Comment by 123wbx321wbx** [comment]
oh thx
