### ISSUE TITLE
Access Points tab refreshing constantly

### ISSUE THREAD

**Issue by enderface36** [spacehuhn/esp8266_deauther#210]
Hey, I am have very basic knowledge so bare with me.
Issue: When i go to 192.168.4.1 the page is frozen other than the scan button flashing and the page constantly refreshing.
Hardware/software: I am using a NodeMCU w/ ESP8266, I used the arduino method of installation.
Plz help

**Comment by jLynx** [comment]
Can you try clear your EPROM and reflash?

**Comment by Mikubo** [comment]
How can i clear the EPROM?

**Comment by jLynx** [comment]
@Mikubo read the wiki faq

**Comment by Mikubo** [comment]
Thanks jLynx. I've read the wiki faq but there is no explanation as I have to use this.
Does this also works? http://s6z.de/cms/index.php/homeautomation-homecontrol/hardwareplattformen/esp8266/131-loeschen-des-gesamten-flashspeichers
