### ISSUE TITLE
My deauth BUTTONS ARE GONE

### ISSUE THREAD

**Issue by Sumeetu47** [spacehuhn/esp8266_deauther#211]
![capture](https://cloud.githubusercontent.com/assets/27898612/25306965/3166eb60-27b6-11e7-9b7a-769470eb18a4.JPG)
![45](https://cloud.githubusercontent.com/assets/27898612/25306966/31697826-27b6-11e7-9791-109c53111fb9.JPG)
I am using lolin nodemsu 
i used auto-flash software provided on your page and it worked perfectly but after 6-7hrs the buttons were gone. it connect properly to every device, even scans ap s and clients and selects them perfectly. just does not show buttons to deauth or becon etc.. please help me

**Comment by jLynx** [comment]
Can you try clear the EPROM and then reupload the sketch?

**Comment by skeeeemer** [comment]
I had this issue too. I cleared the EPROM and then reuploaded it and now it works fine, cheers.

**Comment by Sumeetu47** [comment]
Please Tell me How to

**Comment by spacehuhn** [comment]
https://github.com/schinfo/EEPROM-Cleaner

**Comment by Sumeetu47** [comment]
thanks for help ... there was no need to clear eeprom,..... i just reuploaded using your website page instructions.

**Comment by Sumeetu47** [comment]
my deauth function is not working at all just says status 20pkts/s but nothing happens...
