### ISSUE TITLE
128x32 oled panel

### ISSUE THREAD

**Issue by aididhaiqal** [spacehuhn/esp8266_deauther#213]
Sorry for asking invalid question but

Do 128x32 oled panel [this to be exact](https://www.rapidonline.com/adafruit-2900-featherwing-oled-128x32-oled-add-on-for-all-feather-boards-73-5305) is fine with this project?

**Comment by spacehuhn** [comment]
It needs to be compatible with this library: 
https://github.com/squix78/esp8266-oled-ssd1306

It's only for 128x64 oleds, but maybe you can edit it.

**Comment by aididhaiqal** [comment]
Adafruit say it base on SSD1306 driver.So it does mean it will be compatible right?

**Comment by Fireflaker** [comment]
Is the bin file for i2c or spi? Which pin should i connect it to?
