### ISSUE TITLE
Wifi not working

### ISSUE THREAD

**Issue by tdbnz123** [spacehuhn/esp8266_deauther#216]
HI There

I got a esp8266  board yesterday I flashed it with the bin file etc and was working good as a wifi jammer

I was playing around and (I could of touched a setting in the webpage of the wifi jammer )

now the wifi is not transmitting off the esp8266 board meaning I can't access the device so I can do the wifi jamming etc

I tried to reflash the board with software no luck seeing wifi network ?

is there any way I can reset board / or reflash with default out of the box software??

when I plug in to usb it blinks upon usb power

anyone got suggestion on solution on how to fix

cheers

Thomas

 @spacehuhn

**Comment by jLynx** [comment]
Sounds like you made the SSID hidden. If you want to reset it just clear the EPROM

**Comment by tdbnz123** [comment]
how do i clear Eprom ?
sorry I so new to these / adrenio board

cheers

On 24/04/2017 11:41 AM, jLynx <notifications@github.com> wrote:

Sounds like you made the SSID hidden. If you want to reset it just clear the EPROM

**Comment by jLynx** [comment]
The link to the FAQ would be a good place to start...smh
