### ISSUE TITLE
WI-FI network is named "ESP_1C0F79" instead of "pwned" // Cannot connect to 192.168.4.1

### ISSUE THREAD

**Issue by phased22** [spacehuhn/esp8266_deauther#219]

**Comment by jLynx** [comment]
Did you even flash the bin or code to the device?

**Comment by phased22** [comment]
No, how would I do that?

**Comment by phased22** [comment]
Why'd you add "invalid" to the label?

**Comment by CamGiles** [comment]
I had the same issue. For some reason when you flash the nodemcu it won't work correctly. You have to install the software using Arduino.

**Comment by jLynx** [comment]
It's invalid since you are wasting our time. This isn't a bug or an issue with the software or code
