### ISSUE TITLE
WPS bruteforce

### ISSUE THREAD

**Issue by nisc3** [spacehuhn/esp8266_deauther#22]
Is it possible to bruteforce WPS pins with esp8266? Limitations?

**Comment by spacehuhn** [comment]
If someone finds a way to sniff eapol (handshake) frames with this device, it should be possible.

**Comment by nisc3** [comment]
Is it possible to create fake access point? Like fluxion?

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/issues/3

**Comment by nisc3** [comment]
https://w1.fi/wpa_supplicant/devel/eapol__supp__sm_8c.html
And
https://w1.fi/wpa_supplicant/devel/eapol__supp__sm_8h.html

Does this help?
