### ISSUE TITLE
Some Bugs I Guess 

### ISSUE THREAD

**Issue by PulkitSingh256** [spacehuhn/esp8266_deauther#223]
Issue No 1
settings page keeps reloading and seems abnormal. cant save settings there.
i am on android so as soon as i tap on any field to change values the page gets reloaded.
issue No 2
once entered settings page i was unable to go back to any other page.
for example if i tap on AP it just reloads the settings page
issue No 3
at first it was sending 20 pkt/s (for deauth)
but i observed on my network that none of my devices gets disconnected 
but after trying to reflash the .ino file now its sending 0 pkt/s
and its not because i made any mistake or my network is not 5 ghzz also not 802.11w
deauth was working for this project https://github.com/RandDruid/esp8266-deauth
using this project all my devices were disconnecting so its somewhere problem.
Issue No 4
now none of deauth projects are working none of yours and any other just the Deauth all ones are working
please reply

**Comment by spacehuhn** [comment]
This is no valid issue.
Reflash the chip, clear the EEPROM... look in the serial monitor...
