### ISSUE TITLE
every time i try  do this i get an error 

### ISSUE THREAD

**Issue by pandasniper100** [spacehuhn/esp8266_deauther#224]
---Sketch uses 547706 bytes (52%) of program storage space. Maximum is 1044464 bytes.
Global variables use 56276 bytes (68%) of dynamic memory, leaving 25644 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_open failed

Read [issues.md](https://github.com/spacehuhn/esp8266_deauther/blob/master/.github/issues.md) or your issue might be closed and labeled as invalid.

---

**Comment by pandasniper100** [comment]
why is it invalid ?

**Comment by pandasniper100** [comment]
what am i doing wroung ?

**Comment by pandasniper100** [comment]
well this was a waist of time

**Comment by pandasniper100** [comment]
ok so fixed it my self used a diffrent cable thanks for the help cough cough

**Comment by mcmasterp** [comment]
The reason you get no help is that your issue is not an issue with this project but your ability with arduino and uploading code. Google would be a faster way to fix those issues.

**Comment by pandasniper100** [comment]
hay i read the full install you could of at least said oh have you tryed this or that to troubleshoot instead i got ignored and no it was nothing to do with my abilty with ardunino it had to do with the cable i was using to falsh iti was using one that charges my tonbux power bank but that did not wotk so i used the one for my phone charger witch did so yhea

**Comment by jLynx** [comment]
Not sure if you realise but this is not a help and support section for your esp device. This is a section for posting bug reports for the code. Your "issue" had nothing to do with the code, so it had nothing to do with us
