### ISSUE TITLE
doesn't work on iDevices connected to Guest WiFi

### ISSUE THREAD

**Issue by Mikubo** [spacehuhn/esp8266_deauther#227]
tried to deauth my iDevice connected to my 2,4 GHz Guest WiFi (FirtzBox 7390). It doesn't seem to be affected. On the other hand it works with my Notebook connected to the same Guest WiFi.
Offside that Guest WiFi it works perfectly.

**Comment by jLynx** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ

**Comment by jLynx** [comment]
https://github.com/spacehuhn/esp8266_deauther/issues/218
