### ISSUE TITLE
PASSWORD TOO SHORT - CANT LOGIN ANYMORE

### ISSUE THREAD

**Issue by Pajane** [spacehuhn/esp8266_deauther#232]
Hello!

I accidentally typed in a 7 characters password instead of 8 and saved it. Now I can't login to the network to fix (OBVIOUSLY..).

Already tried to reset and flash... IDK what to do...

**Comment by jLynx** [comment]
Clear your EPROM

**Comment by Pajane** [comment]
how ? :S

**Comment by jLynx** [comment]
Hey mate, there is this really cool thing called a FAQ, not sure if you heard about it before? You can use it to look up simple question and answers instead of wasting our time. Bye.
