### ISSUE TITLE
So I set the Network to "invisible" ....

### ISSUE THREAD

**Issue by Voxzaco** [spacehuhn/esp8266_deauther#233]
Long story short: I wanted to see if my devices still "remember" the network - they dont.

- Can I somehow make it visible again ?
- Can I fully reset my NodeMcu (or the project on it), and how?

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ

**Comment by spacehuhn** [comment]
You have to connect to it to change the settings, or you clear the EEPROM.
