### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by stefanoromanello** [spacehuhn/esp8266_deauther#234]
Can you add the option for select all clients on the list??

**Comment by SaltyViper** [comment]
Or you know, just don't scan for clients and deauth the whole network.

**Comment by stefanoromanello** [comment]
I want to deauth everyone but I also want to exlude my device.

**Comment by stefanoromanello** [comment]
I resolved it by adding this feature by myself and it seems to work. I will let you know. Thanks anyway.

**Comment by snipercon55** [comment]
seems legit exept the fact that your deice is connected to the mcu and you wont be able to select your device because it isn't on that network... unless you would have an ipad or something else

**Comment by spacehuhn** [comment]
Not the purpose of this project.
