### ISSUE TITLE
No Access point appearing on iPhone 5S

### ISSUE THREAD

**Issue by crestxv** [spacehuhn/esp8266_deauther#235]
---
I've uploaded the project to my ESP8266 and arduino states that its "Done Uploading"
However when I plug the ESP8266 into a power supply and check on my phone wifi to connect to it no pwned access point/ssid appears there and I'm unsure why this is happening

---

**Comment by spacehuhn** [comment]
Don't use an iPhone then. It's not providing enough power for the chip to boot up.
