### ISSUE TITLE
Mcu board resets upon reconnecting to device after scanning for clients

### ISSUE THREAD

**Issue by snipercon55** [spacehuhn/esp8266_deauther#237]
Hello 
As you know most of my board works fine until I scan for clients. I select an AP go to the clients tab click search, and after I wait the 15 seconds and reconnect nothing happens. Please help me fix this or find out what I doing wrong.

**Comment by spacehuhn** [comment]
Reload the site?

**Comment by crestxv** [comment]
Try changing it to 10 seconds and make sure you aren't too far from the router this happened to me when I was on the other side of the house
