### ISSUE TITLE
Unable to join. Password got reset. 

### ISSUE THREAD

**Issue by juanitoperez** [spacehuhn/esp8266_deauther#238]
---
I'm fairly new to this but I had gotten everything running properly and it worked like a charm. But recently the security came off and when I went in to change the credentials it glitched and when i tried to login back to it. The default password "Deauther" got changed.  Is there a way to reset it or start it from scratch again. 
note...I only have the nodemcu 8266 board. No other hardware
---

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ
