### ISSUE TITLE
How to select multiple wifi networks

### ISSUE THREAD

**Issue by scmdaman786** [spacehuhn/esp8266_deauther#24]

**Comment by spacehuhn** [comment]
You can not select multiple networks in this version and I will not implement this, but feel free to fork it :)

**Comment by scmdaman786** [comment]
why what's the problem

**Comment by spacehuhn** [comment]
from the FAQ:

**Could` it deauth multiple APs in the range?**

It definitely could! But I will not implement this 'feature' for ethical and legal reasons.
