### ISSUE TITLE
how i turn off the built in led ?

### ISSUE THREAD

**Issue by Giuseppe2018** [spacehuhn/esp8266_deauther#266]

**Comment by spacehuhn** [comment]
Go to settings and change `Use LED`

![settings](https://user-images.githubusercontent.com/3826044/29066521-b69dc538-7c2f-11e7-8213-ee1ad9f02734.jpg)

**Comment by Giuseppe2018** [comment]
It stays on

**Comment by BlueArduino20** [comment]
Yep, I'm using the 1.6 version and the LED always stays on.

**Comment by spacehuhn** [comment]
Works perfect for me on every board.
Are you maybe talking about the Deauther boards? They have multiple LEDs for the charging circuit and a LED on GPIO 16: https://github.com/spacehuhn/esp8266_deauther/blob/master/esp8266_deauther/esp8266_deauther.ino#L20

**Comment by N0vaPixel** [comment]
WoW. Never seen a LED on the GPIO 16 of my board. I use a classic NodeMCU board.

For me this is a red LED and is turned on at the beginning of the firmware.

**Comment by Giuseppe2018** [comment]
Im talking about nodemcu esp8266

**Comment by N0vaPixel** [comment]
You are talking about this red LED ?
![fichier_000](https://user-images.githubusercontent.com/13287666/29069041-86374c0c-7c39-11e7-81fb-b1485bc24380.jpeg)

**Comment by spacehuhn** [comment]
Thanks for the picture @N0vaPixel !
Seems to actually be GPIO16. Not all of my boards have a LED there which is weird.

I will adjust the .bin file.

**Comment by Giuseppe2018** [comment]
@N0vaPixel Yes

**Comment by N0vaPixel** [comment]
To clarrify for all, there is currently two differents LEDs used by the firmware.

The blue is the default used when an attack is running. (Pin 2). You can configure it in the settings web page.

But the red is turned on at startup (GPIO16 confirmed)
This is not bad, it can show that the esp8266 is on and the firmware works correctly ¯\_(ツ)_/¯

**Comment by spacehuhn** [comment]
Yep.

I updated the standart 1mb .bin file:
https://github.com/spacehuhn/esp8266_deauther/releases/download/v.1.6/esp8266_deauther_1mb.bin

I guess most people don't want that LED to be on, just because previous versions didn't had that either.
If you still want it, flash the Arduino code.

I will add it to my to-do list for the next update to put an option for GPIO16 into the web interface as well!

**Comment by BlueArduino20** [comment]
Thanks! I was about to modify it.

**Comment by N0vaPixel** [comment]
@spacehuhn Yes i think it's a good idea. This new LED can be confusing for many.

For those who wants to build a custom firmware 🔨 
In esp8266_deauther.ino
Replace this line #define USE_LED16
With //#define USE_LED16
