### ISSUE TITLE
Encrypt Wifi Clones

### ISSUE THREAD

**Issue by Mr-iX** [spacehuhn/esp8266_deauther#269]
For me the feature to encrypt the cloned Network does not work. 
When I add SSIDs with the checkbox „Encrypted“ checked and start the Beacon Attack all Networks are still open/unencrpted. 

Does anybody else have this issue?

**Comment by spacehuhn** [comment]
Works fine for me with v1.6. Both when cloning or adding it manually to the List.

**Comment by Mr-iX** [comment]
Ok. I will try it tomorrow with a other NodeMCU.

**Comment by MemesGeneral** [comment]
Another one

<img src="http://www.thecoli.com/media/dj-khaled-another-one.6093/full">

**Comment by Mr-iX** [comment]
Now I have tested it with a other NodeMCU. When I search on my Arch Linux Machine, the networks are shown as encrypted, but on my iPhone they are all shown as unencrypted.

Can you reproduce this behavior?

![img_0669](https://user-images.githubusercontent.com/25360303/29136186-c62f7eac-7d3c-11e7-8190-957d5f274cc4.PNG)
![img_0670](https://user-images.githubusercontent.com/25360303/29136187-c64abf5a-7d3c-11e7-862a-992f4dc61b68.JPG)

**Comment by spacehuhn** [comment]
Seems to be an IOS issue. Maybe something with the beacon frames?

**Comment by Mr-iX** [comment]
I think so, because the other networks are show correctly. 
I don’t know how to debug that directly in iOS. Maybe it helps to sniff the packages with a WiFi chip in promiscuous mode.

**Comment by Behooz-Sirouszad** [comment]
i have the same problem with ipad and iphone users they find easily which one is their correct AP

**Comment by hmpowerbt** [comment]
I dont have the same problem. They are encrypted on IOS for me.

**Comment by spacehuhn** [comment]
Please try if it works with the new 2.0 version

**Comment by Mr-iX** [comment]
So now in the new version 2.0 it works!

Thanks for all the effort you put into this new version :smile:

**Comment by spacehuhn** [comment]
Thanks! Great to hear that it works now 😃
