### ISSUE TITLE
Can't change the ssid and the password

### ISSUE THREAD

**Issue by Hammad1029** [spacehuhn/esp8266_deauther#28]
I've edited the ssid and the password char value in the sketch multiple times and also uploaded them multiple times. But the the ssid wont change from "pwned" nor would the password from "deauther"

**Comment by spacehuhn** [comment]
Have you tried to reset your board?

**Comment by Splodgie** [comment]
Hi, I know nothing about programming, total zip.   This took me a good hour to work out.  
The serial monitor was showing the changed SSID & password put it would not change on the WiFi network.
The new Password must have a Min of 8 letters, ie: abcdergh  then the SIDD and Password will change.
Dave

**Comment by Hammad1029** [comment]
splodgie's fix works apparently for some reason, thanks!. sh i hope you look at this for a fix

**Comment by spacehuhn** [comment]
Great!
WPA(2) encryption needs at least an 8 character long password, this can't be be changed or "fixed".
