### ISSUE TITLE
[Feature request] Multiple APs

### ISSUE THREAD

**Issue by VoidTyphoon** [spacehuhn/esp8266_deauther#29]
Hi,

I have multiple AP's in my network all with the same SSID and setup so that my devices automatically switch AP's when moving around the house, I found yesterday while trying to stop my phone from connecting it defaulted to another AP in the house, Would it be possible to implement a feature to Block for ALL the Wireless Access Points with the same SSID?

I'm aware that you won't implement the Multiple SSID blocking and I totally agree with the reasoning, however, could this please be considered? also the support in this mode for scanning all the devices on all the hotspots with the same SSID, not just the one?

Also, I have seen your other Repo for SSID spamming, would it be possible to implement a custom SSID spam into this? say an input field and then it will in essence act the same as SSID spam just with your own custom SSID?

Thanks -Jack

**Comment by spacehuhn** [comment]
OK I understand your problem. I will work something out!

**Comment by VoidTyphoon** [comment]
Awesome. Thanks for the quick reply too 👍

**Comment by spacehuhn** [comment]
Are your APs running on different channels?

**Comment by spacehuhn** [comment]
Implemented here: https://github.com/spacehuhn/esp8266_deauther/tree/testing
please report back if it works with your APs :)
