### ISSUE TITLE
[Feature request] custom SSID beacon spam

### ISSUE THREAD

**Issue by nisc3** [spacehuhn/esp8266_deauther#31]
It would be great if you add custom SSID beacon spam to this repo.

**Comment by spacehuhn** [comment]
working on it.

**Comment by nisc3** [comment]
Superb!

**Comment by xdavidhu** [comment]
I would be happy to see this feature too!

----------------

My idea would be to add an attack menu for the custom beacon spam, with a textfield there, and the program would generate an array from the textfield, every name separated by the new line ("\n"). And after just go trough the array with a forever loop and send those beacons.

**Comment by dvdcd** [comment]
@spacehuhn Is this still planned? It sounds like a fantastic feature.

**Comment by tobozo** [comment]
[CTHULHU mode FTW](https://github.com/spacehuhn/esp8266_deauther/blob/master/web_interface/ssids.json) :octopus:
