### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by DR13** [spacehuhn/esp8266_deauther#33]
I get this error while compiling:

`Arduino: 1.6.12 (Windows 10), Board:"NodeMCU 1.0 (ESP-12E Module), 160 MHz, 115200, 4M (3M SPIFFS)"

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:17:20: error: redefinition of 'const char* ssid'

 const static char *ssid = "pwned";

                    ^

X:17: error: 'const char* ssid' previously defined here

 const static char *ssid = "NodeMCU";

                    ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:18:20: error: redefinition of 'const char* password'

 const static char *password = "deauther"; //must have at least 8 characters

                    ^

X:18: error: 'const char* password' previously defined here

 const static char *password = "123456789"; //must have at least 8 characters

                    ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:20:24: error: redefinition of 'ESP8266WebServer server'

 ESP8266WebServer server(80);

                        ^

X:20: error: 'ESP8266WebServer server' previously declared here

 ESP8266WebServer server(80);

                  ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:28:10: error: redefinition of 'NameList nameList'

 NameList nameList;

          ^

X:28: error: 'NameList nameList' previously declared here

 NameList nameList;

          ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:30:8: error: redefinition of 'APScan apScan'

 APScan apScan;

        ^

X:30: error: 'APScan apScan' previously declared here

 APScan apScan;

        ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:31:12: error: redefinition of 'ClientScan clientScan'

 ClientScan clientScan;

            ^

X:31: error: 'ClientScan clientScan' previously declared here

 ClientScan clientScan;

            ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:32:8: error: redefinition of 'Attack attack'

 Attack attack;

        ^

X:32: error: 'Attack attack' previously declared here

 Attack attack;

        ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void sniffer(uint8_t*, uint16_t)':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:34:6: error: redefinition of 'void sniffer(uint8_t*, uint16_t)'

 void sniffer(uint8_t *buf, uint16_t len){

      ^

X:34: error: 'void sniffer(uint8_t*, uint16_t)' previously defined here

 void sniffer(uint8_t *buf, uint16_t len){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void startWifi()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:38:6: error: redefinition of 'void startWifi()'

 void startWifi(){

      ^

X:38: error: 'void startWifi()' previously defined here

 void startWifi(){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void setup()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:52:6: error: redefinition of 'void setup()'

 void setup(){

      ^

X:52: error: 'void setup()' previously defined here

 void setup(){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void loop()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:95:6: error: redefinition of 'void loop()'

 void loop(){

      ^

X:95: error: 'void loop()' previously defined here

 void loop(){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void load404()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:106:6: error: redefinition of 'void load404()'

 void load404(){ server.send ( 200, "text/html", data_get404()); }

      ^

X:106: error: 'void load404()' previously defined here

 void load404(){ server.send ( 200, "text/html", data_get404()); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void loadIndex()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:107:6: error: redefinition of 'void loadIndex()'

 void loadIndex(){ server.send ( 200, "text/html", data_getIndexHTML() ); }

      ^

X:107: error: 'void loadIndex()' previously defined here

 void loadIndex(){ server.send ( 200, "text/html", data_getIndexHTML() ); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void loadClients()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:108:6: error: redefinition of 'void loadClients()'

 void loadClients(){ server.send ( 200, "text/html", data_getClientsHTML()); }

      ^

X:108: error: 'void loadClients()' previously defined here

 void loadClients(){ server.send ( 200, "text/html", data_getClientsHTML()); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void loadAttack()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:109:6: error: redefinition of 'void loadAttack()'

 void loadAttack(){ server.send ( 200, "text/html", data_getAttackHTML() ); }

      ^

X:109: error: 'void loadAttack()' previously defined here

 void loadAttack(){ server.send ( 200, "text/html", data_getAttackHTML() ); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void loadFunctionsJS()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:110:6: error: redefinition of 'void loadFunctionsJS()'

 void loadFunctionsJS(){ server.send( 200, "text/javascript", data_getFunctionsJS() ); }

      ^

X:110: error: 'void loadFunctionsJS()' previously defined here

 void loadFunctionsJS(){ server.send( 200, "text/javascript", data_getFunctionsJS() ); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void loadStyle()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:111:6: error: redefinition of 'void loadStyle()'

 void loadStyle(){ server.send ( 200, "text/css", data_getStyle() ); }

      ^

X:111: error: 'void loadStyle()' previously defined here

 void loadStyle(){ server.send ( 200, "text/css", data_getStyle() ); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void startAPScan()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:114:6: error: redefinition of 'void startAPScan()'

 void startAPScan(){ 

      ^

X:114: error: 'void startAPScan()' previously defined here

 void startAPScan(){ 

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void sendAPResults()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:121:6: error: redefinition of 'void sendAPResults()'

 void sendAPResults(){ server.send ( 200, "text/json", apScan.getResults()); }

      ^

X:121: error: 'void sendAPResults()' previously defined here

 void sendAPResults(){ server.send ( 200, "text/json", apScan.getResults()); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void selectAP()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:123:6: error: redefinition of 'void selectAP()'

 void selectAP(){

      ^

X:123: error: 'void selectAP()' previously defined here

 void selectAP(){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void startClientScan()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:132:6: error: redefinition of 'void startClientScan()'

 void startClientScan(){

      ^

X:132: error: 'void startClientScan()' previously defined here

 void startClientScan(){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void sendClientResults()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:140:6: error: redefinition of 'void sendClientResults()'

 void sendClientResults(){ server.send( 200, "text/json", clientScan.getResults()); }

      ^

X:140: error: 'void sendClientResults()' previously defined here

 void sendClientResults(){ server.send( 200, "text/json", clientScan.getResults()); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void selectClient()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:142:6: error: redefinition of 'void selectClient()'

 void selectClient(){

      ^

X:142: error: 'void selectClient()' previously defined here

 void selectClient(){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void setClientName()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:150:6: error: redefinition of 'void setClientName()'

 void setClientName(){

      ^

X:150: error: 'void setClientName()' previously defined here

 void setClientName(){

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void sendAttackInfo()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:158:6: error: redefinition of 'void sendAttackInfo()'

 void sendAttackInfo(){ server.send ( 200, "text/json", attack.getResults()); }

      ^

X:158: error: 'void sendAttackInfo()' previously defined here

 void sendAttackInfo(){ server.send ( 200, "text/json", attack.getResults()); }

      ^

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino: In function 'void startAttack()':

C:\Users\Dioni\Desktop\Projects\Deauth\X\esp8266_deauther.ino:160:6: error: redefinition of 'void startAttack()'

 void startAttack(){

      ^

X:160: error: 'void startAttack()' previously defined here

 void startAttack(){

      ^

exit status 1
'const char* ssid' previously defined here

`

How do I fix this?

**Comment by VoidTyphoon** [comment]
uninstall all of your ESP library's and follow the instructions again EXACTLY word for word then get back t me ;)

**Comment by DR13** [comment]
I will

**Comment by DR13** [comment]
Allright, will do.

**Comment by DR13** [comment]
It took a few tries but it works just fine now. With projects like these I tend to go way to fast and I end up reading only half of the text.

Thanks!
