### ISSUE TITLE
'wifi_send_pkt_freedom' was not declared in this scope

### ISSUE THREAD

**Issue by TheDukeOfDeath** [spacehuhn/esp8266_deauther#35]
I got this error:

 "Arduino: 1.8.0 (Mac OS X), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck"

sketch/Attack.cpp: In member function 'bool Attack::send(uint8_t*, int)':
Attack.cpp:41: error: 'wifi_send_pkt_freedom' was not declared in this scope
   if(wifi_send_pkt_freedom(buf, len, 0) == -1){
                                       ^
sketch/Attack.cpp: In member function 'void Attack::run()':
Attack.cpp:179: error: 'wifi_send_pkt_freedom' was not declared in this scope
       if(wifi_send_pkt_freedom(deauthPacket, 26, 0) == -1){/*
                                                   ^
Attack.cpp:190: error: 'wifi_send_pkt_freedom' was not declared in this scope
       if(wifi_send_pkt_freedom(deauthPacket, 26, 0) == -1){/*
                                                   ^
Attack.cpp:221: error: 'wifi_send_pkt_freedom' was not declared in this scope
         if(wifi_send_pkt_freedom(packet, packetSize, 0) == -1){/*
                                                       ^
exit status 1
'wifi_send_pkt_freedom' was not declared in this scope

![screen shot 2017-02-20 at 7 16 39 pm](https://cloud.githubusercontent.com/assets/24645897/23149505/2d855710-f7a1-11e6-983a-5d9c680cc968.png)

**Comment by spacehuhn** [comment]
Follow the installation steps again and correctly.
