### ISSUE TITLE
Deauth failure

### ISSUE THREAD

**Issue by harshil2105** [spacehuhn/esp8266_deauther#356]
I can't deauth a essid...it gives me a lot of errors like attackinfo.json not found and other related errors and then i have to reload the page or restart the esp8266...I'm using a nodemcu and i haven't faced such issues in other releases of esp8266 deauth firmware

**Comment by tobozo** [comment]
power issues can feature the same symptoms

**Comment by harshil2105** [comment]
Elaborate power issue

**Comment by tobozo** [comment]
one of those but list in non exhaustive : 
- battery is nearly empty
- the USB cable does not provide enough amps (powering from a mobile phone?)
- something else (i.e. custom hardware such as rgb OLED) is drawing power

**Comment by harshil2105** [comment]
Thanks for the info...you may close this issue

**Comment by spacehuhn** [comment]
Also keep in mind that when you start an attack on a network that the ESP maybe has to change the WiFi channel, thus changing the channel of its hostet `pwned` network too.
And changing the channel can result in connectivity issues, so you maybe have to reconnect.

**Comment by harshil2105** [comment]
Yes i have faced this issue a lot....but haven't faced such issues in your
earlier releases
