### ISSUE TITLE
UI: error loading attackStart.json?num=0 while in deauth loop

### ISSUE THREAD

**Issue by ThomSeagal** [spacehuhn/esp8266_deauther#358]
When I do a Deauth attack I get the error error loading attackStart.json?num=0
How to fix it?

**Comment by N0vaPixel** [comment]
This error can mean that the esp8266 is not responding after trying to start an attack.
So we need more informations. Can you provide the output of the serial communication with your esp ?

**Comment by ThomSeagal** [comment]
Where can I find the the output of the serial communication?

**Comment by andrew77768** [comment]
I want to add, I've got the same issue. It starts by saying the JSON attack file couldn't be loaded, and then shortly after I get the same error as OP. Like OP, I don't know where the output is, but if the thread is updated with instructions then I'll will send them over.

**Comment by N0vaPixel** [comment]
Arduino IDE : Menu Tools --> Serial monitor.
Use it when connected to the esp.
You'll get additional debugging informations about what's happening during the firmware execution.

**Comment by andrew77768** [comment]
Okay. Thanks for the promt reply. So, I selected the target network, went to attacks saw the correct network was in the selected APs so continued to start the Deauth attack, first it said there was an error loading the file, it continued and the status changed to starting. Next it created the attackStart.json?num=0 error. The monitor outputted this during that time:  https://pastebin.com/ek8PVYRp and the button to stop the attack wouldn't work as it was stuck on starting

**Comment by spacehuhn** [comment]
That looks like the wrong baudrate. On the serial monitor in the bottom right corner, set it to 115200.

**Comment by ThomSeagal** [comment]
with 115200 the output stays empty. But now I get this error in the arduino coding screen, java.io.IOException: jssc.SerialPortException: Port name - COM4; Method name - setEventsMask(); Exception type - Can't set mask.

http://puu.sh/x8nG4/0c4c6ea876.png

**Comment by ThomSeagal** [comment]
I think I got it figured out, according to the serial monitor everything is working, but I still get the error. I ignored the error and pressed stop, it stopped, then I pressed start again and it worked without any errors. I will add a pastebin link down below.  It looks like it is working fine. Only problem is the wrong error I guess.

https://pastebin.com/JUDqFrAx

**Comment by andrew77768** [comment]
Okay. https://pastebin.com/PpL1XPbD That's the log. It continued the spam after i pasted it but it was the same line "running Deauth attack... done". It was while I got that spam that I got the errors.

**Comment by ihatecreatingaccounts** [comment]
nice theres no support here. this product is not working fuckers

**Comment by ChiLegend** [comment]
I am also have this problem

**Comment by ChiLegend** [comment]
But I actually can't deauther

**Comment by ihatecreatingaccounts** [comment]
Its Not working. Its a scam

Am 01.10.2017 5:08 nachm. schrieb "ChiLegend" <notifications@github.com>:

**Comment by ChiLegend** [comment]
What do you mean scam?

**Comment by ChiLegend** [comment]
I just switched to a lower version and It works lol

**Comment by tobozo** [comment]
fixed in the next version, closing this
