### ISSUE TITLE
Deauth from PC

### ISSUE THREAD

**Issue by talal2** [spacehuhn/esp8266_deauther#360]
Hi ALL,

I Wanna know if this tool: http://www.ebay.com/itm/NodeMcu-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266-/171907569391?epid=1646111585&hash=item28067d56ef:g:aYwAAOSwgkRVSiBa
Can deauth from PC, cz i don't want to use it in SMARTPHONE .
I Prefer use it PC ?
Is that possible ?

                                                           Thanks in advance ;) :)

**Comment by NurdTurd** [comment]
Just connect to the esp8266 through WiFi but with your computer and go to the IP address in your browser just as if you were on your phone. No need to change anything. :)
