### ISSUE TITLE
Oled usability screenshots preview for new users

### ISSUE THREAD

**Issue by mrhut10** [spacehuhn/esp8266_deauther#363]
I've been looking all throughout the interwebs for a screenshot / menu layout of theoled screen.

I've ordered your version so no doubt will see it in person shortly but a layout of the menu would be really awesome.

**Comment by tobozo** [comment]
It might be a bit off topic but you can "capture" an image from the OLED buffer (128*64 = 8 Kilobits = 1 Kilobyte) by accessing `display.buffer` at runtime.

**Comment by spacehuhn** [comment]
And you can see it here:
https://www.tindie.com/products/lspoplove/wifi-deauther-oled-v15pre-flashed/
and here:
https://www.tindie.com/products/lspoplove/wifi-deauther-oled-v2-include-case-and-antenna/
and here:
https://github.com/spacehuhn/esp8266_deauther#adding-an-oled-display

**Comment by dwillmore** [comment]
@mrhut10 are you looking for a description w/pictures of what the contents of the OLED screen show when using it?

**Comment by tobozo** [comment]
closing this as solved
