### ISSUE TITLE
Not working in mobile 

### ISSUE THREAD

**Issue by DushyantPUNK** [spacehuhn/esp8266_deauther#40]
I tried many browsers in mobile such as opera, Uc and inbuilt browser but when I press the scan button it says scanning and nothing happens.
All is working fine in Laptop and PC. 
Please **help.**

**Comment by spacehuhn** [comment]
see:
https://github.com/spacehuhn/esp8266_deauther/issues/5

**Comment by Splodgie** [comment]
FireFox or Chrome
