### ISSUE TITLE
esp8266_deauther .html not able to modify

### ISSUE THREAD

**Issue by sounakdeb** [spacehuhn/esp8266_deauther#41]
How to modify the esp8266_deauther .html files i try but not working.
i'm edit the index.html then upload its not showing in the browser.

**Comment by spacehuhn** [comment]
Use the `minifier.html` in html files to minify and then 'byte-ify' your changed code. In data.h you can then replace the byte array and upload.

**Comment by sounakdeb** [comment]
thank you it's working now

**Comment by sounakdeb** [comment]
deauther only block single wifi network not available multiple wifi network selection options. can you please add multiple wifi selected option.

**Comment by castalia3** [comment]
@spacehuhn @sounakdeb 

**I apologize in advance for any questions that may seem silly**


I am trying to perform the procedure for editing html files,

- i installed anglerfish

- I run the script from its location after modifying the files in web_interface

- i've upload the files via sketch data upload from the arduino IDE

- I start the esp8266 but the changes don't appear, where am I wrong?

*before uploading the files via IDE I flashed the bin file (v1) via ESP8266 FLASHER

*i also tried reloading the new .bin file (generated by the python script) with updated webfiles.h page, i get `error: (before loading the new bin I reset the board)

*the changes I made concern only the index page, I added a letter to h1, as a test


```

In file included from E: \ esp8266_deauther-2 \ esp8266_deauther \ esp8266_deauther.ino: 52: 0:

sketch \ wifi.h: In lambda function:

wifi.h: 343: 25: error: 'indexhtml' was not declared in this scope

             sendProgmem (indexhtml, sizeof (indexhtml), W_HTML);

                         ^

More than one library found for "EEPROM.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ EEPROM
More than one library found for "ESP8266WiFi.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ESP8266WiFi
More than one library found for "SSD1306Wire.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ esp8266-oled-ssd1306-4.0.0
More than one library found for "ESP8266WebServer.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ESP8266WebServer
More than one library found for "ESP8266mDNS.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ESP8266mDNS
More than one library found for "Hash.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ Hash
More than one library found for "ArduinoJson.h"
Used: C: \ Users \ myname \ Documents \ Arduino \ libraries \ ArduinoJson
Not used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ArduinoJson
More than one library found for "Wire.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ Wire
More than one library found for "SimpleButton.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ SimpleButton
More than one library found for "DNSServer.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ DNSServer
exit status 1
'indexhtml' was not declared in this scope
```

**Comment by Bommlon** [comment]
Did you make sure 'indexhtml' was written correctly? Because this error usually means that there's no variable with that name in the code.

**Comment by castalia3** [comment]
@Bommlon 
> Did you make sure 'indexhtml' was written correctly? Because this error usually means that there's no variable with that name in the code.

yes I checked the code, I also opened the updated file in data / web and I checked that the contents of index.html.gz were written correctly.

What should be the step by step procedure to edit the html? Were you successful?

thanks for the support

**Comment by spacehuhn** [comment]
The procedure to is very easy as long as you only modify existing files (without adding, renaming or removing files):
1. Make your changes to the files in the folder [`web_interface`](https://github.com/SpacehuhnTech/esp8266_deauther/tree/v2/web_interface)
2. Run [`utils/webconverter.py`](https://github.com/SpacehuhnTech/esp8266_deauther/tree/v2/utils/web_converter) 
3. Upload the code using Arduino

If you add or remove files, you'll need to edit [`wifi.h`](https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/esp8266_deauther/wifi.h#L233) as well.

If you make changes and don't see the result, try clearing the browser cache.

**Comment by castalia3** [comment]
@spacehuhn 
> The procedure to is very easy as long as you only modify existing files (without adding, renaming or removing files):
> 
> 1. Make your changes to the files in the folder [`web_interface`](https://github.com/SpacehuhnTech/esp8266_deauther/tree/v2/web_interface)
> 2. Run [`utils/webconverter.py`](https://github.com/SpacehuhnTech/esp8266_deauther/tree/v2/utils/web_converter)
> 3. Upload the code using Arduino
> 
> If you add or remove files, you'll need to edit [`wifi.h`](https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/esp8266_deauther/wifi.h#L233) as well.
> 
> If you make changes and don't see the result, try clearing the browser cache.

Thanks for replying, The procedure you indicated is the one I followed. When I try to upload the .ino file via IDE I get this error:

```
More` than one library found for "EEPROM.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ EEPROM
More than one library found for "ESP8266WiFi.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ESP8266WiFi
More than one library found for "SSD1306Wire.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ esp8266-oled-ssd1306-4.0.0
More than one library found for "ESP8266WebServer.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ESP8266WebServer
More than one library found for "ESP8266mDNS.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ESP8266mDNS
More than one library found for "Hash.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ Hash
More than one library found for "ArduinoJson.h"
Used: C: \ Users \ myname \ Documents \ Arduino \ libraries \ ArduinoJson
Not used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ ArduinoJson
More than one library found for "Wire.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ Wire
More than one library found for "SimpleButton.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ SimpleButton
More than one library found for "DNSServer.h"
Used: C: \ Users \ myname \ AppData \ Local \ Arduino15 \ packages \ deauther \ hardware \ esp8266 \ 2.0.0 \ libraries \ DNSServer
exit status 1
'indexhtml' was not declared in this scope
```


Have no idea what the problem could be?

I want to clarify that to run the python script, I load the files on a usb key that I insert in raspberry with the kali linux operating system, once the script has been executed I reload the files on a usb key and load them from windows10 via arduino IDE, it could depend on it?

**
i also tried doing everything from windows 10 without going through linux, i get the exact same error message.

Thank you,

**Comment by castalia3** [comment]
![image](https://user-images.githubusercontent.com/73337350/97188854-45ea7200-17a4-11eb-9454-a589cc3feb97.png)

**Comment by castalia3** [comment]
Does anyone have any idea what the problem might be?

**Comment by spacehuhn** [comment]
This should be fixed, but for reference:
The compiler doesn't like the `-`. Instead of `pt-brlang` you could call it `ptbrlang` or `pt_brlang`.
