### ISSUE TITLE
Hast du schon einmal über eine Projektseite nachgedacht + Blog

### ISSUE THREAD

**Issue by H1ghTech** [spacehuhn/esp8266_deauther#44]
Hey :) 
Ich finde deine Projekte echt super und wollte dir deswegen gerne eine Projektseite machen z.B auf meinem Server oder auch auf github-pages. 

Ach so: ich habe Repos, die sind nur alle private lol ( nur um das klarzustellen weil ich das oft gefragt werde)

**Comment by spacehuhn** [comment]
Coole Idee.
Wenn du darauf lust hast gerne!
Ich würde dann allerdings bevorzugen das ganze auf github pages zu machen und auch auf englisch und so das jeder mithelfen kann. Also so als richtiges open source Projekt.

Wenn du twitter hast kannst du mich da auch gerne bei mir melden (wie hier @spacehuhn).

**Comment by H1ghTech** [comment]
OK welche Domain möchtest du?
![screenshot_20170228-103908](https://cloud.githubusercontent.com/assets/22871157/23399917/5cc18d30-fda2-11e6-8e30-0c7f309df7c8.png)

**Comment by spacehuhn** [comment]
was genau hast du denn jetzt vor? Einen Blog habe ich ja schon.
Wenn du eine allgemeine Projektseite machen möchtest gerne, aber dann musst du mir auch sagen was du dir genau darunter vorstellst.

**Comment by H1ghTech** [comment]
Ja ne Projektseite wo halt all deine Projekte erklärt werden vlt auch mit wiki

**Comment by spacehuhn** [comment]
Dafür hab ich ja schon Spacehuhn.de
Ich wäre wenn für eine Projektseite über den deauther. Wiki wäre da wahrscheinlich etwas übertrieben aber mit genaueren Anleitungen, Informationen, Bildern etc. wäre das wahrscheinlich schon ganz nützlich.

**Comment by H1ghTech** [comment]
OK kann Ich machen

**Comment by H1ghTech** [comment]
Ich lass die Seite dann erstmal bei mir laufen und du kannst dir die dann einfach forken

**Comment by tpmodding** [comment]
das wird nix...irgendwann hast du keine lust mehr zu supporten...lieber das github wiki nutzen

**Comment by spacehuhn** [comment]
Ich überlass das euch. Ich habe nur keine Zeit mich auch noch darum zu kümmern.

**Comment by H1ghTech** [comment]
@tpmodding Ich mach das mit nem statischen site gen
der läuft in gh-pages (jekyll)
wenn ich net mehr supporte kann @spacehuhn das auch ganz einfach selber machen

**Comment by H1ghTech** [comment]
https://github.com/H1ghTech/esp kannste ja mal anschauen =)

**Comment by spacehuhn** [comment]
Für die Übersicht schließe ich das jetzt mal, ist ja kein Issue.

**Comment by H1ghTech** [comment]
@spacehuhn OK ich hab die Seite ja fertig wie ist das denn jetzt willste die haben?

**Comment by spacehuhn** [comment]
Hatte noch keine Zeit sie mir anzuschauen.

**Comment by H1ghTech** [comment]
Ah ok du kannst ja Mal ne neue repo machen mit dem Namen spacehuhn.github.io

**Comment by H1ghTech** [comment]
Uhm?!?

**Comment by spacehuhn** [comment]
Also habs mir angeschaut. Du hast ja jetzt eine Projektübersicht von meinem Account gemacht. Das ist eigentlich etwas was ich auf meiner Website noch selber machen werde und ich sehe jetzt keinen Grund 2 Seiten dafür online zu stellen.

Hatte das jetzt eher auf dieses Projekt bezogen verstanden. Was aber auch unsinnig ist wenn ich so drüber nachdenke. Wie @tpmodding sagte wäre das github Wiki da sinnvoller. Github selber ist ja auch schon eine Projektseite also nicht böse gemeint aber ich brauche es ganz einfach nicht.

**Comment by H1ghTech** [comment]
OK gut

Stefan Kremser <notifications@github.com> schrieb am Sa., 4. März 2017,
12:54:
