### ISSUE TITLE
esp8266_deauther support board

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#45]
@spacehuhn  esp8266_deauther code support  ESP8266 ESP-01 module

**Comment by spacehuhn** [comment]
You can flash the code on every ESP8266 with 1mb or more.
When you wanna use 512kb module comment out the vendor list in data.h to save memory.

**Comment by joneroy** [comment]
@spacehuhn  You mean mac vendor list in data.h ?

**Comment by spacehuhn** [comment]
yap. if you comment out all bytes in the array expect the first line it should work.

**Comment by Splodgie** [comment]
@joneroy   What ESP are you using ?.  are you commenting out in data list ?.

Dave
