### ISSUE TITLE
show hidden ssid's

### ISSUE THREAD

**Issue by H1ghTech** [spacehuhn/esp8266_deauther#46]
Almost every network in my house are not broadcasting the SSID (for obvious reasons). So I asked myself if it is possible to show them :)

**Comment by spacehuhn** [comment]
I think it's possible but I haven't tried it out yet. It would require to get into the promiscuous mode just like when it's scanning for clients and it would only see the MAC adress.

**Comment by joneroy** [comment]
@H1ghTech ya it's possible to show hidden ssid's using esp8266 but i don't no software implementation easy or not.

**Comment by DevShekhawat7** [comment]
ya please add this feature..there are so many hidden ssid around me which this guy is no pulling up. please add this feature

**Comment by spacehuhn** [comment]
merged into testing branch. You can test it now.

**Comment by DevShekhawat7** [comment]
@spacehuhn thank you soo much

**Comment by H1ghTech** [comment]
@spacehuhn thank you:)
