### ISSUE TITLE
Can i modify your esp8266_deauther

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#47]
can i modify your ""esp8266_deauther"" name and codes i think a good name for ""esp8266_deauther"" and web interface not look good so i need to modify this web ui so can you give me permission for modifying.

**Comment by poslogic** [comment]
Did you read the license?

https://github.com/spacehuhn/esp8266_deauther/blob/master/LICENSE

**Comment by joneroy** [comment]
Thank You @poslogic
