### ISSUE TITLE
Deauth doesn't work

### ISSUE THREAD

**Issue by JonathanJhon55** [spacehuhn/esp8266_deauther#49]
So I purchased this board, only to use this script.

Atlough the death shows 20pkt/s nothing happens.

I am not on 5Ghz. And it did work on my Raspberry Pi with the same network.

Any advice? I need to get this working. Thanks

**Comment by poslogic** [comment]
Try using the latest testing branch this is working very well for me.
https://github.com/spacehuhn/esp8266_deauther/tree/testing

**Comment by JonathanJhon55** [comment]
@poslogic I just tested it. Also with 200 packets, it doesn't do anything. My WiFi doesn't even lagg..

**Comment by poslogic** [comment]
Do you have access to any other AP's to test on? Friends or mobile phone hotspot?

I have successfully tested this on my own WiFi, my mums and my Android phone hotspot.

What board are you using?

**Comment by JonathanJhon55** [comment]
https://www.amazon.co.uk/NodeMCU-Internet-Development-ESP8266-ESP-12E/dp/B01GCK3J40/ref=sr_1_1?ie=UTF8&qid=1488393656&sr=8-1&keywords=tinxi+esp8266

I'm using this board. Same seller, just from amazon.fr.

I just tested it too. It doesn't do anything also

**Comment by poslogic** [comment]
I have the same board.
Struggling to think of reasons why yours does not work.

Double check that you followed all steps in Readme.
Make sure board is correctly selected in Arduino/Tools

Board - NodeMCU 1.0 (Esp 12-E)
CPU frequency 80 MHZ
Flash Size 4m
Upload speed 115200
Programmer ArduinoISP

**Comment by joneroy** [comment]
You are using the right SDK version.

**Comment by poslogic** [comment]
Are you seeing any errors in the Serial Monitor?

Are you seeing (running deauth attack done) when deauthing?

**Comment by JonathanJhon55** [comment]
@poslogic

**Comment by poslogic** [comment]
@JonathanJhon55 Serial Monitor output looks the same as mine, only other thing I can think of is that your WiFi router uses 802.11w??? Maybe switch encryption to none and try?

**Comment by JonathanJhon55** [comment]
@poslogic See this screenshots. It doesn't use 802.11w 😞 

![image](https://cloud.githubusercontent.com/assets/24832935/23477826/8d4c33ba-febf-11e6-8a2c-4a1f65bad48e.png)

**Comment by joneroy** [comment]
@poslogic  My Serial Monitor not working only show 3 line :

starting...
SSID: pwned
Password: deauther

**Comment by joneroy** [comment]
@JonathanJhon55  You using wifi ddos protection feature on your wifi.

**Comment by poslogic** [comment]
@joneroy What board are you using? 

Have you switched to the correct SDK 2.0.0

Have you added the lines of code to the user_interfaces.h file (and clicked on save aftwards)

**Comment by Mcewen123** [comment]
Hi
Try using Board - NodeMCU 0.9 (Esp 12-E) it works for me, I have the NodeMCU 1.0 (Esp 12-E) but.................everything works but the deauthing with Board -NodeMCU 1.0 (Esp 12-E) , when I choose the Board -NodeMCU 0.9 (Esp 12-E) everything works, give it a try

**Comment by joneroy** [comment]
@poslogic  i'm using correct SDK 2.0.0 and added the lines of code to the user_interfaces.h file but My Serial Monitor not working only show 3 line :

starting...
SSID: pwned
Password: deauther

i'm using this 115200 baud

![pin](https://cloud.githubusercontent.com/assets/26072408/23480796/3eaad97a-feef-11e6-9ad4-3360be86595a.png)
![pin2](https://cloud.githubusercontent.com/assets/26072408/23480852/7079b3f4-feef-11e6-8a20-cf23dc5dc9af.png)

esp8266_deauther working but i dont show Serial Monitor.

**Comment by poslogic** [comment]
@joneroy We are all using the testing branch with debugging on.

Are you using the Master or Testing branch?

**Comment by joneroy** [comment]
@poslogic  Master branch

**Comment by poslogic** [comment]
@joneroy Try the testing branch if you like it has new features and I think it will be merged into the master soon.

Remember to keep a copy of the version that you have working now, just in case ;-)

https://github.com/spacehuhn/esp8266_deauther/tree/testing

**Comment by joneroy** [comment]
@poslogic  I'm trying the testing branch and leave feedback for Stefan.

**Comment by DevShekhawat7** [comment]
Correct me if i am wrong, If someone is connected with LAN cable and if we deauth the network, will it work? because in my case it's not happening

**Comment by poslogic** [comment]
No this is for WiFi 802:11b,g,n - 2.4 GHz only

Check the other projects by Stefan for LAN

**Comment by N0vaPixel** [comment]
The WiFi deauth attack doesn't affect LAN clients.
This attack spoof clients by sending IEEE 802.11 packets

**Comment by spacehuhn** [comment]
Can we close this?

**Comment by joneroy** [comment]
@spacehuhn close this issue it's solved

**Comment by emon11** [comment]
> @spacehuhn close this issue it's solved

how please

**Comment by spacehuhn** [comment]
Hi, I know this issue is old and has been closed, but since it ranks well on Google, I would like to point people to a new blog post that discusses this topic in further detail:
https://blog.spacehuhn.com/deauth-attack-not-working/
