### ISSUE TITLE
Error: Web Page Loading Problem

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#51]
Error: web page loading problem only on 2 pages

Android/Chrome

1.clients page // when press start button "Error: web page loading problem"
2.attack page // when press start button deauth "Error: web page loading problem"

**Comment by nisc3** [comment]
Yes, you get disconnected and reconnect to it and both deauthentication and client scan works fine. It is because of low memory (?)

**Comment by joneroy** [comment]
@nisc3  I think It's not low memory prob.

**Comment by nisc3** [comment]
Yep, I agree. And as you said client scan doesn't work properly.

**Comment by joneroy** [comment]
two prob i found :

1.clients page // when press start button "Error: web page loading problem"
2.attack page // when press start button deauth "Error: web page loading problem"

**Comment by joneroy** [comment]
@nisc3  i think it's code prob master branch it's workin fine

**Comment by joneroy** [comment]
![roll](https://cloud.githubusercontent.com/assets/26072408/23513515/5154e750-ff8a-11e6-8d7f-9eaf93bcce8c.png)

**Comment by spacehuhn** [comment]
like I said many times before: look at the logs and use the dev tools of your browser. Otherwise we can't help you. 

It's like you ask why your car isn't starting and sending a picture of it. I have no idea...

**Comment by joneroy** [comment]
@spacehuhn Web Page Loading Problem is solved testing branch
