### ISSUE TITLE
[Feature request] Deauth timer

### ISSUE THREAD

**Issue by nisc3** [spacehuhn/esp8266_deauther#53]
A feature to conduct timed deauthentication. For example, deauth for 5min and stop 2min and again start deauth.
Also an option to change these values from web interface.

**Comment by joneroy** [comment]
Deauth timer this good idea

**Comment by H1ghTech** [comment]
I agree

**Comment by spacehuhn** [comment]
But why?

**Comment by nisc3** [comment]
It is nice to have this feature, please please implement it...

**Comment by spacehuhn** [comment]
I don't see any reason for that and the testing branch already has an attack timeout.

**Comment by nisc3** [comment]
But it would be better to have a feature to enable deauth after a user defined time....

**Comment by joneroy** [comment]
@spacehuhn already has an attack timeout you right.

**Comment by spacehuhn** [comment]
Sorry but no. This 'feautre' doens't make sense to me.
