### ISSUE TITLE
OTA Flashing

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#55]
frimware update is feature needed without arduino upload latest deauther codes to esp8266 memory and then reboot done. only first time flash required then code upload using any web browser pc and mobile.

**Comment by N0vaPixel** [comment]
The esp8266 must be conected to an AP in order to use OTA upgrade
And your can't use managed - master and client mode at the same time.
Look, the AP created by esp shutdown when you start the client sniffing

**Comment by spacehuhn** [comment]
I find this also pretty useless. Is it so hard to plug the board into your pc? you need to anyways to debug with the serial monitor. So no I'll close that.

**Comment by joneroy** [comment]
@spacehuhn Ok
