### ISSUE TITLE
Specifies Connected AP >> Clients

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#56]
@spacehuhn 
![untitled](https://cloud.githubusercontent.com/assets/26072408/23525164/84dbc7be-ffb3-11e6-8272-0514ffc45672.png)

**Comment by joneroy** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26072408/23525251/cbfce0ec-ffb3-11e6-9c90-a083bffcffb1.png)

**Comment by joneroy** [comment]
please solve this prob

**Comment by poslogic** [comment]
You asked before if you could use and change code to your needs.

You can, please do and share your results.

**Comment by joneroy** [comment]
@poslogic can you please add this option

**Comment by spacehuhn** [comment]
1. I don't get what you want
2. like poslogic said: implement it yourself
or pay me per hour...

**Comment by joneroy** [comment]
after select 2 ap the client result is mix. please specify ap clients mean A&B is ap and i select both but client result time show A&B ap mix client result like.

**# AP**

A is wifi>1client.5client.3client

B is wifi>6client.7client.10client.11client

**# client** result now show :

1.client- jone
5.client- alex
3.client- shreen
6.client- kid
7.client- sean
10.client- chris
11.client- stife

after you add new this feature

**# AP**

A is wifi>1client.5client.3client

B is wifi>6client.7client.10client.11client

**# client** result after :

A:
1.client- jone
5.client- alex
3.client- shreen
B:
6.client- kid
7.client- sean
10.client- chris
11.client- stife

@spacehuhn feature like this can you add this feature.

**Comment by tpmodding** [comment]
der will das du bei den clients anzeigst welcher client zu welchem ap gehört...welcome to github mit script kiddies... die wollen jetzt alles sofort haben :) du stumpfst schon ab mit der zeit, kein stress :D

**Comment by N0vaPixel** [comment]
Added in the testing branch
