### ISSUE TITLE
Code shows error exit status 1 no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

### ISSUE THREAD

**Issue by pks9862728888** [spacehuhn/esp8266_deauther#569]
Please help me...your code shows compilation error:
![capture](https://user-images.githubusercontent.com/30013603/29489917-1ced12d0-84fa-11e7-9959-953703b32926.JPG)
exit status 1
no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

**Comment by spacehuhn** [comment]
Follor step 12 to 14: https://github.com/spacehuhn/esp8266_deauther#compiling-the-source-with-arduino

Also look for similar issues next time before opening a new one!
https://github.com/spacehuhn/esp8266_deauther/search?q=ESP8266WiFiClass%3A%3AscanNetworks%28bool%2C+bool%26%29&type=Issues&utf8=%E2%9C%93

**Comment by AssadAnabosi** [comment]
Wifi.scanNetworks() it'll work at least with me
