### ISSUE TITLE
[Feature request] Login Page

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#57]
@spacehuhn 
add a login page 192.168.4.1 
>user name
>password

login

then redirected to main ap page.

**Comment by H1ghTech** [comment]
Wow you have really good ideas!!!

**Comment by joneroy** [comment]
@H1ghTech  I like open source projects. thank you for like my ideas!!

**Comment by H1ghTech** [comment]
Np xD

**Comment by poslogic** [comment]
Logging into the board via WiFi connection requires a password.

Default:
pwned
Deauther

Which can be changed.
What would login page add?

**Comment by joneroy** [comment]
wifi password hacking now day super easy. 2nd time authentication needs like a router.

**Comment by poslogic** [comment]
Okay another level of authentication is always good.

But using good passphrase and limited time that (I personally use) ESP board is on for makes attacks not a problem ( in my use for this project)

**Comment by spacehuhn** [comment]
I agree with poslogic. This is obsolete, it has already an authenticstion build in which is (mostly) annoying enough.
