### ISSUE TITLE
How can i flash on an apple computer

### ISSUE THREAD

**Issue by sym300** [spacehuhn/esp8266_deauther#572]
i do not own a pc unfortunately

**Comment by tobozo** [comment]
you don't need to own a PC, a browser a some googling is enough to find out how to flash an ESP from a mac

Here's a tutorial with links in description: 
https://www.youtube.com/watch?v=kS8PucmUt5Y

**Comment by spacehuhn** [comment]
I also linked the ESPtool-GUI in the readme and you could use Arduino too.
https://github.com/spacehuhn/esp8266_deauther#installation
