### ISSUE TITLE
Beacon Clone The Only Thing Working

### ISSUE THREAD

**Issue by cooledwhip** [spacehuhn/esp8266_deauther#577]
I get no SSID for 2 of the features and the one feature that actually deauths the wifi doesn't even work.
http://imgur.com/a/uz8sZ

**Comment by spacehuhn** [comment]
You have to add SSIDs to the list in order to send SSIDs out.

Also please update your device, you seem to use an old outdated version. Follow the instruction on this GitHub repository and not other tutorials in the webs, they're mosty 💩

**Comment by cooledwhip** [comment]
Ok thanks! I'm not so good with this stuff so I will update you!

**Comment by cooledwhip** [comment]
Should I be looking at how to flash it? or what tutorial specifically?

**Comment by tobozo** [comment]
[From the ReadME](https://github.com/spacehuhn/esp8266_deauther#installation)

**Comment by cooledwhip** [comment]
@spacehuhn  Awesome! Got it to work! On the flasher I thought the (Flash F) thing was going to flash it to my F drive on my PC haha... that's why I didn't do that. Anyway I got it working. The problem is I'm only getting like 2 stations that show up. One of the 4 cell phones in my house and my raspberry pi that is on... My megaPC doesn't show up, nor do other family member phones. Also it takes forever to find the stations. Any tips??

And the deauthorizer doesn't stay active for so long. It's only deauthorizing for a few minutes max. Thanks!!

And great project. All these criticisms aren't bashes towards you but are rather just things that I am experiencing. Your work is so genius and way beyond me. Thanks

**Comment by FietsenRijder** [comment]
@cooledwhip 
The problem is I'm only getting like 2 stations that show up. One of the 4 cell phones in my house and my raspberry pi that is on... My megaPC doesn't show up, nor do other family member phones. Also it takes forever to find the stations. Any tips??
I have the same problem have you fixed it yet?

**Comment by tobozo** [comment]
Closing this issue as it seems to be solved

@FietsenRijder not all devices are vulnerable or visible (ESP8266 can't see 5GHz, only 2.4GHz)
Also interferences can affect the ESP, don't put it over your router :-)
