### ISSUE TITLE
Can't connect to "192.168.4.1"

### ISSUE THREAD

**Issue by ghost** [spacehuhn/esp8266_deauther#578]
Basically, it works! But I can't connect to "192.168.4.1" It works with my computer and the phone of my girlfriend but not with my phone!

**Comment by pG5heTMrlbBv0mcH** [comment]
Did you get an IP address?

**Comment by SIlentPain2608** [comment]
What do you mean?

**Comment by XAS-712** [comment]
pG5 thinks your phone didn't get a valid IP address. So your phone also didn't know how to access 192.168.4.1.

**Comment by SIlentPain2608** [comment]
How do I fix it?

**Comment by twosdai** [comment]
Having the same issue as XAS-712

**Comment by osysltd** [comment]
Reset the phone and try to connect from scratch to the re-flashed device.

**Comment by XAS-712** [comment]
@twosdai Sorry, I can't understand it what you said. Could you point it out?

**Comment by FietsenRijder** [comment]
@XAS-712 Your English isn't bad but twosdai has the same issue as yours.

**Comment by herdir** [comment]
I do have a similar problem here.
I've a WiFi Deauther V1.5 (Pocket 8266), i can see the wifi with my laptop and phone.
I can connect to it, and i can ping it without packet lost.
But when i try to go to my browser and connect to 192.168.4.1 then it fails all the time (This site can’t be reached).
Seems like the webserver isn't up (the port 80 is well open when scanning)
I tried to reset the device but still the same.

**Comment by tobozo** [comment]
@herdir using the deauther while the battery is charging may produce this
What does the serial output say ?

**Comment by olmstead819** [comment]
Hi, i'm having the same problem here. The nodemcu connected to my pc for power is working but out of the home is not working... Help please?

**Comment by twosdai** [comment]
Sorry everyone for how long it took me to comment back, basically I was just bad at imaging my device and didnt image it correctly the first time. Re imaging it worked for me and make sure you have the image pointing at the correct area.

**Comment by TheVados** [comment]
> How did you solve this problem? My phone also connects to 192.168.4.1, but the other devices are connected.

**Comment by colognaut** [comment]
same here. brandnew v2.5 board.

**Comment by MrAppAndCrap** [comment]
Hey guys I had the same problem. You need to flash firmware first. 
I followed this tutorial and it worked fine after that. 
https://www.youtube.com/watch?v=r5aoV5AolNo

**Comment by fabiom91** [comment]
So what's the solution??

**Comment by twosdai** [comment]
Its been a while since I solved this problem I ended up just flashing the firmware again. Via what the tutorial told me to do.

**Comment by fabiom91** [comment]
Thank you twosdai, I wasn’t able to flash my esp8266 (I only found instructions for windows) but I solved it just changing my WiFi password

**Comment by Ritesh8732** [comment]
> I do have a similar problem here.
> I've a WiFi Deauther V1.5 (Pocket 8266), i can see the wifi with my laptop and phone.
> I can connect to it, and i can ping it without packet lost.
> But when i try to go to my browser and connect to 192.168.4.1 then it fails all the time (This site can’t be reached).
> Seems like the webserver isn't up (the port 80 is well open when scanning)
> I tried to reset the device but still the same.

You figured out? 
I am also facing same issue.

**Comment by Ritesh8732** [comment]
> I do have a similar problem here.
> I've a WiFi Deauther V1.5 (Pocket 8266), i can see the wifi with my laptop and phone.
> I can connect to it, and i can ping it without packet lost.
> But when i try to go to my browser and connect to 192.168.4.1 then it fails all the time (This site can’t be reached).
> Seems like the webserver isn't up (the port 80 is well open when scanning)
> I tried to reset the device but still the same.

have you figured out ? i have the same issue don't know what to do

**Comment by prostealth** [comment]
hi, this is happened to me today. i just updated my phone and when im trying to use my deauther i cant access the web UI. and i realized when typing on address bar showing search suggestion while it supposed to not show the suggestion because the network doesnt have internet connection. but it does. so thats mean youre  connected to wifi but the phone still can access internet using mobile network.
here is how to fix this. go to wifi setting and open wi-fi assistant. enable "stay connected" and set it to manual.

 ![Screenshot_2022-01-20-23-09-02-209_com.android.settings.jpg](https://user-images.githubusercontent.com/39737044/150376791-54371f33-0b9c-4b00-bb7c-7ad3a6707c26.jpg)

**Comment by Specbee-onchain** [comment]
😑

**Comment by JJDS** [comment]
in my case, on a Samsung S7, I solve the problem, using Chrome and, on the page :192.168.4.1,  browser settings (top right ) check Desktop site, and  ...voila access OK. Hope this help some of you.

**Comment by JJDS** [comment]
following my previous post, I must say that I do not have the esp8226_deauther, so I do not try on it but on one of my onw apk using the esp32 in AP mode .I think that it will work also with all projects due to the fact that  the problem is smartphone 
settings

**Comment by JJDS** [comment]
may be necessary to restart the smartphone

**Comment by twosdai** [comment]
Can we lock this thread, I don't think it needs to be repeatedly Necro'd over and over again with slight variations around the same issue.

**Comment by JJDS** [comment]
I do agree.
I have only sent more posts as soon as I discover them.
