### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by drmacsoft** [spacehuhn/esp8266_deauther#580]
Hi,
I first time use this kind of chipset and adruino, i want to change the language to the web, what files i must reconfigure to change it?

**Comment by XAS-712** [comment]
Please watch my fork.
It's in Chinese.
[Transport](https://github.com/XAS-712/esp8266_deauther)
Or if you want to change the language to other languages, just edit HTML files, then compress them and convert them by byteconverter.exe.

**Comment by drmacsoft** [comment]
are links available to download the right compress and converter program?

**Comment by drmacsoft** [comment]
ok is done, chrome has the problem, with other explorer open ok.

**Comment by drmacsoft** [comment]
another bug now dark mode not work after modify.
