### ISSUE TITLE
Deauth attack doesnt kick everyone

### ISSUE THREAD

**Issue by FietsenRijder** [spacehuhn/esp8266_deauther#583]
I reset my esp 8266 and it finally works. But there is one problem: wen I select deauth attack I doesn't kick everyone of the internet. 
 Any suggestions?

**Comment by FietsenRijder** [comment]
Does anyone know how to fix this?

**Comment by tobozo** [comment]
Probable cause: not all devices are vulnerable to this kind of attack.
