### ISSUE TITLE
Deauth not working 

### ISSUE THREAD

**Issue by coolneb** [spacehuhn/esp8266_deauther#588]
So basically I tried to deauth. And it only sent 6-9 packets. It didn't deauth. Although beacon did work. By the way this is a school wifi. I had permission since I'm in the robotics club after school.

**Comment by tobozo** [comment]
[Maybe the router supports 802.11n](http://www.esp8266.com/viewtopic.php?f=6&t=4032).

**Comment by coolneb** [comment]
Ahh that just might be the case here. I heard my teacher also mention that. Is there a way to use the full 5 GHz instead of using the allotted 2.5 GHz ? 
Thanks.

**Comment by tobozo** [comment]
The ESP8266 only has a 2.4GHz radio.
