### ISSUE TITLE
auto AP scan

### ISSUE THREAD

**Issue by A4A4ANDY** [spacehuhn/esp8266_deauther#59]
Not that big of a life changer I think but would be nice :)

**Comment by N0vaPixel** [comment]
Scan for AP or for client ?
And why since you need to select yourself the targets.

**Comment by nisc3** [comment]
Automatic scan for AP is a nice idea!

**Comment by spacehuhn** [comment]
I don't know If this will work out... Possible but a lot of work! With the current structure it isn't possible, you'd have to change so much in order to get this to work!
So it's way easier just to click on the little scan button.

**Comment by joneroy** [comment]
@spacehuhn I think little **scan** button better then auto ap scan.

**Comment by spacehuhn** [comment]
But I think this can be achieved with JavScript directly in the webinterface. Then the main code remains untouched. I'll test this.

**Comment by spacehuhn** [comment]
There you have it: d63c97f06a8b3527fd476b800bf43bb7f8bb636b

**Comment by joneroy** [comment]
@spacehuhn Grate!!
