### ISSUE TITLE
Yellow symbole in wifi 

### ISSUE THREAD

**Issue by talal2** [spacehuhn/esp8266_deauther#592]
When i connect my esp8266, i connect it to my pc, but when put the password, the yellow triangle symbole is on my wifi, and 192.168.4.1 can't connect, and the internet is down .

**Comment by marek26340** [comment]
Ofcourse you can't surf the internet while connected to esp8266 with the deauther installed on it.
Did you upload the esp8266_deauther project to your esp properly? Which method did you use? Can you copy and paste the output from serial monitor from Arduino IDE (while connected to the computer via USB) to here?

**Comment by tobozo** [comment]
closing this as not an issue
