### ISSUE TITLE
error loading attackstart.json

### ISSUE THREAD

**Issue by talal2** [spacehuhn/esp8266_deauther#593]
Hi 
I Got connected with yellow symbole in my wifi, but i still entered to my esp board, with IP, but when i launch the attack, i got this error: error loading attackstart.json
I Did the sme steps in this video: https://www.youtube.com/watch?v=1cpVJTcHK7U

**Comment by marek26340** [comment]
Try enabling the "LED while attacking" option in the settings. If it will light up on the ESP when you start attack, that means the ESP has changed it's WiFi channel to the channel of the WiFi you want to attack. Simply reconnect WiFi, go to 192.168.4.1 and everything should be fine. If it is not lighting up, then please copy the output from the serial monitor in Arduino IDE and paste it here or on pastebin, whatever, so we can get an idea of what's wrong.

**Comment by tobozo** [comment]
Launching the attack will disconnect you (there's a big message in red letters telling you this).
Feel free to reopen this if you think it's a bug.
