### ISSUE TITLE
Help with 'Scan for wifi stations'

### ISSUE THREAD

**Issue by PxLtommy** [spacehuhn/esp8266_deauther#597]
When I scan on the 'Stations' tab, it gives me the error 'reponse error clientscan.json'.
It says that i may have to reconnect, but i do that and refresh but it is the same, I am on version 1.6 by the way :)

**Comment by spacehuhn** [comment]
Be sure to have an Access Point selected before you scan for Clients.

**Comment by PxLtommy** [comment]
Thankyou very much! ++
