### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by BUYMERCIER** [spacehuhn/esp8266_deauther#600]
*I am not totally sure this is the right place to talk about that, but I couldn't find any other...*

Well, here is my question:  
### How can I compile the source code (after i modified what i wanted) using a C/C++ compiler (clang/g++)?

I read the README and WIki of the project, but all that's written is "modify this and COMPILE then upload". It is explained how to upload, but never how to compile.

Thank you for your help 🥇

**Comment by jLynx** [comment]
You need to use the Arduino IDE

**Comment by BUYMERCIER** [comment]
Thank you for the information 👍
