### ISSUE TITLE
can i eddit the home page? 

### ISSUE THREAD

**Issue by sean-the-random** [spacehuhn/esp8266_deauther#601]
am i able to eddit the home page for the hack? if so were is that located?

**Comment by tobozo** [comment]
It's in the [web_server](https://github.com/spacehuhn/esp8266_deauther/tree/master/web_server/html) folder.
Once modified you have to run the converter (parent folder) to generate the byte code, then replace the existing declarations it in data.h, then recompile the project and flash your ESP8266.
