### ISSUE TITLE
i get (internet may not be available)

### ISSUE THREAD

**Issue by 101tuck** [spacehuhn/esp8266_deauther#602]
i try to go to the ip and it will not load can someone help meh plz

**Comment by jLynx** [comment]
So what IP are you trying to load, what is the SSID name...etc. You need to give us more information than that if you want help

**Comment by 101tuck** [comment]
i try to load pawnd i put the pass in and i go to  192.168.4.1 put it says there is no internet

**Comment by tobozo** [comment]
Please give us more information, we can help but we won't assist.

The "more info" you can provide us with *details* on:

- what ESP are you using ?
- did you flash it yourself ? if so, what version of Arduino, what Operating system are you using ?
- what device are you using when you connect to 192.168.4.1 ? what browser ?

please edit your first comment and add those details

**Comment by 101tuck** [comment]
1.HiLetgo New Version NodeMCU LUA WiFi Internet ESP8266 Development
2.i did flash it myself 64 bit operating system
3.useing my phone and i try it on the computer and useing chrome

**Comment by tobozo** [comment]
possible causes:
- flashing failed => you need to tweak some settings in Arduino before recompiling and flashing
- power problem => ESP8266 is spec'd at 250mA, make sure your power supply can provide that
- boot problem => plug the ESP to the PC and open your serial monitor (115200bauds), push the reset button on the ESP, what does it say in the serial monitor ?

**Comment by 101tuck** [comment]
>flashing failed=>what setting would i mess with 
>power problem=the power supply dose provide that
>boot problem=open serial monitor????
(Kind of new to this)

**Comment by 101tuck** [comment]
is there any way to reset the bored so it is like you just took it out of the package ??

**Comment by sean-the-random** [comment]
Yes go to the update 1.6 and ree inject it and its new agen...

**Comment by tobozo** [comment]
Chances are the binary you used to flash your ESP is pre compiled for a different model (i.e. not the same amount of flash memory), you might be more lucky by compiling from Arduino IDE.
This is where you'll find the serial monitor.
If you're new to this maybe put this project on wait and get familiar with Arduino IDE by doing trivial stuff first (blink the led, do a wifi scan).

**Comment by 101tuck** [comment]
ok i got working i can load the 192.168.4.1 but i get error loading attackstart.json?num=0

**Comment by 101tuck** [comment]
truns out i was not getting the right amount of power
