### ISSUE TITLE
deauther esp

### ISSUE THREAD

**Issue by thegitter12345** [spacehuhn/esp8266_deauther#603]
I need a little help. I turned the board on and it stayed on for an hour then turned off. I could not get it back on for a half hour. when it did come back on the credentials changed to hidden network from my ssid. Now I cant log on. Before I get a refund I want to see if I can't fix this. This is the model below:

https://www.tindie.com/products/lspoplove/wifi-deauther-oled-v2-include-case-and-antenna/

**Comment by spacehuhn** [comment]
Maybe have a look at the FAQ: https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ

**Comment by tobozo** [comment]
@thegitter12345 did reading the FAQ solve your issue? If so, can we close this issue?

**Comment by tobozo** [comment]
closing this, feel free to reopen when new details come up
