### ISSUE TITLE
Resetting the deauther

### ISSUE THREAD

**Issue by Spazticz** [spacehuhn/esp8266_deauther#606]
when I try to reset the deauther by using arduino I set the baud to 115200 and press send but nothing happens

**Comment by tobozo** [comment]
you must type "reset" before pressing the send button

**Comment by Spazticz** [comment]
I did type reset and sent it but nothing happened

**Comment by spacehuhn** [comment]
How do I reset it? -> https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ
Be sure to use the latest version, otherwise it might not work.

**Comment by Spazticz** [comment]
when i flashed the deauther i used nodemcu flasher should i try to flash it with arduino and then reset it?
