### ISSUE TITLE
fatal error: include/wl_definitions.h: No such file or directory

### ISSUE THREAD

**Issue by chamithjay97** [spacehuhn/esp8266_deauther#607]
before i compiled scripts to my nodemcu, but however now scripts dont compiled... this is the full error..

In file included from D:\death\esp8266_deauther\esp8266_deauther.ino:11:0:

C:\Users\JAY\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/ESP8266WiFi.h:28:38: fatal error: include/wl_definitions.h: No such file or directory

   #include "include/wl_definitions.h"

                                      ^

compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.

(error saying that wl_definitions.h is not in directory... but it is in there.. and i downloaded it again and put, but dont work..installed IDE several times... i done all steps in your github... but didnt work yet... can you please help me to fix these...)

**Comment by tobozo** [comment]
looks like you didn't follow all the steps in the installation instructions

**Comment by chamithjay97** [comment]
i followed the all steps... trust me.. after any update on ide its not compiled... i got all the way this error after that

**Comment by narcomerk19** [comment]
try on other computer, with all admin priviledge ☺
I think the problem is in your pc.

**Comment by tobozo** [comment]
well read again then

13 Copy ESP8266Wi-Fi.cpp and ESP8266Wi-Fi.h

14 Paste these files here packages > esp8266 > hardware > esp8266 > 2.0.0 > libraries > ESP8266WiFi > src

you mixed step 9 and 14, now you have unnecessary files in your sdk/include folder and the IDE complains about it

**Comment by chamithjay97** [comment]
so see this https://ibb.co/igGWjQ

am i wrong? and still getting that problem... :/

**Comment by chamithjay97** [comment]
oh my dear sir,, you are a god!!! you exactly right!!! unnecessary files in my sdk... i added that ESP8266Wi-Fi.cpp and ESP8266Wi-Fi.h to sdk thats why i got this problem!!!! oh my god thanks sir!!!! you are a god!!! no words!!!! i love you sir!!!! thank you very much!!!! oh god.... thank you again sir!!!! you are a legend!!!!
