### ISSUE TITLE
Uploading the code

### ISSUE THREAD

**Issue by arcter** [spacehuhn/esp8266_deauther#611]
Hi dear Stefan!
I recently get my hands on a ESP8266MOD and I tried to upload your code warious ways. When I tried with ESP8266Flasher the SSID didn't appear on my phone so I tried to upload it with arduino. I followed this video documentation (https://www.youtube.com/watch?v=N5JVQ-m5Kd0&t=615s) but it didn't work to.
This time I got this error message:
Arduino: 1.6.9 (Windows 7), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

sketch\APScan.cpp: In member function 'bool APScan::start()':

APScan.cpp:18: error: no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

   results = WiFi.scanNetworks(false, settings.apScanHidden) );  //lets scanNetworks return hidden APs. (async = false & show_hidden = true)

                                                           ^

sketch\APScan.cpp:18:59: note: candidate is:

In file included from sketch\APScan.h:6:0,

                 from sketch\APScan.cpp:1:

C:\Users\x\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note: int8_t ESP8266WiFiClass::scanNetworks(bool)

     int8_t scanNetworks(bool async = false);

            ^

C:\Users\x\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note:   candidate expects 1 argument, 2 provided

APScan.cpp:18: error: expected ';' before ')' token

   results = WiFi.scanNetworks(false, settings.apScanHidden) );  //lets scanNetworks return hidden APs. (async = false & show_hidden = true)

                                                             ^

exit status 1
no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

I hope you can understand it and help me out. Thank you very much in advance.

**Comment by tobozo** [comment]
make sure you follow all the steps of the [documentation] (see steps 9 to 14)
