### ISSUE TITLE
Typo - "lose" not "loose"

### ISSUE THREAD

**Issue by binarypower2** [spacehuhn/esp8266_deauther#612]
https://github.com/spacehuhn/esp8266_deauther/blob/cbb5735dd59e3430f41cfc57f9bc2196fc7caa3d/web_server/html/attack.html#L46

**Comment by tobozo** [comment]
Thanks for reporting this, it's already been corrected in the testing branch, see this [commit](https://github.com/spacehuhn/esp8266_deauther/commit/3dd1969850a791c90c33729026acc7733133ddcb)
