### ISSUE TITLE
I Literally Just Updated Firmware And Reflashed And I Still Get 0 Packets/Second

### ISSUE THREAD

**Issue by cooledwhip** [spacehuhn/esp8266_deauther#613]
Just updated firmware and the beacon feature doesn't work. I keep getting 0pkts/s.

Help please!!

I have the 512mb version.

**Comment by tobozo** [comment]
Can you paste the serial output ?

**Comment by spacehuhn** [comment]
0pkt/s mean either that you start an attack without selecting anything, for example start the beacon flood without having anything in the list,
or you did the Arduino installation but used a different version than the necessary version 2.0.0 of the ESP8266 SDK (installation step 6).

**Comment by spacehuhn** [comment]
Please try out the new version or give more information about the problem.
