### ISSUE TITLE
request posibility to add feature if not all ready possible 

### ISSUE THREAD

**Issue by mydakota** [spacehuhn/esp8266_deauther#614]
Would it be possible to add or change config so as when unit is rebooted it can continue last scan or attack.
or have to possibility to add manual ssid macs and devices and the type of attack so as on reboot it just starts working this would save having to continually connect to web UI and scan for my network and deauth my already known devices thanks in advance as i like automation alot

**Comment by tobozo** [comment]
Everything is possible if you edit the source, however there are different motivations behind this kind of use that are not covered by this project such as being crashproof or persistent.

Happy hacking :-)
