### ISSUE TITLE
error loading attackinfo.json

### ISSUE THREAD

**Issue by giuggigiuggi** [spacehuhn/esp8266_deauther#623]
when i try to stop the deauth attack appears: error loading attackinfo.json and the nodemcu don't respond and i have to turn it off. I installed the esp.......bin because when i try to install the 1.6 version from arduino pops up lots of errors. how can i fix this error (loading attackinfo.json)???

many thanks.

**Comment by tobozo** [comment]
What you're experiencing here may be normal, when performing attacks, the deauther changes its WiFi mode and disconnects you. See #356 and other related (closed) issues as hints.

The fact that you get errors in the Arduino IDE is a totally different issue you may solve by applying the README and/or reading the FAQ.
