### ISSUE TITLE
[Feature]: How do i view the attack log?

### ISSUE THREAD

**Issue by ExaCrystal** [spacehuhn/esp8266_deauther#624]
What command do i use in Arduino serial monitor at 115200 baud to view the log of all the attacks that happened? (When you first use the web interface there's a notice saying that every attack is logged) Or if it has to be done another way, how do i do it? Thanks

**Comment by tobozo** [comment]
There is no such implementation yet but it's not that far.

```
    void loadLogFile() {
        File logFile = SPIFFS.open("/log.txt", "r");
        server.streamFile(logFile, "text/plain");
        logFile.close();
    }

    (...)

    void setup() {

        (...)

        server.on("/log.txt",loadLogFile);

        (...)

    }

```

this will probably be added soon to the testing branch, please leave this ticket open until then

**Comment by tobozo** [comment]
closing this now it is merged into the testing branch
