### ISSUE TITLE
How can I update a old version?

### ISSUE THREAD

**Issue by Sleek-Tech** [spacehuhn/esp8266_deauther#633]
How can I update the deauther? It won't scan for wifi access points anymore. Thanks

**Comment by Phoenix1747** [comment]
You have to flash a new release if you want to update the software itself.

**Comment by dfghdsg** [comment]
Hi, I saw a video about  WiFi Jammer... wanted to repeat but it did not work ... I'm new to this :)
![img_20171012_185808](https://user-images.githubusercontent.com/32743584/31506629-a056a306-af80-11e7-87a3-ef45574bd0ec.jpg)
![img_20171012_185908](https://user-images.githubusercontent.com/32743584/31506630-a0ad5c32-af80-11e7-8e49-82020f8c325d.jpg)
![screenshot_1](https://user-images.githubusercontent.com/32743584/31506632-a1b5d690-af80-11e7-9202-ec47c89942e8.jpg)
![screenshot_2](https://user-images.githubusercontent.com/32743584/31506633-a1e56a5e-af80-11e7-9694-bfb4c1a586ff.jpg)
![screenshot_3](https://user-images.githubusercontent.com/32743584/31506634-a205922a-af80-11e7-9638-391ae50ef8b1.jpg)

**Comment by tobozo** [comment]
@ dfghdsg  if you just happened to read the documentation clearly visible on the screenshot you just posted, you know it's not a jammer.

**Comment by dfghdsg** [comment]
I did everything on this video (not advertising), but there is not that old sketch ...  https://www.youtube.com/watch?v=RZt2IBZ7t_4

**Comment by tobozo** [comment]
I'm sure you'll find a way to get it working, it's all about trial and error,
Just have faith in the ReadME because it gets updated while the video does not.

**Comment by dfghdsg** [comment]
Thank you very much for the support and advice ... I will try again :)
