### ISSUE TITLE
Beacon Flooding - SSID/Beacon doesn't show up as encrypted

### ISSUE THREAD

**Issue by HenningBertsch** [spacehuhn/esp8266_deauther#634]
### Hardware/Flashing:
Board:				ESP8266 NodeMCU V3
Using OLED:                  No
Using WebServer:         No
Using Serial:                  Yes
Installation mode:         source
Code/binary version:    1.6? (downloaded 10. Oct. 2017)
Flash size:                     4M(3M SPIFFS)
Flash method:		Arduino IDE
Flash Frequency:		80Mhz
Upload Speed:		115200
Powered by:                   USB

### Description:
Added SSIDs to flood but none of them will show up as encrypted. I tried to add the SSIDs with and without the "Encrypted" checkbox ticked.

What you're expecting: Networks shown as encrypted if encrypted checkbox is ticked
What you get instead: All SSDIs shown as unprotected

### Debug Messages:
- getting attacks JSON (229)...done (everything normal)

### Settings:
![settings](https://user-images.githubusercontent.com/14974052/31330097-3f0d9d20-acdd-11e7-9c97-afb474fd435d.png)

### Result:
![result](https://user-images.githubusercontent.com/14974052/31330102-46838ab0-acdd-11e7-89c8-fbcb03348efd.png)

**Comment by tobozo** [comment]
this is a known bug, please subscribe to issue #269 and close this ticket so all feedback about this stays in one place
