### ISSUE TITLE
nethunter

### ISSUE THREAD

**Issue by Robiii97** [spacehuhn/esp8266_deauther#641]
This maybe is a very off topic and stupid question but...
Would it be possible to port this project to kali nethunter android phone?
and use it with a external wifi dongle in monitor mode?

**Comment by tobozo** [comment]
Quoting reddit: [It's just doing a deauthentication attack, possibly repeatedly. If you understand the technique and have any monitor-mode capable wireless hardware, you can write a 10-line shell script(probably less if you sacrifice clarity) to do the same thing.](https://www.reddit.com/r/netsecstudents/comments/5z0i1v/esp8266_deauther_for_other_systems/deupzw4/)
