### ISSUE TITLE
Only scans 2.4g?

### ISSUE THREAD

**Issue by chadillac3006** [spacehuhn/esp8266_deauther#645]
idk about anyone else but the one thats made for this project from [tindie ](https://www.tindie.com/products/lspoplove/wifi-deauther-oled-v25-case-and-antenna/) only picks up 2.4g and not the 5g band

**Comment by jLynx** [comment]
Thats correct, read the FAQ

**Comment by chadillac3006** [comment]
oh gottcah sorry "Make sure there are 2.4ghz networks in your area. This device will not find any 5ghz networks!

" didnt see that lol thx
