### ISSUE TITLE
can we run linset  or fluxion on esp8266 instead of  the deauther ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [spacehuhn/esp8266_deauther#648]

**Comment by sk-y2k** [comment]
No. Period.

**Comment by minanagehsalalma** [comment]
So it's impossible to run it on esp8266 and what do you mean with period

**Comment by jLynx** [comment]
Google "period English"

**Comment by minanagehsalalma** [comment]
I have already did.  So what.  Can you complete the sentence?  Because it
mean nothing alone.

**Comment by sk-y2k** [comment]
It means nothing more.

**Comment by sk-y2k** [comment]
@spacehuhn
Stefan, can we expect a release?
