### ISSUE TITLE
error: espcomm_open failed

### ISSUE THREAD

**Issue by m00n21** [spacehuhn/esp8266_deauther#649]
### Hardware/Flashing:
Board:NodeMcu Lua CH340G ESP8266			?ESP8266 dev module?Tindie OLED?Wemos Mini?Other (specify)?
Using OLED:   ?YES?NO?no
Using WebServer: ?YES?NO?no
Using Serial: ?YES?NO?no
Installation mode:  ?binary?source?source
Code/binary version: ?1.5?1.6?
Flash size:  ?1M/512K?i dont know
Flash method:		i tryed both and didnt work					?esptool?Arduino IDE?
Flash Frequency:		40			?40Mhz?
Upload Speed:			115200			?115200?
Powered by:  ?USB?Battery? mico cabele

### Description:
 ---  i click up load arfter all of the steps and it comes up with an error 
--- error: espcomm_open failed

### Debug Messages:
``` error: espcomm_open failed

**Comment by bolbolmm** [comment]
go to Tools>Port>COM4 
and i think it will work

**Comment by m00n21** [comment]
I only have COM1 an COM8

**Comment by tobozo** [comment]
@m00n21 this is progress! 
You'll find out this com number will change every time you plug or unplug your ESP, so make sure you check this before flashing.

**Comment by m00n21** [comment]
you fucking retards ,i know what port it is
