### ISSUE TITLE
Time limit on attacks

### ISSUE THREAD

**Issue by disavowedking** [spacehuhn/esp8266_deauther#650]
### Hardware/Flashing:
Board:	Tindje			?ESP8266 dev module?Tindie OLED?Wemos Mini?Other (specify)?
Using OLED:   YES
Using WebServer: YES
Using Serial: NO
Installation mode: source
Code/binary version: 1.6
Flash:
Flash Frequency:					
Upload Speed:						
Powered by:  Battery

Maybe this is happening by design or I am missing something but all attacks last roughly five minutes and then need to be started manually. Whether it is from using the WebServer or using the OLED screen on the unit. Am I an idiot or do I need to reflash?

What you're expecting:  Attacks to last for an unlimited amount of time. 
What you get instead: Attack length roughly five minutes. 

### Debug Messages:
```
Put the serial output here

**Comment by tobozo** [comment]
That's a [default setting](https://github.com/spacehuhn/esp8266_deauther/blob/34b5f08f75e560e036ad58626586073e18c9f39b/esp8266_deauther/Settings.cpp#L109) you can change from the settings page,
