### ISSUE TITLE
ESP8266 NodeMCU (ESP12E Module) wont work

### ISSUE THREAD

**Issue by addisonrudd** [spacehuhn/esp8266_deauther#652]
Getting this error.

In file included from sketch/Settings.h:12:0,
                 from sketch/APScan.h:9,
                 from sketch/APScan.cpp:1:
/Users/addisonrudd/Library/Arduino15/packages/esp8266/hardware/esp8266/2.0.0/tools/sdk/include/user_interface.h:456:174: error: declaration of C function 'int wifi_send_pkt_freedom(uint8**, int, bool)' conflicts with
 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);
                                                                                                                                                                              ^
In file included from sketch/Settings.h:12:0,
                 from sketch/APScan.h:9,
                 from sketch/APScan.cpp:1:
/Users/addisonrudd/Library/Arduino15/packages/esp8266/hardware/esp8266/2.0.0/tools/sdk/include/user_interface.h:453:5: error: previous declaration 'int wifi_send_pkt_freedom(uint8*, int, bool)' here
 int wifi_send_pkt_freedom(uint8 *buf, int len, bool sys_seq);
     ^
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by tobozo** [comment]
Too much of a hurry to follow all the steps in the [ReadMe](https://github.com/spacehuhn/esp8266_deauther/blob/master/README.md)?

**Comment by addisonrudd** [comment]
@tobozo no i read it. i also watched like 5 videos and looked at tutorials. im just new to this so its hard. if you arent going to try to help then dont bother to comment

**Comment by tobozo** [comment]
you're getting close, you just skipped a step in the readme, just make sure you follow all of them and it'll work

**Comment by XAS-712** [comment]
You may used a library of a wrong version.
Just 2.0 can be used.

**Comment by tobozo** [comment]
fixed in the next version, closing this
