### ISSUE TITLE
How to disable limit?

### ISSUE THREAD

**Issue by loskiq** [spacehuhn/esp8266_deauther#656]
Attack lasts no more than five minutes. How to disable this limit?

### Hardware/Flashing:
Board: Wemos Mini
Using OLED: No
Using WebServer: Yes
Using Serial: Yes
Installation mode: Binary
Code/binary version: 1.6
Flash size: 1M
Flash method:	esptool
Flash Frequency:	40Mhz
Upload Speed:	115200
Powered by: USB

**Comment by tobozo** [comment]
you can't disable the limit but you can change the timeout to a higher value from the settings page

**Comment by loskiq** [comment]
@tobozo thank you!
