### ISSUE TITLE
How to reboot the device using a serial console?

### ISSUE THREAD

**Issue by loskiq** [spacehuhn/esp8266_deauther#657]
How to reboot the device using a serial console?

**Comment by tobozo** [comment]
You can't (yet), you can only reset settings.

**Comment by Wither2** [comment]
Hello, please tell me how I can reset the settings without logging in through the browser. I just changed the password and forgot it. And I do not know what to do. I'm asking you, help.

**Comment by tobozo** [comment]
just [erase_flash](http://www.pratikpanda.com/completely-format-erase-esp8266-flash-memory/) and reflash it with the binary
