### ISSUE TITLE
How to protect yourself from such a Deauthentication attack? 

### ISSUE THREAD

**Issue by Jayeshpatil665** [spacehuhn/esp8266_deauther#659]
Why did i don't get noticed... My pool request get canceled... "Spacehuhn " sir. Please Answer my query.. Ho to protect yourself from such a Deauthentication attack, is there any configuration/settings in WiFi router?

**Comment by tobozo** [comment]
[Many answers here](https://security.stackexchange.com/questions/20219/preventing-deauthentication-attacks)

**Comment by Jayeshpatil665** [comment]
Thanks
