### ISSUE TITLE
OLED display - only every other row of pixels

### ISSUE THREAD

**Issue by RChadwick7** [spacehuhn/esp8266_deauther#664]
### Hardware/Flashing:
Board:	http://cgi.ebay.com/ws/eBayISAPI.dll?ViewItem&item=222661781226
Using OLED:   YES
Using WebServer: NO
Using Serial: NO
Installation mode:  binary
Code/binary version: 1.5, 1.6
Flash size:  1M
Flash method:	Nodemcu
Flash Frequency: 40Mhz
Upload Speed:	230400
Powered by:  Battery

### Description:
The OLED display appears to only show every other line of pixels, making it impossible to read small text.

What you're expecting:  A normal OLED display
What you get instead: Corrupted display

![untitled](https://user-images.githubusercontent.com/8503659/33242334-28ea5c7e-d2a1-11e7-917b-c2d745d0ee43.jpg)

**Comment by lspoplove** [comment]
This is a fake board of my product. I do not suggest you use this board.

**Comment by RChadwick7** [comment]
I'm surprised, as it doesn't look anything like the D-duino.

**Comment by tobozo** [comment]
I row out of two means you probably broke one of the corners on the OLED, cool effect though

**Comment by RChadwick7** [comment]
That is possible. Before replacing the display, I wanted to explore the possibility it was software. In my Googling, I came across this : http://forum.espruino.com/conversations/269330/
Could it be an init issue?

**Comment by RChadwick7** [comment]
You're right. Replacing the display fixed the issue. Thanks!
