### ISSUE TITLE
Deauther only works once

### ISSUE THREAD

**Issue by epiclololol** [spacehuhn/esp8266_deauther#665]
When I activate the deauther attack, my client diconnects once and then reconnects. Shouldn't it be disconnecting?

**Comment by tobozo** [comment]
Maybe it's switching channel

**Comment by spacehuhn** [comment]
Or switching network, or switching the frequency, or switching to protected managment frames or or or....
This is for testing anyway, if it doesn't work for your device - be happy :)

**Comment by epiclololol** [comment]
Ok thanks
