### ISSUE TITLE
Error: clear the client list.

### ISSUE THREAD

**Issue by Ben-Lichtman** [spacehuhn/esp8266_deauther#666]
NodeMCU 2.0

### Description:
I select the correct access point, but then on the "Stations" tab I get the error bar in red saying "Error: clear the client list." and am unable to progress with scanning for clients.

This happens even after reuploading the sketch.

**Comment by token47** [comment]
Right after erroring out, the board resets (wdt reset message on boot). Celphone looks for another AP and have to reconnect by hand. Reload page, scan APs again, so far so good. Go to the clients page, try to scan, same error. Repeat.

**Comment by tobozo** [comment]
see if it is fixed in the next version, reopen if necessary

closing this
