### ISSUE TITLE
Bug in attacks.json

### ISSUE THREAD

**Issue by louia** [spacehuhn/esp8266_deauther#667]
### Hardware/Flashing:
Board:				?ESP8266 dev module?Tindie OLED?Wemos Mini?Other (specify)?
Using OLED:   NO
Using WebServer: YES
Using Serial: NO
Installation mode:  source
Code/binary version: 1.6
Flash size:  ?1M
Flash method:	Arduino IDE
Flash Frequency:	
Upload Speed: 115200
Powered by:  Battery

### Description:
When i start an attack by deauth, sometime i must reboot my card because a message say on my webphone "Attack.json failed".

What you're expecting:  ---
What you get instead: ---

### Debug Messages: Attack.json failed
```
Attack.json failed

**Comment by marek26340** [comment]
Have you tried another browser?

**Comment by louia** [comment]
No, just chrome on android

**Comment by marek26340** [comment]
Try to find the channel of the network that you are trying to attack, set the channel of your deauther to the channel of the AP that you are trying to deauth, and try to attack it again. Did you get that error again?

**Comment by cambgiles** [comment]
I have been having this issue as well.

**Comment by bert4** [comment]
Same here, except I am also getting it on ClientScan.json

**Comment by RudyTheKid** [comment]
I get an error loading attackinfo.json

**Comment by tobozo** [comment]
see if it is fixed in the next version, reopen if necessary

closing this

**Comment by spacehuhn** [comment]
You can loose connection when starting an attack, as explained in the web interface.
