### ISSUE TITLE
Device resets with Exception while scanning

### ISSUE THREAD

**Issue by kwinz** [spacehuhn/esp8266_deauther#670]
### Hardware/Flashing:
Board:				tindie Travis Lin WiFi deauther OLED V2.5 with case and antenna
Using OLED:   YES
Using WebServer: NO
Using Serial: NO
Installation mode:  original firmware
Code/binary version: 1.6
Flash size:  unknown
Flash method:							original firmware
Flash Frequency:					original firmware
Upload Speed:						original firmware
Powered by:  both USB and Battery exhibit the issue

### Description:
When I am in an area with little wifi the device works expected.
However in the city when I scan the device resets while scanning.
I get back to the boot screen.
Serial shows an exception (see below).

What you're expecting:  scan results are shown.
What you get instead: device hard resets.

How best to debug this?

### Debug Messages:
```

starting AP scan...
MAC - Ch - RSSI - Encrypt. - SSID - Hidden

Exception (29):
epc1=0x4000df64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd80 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff20:  40288b70 00000000 0000000d 4020e39c  
3fffff30:  40232fdb 3ffef9dc 3fff6368 40232fe6  
3fffff40:  00000000 40232dcf 3ffef9f4 3ffe9ff0  
3fffff50:  02b3651a 3ffef9f4 3ffe9ff0 02b3651a  
3fffff60:  40233260 3ffebe6d 40223e65 3ffee348  
3fffff70:  4021d7ad 000000f5 3ffea928 3ffea928  
3fffff80:  4021d7f2 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffea010 3fffdab0 00000000 3fffdcc0  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld
Settings:
SSID: pwned
SSID length: 5
SSID hidden: 0
password: deauther
password length: 8
channel: 1
Default MAC AP: 62:01:94:69:<removed>
Saved MAC AP: 62:01:94:69:<removed>
MAC AP random: 0
Scan hidden APs: 1
deauth reson: 1
attack timeout: 300
attack packet rate: 10
client scan time: 15
use built-in LED: 1
channel hopping: 0
multiple APs: 0
multiple Attacks: 0
mac change interval: 4
1s beacon interval: 0
LED Pin: 2
Trying to sync the MAC addr with settings
Synced with saved mac addr : 62:01:94:69:<removed>
nameList cleared
Attack LED : OFF

Starting WiFi AP:
SSID     : 'pwned'
Password : 'deauther'
-----------------------------------------------

 generating MACs...done

Starting...
```

**Comment by tobozo** [comment]
Probably the same as seen [on various issues](https://github.com/spacehuhn/esp8266_deauther/search?q=busy+area&type=Issues&utf8=%E2%9C%93).

@kwinz I feel bad about closing this issue because it's the cleanest report we've had so far since we created the issue template. 
This is a known problem and has some workarounds but no solution. If you're willing to play with the code you may try some of the suggestions you'll find in the various issues, otherwise there's a V2 on the way.

Thanks for reporting!
