### ISSUE TITLE
Everything Appears To Work - But Network is Unaffected

### ISSUE THREAD

**Issue by Davidjb7** [spacehuhn/esp8266_deauther#671]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware/Flashing:
Board:				NodeMCU EP8266MOD
Using OLED:   No
Using WebServer: Yes
Using Serial: Unsure 
Installation mode:  Binary
Code/binary version: 1.6
Flash size:  1M
Flash method:	esptool
Flash Frequency: 40Mhz
Upload Speed: 230400 buadrate
Powered by:  USB wall socket

### Description:
Everything appears to work, the flashing process went well, "pwned" comes up, logs in, access to the server works on web or phone. I can see all networks, I can pick my own network. I then go to attacks and choose deauther and it tells me it is going at 10pkts/s. But there is no change on the network. No slowdown, nothing. I tried increasing the packet rate to 1000 and enabling simultaneous attacks...still nothing. I've also gotten the "error loading ATTACKINFO.JSON" message a few times.

What you're expecting:  The network to freeze up.
What you get instead: no change/trivial change

### Debug Messages:
```
Put the serial output here

**Comment by jLynx** [comment]
``` If it can send packets but your target doesn't loose its connection, then the Wi-Fi router either uses 802.11w and it's protected against such attacks, or it communicates on the 5GHz band, which the ESP8266 doesn't support. Also note that some devices reconnect faster than it's deauthenticating them, so it will not block the connection completely, but slowing it down.```
Then your network is not vulnerable, congratulations :)
