### ISSUE TITLE
Deauth attack is seen as working but has no effect

### ISSUE THREAD

**Issue by ztufenkjian** [spacehuhn/esp8266_deauther#673]
### Hardware/Flashing:
Board:				?ESP8266 dev module?Tindie OLED?Wemos Mini?Other (specify)?
Using OLED:   No
Using WebServer: ?No
Using Serial: No
Installation mode:  Flashing via micro-usb
Code/binary version: ?1.6
Flash size:  1MB
Flash method: Esptool
Flash Frequency:	80Mhz
Upload Speed: 230400
Powered by: USB

### Description:
Hello,

The webpage states that it is sending out packets at 10pkts/s but there seems to be no issue with the selected network whatsoever. I am using a Google OnHub as my access point that is connected to a modem. I have tried attacking the OnHub and modem individually and both at once, but the same problem occurs. It seems like the device thinks it is attacking the network but there is simply no sign of interference. I am able to use the other two attacks with no problem. They go out very quickly. I have tried restarting the device, network, and reflashing it as well. I have also tried increasing and decreasing the number of packets being sent out to no avail.

What you're expecting:  A working Deauth attack with packets that actually have an effect on the network.
What you get instead: A Deauth attack that visually says it is working but has no effect on the network targeted.

You'll have to forgive me if I am missing something entirely or misstated something. I am new to this community and had this device referred to me by a friend.

**Comment by tobozo** [comment]
Google WiFi has 5 GHz wireless 802.11a/n/ac, you're only forcing your devices to switch band and get out of attack range.
This is normal behaviour for a non-vulnerable device, congratulations!
