### ISSUE TITLE
How to convert all the source code to a .bin?

### ISSUE THREAD

**Issue by yasha107** [spacehuhn/esp8266_deauther#684]
I want to modify a little bit the design, and i want to know how do i compile all the source back to a .bin

**Comment by marek26340** [comment]
Did you even try asking our best friend google about this? 
https://forum.arduino.cc/index.php?topic=61365.0

**Comment by XAS-712** [comment]
By Arduino.
Run Arduino IDE, and open the .ino file.

**Comment by spacehuhn** [comment]
You can compile a .bin file with Arduino under Sketch -> Export compiled Binary
