### ISSUE TITLE
Need help with configuration (reset settings, without logging in through the browser)

### ISSUE THREAD

**Issue by Wither2** [spacehuhn/esp8266_deauther#686]
Hello, please tell me how I can reset the settings without logging into the browser.  I just changed my password and forgot it. As a result, I can not connect to its Wi-Fi network. And I do not know what to do.  I ask you, help.

**Comment by loskiq** [comment]
**How do I reset it?**

Method 1: Connect pin 4 (D2 on the NodeMCU) to GND and plug the device in.
Method 2: Connect your device, open up the serial monitor in Arduino, change the baudrate to 115200, type in "reset" and click send.

https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ

**Comment by Wither2** [comment]
Sorry, but you can tell me more about 2 variants. I'm just completely new, and I do not understand many things. I'll be infinitely grateful if you help me.

**Comment by Wither2** [comment]
On the second option

**Comment by loskiq** [comment]
Connect ESP8266 to your computer via USB cable. Then open console client, select com port and baud rate (115200). Type "reset" and click Enter.

**Comment by Wither2** [comment]
Tell me please, "open the Windows console client" is it in Arduino or in CMD Windows?

**Comment by Wither2** [comment]
And please tell me which module in Arduino you need to select for this board, in order to reset the settings and see all the code as a whole.


![vfy6jyxevz8](https://user-images.githubusercontent.com/35061025/34532931-1aaa27a2-f0c9-11e7-8298-210bd2d2e284.jpg)
![3qksjd-sg6k](https://user-images.githubusercontent.com/35061025/34532933-1ae7c170-f0c9-11e7-8211-e65620405409.jpg)

**Comment by tobozo** [comment]
have you tried pushing this button while the device is powered ?

![image](https://user-images.githubusercontent.com/1893754/34540432-d7b1f55e-f0d4-11e7-8814-599c99b03f3e.png)

**Comment by Wither2** [comment]
Yes, the device simply restarts.  
Please, let's get to sleep in VKontakte, here is my sramnica: https: //vk.com/xax101001 
Or in any social network convenient for you.

**Comment by spacehuhn** [comment]
You can try the new version. The other reset options are explained above.
