### ISSUE TITLE
Encryption option not working

### ISSUE THREAD

**Issue by KnifeBoss** [spacehuhn/esp8266_deauther#687]
### Hardware/Flashing:
Board: ESP8266 
Using OLED:  NO
Using WebServer: YES
Using Serial: ?YES?NO?
Installation mode:  binary
Code/binary version: ?1.5?1.6?
Flash size:  1M
Flash method:	esptool
Flash Frequency: 80Mhz?
Upload Speed: 115200
Powered by:  USB

### Description:
When I select the option to make AP with encryption, and I press Start the AP appear but they are not encrypted (no pass)

What you're expecting:  Im expecting the AP to be encrypted with a password.
What you get instead: Unsecure AP

**Comment by marek26340** [comment]
What code version are you using? I hope that you are using the latest one.

**Comment by spacehuhn** [comment]
That's known issue on Apple devices. Will be fixed in the next version.

**Comment by leperjulien** [comment]
Same for me of Apple Computer and smartphone :) Do you know what part of the code will be modified in order to fix this ?

Thanks

**Comment by tobozo** [comment]
see if it is fixed in the next version, reopen if necessary

closing this
