### ISSUE TITLE
Pwend network not showing up

### ISSUE THREAD

**Issue by Johnsjs232** [spacehuhn/esp8266_deauther#689]
### Hardware/Flashing:
Board:				Esp8266
Using OLED:  no
Using WebServer: ?YES?NO?
Using Serial: ?YES?NO?
Installation mode:  ?binary?source?
Code/binary version: ?1.5?1.6?
Flash size:  1M
Flash method:	Nodemcu flasher program
Flash Frequency: 40Mhz
Upload Speed: 115200
Powered by: Usb

### Description:
It says that it is complete but it will not give off a wifi signal? I have no idea what to do
What you're expecting:  Idk
What you get instead: ---

### Debug Messages:
```
Put the serial output here

**Comment by marek26340** [comment]
Please give us the serial output from the serial monitor in Arduino IDE. Also it would be better if you will fill out the information like "Installation mode: binary/source" properly.

**Comment by Johnsjs232** [comment]
where do I find this info

**Comment by XAS-712** [comment]
Connect its serial port to you computer. Then run a serial port monitor and open the port.

**Comment by hmpowerbt** [comment]
Try adding the network its probably hidden.

**Comment by tobozo** [comment]
see if it is fixed in the next version, reopen if necessary

closing this
