### ISSUE TITLE
OLED SPI Interface

### ISSUE THREAD

**Issue by nhocconlangthang** [spacehuhn/esp8266_deauther#690]
Board: ESP8266 NodeMCU Lua CP2102
Using OLED:   YES
Using WebServer: YES
Using Serial: NO
Installation mode:  SOURCE
Code/binary version: 1.6
Flash size:  1M
Flash method:	ArduinoIDE
Flash Frequency:	40MHZ
Upload Speed:	115200
Powered by:  USB

### Description:
I can't display with OLED using SPI interface. please help me wire diagram and code plz

**Comment by tobozo** [comment]
check the [display library](https://github.com/squix78/esp8266-oled-ssd1306) documentation

**Comment by nhocconlangthang** [comment]
i don't know how to connect wire.
and in code not support spi oled version
