### ISSUE TITLE
What do the other attack modes do?

### ISSUE THREAD

**Issue by sam-gurdus** [spacehuhn/esp8266_deauther#692]

**Comment by marek26340** [comment]
You have everything described if you will scroll down on the attacks page.

**Comment by XAS-712** [comment]
There are 3 modes.
One is to make some fake APs.
One is to access other APs quickly to let them down.
The other is deauth mode, you know.

**Comment by hmpowerbt** [comment]
Deauth: Disconnect all users of the Wi-Fi
Beacon: Create Fake Networks
Probe Request: AP Take down
Stations: Select certain people to kick out 
                 of the Wi-Fi
