### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by xGabbro** [spacehuhn/esp8266_deauther#694]
Board:	NodeMCU V.1
Using OLED:   no
Using WebServer: yes
Using Serial: yes
Installation mode:  source
Code/binary version: 1.6
Flash size:  1
Flash method:	Arduino
Flash Frequency: all
Upload Speed: all	
Powered by:  Pc port

Description of problem:
ESP8266 make a red led after compiling and updating in all mode.the normale non file (1mb) work,only when i update my file not work

**Comment by spacehuhn** [comment]
english please

**Comment by tobozo** [comment]
closing this
