### ISSUE TITLE
Request : Add Esp8266 Deauther menu with DeauthDetector

### ISSUE THREAD

**Issue by ChandraOrbit** [spacehuhn/esp8266_deauther#697]
Board:DSTIKE v3.0
Using OLED: Using USE_DISPLAY: yes
Using WebServer: YES
Using Serial: YES
Installation mode: both.
Code/binary version: 1.6
Flash size: 1M & 4M
Flash method: Nodemcu
Flash Frequency: in arduino 80mhz
Upload Speed: in arduino 115200
Powered by: Tested on both USB and battery.

### Description:
Can ESP8266_Deauther join or add DeauthDetector menu?
In the [WI-PWN](https://github.com/samdenty99/Wi-PWN) release there is an additional menu that is DeauthDetector which should be ESP8266_Deauther can also.

**Comment by spacehuhn** [comment]
Added in new version 😃
