### ISSUE TITLE
No favicon on http://192.168.4.1/apscan.html or http://192.168.4.1/stations.html

### ISSUE THREAD

**Issue by sam-gurdus** [spacehuhn/esp8266_deauther#699]
Attacks and settings both have it, though.

**Comment by XAS-712** [comment]
Check if these pages have a link to fav icon.
Or see the source code. Maybe it didn't have a favicon handler.

**Comment by sam-gurdus** [comment]
I checked, I am getting a 404 error when going to the favicon link.

**Comment by XAS-712** [comment]
see if there is a handler in the source code。

**Comment by tobozo** [comment]
see if it is fixed in the next version, reopen if necessary

closing this

**Comment by spacehuhn** [comment]
I don't see how this is a problem. 
There is no favicon and I don't think I want to waste the memory and loading times to add one. The web server is already buggy enough.

**Comment by Maddeano** [comment]
Hi, I have loaded every thing up to PWNED,but cat get the 192.186.4.1/attack.html,to work,can anyone help me Please,Thanks in advance...
