### ISSUE TITLE
Not able to find pwned Wifi 

### ISSUE THREAD

**Issue by akshayshekade5** [spacehuhn/esp8266_deauther#7]
I uploaded sketch successfully but, i am not able to find wif name "pwned" and my NodeMcu esp8266 blue ed is not blinking  which is near to that wifi module
![20170207_205324](https://cloud.githubusercontent.com/assets/25614535/22697599/f4092d14-ed77-11e6-8359-8aed846b0e01.jpg)

**Comment by spacehuhn** [comment]
Please provide your solution to your problem before closing it. It may help others!
