### ISSUE TITLE
Customize HTML/CSS

### ISSUE THREAD

**Issue by sam-gurdus** [spacehuhn/esp8266_deauther#700]
Is there the possibility to add a customization option in the settings so we can edit the HTML/CSS without having to edit the source and compile it ourselves.

**Comment by tobozo** [comment]
you may try the [testing branch](https://github.com/spacehuhn/esp8266_deauther/tree/testing) and edit everything in the /data folder but it requires the Skecth Data Uploader component for the Arduino IDE (see the ReadME) and it's highly unstable.

Otherwise you can wait for the next release, @spacehuhn may reveal the roadmap soon.

**Comment by XAS-712** [comment]
It's a good idea. But the length of byte arrays is fixed. You may not change it successfully.

**Comment by sam-gurdus** [comment]
So is the new release a complete overhaul? Do we know when?

**Comment by tobozo** [comment]
could be serverless version as most problems come from the web server

**Comment by sam-gurdus** [comment]
What does that mean? You mean it doesn't have a web interface or what?

**Comment by tobozo** [comment]
I said it *could*, but in reality I just hope it won't have a web interface. 
Most issues in this version go away as soon as you disable the webserver so that would be fair.

**Comment by sam-gurdus** [comment]
How would you control it then?

**Comment by tobozo** [comment]
new approach to customizing web content is introduced by the new release, closing this

**Comment by spacehuhn** [comment]
Tutorials and infos on how to modify it follow soon, keep an eye on the wiki.
In the meantime:
- edit the stuff in the web_interface folder
- convert it with the webConverter.py in utils
- upload it using the SPIFFS arduino addon (google is your friend)
