### ISSUE TITLE
Code Compiling problem

### ISSUE THREAD

**Issue by Shreyas700** [spacehuhn/esp8266_deauther#706]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------
Arduino: 1.8.5 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

sketch\APScan.cpp: In member function 'bool APScan::start()':

APScan.cpp:14: error: no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

     results = WiFi.scanNetworks(false, settings.apScanHidden);

                                                             ^

sketch\APScan.cpp:14:61: note: candidate is:

In file included from sketch\APScan.h:6:0,

                 from sketch\APScan.cpp:1:

C:\Users\Shreyas Mhatre\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note: int8_t ESP8266WiFiClass::scanNetworks(bool)

     int8_t scanNetworks(bool async = false);

            ^

C:\Users\Shreyas Mhatre\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note:   candidate expects 1 argument, 2 provided

exit status 1
no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

### Hardware/Flashing:
Board:			ESP8266 

Using WebServer: ?YES?NO?
Using Serial: ?YES?NO?
Installation mode:  ?binary?source?
Code/binary version: ?1.5?1.6?
Flash size:  ?1M/512K?
Flash method:							?esptool?Arduino IDE?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?
Powered by:  ?USB?Battery?

### Description:
Describe your problem here, provide as many details as possible.
Make sure you read the FAQ first, incomplete bug reports will be CLOSED without notice.

What you're expecting:  ---
What you get instead: ---

### Debug Messages:
```
Put the serial output here

**Comment by tobozo** [comment]
You skipped steps 9 to 14 in the [Readme](https://github.com/spacehuhn/esp8266_deauther/blob/master/README.md)
