### ISSUE TITLE
Please Help : Can't connect to this network

### ISSUE THREAD

**Issue by Rexypad** [spacehuhn/esp8266_deauther#707]
Hi guys, a few months ago, the wifi jammer worked fine and I really loved it. However, the day before yesterday, when I tried to connect my windows 10 laptop to the deautherizer, it says "can't connect to this network", then I tried to do it for my iphone 6s phone as well. It also said "Unable to connect to this network". Help would be much much much appreciated. I long for the time before. Thanks.

**Comment by hmpowerbt** [comment]
Try Flashing It again or reseting it.

**Comment by spacehuhn** [comment]
> jammer
