### ISSUE TITLE
please help:espcomm_open failed

### ISSUE THREAD

**Issue by suraandcrisaldo** [spacehuhn/esp8266_deauther#708]
I use arduino and follow the steps,but when I upload the code it shows me "error:espcomm_open failed"
![error](https://user-images.githubusercontent.com/35965398/35791981-8ce248ba-0a85-11e8-83eb-e350a13b23f7.png)

**Comment by marek26340** [comment]
Did you select the correct port? (for ex. COM3, COM9......)

**Comment by suraandcrisaldo** [comment]
Oh thank you ,I chose the wrong port

**Comment by PolicyWsy** [comment]
I already had the same problem. And I've tried all ports but none is available.

**Comment by marek26340** [comment]
@PolicyWsy Then it could be the drivers.
