### ISSUE TITLE
I Upload it->Red light constantly on->Nothing happens

### ISSUE THREAD

**Issue by James20002** [spacehuhn/esp8266_deauther#709]
### Hardware/Flashing:
Board:NodeMCU v.1
Using OLED: NO
Using WebServer: NO
Using Serial: YES
Installation mode:  BINARY
Code/binary version: 1.6
Flash size:  1M
Flash method:	ESP8266FLASHER
Flash Frequency:40Mhz
Upload Speed:On back it says 9600 baud but I have tried it and 115200
Powered by: USB

### Description:
I have tried uploading and erasing and changing settings but nothing has happened but a red light stays on, blue light blinks once and goes dead, and red and blue lights blink back and forth...not sure what to do other than to keep switching settings and try again but I just don't know...please help.

What you're expecting:  ---idk
What you get instead: ---idk

**Comment by marek26340** [comment]
Hmm... How could you flash the ESP with binary file through Arduino IDE?
Anyways, you can also try this: Get a ESP8266 flash tool and this .bin file: 

> https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/bin/esp_init_data_default_v08.bin

and flash it to 0x7c000 for 512 kB modules (some ESP-01, Sonoff Switch), 0xfc000 for 1 MB modules (most ESP-01), or 0x3fc000 for 4 MB modules (most ESP-12, Wemos D1).

**Comment by spacehuhn** [comment]
What is even the problem here despite blinky LEDs when uploading?

**Comment by spacehuhn** [comment]
No answer... closing this.
