### ISSUE TITLE
An option to change MAC address

### ISSUE THREAD

**Issue by nisc3** [spacehuhn/esp8266_deauther#71]
Add an option to change MAC address.

**Comment by nisc3** [comment]
Is it possible?

**Comment by anudeepND** [comment]
Yup, it is possible. Here's an example:
// Change MAC 
 byte *mac = (byte*)malloc(6);
 WiFi.macAddress(mac);
 mac[0] = 0x19;
 mac[1] = 0x14;
 mac[2] = 0xCA;
 wifi_set_macaddr(STATION_IF, mac);
 mac[2] = 0xCB;
  wifi_set_macaddr(SOFTAP_IF, mac);
  free(mac);
Entire MAC can be changed, here I have changed only a few bytes. 
I haven't tried it with this project though...

**Comment by N0vaPixel** [comment]
It can be useful and would be easy to implement
I'll try to add this feature tonight

**Comment by spacehuhn** [comment]
OK cool one thing Iess on my to-do list ^^

**Comment by joneroy** [comment]
@nisc3 MAC changing is a Good Feature.
