### ISSUE TITLE
Please Help:can't find the AP "pwned" to connect

### ISSUE THREAD

**Issue by suraandcrisaldo** [spacehuhn/esp8266_deauther#710]
After all the steps,I upload the code succeed,but when I plug my ESP8266,I can't find the AP called"pwned",should I do something to the button on the ESP8266 after I plug it?

**Comment by hmpowerbt** [comment]
It's probably a hidden AP. Just add the network and it should work.

**Comment by jLynx** [comment]
Reset everything, empty the EEPROM and start again as given u have missed a step
