### ISSUE TITLE
Attack.cpp:109: error: 'wifi_send_pkt_freedom' was not declared in this scope

### ISSUE THREAD

**Issue by ljubomad** [spacehuhn/esp8266_deauther#715]
Hi. When I compile I do get this error message. Please, what can I do?

Arduino: 1.8.5 (Windows 10), Board: "Generic ESP8266 Module, Serial, 80 MHz, 80MHz, DIO, 115200, 4M (3M SPIFFS), nodemcu"

### if (wifi_send_pkt_freedom(packet, packetSize, 0) == -1) {

                                                  ^

exit status 1
'wifi_send_pkt_freedom' was not declared in this scope

**Comment by spacehuhn** [comment]
>Please, what can I do?

Follow the installation steps https://github.com/spacehuhn/esp8266_deauther#installation
