### ISSUE TITLE
Able to dearth 3G/4g connections?

### ISSUE THREAD

**Issue by EPiCxRIOTZZ** [spacehuhn/esp8266_deauther#716]
Is there a way of being able to deauth 3G/4g LTE connections

**Comment by tobozo** [comment]
yep, usually you switch your phone to plane mode and that does it

**Comment by marek26340** [comment]
Well, now the reality. NO, you can't disconnect all mobile users from the mobile network, not even one single user. The ESP8266 operates in the ISM band, that is 2.4~2.5GHz. The mobile network operates at 800, 850, 900, 1800, 1900, 2100, 2600 MHz. By this I want to explain that mobile and WiFi frequencies are different...

And also, **deauthing or jamming any mobile network is highly illegal!**

**Comment by jLynx** [comment]
That's where you are wrong, my friend who has a mate who's brothers friend has done it with an ESP. He got sent to jail though, but the good news is he broke out recently and is still "dearth"ing all the 3g and 4g networks

**Comment by marek26340** [comment]
But just how?! This is impossible with an ESP8266! wtf

I think that you are lying. I think that this is just a hoax...

**Comment by jLynx** [comment]
Nope fully possible, as I said my sisters friends bothers sons friend has done it

**Comment by spacehuhn** [comment]
Yeah man don't you believe jlynx sisters friends brothers sons friend? He has done it!

**Comment by spacehuhn** [comment]
![grafik](https://user-images.githubusercontent.com/3826044/37056191-eeab9686-2183-11e8-8aeb-55c277a1b734.png)

**Comment by marek26340** [comment]
omg okay... then what's the code that I have to upload to my ESP? Or what do I have to do?
I'd really like to deauth the 4G networks too! I would really like to hear the fear from all the 300 kids at our school that the internet is not working! xD that would be really funny lol

**Comment by deantonious** [comment]
Once you open the corner, look for the smd pad inside and solder the 3/4G antenna to it using some hot air or a thin soldering tip (works on the ESP32 too):
 
![1](https://user-images.githubusercontent.com/6786044/37059549-0daa8952-218e-11e8-8a61-9d8ab0a62bc5.jpg)
![2](https://user-images.githubusercontent.com/6786044/37059559-12bfbc32-218e-11e8-9202-03aee4553d70.jpg)

Hope this helps you :)

**Comment by r0073rr0r** [comment]
troll to the perfection :D

**Comment by jLynx** [comment]
@marek26340  let me know if you need any help with setting it up. But please make a nicer hole than @deantonious . Yes his works, but doesnt look nice at all to the eye

**Comment by marek26340** [comment]
ehm... it works on an esp32 too?

**Comment by jLynx** [comment]
Yeah it does which is many people don't realise

**Comment by Schokobecher** [comment]
I can vouch for this working!
