### ISSUE TITLE
Powering esp8266 nodemcu with 9v through vin gives a shocking result!

### ISSUE THREAD

**Issue by Booooozo** [spacehuhn/esp8266_deauther#717]
So I have an amica esp8266 nodemcu which I flashed the deauther program on. I love it and it works fine. But I found out that powering the nodemcu through vin port with a 9v battery sends deauthentication packets around my whole neighborhood. I tested this by simply browsing on my iPad and then powering up the nodemcu through vin and immediately my iPad disconnected from my WiFi and the same happened when I was using a mobile hotspot. It’s really and also my nodemcu led does not light up nor does the nodemcu broadcast its network when this is happening. Do you guys experience this same thing?

**Comment by spacehuhn** [comment]
Black Magic

**Comment by kaosproject** [comment]
Vin and G ?

**Comment by Booooozo** [comment]
Yes no external antenna I connected it to VIN and G

**Comment by abdullahseba** [comment]
Yeah its simple really. `9V x 20dVm = 180VdBm` So that means you get more packets per meter which means there is more for each device. `180VdBm ÷ 1000mm = 0.18 packets rms` while with 5v all you get is 0.04 `40VdBm ÷ 1000mm = 0.04 packets rms`.

**Comment by tobozo** [comment]
neat ! just add a pot

**Comment by marek26340** [comment]
@abdullahseba wtf I don't understand.................

**Comment by digmorepaka** [comment]
@marek26340 quick mafs

**Comment by abdullahseba** [comment]
^^

**Comment by marek26340** [comment]
quick, but weird mafs

**Comment by spacehuhn** [comment]
Was fun but closing this now.
