### ISSUE TITLE
What button do I click to auto deauth all routers in range?

### ISSUE THREAD

**Issue by Booooozo** [spacehuhn/esp8266_deauther#719]
So I’ve heard that by clicking the reset or flash button on my amica esp8266 nodemcu will deauth all routers in range i have tried it but it doesn’t work. Is this true that by clicking the reset or flash button will deauth everyone or does my board not work with this feature?

Source from where I heard it: An open issue in your project which says something like “Stuck on Starting....”

**Comment by spacehuhn** [comment]
I heared that if you leave it in water for a minute it will actually start jamming Cabrios frequentiert  due to the freed electrons on the metal finish.

**Comment by spacehuhn** [comment]
sorry wrong button

**Comment by Booooozo** [comment]
Nice joke. Haha

**Comment by andixum** [comment]
put it in your toaster to warm up the signal a bit. That should make it uber powerful and will deauth everything.

**Comment by Booooozo** [comment]
Hahahahaha!
