### ISSUE TITLE
Beacon list gone after restart

### ISSUE THREAD

**Issue by EmiSchurr** [spacehuhn/esp8266_deauther#722]
### Hardware/Flashing:
Board: NodeMCU ESP8266 AI-Thinker
Using OLED:   NO
Using WebServer: YES
Using Serial: NO
Installation mode:  binary
Code/binary version: 1.6
Flash size:  1M
Flash method: NodeMCU-flasher						
Flash Frequency:	40Mhz
Upload Speed: 9600
Powered by: 5V

### Description:
Beacon list disappears after rebooting device. Beacons still appear when starting 'attack' and can still be added but not individually deleted

**Comment by XAS-712** [comment]
The list has been saved in memory. If you restart the board, any data in memory will lost.

**Comment by marek26340** [comment]
If you want the ESP to remember the beacon list, there is a button to save the list at the bottom of the page.

**Comment by EmiSchurr** [comment]
It has eben saved because upon starting the attack all beacons are shown by every device in range. Adding an Beacon also works, just the list on the web page isn’t shown.

**Comment by marek26340** [comment]
Does the serial monitor tell us anything useful? (Connect to pc, make a beacon list, save it, reset esp, try to read the beacon list)

**Comment by spacehuhn** [comment]
You have to click save. Otherwise it won't remember them. The list is always in the RAM but if you don't save them before restart, they will get lost.
