### ISSUE TITLE
Not work anymore

### ISSUE THREAD

**Issue by Cyberdade** [spacehuhn/esp8266_deauther#726]
### Hardware/Flashing:
Board:				ESP8266 dev module
Using OLED:   NO
Using WebServer: probably not
Using Serial: Probably not
Installation mode:  binary
Code/binary version: Probably 1.5
Flash size:  Probably 1M
Flash method:							esptool
Flash Frequency:					40Mhz
Upload Speed:						115200
Powered by:  Battery

### Description:

Hi, I'm again here.
I found a problem:
When I flash my esp it work, but when I go to the settings and change the Mac to 00:00:00:00:00:00
I can't connect to my esp and if I try to reboot/reflash it I can't find it.
I gave 5€ to the Chineses :'-(
Can anyone help me?

**Comment by hmpowerbt** [comment]
Get you board and power it on... then hold the rst button for atleast 5-10 seconds. This will reset the module and erase everything off of. Then reflash the deauther and everything should be back to normal.. hopefully I helped. 😁

**Comment by hmpowerbt** [comment]
Get you board and power it on... then hold the rst button for atleast 5-10 seconds. This will reset the module and erase everything off of it. Then reflash the deauther and everything should be back to normal.. hopefully I helped. 😁

**Comment by Cyberdade** [comment]
Still not work :-(

**Comment by spacehuhn** [comment]
The mac address you gave it is invalid.  
My tip: don't play around with settings if you don't know how to fix it when it breaks!

Reflash your device or see FAQ on how to reset: https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ

**Comment by Cyberdade** [comment]
Thanks again, it work!
