### ISSUE TITLE
COM port (Solution)

### ISSUE THREAD

**Issue by hmpowerbt** [spacehuhn/esp8266_deauther#727]
This is not a problem. This is a "Fix" for the COM port issue.                                             
              

- Download these drivers for your Version of Windows/OSx/linux etc.

To download these go to...

https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by hmpowerbt** [comment]
Stupid Autocorrect

**Comment by Pow674** [comment]
THANK YOUUUUUU SO MUCHHH!!!!

**Comment by hmpowerbt** [comment]
Ok...
