### ISSUE TITLE
Error finding COM1

### ISSUE THREAD

**Issue by Lexander01** [spacehuhn/esp8266_deauther#730]
When uploading the Arduino code into the NodeMCU board, it gives me the following error messages:

Arduino: 1.8.5 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

Archiving built core (caching) in: /var/folders/5d/vs67dq2x3gb6mxd0gl_mrk6c0000gn/T/arduino_cache_131691/core/core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,UploadTool_esptool,UploadSpeed_115200,FlashSize_4M3M_19866a75959d55d6c58af4338ae95cfe.a
Sketch uses 544696 bytes (52%) of program storage space. Maximum is 1044464 bytes.
Global variables use 55522 bytes (67%) of dynamic memory, leaving 26398 bytes for local variables. Maximum is 81920 bytes.
error: cannot access COM1

error: espcomm_open failed
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Can anyone help me?

**Comment by spacehuhn** [comment]
Select the right com port. You might need to install additional drivers (ch340 or cp2102 usually).
Or you have a look at the 26 other issues about this: 
https://github.com/spacehuhn/esp8266_deauther/search?p=1&q=com+port&type=Issues&utf8=%E2%9C%93
