### ISSUE TITLE
Add Version Nummer in the esp8266_deauther.ino

### ISSUE THREAD

**Issue by Dtrieb** [spacehuhn/esp8266_deauther#732]
Please add the Version Nummer in the head of the esp8266_deauther.ino file:

       Copyright (c) 2017 Stefan Kremser
              github.com/spacehuhn
                  Version x.xx

**Comment by spacehuhn** [comment]
maybe the source code is version fluid ;)

**Comment by jLynx** [comment]
DID YOU JUST ASSUME IT'S VERSION NUMBER?!?!!! 😡

**Comment by killergeek** [comment]
how about the function getversion();
