### ISSUE TITLE
Deauth doesn't work 

### ISSUE THREAD

**Issue by avanguard6** [spacehuhn/esp8266_deauther#733]
Deauth attack suddenly stopped working. Deauth shows 20pkt/s nothing happens. But other attacks are working. I have purchased new one but it also doesn't work.
### Hardware/Flashing:
Board: ESP8266 https://ru.aliexpress.com/item/1pcs-Wireless-module-NodeMcu-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266-CP2102-with-pcb/32801961146.html?aff_platform=link-c-tool&cpt=1521128306960&sk=YFAI6ub&aff_trace_key=07cc03778eee49f4b2db21a203a65812-1521128306960-03437-YFAI6ub&terminal_id=50d88890d2144c09ac426b2f14e41c48
Using OLED:   no
Using WebServer: yES
Installation mode:  binary
Code/binary version: 1.6

**Comment by tobozo** [comment]
what device are you trying to deauth ? maybe it isn't vulnerable to deauth attacks

**Comment by avanguard6** [comment]
It's my home wifi. I tried to deauth it later, before it stopped vorking, and it was success

**Comment by tobozo** [comment]
you must select your AP first, then launch the attack
also everything is logged, so depending on how you initially flashed it, you may have to re-flash the deauther from time to time as things will eventually get overwritten and messed up :p

**Comment by avanguard6** [comment]
I have reflashed my deauther and noticed that deauth works only for my phone and Ipad but on pc networks works without any difficulties. Another pc also works normally, but earlier the same computers lost access to the Internet after activation.
From time to time i see  "error loading attackInfo.json" on the top.
I really need to make it working on pcs

**Comment by spacehuhn** [comment]
Not every device is vulnerable and you can loose connection when starting the attack. That's why you get the error. It says it on th website.
