### ISSUE TITLE
esp8266

### ISSUE THREAD

**Issue by masterofdeather** [spacehuhn/esp8266_deauther#735]
Need help!
i uploadet one time the Driver on arduino and it worked. Then i forgot my Password on it. then i uploadet misakeli agan the Driver but it dosent worked. Now noting is working and i get an error massage every time i do the same on step 1(download the Driver). 
can somone help my two fix my esp8266. so i cn run it like it does?

**Comment by spacehuhn** [comment]
Nice try "masterofdeather"

**Comment by masterofdeather** [comment]
? What @spacehuhn

**Comment by spacehuhn** [comment]
Yo if you shit post on purpose, you have to put more efford into it!
But maybe this helps: http://bfy.tw/Mjt

**Comment by deantonious** [comment]
Please wait until next EIF for a better answer. Thanks.

**Comment by tobozo** [comment]
~~I want an error massage too
