### ISSUE TITLE
error loading attackInfo.json

### ISSUE THREAD

**Issue by nymda** [spacehuhn/esp8266_deauther#737]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware/Flashing:
Board:Tindie OLED
Using OLED: YES
Using WebServer: YES
Using Serial: NO
Installation mode: preinstalled
Code/binary version: unknown
Flash size:  unknown
Flash method:	unknown
Flash Frequency: unknown
Upload Speed: unknown
Powered by:  USB

### Description:
upon starting the deauth attack i get the error "error loading attackInfo.json" in the window and the attack does not start. I then need to restart the board to use it again. 

i am using a board i brought off tindie, specifically the v3 oled board. 

everything else seems to work fine

What you're expecting:  deauth attack
What you get instead: error loading attackInfo.json

### Debug Messages:
cannot get this currently, will update whenever i can.

**Comment by tobozo** [comment]
you need to select an AP first, also depending on the channel you're attacking, you may get disconnected every time the ESP switches channels.
