### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by twei21** [spacehuhn/esp8266_deauther#738]
i have everything ready and it is working. 
but i cannot attack any windows PC. 
it works on my android phone, mac, ps4 and iphone but not PC

**Comment by spacehuhn** [comment]
The deauth attack will, if the connection **is vulnerable**, disconnect the devices from the network. Because the attack is running constantly, the devices will be disconnected again and again. Depending on the network, that can either block a connection or slow it down.
