### ISSUE TITLE
Where is the sdk_fix?

### ISSUE THREAD

**Issue by godzillamesel** [spacehuhn/esp8266_deauther#742]
Can't find it o.O

**Comment by ChandraOrbit** [comment]
Read [THIS](https://github.com/spacehuhn/esp8266_deauther/issues/740) and https://github.com/spacehuhn/esp8266_deauther/issues/739 and [THIS](https://github.com/spacehuhn/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide)

**Comment by spacehuhn** [comment]
Actually a look at the wiki should be enough: https://github.com/spacehuhn/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide
