### ISSUE TITLE
charging current

### ISSUE THREAD

**Issue by Basti77** [spacehuhn/esp8266_deauther#744]
Is the charging current intentionally set to 100mA?
How can I change this?
Loading a LiOn cell takes so long.

**Comment by spacehuhn** [comment]
You're probably talking about the DSTIKE boards (?).
I don't think that hehy have a 100mA limit but I'm not sure. I rarely charge batteries over them.
Ping @lspoplove

**Comment by Basti77** [comment]
JA genau. DSTIKE 
gehört die frage hier nicht hin?

**Comment by tobozo** [comment]
Deauther issues belong here, this is more of a question related to a product specification, which the vendor (@lspoplove) can answer.

**Comment by Phoenix1747** [comment]
I didn't observe the battery charging myself, but maybe your battery was overdischarged and needed to be 'revived' slowly.

**Comment by Basti77** [comment]
I'm a model aviator and have a lot to do with batteries.
I have never experienced such behavior.
I have a test load on my JUNSI charger. the cell is OK.
The battery was only used on the Dstrike board and that has a deep discharge protection?

**Comment by tobozo** [comment]
please post pics of your model and a link to the product page

**Comment by Phoenix1747** [comment]
Strange, have you observed this behaviour for the whole time it took the cell to charge?

**Comment by lspoplove** [comment]
Hello, I use IP5306 solution charging current is 2A.
Your battery maybe discharged too much or not avaliable again.
You have to wait when trickle charge process finish then it will reach 2A

**Comment by Basti77** [comment]
My Hardware.
![dsc_0037](https://user-images.githubusercontent.com/8112783/37899732-a41b79d8-30ec-11e8-9ab1-643630821d06.JPG)
![dsc_0038](https://user-images.githubusercontent.com/8112783/37899735-a4389518-30ec-11e8-9520-8f95d8e1342f.JPG)

**Comment by tobozo** [comment]
I have this model too and charge the battery from a separate charger, since you can't turn the deauther off while it's charging, the OLED stays on and the charge speed isn't ideal.

**Comment by spacehuhn** [comment]
The version 2 board might not have a high current charging circuit, I also charge them with a seperate charger. The new deauther boards come with better charging chips.
I hope we answered all the questions.

**Comment by Phoenix1747** [comment]
@spacehuhn Are there any detailed hardware specs available for the deauther boards?

**Comment by tobozo** [comment]
closing this as solved

**Comment by rayzzzor** [comment]
Hey everybody, I have the deauther Dstrike SE. I will charge it and every light is like it should be  but when I try to use it without charging it will not turn on anymore. Somebody can help pls? I got the watch yesterday
![Uploading image.jpg…]()
