### ISSUE TITLE
ESP8266 with hidden SSID

### ISSUE THREAD

**Issue by anudeepND** [spacehuhn/esp8266_deauther#75]
Is it still possible to deauthenticate with hidden SSID. The NodeMCU doesn't broadcast it's SSID.
Here's the code:
`void softAP(const char* ssid, const char* passphrase, int channel = 1, int ssid_hidden = 0); `

**Comment by anudeepND** [comment]
I don't have a esp8266 right now, can anyone please confirm that it works or not?

**Comment by joneroy** [comment]
@anudeepND Ya it's possible this feature is recently implemented to testing branch to esp8266_deauther

**Comment by anudeepND** [comment]
I haven't been able to try it out.
It is about hiding our SSID, not be confused with deauthenticating hidden SSID of victim...

**Comment by joneroy** [comment]
@anudeepND what mean of

> It is about hiding our SSID

**Comment by joneroy** [comment]
https://github.com/spacehuhn/esp8266_deauther/tree/testing

**Comment by anudeepND** [comment]
Consider like this, I have a Nodemcu with WiFi name as 'deauther', so when I turn my phone's WiFi on, I can see 'deauther' or anyone with WiFi can see the name. 
It is like not broadcasting the name 'deauther'

**Comment by joneroy** [comment]
This feature is recently implemented to testing branch to esp8266_deauther

**Comment by N0vaPixel** [comment]
You doesn't need the ssid to communicate with AP..

**Comment by joneroy** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26072408/23580421/805789e2-0127-11e7-83a8-6e8174cfebf2.png)

**Comment by joneroy** [comment]
@anudeepND 

## **I hope you find your ansr so close this issue.**

**Comment by anudeepND** [comment]
Apologies. As joneroy said, it is already included in testing branch. Sorry
