### ISSUE TITLE
Deauther doesnt work

### ISSUE THREAD

**Issue by jeremey2002** [spacehuhn/esp8266_deauther#757]
Hii i have a question everything works fine but wen i start deauther it doesnt work
When i start it i says he send packages but my wifi doesnt go of or slower
Pleas help me im.using esp8266 and the latest version deauther

**Comment by digmorepaka** [comment]
hmm weird, i guess deauthentication packets are suposed to slow the wifi down

**Comment by Phoenix1747** [comment]
@digmorepaka They are not intended to slow down the wifi, but to get all the connected devices to disconnect.
@jeremey2002 Maybe you need to increase the packet rate?

**Comment by digmorepaka** [comment]
i know

**Comment by tobozo** [comment]
@Phoenix1747 on some iPhones and notebooks there are situations where the deauthing works but you can only feel a slowdown because the device can reconnect very fast, and the OS doesn't care.

**Comment by Phoenix1747** [comment]
@tobozo Yeah, right but that's only like a symptom of the deauther ^^

**Comment by sudipto3331** [comment]
I have the same problem here.
All are working fine. But after pressing start button packets are not being sent.

**Comment by spacehuhn** [comment]
Have you clicked the reload button to refresh the displayed packet rate?

**Comment by jeremey2002** [comment]
How you increase the packet rate?
Because on my old tablet its disconnect  the other devices not?

**Comment by Lilwiggy** [comment]
If you put it in something metallic like a pringles can the range and lackey rate will sky rocket

**Comment by Lilwiggy** [comment]
Packet rate*

**Comment by Phoenix1747** [comment]
@Lilwiggy You can log into the web ui and change the packet rate in the settings.

**Comment by sudipto3331** [comment]
@spacehuhn Yeah. I had done it already. But no packets are being sent. As a result targeted wifi's clients aren't disconnecting. Even I have increased the packets rate. But still it isn't Working. It is noted that I'am using NodeMcu. I was using deauther V1.6 previously.

**Comment by Phoenix1747** [comment]
@sudipto3331 Just out of curiousity, what specific packet rate are you using?

**Comment by sudipto3331** [comment]
@Phoenix1747 Now I am using the value 20

**Comment by spacehuhn** [comment]
Without the serial output, we can only speculare why that is.

**Comment by sudipto3331** [comment]
With speculating, give some solution

**Comment by tobozo** [comment]
With solution, close this issue ?
