### ISSUE TITLE
How to fix it ?

### ISSUE THREAD

**Issue by tfujdiler** [spacehuhn/esp8266_deauther#790]
Hi, I found smal bug in APs when SSID it's too long and does not contain spaces btn,
the layout and size of the rest of the page change.
Expo_InternetDomowyM10/33 this name is one string of characters in addition, it does not contain a dash.
You have an idea how to change it ?
![blad](https://user-images.githubusercontent.com/37963657/38433327-b65c3d6c-39ca-11e8-8df0-00e742f8d0e2.jpg)

**Comment by tobozo** [comment]
![CSS is awesome](https://ih1.redbubble.net/image.168622440.1528/flat,800x800,070,f.jpg)

**Comment by tfujdiler** [comment]
Changing the text on the button is a last resort :)
sooner I will go to the indicated address M18 / 33 and try to log in to the neighbor router 
maybe "admin admin" work :) then i can change his SSID :)
If this option does not work I will knock on the door but i use the hammer :)
and I will ask why it has such a long network name ;)

**Comment by tobozo** [comment]
technically a SSID can go up to 32 chars so the UI should be able to display the complete string, or at least not break the layout when it's overflowed.

[Actually it's already half implemented](https://github.com/spacehuhn/esp8266_deauther/blob/master/web_interface/style.css#L238), the missing part is in the `table-layout: fixed;` in the [table declaration](https://github.com/spacehuhn/esp8266_deauther/blob/master/web_interface/style.css#L232):

    table {
        table-layout: fixed;
        width: 100%;
        min-width: 400px;
        margin-bottom: 2em;
    }

can you try that and see if it fixes the word-break problem ?

if it can save the life of your arrogant neighbour's router it's worth a try !

**Comment by tfujdiler** [comment]
I was close I changed the width to 80%, 
![33](https://user-images.githubusercontent.com/37963657/38442663-4eb05724-39e9-11e8-85ad-cc33bd4e41f0.jpg)
first impression great the table has decreased and the neighbor's network has disappeared :) but when I refreshed the list of networks the table was again on the entire width of the screen and the M10 / 33 network appeared :( 
I have the impression that the length of the network name forces the width of the table
I will try use your idea but file style.css is different in the deauther 1.6 version

**Comment by tfujdiler** [comment]
I change my mind :) I will not be buried in style.css I suffered a lot of failures for one day,
so time to be bad :)
will direct all available power esp into this network with a long name,
maybe it will trigger self-ignition of the router ;)
and the problem will be solved by the flames :) anyway thanks for the help :+1: 
I'm glad that the support works :)

**Comment by tfujdiler** [comment]
I think the topic can be moved to closed ones ;)

![ols](https://user-images.githubusercontent.com/37963657/38444148-82c887ca-39ee-11e8-9d19-a6ab2de4e320.jpg)
