### ISSUE TITLE
no continuous scanning mode

### ISSUE THREAD

**Issue by ErfanDL** [spacehuhn/esp8266_deauther#799]
Hi. where is continuous scanning mode in version 2.0 ? how to enable ?

thanks

**Comment by spacehuhn** [comment]
That is possible over the serial interface, see the reference: https://github.com/spacehuhn/esp8266_deauther/blob/master/serialcommands.md

**Comment by spacehuhn** [comment]
`set led false` and then
`save settings` and restart the device

**Comment by ErfanDL** [comment]
@spacehuhn thanks the led is disabled.  I connecting neopixel rgb to pin SD2 but nothing happen and cant turning on.

**Comment by tobozo** [comment]
@ErfanDL did you manage to get your neopixel ring to turn on?

**Comment by ErfanDL** [comment]
@tobozo 
No. neopixel cannot working. I have a problem with compiling from source. after compile and modifying code to working with neopixel the board cannot boot and stock at bootloop.
