### ISSUE TITLE
Blinking onboard LED while attack is going on

### ISSUE THREAD

**Issue by nisc3** [spacehuhn/esp8266_deauther#80]
Add a feature to blink onboard LED on esp8266 while attack is going on. The les can be controlled by GPIO,
` int pin = 1;  //GPIO1
PIN_FUNC_SELECT(PERIPHS_IO_MUX_U0TXD_U, FUNC_GPIO1); 
gpio_output_set(0, 0, 1 << pin, 0); 
gpio_output_set(1 << pin, 0, 0, 0); // set pin high
gpio_output_set(0, 1 << pin, 0, 0); // set pin low
`
An option to turn off this on web interface will be nice.

**Comment by joneroy** [comment]
@N0vaPixel #79
