### ISSUE TITLE
Error loading atackinfo.json

### ISSUE THREAD

**Issue by xxskater** [spacehuhn/esp8266_deauther#804]
the ssids wasn't showing and i cant attack my router any help

**Comment by deantonious** [comment]
Bonvenon al la EIF. Bonvolu RTFM kaj ne afiŝu generojn kaj strangan demandojn. Dankon :D

**Comment by tobozo** [comment]
??? Ĝi diras, ke mi aldonis kaj forigis la etikedon, sed mi forigis kaj aldonis ĝin

**Comment by spacehuhn** [comment]
stranga 😕

**Comment by deantonious** [comment]
Maloftaj aferoj okazas en maloftaj afiŝoj ¯\_(ツ)_/¯

**Comment by tobozo** [comment]
closing this as failure to comply to the latest Esperanto Friday, feel free to reopen if you have more Esperanto to speak, but only do it on friday!

**Comment by spacehuhn** [comment]
![img-20180309-wa0000](https://user-images.githubusercontent.com/3826044/39081055-ddb15232-453a-11e8-883e-1099b7b12011.jpg)
