### ISSUE TITLE
Deauthentication Attack Using Lua or Micropython Script

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#81]
It's possible wifi deauthentication attack using lua script.

**Comment by H1ghTech** [comment]
Yup it's possible but very inefficient

**Comment by joneroy** [comment]
Why inefficient ?

**Comment by H1ghTech** [comment]
Cause it doesn't attack very fast.
,You can't kick anyone out because it's to slow

**Comment by joneroy** [comment]
@H1ghTech and NodeMcu frimware it's a elua based frimware, 

> NodeMcu

Advanced API for hardware IO, which can dramatically reduce the redundant work for configuring and manipulating hardware. Code like arduino, but interactively in Lua script.

**Comment by joneroy** [comment]
@H1ghTech and What about Micropython now it's available for esp8266

**Comment by joneroy** [comment]
@H1ghTech 

> Cause it doesn't attack very fast.
You can't kick anyone out because it's to slow.

I think it's impossible with lua but now no esp8266_deauther source code available.

**Comment by H1ghTech** [comment]
I think micropython would work great

**Comment by joneroy** [comment]
@H1ghTech i think micropython better then lua

**Comment by H1ghTech** [comment]
That's what I just said lol

**Comment by joneroy** [comment]
@H1ghTech You right :100:

**Comment by spacehuhn** [comment]
@joneroy stop posting useless messages like this one in every damn issue! it's really annoying and I'll delete them.

**Comment by spacehuhn** [comment]
I don't meant the issue, I meant your messages like this one:

> @H1ghTech You right 💯

**Comment by ebad84** [comment]
is there any way to do it on micropython?
