### ISSUE TITLE
Whitelist registered MAC address and Deauth Everyone Else. 

### ISSUE THREAD

**Issue by darkprince1337** [spacehuhn/esp8266_deauther#810]
Hello.
I'm working on a project on WIFI security, i have to debar/deauth unauthorized users from our WIFI network.
I've created captive portal with radius authentication on a raspberrypi 3. It uses MAC auth but it's not reliable in terms of security.
So i want to add NodeMCU ESP8266 module to deauth users which are not registered (their MAC address) to my database. 
Can you help me out?

**Comment by spacehuhn** [comment]
Please read this:
https://github.com/spacehuhn/esp8266_deauther/wiki/Serial#deauth-all

**Comment by marek26340** [comment]
You don't need to use a deauther to just congest the 2.4GHz band more than it's really necessary. If you will need to make a whitelist of devices that can be on the network and then block everyone else, then use the MAC filtering function of the router. 
Why should I/you pay for a feature that's free and included in one device? :D
At least I hope that you didn't buy a very simple and cheap router without any features *sigh*

**Comment by darkprince1337** [comment]
Thanks for reply.
I'm using ESP8266 because it's an Hardware based project.

Can i e-mail you my problem statement? have a look if you got some time. It will be really helpful for me to discuss it with you.

**Comment by marek26340** [comment]
In most cases, you need some software to be able to work with some hardware. I still don't understand your project, so, if you will send some more details, it would be helpful, but not for fixing the issue... But how can you get my email without me sharing it on the entire internet (e.g. writing email here)?

**Comment by tobozo** [comment]
closing this as the discussion moved to another channel, don't forget to share the results of your experiments :+1:

**Comment by SansarSah** [comment]
@darkprince1337  did you find the solution?
