### ISSUE TITLE
Can't find CTHULHU mode

### ISSUE THREAD

**Issue by ntoenis** [spacehuhn/esp8266_deauther#811]
Trying to use what I assume is importing ssid info for beacon attacks using the new CTHULHU mode, but can't find where in the code you can add it or where it is in the interface.

**Comment by tobozo** [comment]
It was a pun for april 1st 🐰 🥚 so it's not exactly implemented, the ssid.json is overwritten after the first scan anyway.

Fortunately for all of us, R'lyeh doors will stay closed and CTHULHU🦑 will keep dreaming 😴
