### ISSUE TITLE
Push ssid list to deauther

### ISSUE THREAD

**Issue by ntoenis** [spacehuhn/esp8266_deauther#812]
Really wish there was a method to save and load remote files to the device whether over wifi through through the portal or through the serial port.

**Comment by tobozo** [comment]
you're not [far from it](https://github.com/spacehuhn/esp8266_deauther/blob/49866e0ccd7b37eaf6f53651e1ec226bde29f61c/esp8266_deauther/wifi.h#L159)

**Comment by tobozo** [comment]
closing this as already implemented but not activated
