### ISSUE TITLE
No COM’s are showing up in the NodeMCU-flasher

### ISSUE THREAD

**Issue by crazyguy830** [spacehuhn/esp8266_deauther#816]
I started setting up my deauther but I ran into this problem where no COM’s were showing up. I switched cables and that did nothing. I want through the whole process again to see if I did something wrong but I couldn’t find anything. So, I am just asking for help to solve this problem

**Comment by tobozo** [comment]
probably a missing driver, hard to say with so few information

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/Installation#drivers-and-com-port

https://github.com/spacehuhn/esp8266_deauther/wiki/Troubleshooting#espcom-error
