### ISSUE TITLE
2.0.0 wifi client

### ISSUE THREAD

**Issue by bilogic** [spacehuhn/esp8266_deauther#818]
Hi,

Does 2.0.0 have wifi client capabilities? Thank you.

**Comment by spacehuhn** [comment]
not yet, no :(

**Comment by bilogic** [comment]
I see.. it worked in earlier versions of deauther. what I did was to:

1. flash wi-pwn v9.0 and enable the wifi client
2. flash deauther
3. wifi client remains functional

but this was no longer possible with 2.0.0

**Comment by tobozo** [comment]
[looking](https://github.com/samdenty99/Wi-PWN/blob/40d137e43036c7f0765c3cfbdb28d7c9c3134031/arduino/Wi-PWN/Wi-PWN.ino#L165) at the [differences](https://github.com/spacehuhn/esp8266_deauther/blob/master/esp8266_deauther/wifi.h#L256) that shouldn't be hard to add
@spacehuhn are you on it or do you need a PR?

**Comment by spacehuhn** [comment]
This isn't a priority for me so it has to wait.
It requires adding additional settings and commands. Not diffucult but annoying to add. 

For a quick fix, you could just hard code the connection in the setup() function and compile it. I'm sure there are some examples on how to connect the esp8266 to an access point.

**Comment by tobozo** [comment]
flagging this as [wontfix] *but* keeping the door open to a WiFi client configurator loaded in the context of the [sd-updatable](https://github.com/spacehuhn/esp8266_deauther/tree/sd-updatable) branch

**Comment by spacehuhn** [comment]
Closing the door now, sorry. I don't have the time anymore for the changes that would be required by such a feature. Everyone is of course welcome to add the feature themselves.
