### ISSUE TITLE
Access deauther from raspberrypi?

### ISSUE THREAD

**Issue by darkprince1337** [spacehuhn/esp8266_deauther#821]
Hello!
Can we access deauther from raspberry pi via MQTT server or something?

i'm trying to make a wireless intrusion prevention system (WIPS), which detects wireless attacks and block/deauth them and this is a hardware based project.
I'm able to detect wireless attack through suricata (Opensource IDS) which is installed in raspberry pi. The problem is , how to send input from raspberrypi to nodemcu to block/deauth the attacker?

**Comment by tobozo** [comment]
You can easily achieve that using [this hat](https://shop.pimoroni.com/products/esp8266-phat), you'll have to add you own buttons and OLED and talk to the deauther through the serial port,

**Comment by tobozo** [comment]
@darkprince1337 did you manage to talk to the deauther from your rpi? If so can we close this issue?

**Comment by tobozo** [comment]
closing this as inactive, please reopen when something new comes up
