### ISSUE TITLE
ArduinoJson.h: No such file or directory

### ISSUE THREAD

**Issue by legendaryvampire51** [spacehuhn/esp8266_deauther#822]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```
In file included from /Users/ksrikanthreddy/Downloads/esp8266_deauther-2.1.4/esp8266_deauther/esp8266_deauther.ino:17:0:
sketch/functions.h:5:25: fatal error: ArduinoJson.h: No such file or directory
 #include "ArduinoJson.h"
                         ^
compilation terminated.
exit status 1
Error compiling for board Generic ESP8266 Module.
```

**Comment by tobozo** [comment]
because [reasons](https://github.com/spacehuhn/esp8266_deauther/search?q=ArduinoJson.h%3A+No+such+file+or+directory&type=Issues)
