### ISSUE TITLE
Error when compiling deauther 1.4 version.

### ISSUE THREAD

**Issue by Booooozo** [spacehuhn/esp8266_deauther#828]
So I downloaded the deauther 1.6 version to make some major changes . But when I compile without making any changes with  Arduino it throws back this error which I can't seem to fix.

```In file included from /Users/macbook/Documents/Arduino/libraries/esp8266-oled-ssd1306-master/src/SSD1306Wire.h:34:0,
                 from /Users/macbook/Documents/Arduino/libraries/esp8266-oled-ssd1306-master/src/SSD1306.h:33,
                 from /Users/macbook/Downloads/esp8266_deauther-v.1.6/esp8266_deauther/esp8266_deauther.ino:28:
/Users/macbook/Documents/Arduino/libraries/esp8266-oled-ssd1306-master/src/OLEDDisplay.h:201:10: error:   initializing argument 1 of 'void OLEDDisplay::setFont(const uint8_t*)' [-fpermissive]
     void setFont(const uint8_t *fontData);
          ^
exit status 1
invalid conversion from 'const char*' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]






I even have all the latest libraries installed. Any ideas on how to fix this?

Thanks!

**Comment by spacehuhn** [comment]
You need a different OLED library version: https://github.com/ThingPulse/esp8266-oled-ssd1306/releases

However, I can't tell you out of the head which version you need because you're using the 1.6 Deauther.

**Comment by Booooozo** [comment]
Yeah sorry I ma actually using the 1.6 version not 1.4

**Comment by Booooozo** [comment]
@spacehuhn Which version of the library should I use?

**Comment by Booooozo** [comment]
Well I am lucky I just installed the 3.2.4 version of the library and it compiled with no problems. Thanks!

**Comment by tobozo** [comment]
1.6 was probably referring to the hardware version rather than the code version?

**Comment by Booooozo** [comment]
@tobozo I was referring version 1.6 of your deauther program
