### ISSUE TITLE
Bug with web server.

### ISSUE THREAD

**Issue by N0vaPixel** [spacehuhn/esp8266_deauther#83]
There is a memory probelm. I noticed if a web page size around 7000 bytes, when you start an attack and try to load the page, the web server will return a blank page.

**Comment by joneroy** [comment]
@N0vaPixel 

> the web server will return a blank page

This is error 404 blank page

**Comment by N0vaPixel** [comment]
@joneroy  No, nothing is returned, this mean no HTTP header and body. It's not an error 404

**Comment by joneroy** [comment]
@N0vaPixel 

I think it's a bug

**Comment by N0vaPixel** [comment]
I minfied all the web pages and the "bug" disapeared. This prove that the memory usage is at stake.

**Comment by spacehuhn** [comment]
Yeah that's not really a bug, at some point you can't implement new things because the RAM is full. Do you use my minifier.html in the htmlfiles folder? I minify them first and then turn them into bytes.

**Comment by N0vaPixel** [comment]
@spacehuhn Yes it's really useful, i decided to use it.

**Comment by joneroy** [comment]
@N0vaPixel 

minifier.html is very useful for update the html data.h

**Comment by N0vaPixel** [comment]
Yes i know, i wouldn't be able to update data without byte-ify 😸
