### ISSUE TITLE
Help - <esp8266>.h

### ISSUE THREAD

**Issue by jpicard01** [spacehuhn/esp8266_deauther#831]
When i go to upload the code it keeps saying,

`<esp8266>.h can't be found `

I'm not sure what is wrong. 

Thanks

**Comment by tobozo** [comment]
I edited your comment as some part of it was misinterpreted as HTML.

Please take the time to read the [wiki](https://github.com/spacehuhn/esp8266_deauther/wiki) there's a link to a video with a tutorial too.

Closing this as not a deauther issue.
