### ISSUE TITLE
No Access Point is created on startup

### ISSUE THREAD

**Issue by SyncedCyberSoul** [spacehuhn/esp8266_deauther#832]
I have two versions of the board. The larger one, and the small compact one. I believe both are the 4mb modules. I have flashed the board with arduino, and upon plugging it into a power bank, it blinks both LEDs twice, once normally and then again very faintly. 
Afterwards there is no result. No wifi network is being broadcasted.
I've tried multiple settings in arduino. nothing works
Please help lmao 
<edit>
the wifi chip also heats up after a while of being plugged in

**Comment by SyncedCyberSoul** [comment]
Yes, I typed status and tested chicken and indeed got serial output from the chip. 
It just doesn’t do da wifi :(

It’s a very nice chicken by the way.

**Comment by spacehuhn** [comment]
Have you tried flashing the reset sketch?
https://github.com/spacehuhn/esp8266_deauther/tree/master/Reset_Sketch

**Comment by ifengchao** [comment]
I got the same problem...
Here's the log from com6:

Mounting SPIFFS...OK
Switched to Channel 1
Settings loaded from /settings.json
Settings saved in /settings.json
Device names loaded from /names.json
SSIDs loaded from /ssids.json
Scan results saved in /scan.json
Serial interface enabled
Started AP
[WiFi] Path: '/web', Mode: 'AP', SSID: 'pwned', password: 'deauther', channel: '1', hidden: false, captive-portal: true
STARTED! \o/
v2.0.5
Executing /autostart.txt
Done executing script


I do have reset the sketch, the log:

  STARTING...
EEPROM initialized
EEPROM cleaned
SPIFFS initialized

**Comment by ifengchao** [comment]
My board is wemos D1 with 4MB flash.

**Comment by spacehuhn** [comment]
Do other sketches work with the WiFi AP? Arduino has examples for that.

**Comment by ifengchao** [comment]
it works well with v1.6 firmware.

**Comment by tobozo** [comment]
`works with 1.6` && `won't work with 2.0.x` could it be pin assignment problems?

Neopixels I'm looking at you :eyes:

**Comment by SyncedCyberSoul** [comment]
Sorry I haven’t been able to get back to you. My cat seems to have nabbed one of my boards, I have yet to find it. The one she did take is the one I was having issues with unfortunately. The small one you recommended works but once I log in it crashes :(

**Comment by xTardguard4** [comment]
same problem here, i've wiped the firmware, reset the arduino code, and reflashed the board several times and the serial monitor shows that everything is working but still no "pwned" AP

**Comment by spacehuhn** [comment]
Can someone here please share the serial output for the sysinfo command?

**Comment by spacehuhn** [comment]
Open the [serial monitor](https://github.com/spacehuhn/esp8266_deauther/wiki/Serial) and do `set mac random` then `save` and restart the device. Someone contacted me per email with a similar issue and it fixed it for him. I suspect some suspicious ESP8266 modules or something with the old SDK.

**Comment by xTardguard4** [comment]
another thing that might work is `< erase_flash>` in esptool and uploading the .ino and the .bin with dio mode,
and also make sure that your usb cable works

**Comment by tobozo** [comment]
closing this as fixed
