### ISSUE TITLE
[Compiling/Flashing issues] Not able to send packages

### ISSUE THREAD

**Issue by McNasty20** [spacehuhn/esp8266_deauther#833]
I have tried to follow your guide but some of the files you told about aren't showing up in the zip folders. I have tried using Arduino and the esp8266 flasher and neither of them have worked for me. The Ardunio keeps giving me an error message about missing files and the flasher doesn't send any packages. I have tried all of the versions and none have worked. Please help!

**Comment by tobozo** [comment]
closing this as incomplete problem description, please visit the [troubleshooting wiki page](https://github.com/spacehuhn/esp8266_deauther/wiki/Troubleshooting) first

If none of the listed methods worked, please reopen this issue after adding as many details as possible.
