### ISSUE TITLE
[Help from Russian Speaker required] dont working anyone.

### ISSUE THREAD

**Issue by russianhackerman** [spacehuhn/esp8266_deauther#835]
sorry for my bad english
so bad. 
i started in v1.5. fast web no errors all work. super
1.6. very slow (hard?) web many web errors and disconnect while attack started. (cant stop attack in web)
2.0. cant compile first gen. network is constantly falling for no reason. very hot chipset. (hardware+network fail when hot). many times reconnect while not doing anything. 
2.xx last update download today (1 may 10pm). successfully compiled&flashed and... nothing. no wifi (cant see pwned) trash in serial at 115200. used binaries and compile arduino ide.
now i use v1.5. (sorry for google translate)
now used the same iron? (hardware?) same ide and same bin flasher. (my english very bad)
1.5 working very good now in same iron/hardware. problem in updates 1.6-last. every time it gets worse and worse. 
used iron esp8266 generic/mcu-v3

**Comment by tobozo** [comment]
You can reset your ESP by flashing [this](https://github.com/spacehuhn/esp8266_deauther/tree/master/Reset_Sketch).

**Comment by rdavydov** [comment]
By "esp8266 generic/mcu-v3" you mean you have tried it only on nodemcu v3 or on both the nodemcu and a separate esp module (which one, 12f?)
---
Под "esp8266 generic/mcu-v3" ты подразумеваешь, что пробовал только на nodemcu v3 или на nodemcu и на отдельном модуле esp (на каком, 12f?)

**Comment by rdavydov** [comment]
If said symptoms occur only on one nodemcu v3 board, it is obvious that your board is a faulty one.

Если указанные тобой симптомы возникают только на одной плате nodemcu v3, очевидно, что твоя плата неисправна.

**Comment by Kili0n** [comment]
Hello, why does this error come out?
How to fix it?
![wyau9-x4-ke](https://user-images.githubusercontent.com/39026746/39673539-81fba372-514f-11e8-82f6-035d318328f2.jpg)

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#timeout-error
