### ISSUE TITLE
Feature: upgrade from web

### ISSUE THREAD

**Issue by ifengchao** [spacehuhn/esp8266_deauther#839]
Is it possible to upgrade the firmware from web interface?

**Comment by tobozo** [comment]
OTA uses 50% of the flash space and the binary size already exceeds that

**Comment by ifengchao** [comment]
So it's possible to have the feature if the flash size is 4MB?
Upload the firmware from 192.168.4.1 manually?

**Comment by vuong244** [comment]
esp07 flash size only 1MB.

**Comment by ifengchao** [comment]
1MB devices can be compiled without OTA, let's just ignore it :)
But we shoud not limit the possibility of  4MB version.

**Comment by tobozo** [comment]
The question is: does it add a real value to the deauther?

Since it's not required for the tool to work, it's unlikely it'll land in the source tree, or at most it'll be a chunk of commented code you just uncomment when you're developing.

@spacehuhn will confirm that anyway

**Comment by spacehuhn** [comment]
My name is @spacehuhn and I approve this message ^

**Comment by ifengchao** [comment]
Uploading the frmware from a serial console is not that convenient than from the web.
Easier for deauthers to upgrade to the latest code, to test, to give a quick feedback. 

:)

**Comment by spacehuhn** [comment]
Hey man if you want it so much, why don't **you** implement it? :D

**Comment by ifengchao** [comment]
Well, that's a nice idea, i'm not quite familar with the esp8266 and arduino things actually... :(

**Comment by tobozo** [comment]
Sure, it could also be installed via an Amazon dash button that would trigger a MQTT deployment with the help of ESP WiFi Smart Config  (c) so the world could finally have the benefits of one-click-buy-and-deauth-all :skull: but I guess this is more of a generic concern and out of the scope of this project.

**Comment by tobozo** [comment]
@ifengchao if your build has a Micro SDCard reader there's an [ongoing test](https://github.com/spacehuhn/esp8266_deauther/tree/sd-updatable) that uses parts of the OTA module to allow flashing on demand from chosen binaries preinstalled on the SDCard.

Currently it's hardwired to the SD Card, but the syntax OTA friendly so it shouldn't be a problem to use it, or make it 'check & download' updated binaries, also I can provide the necessary tech support to help you set it up.

This way you can maintain several versions of the deauther on the same microSD and load them on demand for better testing.

**Comment by spacehuhn** [comment]
I have to decline this Feature Request for now.
Not only is the memory always a bit short on this project, I don't really have the time to implement this.
If someone wants to pick up from here, you're welcome to add your comment ann fork this project or make a pull request.
