### ISSUE TITLE
Deauthentication information on web interface

### ISSUE THREAD

**Issue by nisc3** [spacehuhn/esp8266_deauther#84]
Is it possible to show real-time deauthentication results on web interface? Like this: http://imgur.com/a/PfQiM

**Comment by joneroy** [comment]
@nisc3 it's possible

**Comment by N0vaPixel** [comment]
What in the mdk3 tool is missing here, the web interface show you the packet rate. What more ?

**Comment by nisc3** [comment]
In mdk3, it shows that 'Disconnected between____ and _____' so is it possible to output this information on web interface?

**Comment by spacehuhn** [comment]
yes it would be possible but it's pretty useless and not worth the hardware resources of the chip. So no sorry, if you want that you can implement this yourself.

**Comment by anudeepND** [comment]
Can we implement something like lite version and not as detailed as mdk3?
