### ISSUE TITLE
Cant connect to de ESP8266

### ISSUE THREAD

**Issue by FabFerrari** [spacehuhn/esp8266_deauther#845]
I was using the ESP8266 with the wifi deauthcer, i was messing up in the settings and i clicked at the "Hide from Wi-Fi list" and saved it. Welp, that was bad, and now i cant use the thing anymore cause i cant connect to it. Need help. #844 #836

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#how-to-do-a-reset

**Comment by tobozo** [comment]
@FabFerrari did you manage to fix the settings, if so can we close this?

**Comment by FabFerrari** [comment]
Yeah, i did fix it, you can close it.

Em 9 de mai de 2018, à(s) 9:37 AM, tobozo <notifications@github.com> escreveu:
