### ISSUE TITLE
Can't upload to ESP-01 512kb

### ISSUE THREAD

**Issue by majf1999** [spacehuhn/esp8266_deauther#85]
http://pastebin.com/RUv6XxS3

**Comment by H1ghTech** [comment]
http://pastebin.com/RUv6XxS3

**Comment by joneroy** [comment]
@majf1999 

Which board you you using:

https://github.com/spacehuhn/esp8266_deauther/blob/master/README.md

**Comment by Ultimatefire54** [comment]
I was trying to upload to my esp01 last night and got the same error. In his post, within the error report it says esp generic 512kbs which is the esp01. It doesn't seem to work for the 01, and in the install spacehunh says comment the mac vendor list in data.h for esp01 but that doesn't work.

**Comment by joneroy** [comment]
You read new readme

https://github.com/spacehuhn/esp8266_deauther/blob/master/README.md

**Comment by Ultimatefire54** [comment]
I read it and it says the same thing about the esp01, 'comment the mac vendor list for esp01'

**Comment by spacehuhn** [comment]
> The only thing you will need is a computer and an ESP8266 with at least 1Mb of flash memory.

> (If you using an ESP-01 with just 512kb, you can comment out the mac vendor list in data.h.)

so what is your problem with that? comment out the bytes and you're fine.

**Comment by Ultimatefire54** [comment]
Commenting out any part of data.h results in compiler errors

**Comment by N0vaPixel** [comment]
You don't have enough flash memory
`section .irom0.text' will not fit in regionirom0_0_seg`

I'll try later to reduce the size of the program.

**Comment by spacehuhn** [comment]
@N0vaPixel you can't without deleting important parts. He needs to comment out a part of the mac vendor list. There is no way around this. the array is just to big.

**Comment by N0vaPixel** [comment]
@spacehuhn I see, it may be a problem for many users, but the mac vendor list is very useful.

**Comment by spacehuhn** [comment]
@majf1999 if you have a ESP-01 with 1mb (you can test this with the ESP8266 CheckFlashConfig example) you can set the flash size to 1mb with 64,128 or 256kb SPIFFS - just don't set it to 512kb
![esp-flash-size](https://cloud.githubusercontent.com/assets/3826044/23671262/e5a11378-036a-11e7-9a3e-7ad9624b8358.jpg)

**Comment by N0vaPixel** [comment]
#99
