### ISSUE TITLE
Network shows, but can't connect

### ISSUE THREAD

**Issue by Joshfrog** [spacehuhn/esp8266_deauther#853]
Pwned network shows, but cannot connect.  Tried to most methods of flashing the chip, even erasing it first.
Possible the password is wrong, or some other issue.

**Comment by tobozo** [comment]
you can try the [reset sketch](https://github.com/spacehuhn/esp8266_deauther/tree/master/Reset_Sketch) then reflash the deauther

**Comment by Joshfrog** [comment]
Just tried it same issue not sure if its a password issue

**Comment by Joshfrog** [comment]
password is deauther right?

**Comment by tobozo** [comment]
yep, just remember the first boot is much longer as SPIFFS has to be formatted so give it a minute to be sure ^^

**Comment by schinfo** [comment]
Please download and install the esp8266_deauther again.
We found the problem with the AP and Spacehuhn solved it yesterday evening.
Don't forget, to reset the NodeMCU first - https://github.com/spacehuhn/esp8266_deauther/tree/master/Reset_Sketch (Method 3) - that's very important !!!

**Comment by Joshfrog** [comment]
Thanks works now cool gadget
