### ISSUE TITLE
Feature Request - Capture PSK handshakes

### ISSUE THREAD

**Issue by lamkeysing92** [spacehuhn/esp8266_deauther#86]
Awesome work on the ESP8266 deauther. But I wonder is it possible to capture the 4 way handshake of WPA authentication? Not sure where would it be saved though. May be on the browser at runtime?

**Comment by H1ghTech** [comment]
Read the readme!

**Comment by spacehuhn** [comment]
> Can it sniff handshakes?

> The ESP8266 has a promiscuous mode in which you can sniff packets, but handshake packets are dropped and there is no other way to get them with the functions provided by the SDK.
Maybe someone will find a way around this barrier but I wasn't able to.

**Comment by anudeepND** [comment]
It is possible but you can't see full conversation. You can't sniff all 4 packets

**Comment by risinek** [comment]
ESP32 does not limit the frame buffer, so this can be done on ESP32. I created a [project for ESP32 deauth attack with handshake capture](https://github.com/risinek/esp32-wifi-penetration-tool) if you don't insists on ESP8266

**Comment by SAQO101** [comment]
Bro can you make your project to work in cli ? Cos it works in browser only possible to make it to work in cli plssss 
I have been searching a lot but couldnt find anything except your project pls bro

**Comment by SAQO101** [comment]
> ESP32 does not limit the frame buffer, so this can be done on ESP32. I created a [project for ESP32 deauth attack with handshake capture](https://github.com/risinek/esp32-wifi-penetration-tool) if you don't insists on ESP8266

Bro can you make your project to work in cli ? Cos it works in browser only possible to make it to work in cli plssss 
I have been searching a lot but couldnt find anything except your project pls bro

I meant cli that will not make a wifi.!
And also that . pcap file can be downloadable ! 

Like idk over the serial ? Possible ? 

Pls help im not expert but a cyber sec. Student and intrested in this af 😂😀 if you can pls help i love you guys your the best and your projects are killin 👍
