### ISSUE TITLE
Cannot access /dev/ttyUSB0

### ISSUE THREAD

**Issue by Danilfilatov** [spacehuhn/esp8266_deauther#863]
If on Ubuntu flashing using any method gives access error `cannot access /dev/ttyUSB0` on Arduino or `error: espcomm_open failed` in Terminal, try doing this https://askubuntu.com/a/133244/699236
Solved the problem for me. Add this to the Troubleshooting or near the tip about flash button in the installation guide

**Comment by tobozo** [comment]
thanks for the tip, this looks more like a generic workaround to a linux problem (and we can't fit them all in the FAQ) than a specific deauther issue so I'll close this
