### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Claygala** [spacehuhn/esp8266_deauther#869]
hey,i have flashed this 2.0.5 rom.But i find that i use my pc to search the pwned ssid only. but i can't use my phone to find.how can i do for it?Anyone can help me please?thanks

**Comment by Claygala** [comment]
After i have flashed the rom,there will have a wifi named pwned ..

**Comment by yratof** [comment]
Having the same issue with 2.0.5 – WEnt back to 2.0.0 and it's working again. Problem with latest update?

**Comment by Claygala** [comment]
Thank you,but i prefer chinese lang...wait the coder next update to fix it...
