### ISSUE TITLE
Built-in LED

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#87]
Built-in LED not working when attack is running i'm using testing branch

**Comment by tpmodding** [comment]
kannst den mal nicht blocken oder so? @spacehuhn

**Comment by N0vaPixel** [comment]
From pull request 
> Using built-in LED when an attack is running. (+ options)

Did you enabled it using the setting web page ?

**Comment by H1ghTech** [comment]
Yes of course

**Comment by N0vaPixel** [comment]
This is not happening to me after a fresh install from the testing branch, so try to reset your settings first

**Comment by N0vaPixel** [comment]
Which board are you using.

**Comment by joneroy** [comment]
@N0vaPixel 

> Did you enabled it using the setting web page ?

Yes

> This is not happening to me after a fresh install from the testing branch, so try to reset your settings first

i'm fresh install from the testing branch alos use reset settings

> Which board are you using ?

Tested NodeMcu board and wemos D1 mini

**Comment by N0vaPixel** [comment]
@joneroy  @H1ghTech Can you past here the output of your serial monitor when you start an attack ?

**Comment by joneroy** [comment]
@N0vaPixel 

settings:
SSID: pwned
SSID length: 5
SSID hidden: 0
password: deauther
password length: 8
channel: 1
Scan hidden APs: 1
deauth reson: 1
attack timeout: 300
attack packet rate: 10
client scan time: 10
attack SSID encrypted: 1
use built-in LED: 1
nameList cleared

starting...
starting WiFi AP
SSID: pwned
Password: deauther
generating Macs...done
getting settings json
{"ssid":"pwned","ssidHidden":0,"password":"deauther","apChannel":1,"apScanHidden":1,"deauthReason":1,"attackTimeout":300,"attackPacketRate":10,"clientScanTime":10,"attackEncrypted":1,"useLed":1,"nameList":[] }
done
getting AP scan result JSON { "aps":[ ] }
done
getting settings json
{"ssid":"pwned","ssidHidden":0,"password":"deauther","apChannel":1,"apScanHidden":1,"deauthReason":1,"attackTimeout":300,"attackPacketRate":10,"clientScanTime":10,"attackEncrypted":1,"useLed":1,"nameList":[] }
done
getting AP scan result JSON { "aps":[ ] }
done
starting AP scan...
MAC - Ch - RSSI - Encrypt. - SSID - Hidden
c8:3a:35:68:29:e8 - 3 - -35 - WPA2 - BREEZY - 0
00:90:4c:ec:47:a8 - 4 - -91 - none - ADYYTFlG - 0
dc:1a:c5:68:2f:e7 - 6 - -93 - none - vivo Y51L - 0
scan done
getting AP scan result JSON ...{ "aps":[ {"i":0,"c":3,"m":"c8:3a:35:68:29:e8","ss":"BREEZY","r":-35,"e":4,"se":0},{"i":1,"c":4,"m":"00:90:4c:ec:47:a8","ss":"ADYYTFlG","r":-91,"e":7,"se":0},{"i":2,"c":6,"m":"dc:1a:c5:68:2f:e7","ss":"vivo Y51L","r":-93,"e":7,"se":0}] }
done
{ "aps":[ {"i":0,"c":3,"m":"c8:3a:35:68:29:e8","ss":"BREEZY","r":-35,"e":4,"se":0},{"i":1,"c":4,"m":"00:90:4c:ec:47:a8","ss":"ADYYTFlG","r":-91,"e":7,"se":0},{"i":2,"c":6,"m":"dc:1a:c5:68:2f:e7","ss":"vivo Y51L","r":-93,"e":7,"se":0}] }
getting AP scan result JSON ...{ "aps":[ {"i":0,"c":3,"m":"c8:3a:35:68:29:e8","ss":"BREEZY","r":-35,"e":4,"se":0},{"i":1,"c":4,"m":"00:90:4c:ec:47:a8","ss":"ADYYTFlG","r":-91,"e":7,"se":0},{"i":2,"c":6,"m":"dc:1a:c5:68:2f:e7","ss":"vivo Y51L","r":-93,"e":7,"se":0}] }
done
seect 0 - 1
getting AP scan result JSON ...{ "aps":[ {"i":0,"c":3,"m":"c8:3a:35:68:29:e8","ss":"BREEZY","r":-35,"e":4,"se":1},{"i":1,"c":4,"m":"00:90:4c:ec:47:a8","ss":"ADYYTFlG","r":-91,"e":7,"se":0},{"i":2,"c":6,"m":"dc:1a:c5:68:2f:e7","ss":"vivo Y51L","r":-93,"e":7,"se":0}] }
done
getting client scan result JSON { "clients":[] }
done

starting client scan
set channel to 3
changing to channel 4
changing to channel 6
stopping client scan after 10000ms
0: 375 Universa e0:2a:82:fb:48:08
starting WiFi AP
SSID: pwned
Password: deauther
getting client scan result JSON { "clients":[{"i":0,"p":375,"m":"e0:2a:82:fb:48:08","n":"","v":"Universa","s":0}] }
done
getting client scan result JSON { "clients":[{"i":0,"p":375,"m":"e0:2a:82:fb:48:08","n":"","v":"Universa","s":1}] }
done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "ready","running": 0},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
0
0
1
1
1
Attack LED : ON
starting deauth attack
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "starting","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
running deauth attack done
running deauth attack done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "9pkts/s","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
running deauth attack done
running deauth attack done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "9pkts/s","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "9pkts/s","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "9pkts/s","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
running deauth attack done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "9pkts/s","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
running deauth attack done
running deauth attack done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "9pkts/s","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
running deauth attack done
getting attacks JSON...{ "aps": ["BREEZY"], "clients": ["e0:2a:82:fb:48:08 Universa - "], "attacks": [{"name": "deauth","status": "8pkts/s","running": 1},{"name": "beacon (clone)","status": "ready","running": 0},{"name": "beacon (list)","status": "no SSID","running": 0}],"ssid": []}
done
running deauth attack done
running deauth attack done
running deauth attack done
getting settings json
{"ssid":"pwned","ssidHidden":0,"password":"deauther","apChannel":1,"apScanHidden":1,"deauthReason":1,"attackTimeout":300,"attackPacketRate":10,"clientScanTime":10,"attackEncrypted":1,"useLed":1,"nameList":[] }
done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done
running deauth attack done

**Comment by N0vaPixel** [comment]
Past big datas here: [http://pastebin.com/](url)

Mmmh, interesting.... The LED function was called.
Make a new sketch and update the firmware of your board with this code: [http://pastebin.com/Y9cJt1z8](url)

This is a blink test with the built-in LED

**Comment by joneroy** [comment]
@N0vaPixel 

> Blink test with the built-in LED

LED Blink Not Working

**Comment by N0vaPixel** [comment]
Make sure you have a LED on your board, because she seems to be death 💀

**Comment by joneroy** [comment]
@N0vaPixel 

# **When i'm uploading the sketch it's built-in LED Blink**

**Comment by joneroy** [comment]
@N0vaPixel 

It's not my prob @H1ghTech

**Comment by N0vaPixel** [comment]
> LED Blink Not Working

> When i'm uploading the sketch it's built-in LED Blink

It's difficule to me to understad you000

**Comment by joneroy** [comment]
> LED Blink Not Working after done upload sketch

> When i'm uploading the sketch it's built-in LED Blink

**Comment by N0vaPixel** [comment]
This is not the same LED, this is the RX LED not the IN-BUILD LED

**Comment by joneroy** [comment]
@N0vaPixel 

![nodemcu_esp8266_001](https://cloud.githubusercontent.com/assets/26072408/23592809/3917bf88-022c-11e7-8c85-4a81564bf653.jpg)

this led

**Comment by N0vaPixel** [comment]
If this LED blink during the upload of a sketch, this is not the built-in LED.
Look at the arduino uno, there is 3 LEDs : TX, RX and BUILT-IN LED (connected to i/o 13)
The build-in led must be connected to the inputs/ouputs of the board.

**Comment by joneroy** [comment]
@N0vaPixel 

Thank You

**Comment by N0vaPixel** [comment]
@joneroy  Sorry but you cannot use this feature with this board, i think you don't have a built-in LED.

**Comment by joneroy** [comment]
@N0vaPixel 

You right.

This LED Blink feature with RX LED it's possible

**Comment by N0vaPixel** [comment]
Wow, viewed some documentation, the LED of the esp is connected to GPIO2
I think you don't have a called "built-in led", but you can use the esp one.

I'll commit this change, the program will use the LED of the esp instead of the one on the board to increase compatibility.

**Comment by nisc3** [comment]
This led should blink right?
http://i.imgur.com/fehC28h.jpg

**Comment by joneroy** [comment]
> This led should blink right?

This is RX LED on board BUILT-IN LED

## **With on board BUILT-IN LED**

1.nodemcu amica

![nodemcu_esp8266_amica_001_lowres](https://cloud.githubusercontent.com/assets/26072408/23600368/5a34d904-026c-11e7-887d-75e5d9583541.jpg)

## **Without on board BUILT-IN LED**

2.nodemcu lolin

![nodemcu_esp8266_001](https://cloud.githubusercontent.com/assets/26072408/23600490/c4d037ea-026c-11e7-92d7-50eb9ee669cf.jpg)

3.wemos D1 mini

![wemos-d1-mini-dessus](https://cloud.githubusercontent.com/assets/26072408/23600498/db047846-026c-11e7-9ab1-9d4110df7ced.jpg)

**Comment by nisc3** [comment]
But RX LED on my board is not blinking

**Comment by joneroy** [comment]
@nisc3 

Read full conversation i think you found somthing helpful

**Comment by spacehuhn** [comment]
Works on my new nodeMCU! (it has a LED yey! 🙌 )
But not on the "nodeMCU v3 lolin board", also not on my ESP-01 and the wemos d1 mini pro.

**Comment by N0vaPixel** [comment]
Since many boards dind't have a built-in LED, i'll update the software to use the ESP one, connected to gpio 2, and removed the incompatible (in most cases) constant BUILTIN_LED.

**Comment by joneroy** [comment]
@N0vaPixel 

Most of the esp8266 board not available "BUILTIN_LED" feature is good but board compatibility main issue
Thank you.

**Comment by joneroy** [comment]
@N0vaPixel 

Now LED Working!!

**Comment by N0vaPixel** [comment]
@joneroy  I've never designed the program to make the LED blink

**Comment by joneroy** [comment]
@N0vaPixel 

No Prob

**Comment by N0vaPixel** [comment]
Perfect !
Thank you for your help 💪

**Comment by N0vaPixel** [comment]
Why did you reopened it ?

**Comment by joneroy** [comment]
@N0vaPixel 

Sorry i mistakenly press button.

**Comment by anudeepND** [comment]
An option to choose the behaviour of LED like blinking or constant would be great.

**Comment by N0vaPixel** [comment]
@anudeepND Thank you for helping us. But sorry it's useless. Memory is limited and we can't add extra bytes for funny features

**Comment by anudeepND** [comment]
Ok I understand

**Comment by anudeepND** [comment]
@N0vaPixel did you tried MAC changer? All my ESPs are busy, so if possible try it out
