### ISSUE TITLE
Beacon attack not working properly

### ISSUE THREAD

**Issue by sebampuero** [spacehuhn/esp8266_deauther#871]
**Hardware/Flashing:**
Board: NodeMCU Lolin V3 ESP8266
Using OLED: NO
Using WebServer: YES
Using Serial: NO
Installation mode: bin
Code/binary version: 2.0.5_4mb
Flash size: 4M
Flash method: NodeMCU-flasher
Flash Frequency:	80Mhz
Upload Speed: 230400
Powered by: Powerbank 5V max output 3A

**Description:**
Creating a beacon list of 20 APs and starting the attack works fine. After 10 seconds the attack stops and all the APs disappear, only the random mode works fine. The other attacks (deauth) work fine.

**Comment by spacehuhn** [comment]
Have you tested it with different devices? Some show SSIDs differently than others.
If you could post the serial output would also help, when you start the attack and when it stopps after 10 seconds.

**Comment by spacehuhn** [comment]
Closing due to no response.
