### ISSUE TITLE
No wifi signal.

### ISSUE THREAD

**Issue by mdemeter27** [spacehuhn/esp8266_deauther#877]
I having trying to get this to work for a while now. I have this board-- https://www.amazon.com/gp/product/B010O1G1ES/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
. I have tried flashing 2.05 on Arduino and nodemcu flasher to no prevail. It uploads the code, but when I re plug in the board, no wifi signal comes up. Sometimes in arduino it will say "Error compiling for board Generic ESP8266 Module.". Any help? I have also tried flashing 1.6.

**Comment by petermoor877** [comment]
i have the same board  with no WiFi !!! ?

**Comment by domodial** [comment]
I have 3 sames boards and wifi work fine ^^

**Comment by mdemeter27** [comment]
I think I have a defective board. I am getting a new one soon.
