### ISSUE TITLE
BUG: Error loading client.html Testing Branch

### ISSUE THREAD

**Issue by joneroy** [spacehuhn/esp8266_deauther#88]
After client scan done error loading client.html

![untitled](https://cloud.githubusercontent.com/assets/26072408/23592195/4510ead4-0223-11e7-9796-ae5fc659c8c3.png)

**Comment by N0vaPixel** [comment]
AP is turned off when you are sniffing, make sure that you are connected before trying to access to the web server

**Comment by joneroy** [comment]
@N0vaPixel 

> AP is turned off when you are sniffing

my laptop connected with deauther but loading page to late

**Comment by N0vaPixel** [comment]
Memory may be full.
Pulled a fix #89 

Maybe mentionned here #83

**Comment by N0vaPixel** [comment]
Should be fixed now #89

**Comment by joneroy** [comment]
@N0vaPixel 

Bug Fix now clients.html working.
