### ISSUE TITLE
Option to hide SSID and set time schedule

### ISSUE THREAD

**Issue by wutwo** [spacehuhn/esp8266_deauther#881]
Hi,

is it possible to hide the SSID in the web interface? Also, would it be possible to implement a scheduler in order to set specific time points or time intervalls of activity (e.g. "14:00-15:00 daily" or "every hour for 10 minutes)?

Cheers,
Thomas

**Comment by wutwo** [comment]
Another point, is it possible to spoof the device's MAC?

**Comment by spacehuhn** [comment]
yes, yes if you add an real time clock and the code necessary to get it running, and yes.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen.
