### ISSUE TITLE
error: 'freedom_outside_cb_t' was not declared in this scope

### ISSUE THREAD

**Issue by freedumz** [spacehuhn/esp8266_deauther#884]
Hi everyone, I have the following message

```
Arduino : 1.8.5 (Windows 10), Carte : "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

In file included from sketch\Accesspoints.h:7:0,

                 from sketch\Accesspoints.cpp:1:

C:\Users\domin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:451:39: error: 'freedom_outside_cb_t' was not declared in this scope

 int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

                                       ^

exit status 1
Erreur de compilation pour la carte NodeMCU 0.9 (ESP-12 Module)
```

So I'm following this tutorial : 
http://www.instructables.com/id/DIY-Wifi-Jammer-With-ESP8266-and-Mobile-App/

so I added the following line : > esp8266 > hardware > esp8266 > 2.0.0 > tools > sdk > include> user_interface.h

typedef void (**freedom_outside_cb__t)(uint8 status);
int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb); void wifi_unregister_send_pkt_freedom__cb(void); int wifi_send_pkt_freedom(uint8 **buf, int len, bool sys_seq);

but now when I compile my project i have the error message
so I tried other things like using other board :  NodeMCU 0.9 , NodeMCU 1.0 or  Generic ESP8266 Modul

but nothing has changed, I always have the problem

so any idea of what I'm doing wrong?

Many thanks in advance for your help

**Comment by spacehuhn** [comment]
oui

**Comment by TerrisGO** [comment]
```
In file included from C:\Users\User\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266\core_esp8266_postmortem.c:27:0:

C:\Users\User\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.0.0/tools/sdk/include/user_interface.h:450:39: error: unknown type name 'freedom'

 int wifi_register_send_pkt_freedom_cb(freedom outside_cb_t cb);

                                       ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
```
