### ISSUE TITLE
Whole 2.0 version bugged

### ISSUE THREAD

**Issue by infectedw** [spacehuhn/esp8266_deauther#886]
Well, i followed whole instruction everything installed properly.

But after trying to scan i set channel on all and get error  ERROR: timeout loading file run?cmd=scan but sometimes it find some networks after i select channel, but now moving to "Attack" section, when i press "Deauth" it don't do anything it show me ERROR: loading file: attack.json.

Sometimes it won't load WiFi hotspot so i have to couple times turn off and then turn on NodeMCU. Please i would like to someone explain maybe i'm doing something wrong. I wanna fix this soon i need it.

The 1.6 version had better UI and didn't had that much errors... Please back old UI.

EDITED: New ERROR: timeout loading file run?cmd=save names after clicking "Scan APS"

New bug: Scan show SSIDs after selecting SSID deauth don't do anything and beacon also don't do anything

**Comment by marek26340** [comment]
> but now moving to "Attack" section, when i press "Deauth" it don't do anything it show me ERROR: loading file: attack.json.

Yeah, this is quite normal, and I don't know a solution... It happens when you try to attack on a different channel that your ESP is currently (being controlled) at. 

I can't currently even try to explain the rest of your problems, but I did not encounter any of these, except that attack.json.

**Comment by infectedw** [comment]
I will make video how it all looks, and post here or somewhere else and set link here. I have tons of errors...

**Comment by tobozo** [comment]
![image](https://user-images.githubusercontent.com/1893754/41117297-ea2a70bc-6a8c-11e8-89f8-63d4d568c0d4.png)

**Comment by infectedw** [comment]
First Video: https://vimeo.com/273944772
Second Video: https://vimeo.com/273945836

I hope you guys see enough!

**Comment by tobozo** [comment]
Video 1: you just hit the back button and your browser gave you some cache but you're not actually connected to the ESP8266

Video 2: same as video 1 but you seem to lose your temper :p

**Comment by spacehuhn** [comment]
<a href="https://imgflip.com/i/2btb0t"><img src="https://i.imgflip.com/2btb0t.jpg" title="made at imgflip.com"/></a>

**Comment by deantonious** [comment]
Bonvenon al la EIF. Bonvolu RTFM kaj ekzekutu la komandon "rice" dum sur la seria interfaco por pliaj elpurigado.
