### ISSUE TITLE
What's the highest packet rate that esp8266 can send?

### ISSUE THREAD

**Issue by WYHSniper** [spacehuhn/esp8266_deauther#887]
I tried 150 pkt/s and it works, anyone test it a higher rate?

**Comment by tobozo** [comment]
see #717

**Comment by mdemeter27** [comment]
How do you change the packet rate?

**Comment by tobozo** [comment]
@mdemeter27 you can [play with the settings](https://github.com/spacehuhn/esp8266_deauther/wiki/Serial#improve-packet-rate)

**Comment by spacehuhn** [comment]
There is no standard answer to this. It's highly dependent on the network traffic around you, what kind of packets you're sending, at what speed, with what size.

For the deauther, you can play around with if but the higher you set it, the more unstable the whole ESP can get! And it will only send what it can, not more. But you can see how much packets it's sending and adjust it by that. 

Also note that sending more packets, does not necessarily make anything 'better'.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
