### ISSUE TITLE
pin usage.

### ISSUE THREAD

**Issue by appletechgeek** [spacehuhn/esp8266_deauther#890]
are the pins used by default?
if so wich are for wich?
i  want to have a flashing led indicator when the *attack* is happening on the pins and i'm very new to coding.

**Comment by tobozo** [comment]
[this is the default pinout](https://github.com/tobozo/Arduino/blob/deauther/variants/dstike/pins_arduino.h) and [these are the different configs](https://github.com/spacehuhn/esp8266_deauther/tree/master/configs)

**Comment by spacehuhn** [comment]
Feel free to comment if you have any more questions
