### ISSUE TITLE
when not using USE_PROGMEM_WEB_FILES, wifi.h needs to avoid referncing the consts

### ISSUE THREAD

**Issue by bradanlane** [spacehuhn/esp8266_deauther#891]
This is a minor point which most will not encounter but ...

If you want to use the `/web` folder on the spiffs storage, the process is partially described in `utils/web_converter_python/README.md` and then `settings.md` for the setting of `webSpiffs` to `true`.

The code then indicates to comment out the definition of `USE_PROGMEM_WEB_FILES` from `webfiles.h` the code in wifi.h is not aware the file strings no longer exist. The compiler throws an error.

The fix is not as easy as referencing the definition of `USE_PROGMEM_WEB_FILES` because its not available outside of `esp8266_deauther.ino`.

_BTW: the only reason I went down this path was to add a PNG file to the web files. I didn't see an efficient way to go about it otherwise._

**Comment by bradanlane** [comment]
There also seems to be some issue with page loads once the compressed `gz` files are moved to the spiffs. I frequently get the first page to load in my web browser but a subsequent page will not completely load. It appears the `.html.gz` file is loaded but one of the referenced files (css, js, etc) never completes. Disconnecting from the `ESP8266` AP and reconnecting usually fixes it. 

Have others moved the web interface to spiffs with success or issues?

**Comment by spacehuhn** [comment]
I added the missing #ifdef in wifi.h so it completley ignored the progmem files but i would not recomment that. 

You can of course do that and then upload your own files to the SPIFFS with this plugin: https://github.com/esp8266/arduino-esp8266fs-plugin

But it's better to use the converter script and use the PROGMEM, because the SPIFFS isn't as efficiant as the PROGMEM and the website can be a bit unstable.

**Comment by bradanlane** [comment]
I eventually made the same conclusion. While I was successful at uploading web files to SPIFFS, it was not as stable - occasional resource load timeouts at the browser.

_The reason for attempting to move the web resources out of PROGMEM was to allow for a few additional resources (images)._

**Comment by spacehuhn** [comment]
Yeah I suppose images aren't that great for improving performance either :D

**Comment by tobozo** [comment]
just throwing a rock into water: images could be served from spiffs while other assets are still served from PROGMEM?

**Comment by bradanlane** [comment]
Good suggestion. Thanks.

Ultimately, I created the graphic I needed using pure CSS.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
