### ISSUE TITLE
Issue after flashing

### ISSUE THREAD

**Issue by NIEIXIUIS** [spacehuhn/esp8266_deauther#897]
The network does not show up on v2.05. Ive tried different ways and i have made it connect with first ereasing all the data on the board then running a wifi connect script witch made the nodemcu esp8266 connect to my wifi. Then i uploaded the v1.6 file and it worked nice. Suddenly it stops working and it says no internet access and doesn't let me connect. When i cycled to another place in my city it started working, then i cycled a little back and it stopped working, and when i cycled back again and it worked. It seems like it's position based. But at home it doesn't always work either. When i first upload the code using the way mentioned at the start it works for a few hours and then it stops working, it won't let me connect. If im aleready connected to the esp8266 and it stops working it will me an error during ap scan and then disconnect. I've tried all the other versions with no luck. I just tried flashing the v2.05 version and this is the serial output i got.  

```
ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

This output was repeated till i unplugged it.

After using the esp8266 flasher this was the output.

Mounting SPIFFS...OK
Switched to Channel 1
Settings loaded from /settings.json
Settings saved in /settings.json
Device names loaded from /names.json
SSIDs loaded from /ssids.json
Scan results saved in /scan.json
Serial interface enabled
Started AP
[WiFi] Path: '/web', Mode: 'AP', SSID: 'pwned', password: 'deauther', channel: '1', hidden: false, captive-portal: true
STARTED! \o/
v2.0.5
Executing /autostart.txt
Done executing script
```

The network still did not show up.

When using the v1.6 version it sometimes works. This is the output i got.

SSID: AndroidAp
SSID length: 9
SSID hidden: 0
password: Password123
password length: 11
channel: 1
Default MAC AP: 86:f3:eb:5a:7d:16
Saved MAC AP: 86:f3:eb:5a:7d:16
MAC AP random: 0
Scan hidden APs: 1
deauth reson: 1
attack timeout: 0
attack packet rate: 10
client scan time: 15
use built-in LED: 1
channel hopping: 0
multiple APs: 1
multiple Attacks: 0
mac change interval: 4
1s beacon interval: 0
LED Pin: 2
Trying to sync the MAC addr with settings
Synced with saved mac addr : 86:f3:eb:5a:7d:16
nameList cleared
Attack LED : OFF

Starting WiFi AP:
SSID     : 'AndroidAp'
Password : 'Password123'
-----------------------------------------------

 generating MACs...done

Starting...

This is what i got but now i cant connect. Sometimes i can tho.

**Comment by cjs1502** [comment]
i have the same problem.please let me know if you get through this problem.

**Comment by tobozo** [comment]
sometimes issuing the "reset" command from the serial console and waiting a few seconds solves it

**Comment by newlearnergrgsm** [comment]
hello. ı am sorry for my bad english . ı dont know which issue to write sorry for missunderstand.
ı would like to ask, ı have loaded ESP8266 with flash program and it shows AP MAC and  ST MAC. 
How can I change it. !! 
Thanks for any answer.

**Comment by spacehuhn** [comment]
The access point or the web server (probably both) have performance problems that were solved in a later version of the SDK, that we unfortunately can't use for this project. I noticed that there are heavy performance differences depending on how much other WiFi devices or networks are in the area.

Some phones also don't like connecting to a network without internet access and switch to other networks, that doesn't help either...

That's why I want to concentrate more on the display UI, as that doesn't have to deal with such problems.

**Comment by bradanlane** [comment]
I would like to "dig into" the web performance and stability issue. Adding a display is not an option in my case. 

Could you outline the key reason the newer version of the SDK cannot be used?

**Comment by tobozo** [comment]
@bradanlane The newer SDK does not expose the function needed to send deauth frames and this SDK is closed source.

**Comment by bradanlane** [comment]
Thanks for the background.
