### ISSUE TITLE
arduino json fatal error

### ISSUE THREAD

**Issue by kadali1212** [spacehuhn/esp8266_deauther#898]
i am using esp826612e
i already  added libarry files 

Build options changed, rebuilding all
F:\Arduino\objectdetection\objectdetection.ino:2:26: fatal error: aurduinoJson.h: No such file or directory

 #include <aurduinoJson.h>

                          ^

compilation terminated.

**Comment by tobozo** [comment]
it's supposed to be "ArduinoJson" not "aurduinoJson"

did you mess with the code ?

**Comment by tobozo** [comment]
also the project name isn't related to this project, not a bug but more a turing path problem, closing this
