### ISSUE TITLE
Error loading apscan.json

### ISSUE THREAD

**Issue by NIEIXIUIS** [spacehuhn/esp8266_deauther#899]
After using my nodemcu a while i get a error with apscan. When this ussue pops up i can't reconnect to the network even if i press the reset button. The soulution is to upload the script again. But suddenly it stops working again. In certain places in my city it works, almost all places it doesn't. Why??

**Comment by spacehuhn** [comment]
The access point it creates is not always reliable. That is due to the Arduino ESP8266 core version 2.0.0 that has to be used, otherwise the deauthing wouldn't work.
