### ISSUE TITLE
Only 20pkts per second in deauth mode

### ISSUE THREAD

**Issue by doge27** [spacehuhn/esp8266_deauther#9]
I'm getting only 20pkts per second in deauth mode, so clients are not getting disconnected. Other functions are working normally

**Comment by spacehuhn** [comment]
It's working, the deauth attack is limited to 20pkts/s. 
For more information read the FAQ.

**Comment by doge27** [comment]
Clients don't get disconnected. What to do?

**Comment by doge27** [comment]
Is it possible to increase that value?

**Comment by spacehuhn** [comment]
From the FAQ:

**Deauth attack won't work**
[...]
If it can send packets but your target don't loose its connection then the WiFi router uses 802.11w and it's protected against such attacks or they communicate via 5 GHz WiFi, which the ESP8266 doesn't support.

**Comment by doge27** [comment]
How to increase deauth packets? Where to change the value?

**Comment by sarimnaveed2** [comment]
Go-to the settings where you change your SSID and Password, go to the Bottom of the page and you'll see the Packets . You can change the value from there.
