### ISSUE TITLE
Jamming

### ISSUE THREAD

**Issue by TwinkleFredrik** [spacehuhn/esp8266_deauther#90]
This would be a malicious feature, but what are your thoughts on a feature where the software chooses for example the 10 closest APs and starts deauthing them with a click of a single button?
-----
Just got the idea and thought I would share it since I could not find any post about it myself.
I would implement this myself if I was just not new to arduino :p

**Comment by N0vaPixel** [comment]
For the pleasure of the script kiddies...

> Could it auto-deauth all APs in the range?
> 
> Yes, but I will not implement this 'feature' for ethical and legal reasons.

**Comment by TwinkleFredrik** [comment]
Thanks for the quick reply! :)
