### ISSUE TITLE
Can I save the SSID of the selected access points ?

### ISSUE THREAD

**Issue by T1MOXA** [spacehuhn/esp8266_deauther#903]
Can I save the SSID of the selected access points from the "Scan" section to my SSID list via WEB interface (like `add ssid -s` command)?

**Comment by spacehuhn** [comment]
Yes you select the APs in Scan, go to SSIDs and click on `CLONE SELECTED APS`
![grafik](https://user-images.githubusercontent.com/3826044/41969730-a9608de2-7a08-11e8-821e-12218603fd5c.png)

**Comment by T1MOXA** [comment]
Thanks, but I have a new problem.
After clicking "CLONE SELECTED APS" I had 20 aps with the same name.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
