### ISSUE TITLE
invisible jamming

### ISSUE THREAD

**Issue by newlearnergrgsm** [spacehuhn/esp8266_deauther#908]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```inside these 3 quotes/grave accents```
(Delete this text when you've read it)

**Comment by spacehuhn** [comment]
more like invisible question

**Comment by jLynx** [comment]
I'll give that joke a 9/11. Don't quit your day job @spacehuhn

**Comment by spacehuhn** [comment]
thanks, I'll give your response 5 kiwi's 🥝🥝🥝🥝🥝 out of 3, because I ate the other 2.

GitHub should add a donation button to the issues, so people that feel bad for me answering this 💩 can buy me more 🥝
