### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by 5465da** [spacehuhn/esp8266_deauther#91]
I uploaded the code to my esp8266 and run it on my phone at 192.168.4.1. And tried to deauth my client on the wifi and it doesn't work. It doesn't disconnect the client

**Comment by H1ghTech** [comment]
Do u have a 5ghz network?

**Comment by 5465da** [comment]
Yes,It is connected to my wifi extender and I tested on my wifi extender 2.4ghz

**Comment by 5465da** [comment]
Plus my connection to the esp8266 keep disconnecting

**Comment by tobozo** [comment]
ESP8266 can't do 5Ghz, and 5Ghz AP are usually protected against deauth attacks.

**Comment by 5465da** [comment]
But I tested it on 2.4ghz... The configuration on my router 2.4ghz and 5ghz is enabled

**Comment by 5465da** [comment]
Nvm tmr I will test it again

**Comment by tobozo** [comment]
Just edited my comment, make sure your router has no anti DDOS enabled when you test. 
Also deauth packets won't affect devices using the 5Ghz band.

**Comment by spacehuhn** [comment]
> Deauth attack won't work

> If you see 0 pkts/s on the website you have made a mistake. Check if you have followed the the installation steps correctly and that the right SDK installed, it must be version 2.0.0!
If it can send packets but your target don't loose its connection then the WiFi router uses 802.11w and it's protected against such attacks or they communicate via 5 GHz WiFi, which the ESP8266 doesn't support.

**Comment by 5465da** [comment]
I encountered another problem when I scan for clients, the esp8266 will disconnect to the phone connected to it.

**Comment by 5465da** [comment]
`
![problme](https://cloud.githubusercontent.com/assets/26222974/23655924/603f21cc-0372-11e7-9b29-4d6a81eb12cc.png)
`

**Comment by 5465da** [comment]
![problme](https://cloud.githubusercontent.com/assets/26222974/23655945/78ff64d8-0372-11e7-86f3-ec7d9257119f.png)

**Comment by spacehuhn** [comment]
read the readme
