### ISSUE TITLE
where do I download missing files?

### ISSUE THREAD

**Issue by KeithDaBeef** [spacehuhn/esp8266_deauther#910]
I'm having an issue when it says I have missing files such as "SH1106wire.h" i was wondering if there was a place to download these files or how to solve this problem thanks!

full error message:

Arduino: 1.8.5 (Mac OS X), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from sketch/Settings.h:11:0,
                 from /Users/keithvermeulen/Downloads/esp8266_deauther-2.0.5/esp8266_deauther/esp8266_deauther.ino:14:
sketch/A_config.h:7:24: fatal error: SH1106Wire.h: No such file or directory
 #include "SH1106Wire.h"
                        ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by spacehuhn** [comment]
Werid...
If you installed the deauther SDK as described in the installation tutorial on the wiki, the display library should already be included/installed.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
