### ISSUE TITLE
stastion scan time is not being saved

### ISSUE THREAD

**Issue by itsik-b** [spacehuhn/esp8266_deauther#911]
I cant find any variable  for the station scan timeout... 
![scan_timeout](https://user-images.githubusercontent.com/33322719/42309296-dfc02616-8040-11e8-90a0-3a88069f63ce.jpg)

**Comment by tobozo** [comment]
It's [hardcoded](https://github.com/spacehuhn/esp8266_deauther/blob/master/web_interface/scan.html#L62) in the HTML

This hardcoded time unit should probably be cleaned up from the HTML and deferred in the label instead:
`Station Scan Time (seconds)`

**Comment by spacehuhn** [comment]
first world problems...

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
