### ISSUE TITLE
Can't see "ADD" button on scan page & Issue with cloning selected SSIDs ....

### ISSUE THREAD

**Issue by itsik-b** [spacehuhn/esp8266_deauther#912]
I'm not able to add a specific SSID to SAVED SSIDs ... missing ADD button.

![scan ap](https://user-images.githubusercontent.com/33322719/42321460-b1f115bc-8061-11e8-9f37-912d8dd2ed8d.jpg)

**Comment by spacehuhn** [comment]
If you open the website with a device with a small screen, you have to open the website in desktopmode to access everything. THe mobile view is simplified.

**Comment by itsik-b** [comment]
I see now that on SSID when you add manually it works fine, but when you "Clone Selected APs" it ignores the "Number", and clones it 60 times.

**Comment by spacehuhn** [comment]
Clone selected APs is different to adding SSIDs manual. It will fill the list until it's full.
But I see why it can be confusing, I added it on the todo list for the next update :)

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
