### ISSUE TITLE
i try to upload esp8266_deauther-master > esp8266_deauther.ino code.but it can't upload and throw this error  fatal error: SH1106Wire.h: No such file or directory  #include "SH1106Wire.h"                          ^ compilation terminated.  please help me how to fix this error ?

### ISSUE THREAD

**Issue by chalananupun** [spacehuhn/esp8266_deauther#914]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhn/esp8266_deauther/wiki).  
Please put error messages and code ```inside these 3 quotes/grave accents```
(Delete this text when you've read it)

**Comment by spacehuhn** [comment]
no
