### ISSUE TITLE
How to change password and SSID of esp8266 AP?

### ISSUE THREAD

**Issue by themakerman** [spacehuhn/esp8266_deauther#92]

**Comment by H1ghTech** [comment]
Look in the settings

**Comment by joneroy** [comment]
@themakerman 

I hope you found your answer

![untitled](https://cloud.githubusercontent.com/assets/26072408/23621274/f932ed68-02bf-11e7-9fcf-2b7d8fe40aa4.png)

**Comment by joneroy** [comment]
@themakerman 

## **If your prob solved please close issue**
