### ISSUE TITLE
Please add the automatic-reload feature

### ISSUE THREAD

**Issue by Cherubrine** [spacehuhn/esp8266_deauther#920]
In the newer versions there is no auto-reload feature any more,
so you have to press reload after every scan, or if you want to see the actual packetrate.
Please insert this feature in a future release.

**Comment by spacehuhn** [comment]
Thanks but this is on purpose

**Comment by Cherubrine** [comment]
ok thanks

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
