### ISSUE TITLE
Wemos D1 Mini Pro v2 (Alixpress) not running

### ISSUE THREAD

**Issue by JeroenVBH** [spacehuhn/esp8266_deauther#926]
Can I run this on Wemos D1 Pro Mini v2 16M (128M bit) from Alixpress?

**Comment by beykansen** [comment]
Did you resolve this problem? @JeroenVBH

**Comment by remy99c** [comment]
I can't get it to work on wemos d1 mini lite, It does work on a nodeMCU.

**Comment by JeroenVBH** [comment]
No the issue is still open

**Comment by spacehuhn** [comment]
Thee Wemos D1 mini lite uses an ESP8285 with 1MB embedded flash. The 1MB bin file should work. I tested it on all available (original) Wemos boards.

**Comment by OtakuNekoP** [comment]
Hey guys, I resolve the problem today.

Do NOT use the **QIO** SPI MODE, you will not boot up like that.

![image](https://user-images.githubusercontent.com/9425352/47420105-f5d41180-d77d-11e8-858b-4c2971e8c212.png)


Use the **DIO** mode instead, and it works fine on my Wemos D1.

![image](https://user-images.githubusercontent.com/9425352/47419926-89591280-d77d-11e8-9c10-28a1c1346e56.png)


I hope this tip will help you guys. w

**Comment by JeroenVBH** [comment]
I also got IT working now! One problem remains, after a powerloss, the WeMos has lost its settings like WiFi SSID and Password.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
