### ISSUE TITLE
OLED scrambled after 2.0.6 flash

### ISSUE THREAD

**Issue by anusplaya** [spacehuhn/esp8266_deauther#929]
I have a DSTIKE OLED v3.5 board, tried to flash with Arduino using: 
Board:  DSTIKE by Travis Lin 
Flash Mode: DIO
Flash Frequency: 80 MHZ
CPU Frequency: 160 MHz
Flash Size: 1M (256K SPIFFS)
Reset Method: nodemcu
Upload Speed: 115200

OLED is all scrambled now?  I remember this happening before with changing flashing settings by accident, but can't remember exactly what remedied the problem.

**Comment by spacehuhn** [comment]
Please have a look here: https://github.com/spacehuhn/esp8266_deauther/wiki/Setup-Display-&-Buttons

You will have to use the config file for the DSTIKE OLED: https://github.com/spacehuhn/esp8266_deauther/blob/master/configs/DSTIKE_OLED_v3.5_Monster_Mini/A_config.h

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
