### ISSUE TITLE
Seems like new program isn't loading on the board.

### ISSUE THREAD

**Issue by whyAllUsernamesAreTaken** [spacehuhn/esp8266_deauther#93]
I uploaded the new program to the board using the previous settings which worked fine with the previous program but now i don't get any AP. 
All the previous programs are working fine but not this one. 
The ssidHidden is also false and i have not touched any line of the program.
I get the full signal in other network AP but when i try to connect to it by giving the ssid of my ap  it does not connects. I have also tried giving it the previous ssid that i have assigned manually by settings webpage.
**Please help.**

**Comment by joneroy** [comment]
@whyAllUsernamesAreTaken 

you are using sdk_fix new update

**Comment by spacehuhn** [comment]
can you test this with other boards? Is the old version still working? Have you tested one of the example code to see if it's a hardware problem...?

**Comment by whyAllUsernamesAreTaken** [comment]
The old versions are working fine. I have also tested the example code and it is also working. and i am using sdk_fix updated that you suggested.

**Comment by whyAllUsernamesAreTaken** [comment]
can anyone please help me?

**Comment by N0vaPixel** [comment]
It's difficult to find the problem. First check the version of your sdk, are you using the version 2.0.0 ?

**Comment by whyAllUsernamesAreTaken** [comment]
Yes i am using 2.0.0

**Comment by N0vaPixel** [comment]
Try the example of your sdk: `\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\examples\WiFiScan`

**Comment by whyAllUsernamesAreTaken** [comment]
I have already tried some of the examples they are working fine, but when i upload the deauther program firstly i cannot find the ap and i get the full signal in other network which is hidden but when i try to connect it fails.

**Comment by spacehuhn** [comment]
If debug is set to true, you should see all information you need in the serial monitor, the SSID, the password and if it's hidden.

**Comment by whyAllUsernamesAreTaken** [comment]
Ok i will share the debug report after checking, thanks.

**Comment by whyAllUsernamesAreTaken** [comment]
The  language in the serial monitor is not understandable.

**Comment by N0vaPixel** [comment]
Set the baud rate to 115200

**Comment by whyAllUsernamesAreTaken** [comment]
yes it is 115200, should i try with 9600?

**Comment by N0vaPixel** [comment]
Normaly not. The unreadable text is contained on one or multiple lines ?

**Comment by whyAllUsernamesAreTaken** [comment]
when i used the 9600 baud rate the symbols on serial monitor keeps on increasing and the led on the board is on. What to do next ?
![capture](https://cloud.githubusercontent.com/assets/24974583/23717936/c90f2a96-045b-11e7-98d0-176ab556d90f.JPG)

**Comment by spacehuhn** [comment]
Set the baud rate to 115200 and show us the log.

**Comment by whyAllUsernamesAreTaken** [comment]
![capture](https://cloud.githubusercontent.com/assets/24974583/23718725/aa876464-045e-11e7-8177-232eb4781804.JPG)

**Comment by N0vaPixel** [comment]
![aa876464-045e-11e7-8177-232eb4781804](https://cloud.githubusercontent.com/assets/13287666/23719140/768edf44-043a-11e7-98e9-eb583902da9d.JPG)

**Comment by N0vaPixel** [comment]
And you restarted the esp ?

**Comment by whyAllUsernamesAreTaken** [comment]
yes now i got it. But i am not getting the ap while i am scanning
andthe ap is not named as pwned.
![capture](https://cloud.githubusercontent.com/assets/24974583/23719282/c4746550-0460-11e7-960d-e3c3636727a6.JPG)

**Comment by N0vaPixel** [comment]
The AP while scanning ? You are trying to connect to your esp AP ?

**Comment by whyAllUsernamesAreTaken** [comment]
The ap is hidden but i have not set the ssidHidden to true how is that possible ?
I have connected to the ap it was hidden.

**Comment by whyAllUsernamesAreTaken** [comment]
I was not getting my esp AP. It was hidden by default but i don't know how?

**Comment by N0vaPixel** [comment]
Just understood ^^ When you said scan for AP i thought this was to find target AP

**Comment by N0vaPixel** [comment]
You may have downloaded an older version of the soft. Because the settings structure in eeprom memory has changed, the old one may have Interfered the current soft

**Comment by whyAllUsernamesAreTaken** [comment]
How can i solve this brother?

**Comment by N0vaPixel** [comment]
do you know how to connect to hidden networks ?

**Comment by whyAllUsernamesAreTaken** [comment]
Yes. Well i can change the setting on the browser for my esp.

**Comment by whyAllUsernamesAreTaken** [comment]
Now you can remove the bug label from this issue as the problem is solved, Thanks again brother.

**Comment by N0vaPixel** [comment]
Good news. Now you can try all the features, see how the soft works ect... Have fun 👍
