### ISSUE TITLE
Ssid name won't change

### ISSUE THREAD

**Issue by yippiez** [spacehuhn/esp8266_deauther#930]
i flashed my wemos d1 mini using Arduino Ide (version 1.6). pwned shows up and everything works fine but i forgot the change the name and the password. Then i changed the password and the name in settings.cpp and flashed it again, but it still shows as pwned. Do i need to clean the wemos first if so how?

**Comment by spacehuhn** [comment]
Why don't you just change the settings over the web interface?

**Comment by yippiez** [comment]
didn't know i could thanks.
