### ISSUE TITLE
Question on the deauther.

### ISSUE THREAD

**Issue by TecTom101** [spacehuhn/esp8266_deauther#934]
So there used to be a spot to scan for devices on the selected network and then you could specifically boot them off from the network and I was really planning on using that feature around the house but I can't seem to find that feature or don't know what it looks like now and I was just wondering if it was removed or if the name was just changed or it's hidden somewhere.

**Comment by spacehuhn** [comment]
If I understand you correctly, you want to scan for stations (which are the client devices). It's on the scan page together with the APs.
It is still there 😉

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
