### ISSUE TITLE
Death : Auto Change Channels

### ISSUE THREAD

**Issue by avcvv** [spacehuhn/esp8266_deauther#942]
Hi, explain me please one moment, my victim always changing a channels when deauth are started, how to make that would attacking  AP will attach victim AP on rndom channels

**Comment by v0rtex77** [comment]
bump
I am also interested to know if deauther can lock on a bssid and hop channels

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
