### ISSUE TITLE
No response from esp-01 and no pwned network

### ISSUE THREAD

**Issue by MauroB3** [spacehuhn/esp8266_deauther#946]
Hi, I'm trying to get this work on my esp-01 (1MB, the one of the picture below), but it doesn't seems to work. When I finish to upload the code, I have no pwned network and I have no response from serial monitor. Am I doing something wrong? Or maybe my esp is broken?

 I tried flashing the .bin file (I tried with versions 2.0.5, 1.1 and 1.2, with the same results) using esptool (on linux) and es8266_flasher (on windows) with no errors. I tried too using Arduino Ide (uploading uploading both esp8266_deauther and Reset_Sketch) and again, I have no error messages.

esp8266-01 module:
![esp8266-01](https://user-images.githubusercontent.com/42558260/45273215-ed52a080-b487-11e8-919b-1a79e70020ad.jpg)

Arduino config:
![config](https://user-images.githubusercontent.com/42558260/45273222-f5124500-b487-11e8-8803-148801dc080c.jpg)

I'm connecting esp to pc using a usb serial port, this one:
![ftdi-usb-serial-port-adapter](https://user-images.githubusercontent.com/42558260/45273395-f4c67980-b488-11e8-854e-579709dfff5d.jpg)

Thank you for any help.

**Comment by FirstPure** [comment]
Board: ESP8266
CPU Frequancy: 80
Reset Method: ck

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
