### ISSUE TITLE
ERROR esp8266 after the firmware is not present in the list of wi fi

### ISSUE THREAD

**Issue by thegekagamer** [spacehuhn/esp8266_deauther#949]
Prompt bought the esp8266 module, wanted to put on it Wi Fi-deather
WiFi-jammer. First, the program found modular .bin file did not want to put esp8266, with a hundredth attempt turned out, but for some reason esp8266 ceased to see in the lists of WiFi. What to do?

**Comment by spacehuhn** [comment]
![nojammer](https://user-images.githubusercontent.com/3826044/47010325-f0077c00-d13e-11e8-9a24-c88d0eee8c7b.jpg)

https://github.com/spacehuhn/esp8266_deauther/wiki/Installation

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
