### ISSUE TITLE
ESP8266 Nodemcu not responding at all after flash ver 2.0.5 by arduino

### ISSUE THREAD

**Issue by trngkn** [spacehuhn/esp8266_deauther#951]
I have an ESP8266 Nodemcu 1.0. I flashed it with Deauther ver 2.0.5 by Arduino but i selected DSTIKE at  Tool --> Board  and after that it seem dead, cant detected by my pc and led isn't blink when i connect with cable. How can i fix this?? 

p/s: sr about my Eng, i'm just know a little

**Comment by huangwenweia** [comment]
Metoo，my deauther also brick

**Comment by MrJabu** [comment]
did you try running the reset sketch and uploading the program again?

**Comment by trngkn** [comment]
@MrJabu right now, my esp8266 can't recognize by pc so i can't run reset sketch :<

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.

**Comment by Raidr1212** [comment]
I am experiencing the same issue
