### ISSUE TITLE
Help with OLED and NodeMCU/Wemos D1

### ISSUE THREAD

**Issue by MrJabu** [spacehuhn/esp8266_deauther#954]
I cannot for the life of me get the 1306 i2c OLED working at all. I changed to #define USE_DISPLAY true but nothing happens. i ran the Adafruit 1306 example and the screen works fine.

is there anything else i need to change?

**Comment by MrJabu** [comment]
got it working..

**Comment by Fede-26** [comment]
how have you got working?
