### ISSUE TITLE
ERROR: loading file: run?cmd=save names with Version 2.0.5 on Arduino 1.8.7

### ISSUE THREAD

**Issue by KotamRamana** [spacehuhn/esp8266_deauther#958]
Using arduino code from esp8266_deauther-2.0.5.zip and compling from Arduino 1.8.7 with json version 5.13.2 only. 

Note: Version 6.0 and above json function has some depreciated methods.

Once login into web portal.I get this ERROR: timeout loading file run?cmd=scan aps -ch all.
Once Press button scan station this 	ERROR1: timeout loading file run?cmd=scan stations -t 15s -ch all
			                                ERROR2: loading file: settings.json
			                                ERROR3: loading file: run?cmd=save settings

**Comment by spacehuhn** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#timeout-error

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
