### ISSUE TITLE
ESP8266_Deauther_v2.0.5_4MB Missing files ncsi.txt & success.txt

### ISSUE THREAD

**Issue by KotamRamana** [spacehuhn/esp8266_deauther#959]
Used ESP8266Flasher alongwith ESP8266_Deauther_v2.0.5_4MB.bin on 8266 nodemcu v1. 

Using arduino 1.8.7 Serial monitor to check error log.

1)When logged into webpage this error msg is displayed "Error: timeout loading file lang/en.lang"
	
Web page clicked scan AP command:
   Serial consoleoutput: Executing /autostart.txt
			            Done executing script
			             [AP] request: /ncsi.txt NOT FOUND
			             [AP] request: /ncsi.txt NOT FOUND
			             [AP] request: /ncsi.txt NOT FOUND
			             [AP] request: /ncsi.txt NOT FOUND
			             [AP] request: /success.txt NOT FOUND
			             [AP] request: /success.txt NOT FOUND
			             [AP] request: /success.txt NOT FOUND
			             [AP] request: /success.txt NOT FOUND
			            [AP] request: /pki/crl/products/CodeSignPCA2.crl NOT FOUND
   Web page error : ERROR: timeout loading file run?cmd=scan aps -ch all
               next time: ERROR: timeout loading file run?cmd=save names
			   
   second execution console error:  
			       # scan aps  -ch all
				Stopped scan
				Scan results saved in /scan.json
				Removed all APs
				Cleared station list
				Starting scan for access points (Wi-Fi networks)...
				[===== Access Points =====]
				ID SSID                             Name             Ch RSSI Enc. Mac               Vendor   Selected

				Exception (28):
				epc1=0x402102b9 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

				ctx: cont 
				sp: 3fff1810 end: 3fff1bf0 offset: 01a0

				>>>stack>>>
				3fff19b0:  3fff1a1c 3fff1a10 00000006 4022a164  
				3fff19c0:  40106970 3fff1a60 3fff1a60 40211a78  
				3fff19d0:  00000000 ffffffff 3fff1a00 00000001  
				3fff19e0:  3fff6390 40226aca 00000000 40211a38  
				3fff19f0:  3fff3460 3fff07c8 00000000 402104f9  
				3fff1a00:  3fff63a0 00000020 40210300 402102b0  
				3fff1a10:  3fff6f90 3fff07a4 00000001 402074b1  
				3fff1a20:  3fff1a40 3fff07a4 00000001 00000000  
				3fff1a30:  00000001 3fff07c8 3fff1a90 402107b0  
				3fff1a40:  3ffe0020 3fff07a4 3fff1a90 40207679  
				3fff1a50:  3ffe922c 3fff07a4 00000001 402078ef  
				3fff1a60:  3fff6510 0000002f 00000021 3fff6480  
				3fff1a70:  0000000f 00000008 3fff6380 0000000f  
				3fff1a80:  00000001 3fff6360 0000000f 00000001  
				3fff1a90:  3fff63a0 0000000f 00000007 3fff64a0  
				3fff1aa0:  0000000f 00000000 00000001 4020740d  
				3fff1ab0:  3fff0af8 0000001a 3fff0af8 00000000  
				3fff1ac0:  00000000 3fff07a4 00000001 40207b59  
				3fff1ad0:  00000009 0000000a 3fff07a4 00000001  
				3fff1ae0:  3fff07a4 0000000a 00000001 40207bc2  
				3fff1af0:  00000000 3fff34e0 3fff07a4 40207254  
				3fff1b00:  3fff6360 3fffdc20 402070e8 3fff0764  
				3fff1b10:  000000ff 0000000a 3fff07a4 40214c66  
				3fff1b20:  00000000 00000000 3fff0bd0 3fff0af8  
				3fff1b30:  3fffdc20 3fff0bbc 40226bf4 3fff0bd0  
				3fff1b40:  3fff6e88 3fff2b34 00000005 40226c68  
				3fff1b50:  000001cf 00000000 3fff2b10 40226cac  
				3fff1b60:  00000001 3ffef9d0 3fff3760 40226234  
				3fff1b70:  40106970 3ffef9b4 3fff061c 402193fa  
				3fff1b80:  3fffdc20 00000021 3ffef9b4 40225355  
				3fff1b90:  00000000 3fff3660 3fff085c 402093c1  
				3fff1ba0:  3fffdc20 3ffef95c 3fff0bb5 3fff0bbc  
				3fff1bb0:  3fffdc20 3ffef95c 3fff0bb5 4021eb08  
				3fff1bc0:  40226c15 00000000 00000000 3fff0bbc  
				3fff1bd0:  3fffdc20 00000000 3fff0bb5 40226c3d  
				3fff1be0:  00000000 00000000 3fff0bd0 40100114  
				<<<stack<<<

				 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

				load 0x4010f000, len 1264, room 16 
				tail 0
				chksum 0x42
				csum 0x42
				~ld

				Mounting SPIFFS...OK
				Switched to Channel 1
				Settings loaded from /settings.json
				Settings saved in /settings.json
				Device names loaded from /names.json
				SSIDs loaded from /ssids.json
				Scan results saved in /scan.json
				Serial interface enabled
				Started AP
				[WiFi] Path: '/web', Mode: 'AP', SSID: 'pwned', password: 'deauther', channel: '1', hidden: false, captive-portal: true
				STARTED! \o/
				v2.0.5
				Executing /autostart.txt
				Done executing script

Error3: Save setting page
     Console log: # save settings
				[AP] request: /settings.json  OK
				[AP] request: /settings.json  OK
				[AP] request: /pki/crl/products/WinPCA.crl NOT FOUND

**Comment by spacehuhn** [comment]
The not-found message pops up in the serial command line interface on versions 2.0.0 - 2.0.6.
It tells you that a file was requested by the client, that couldn't be found in the ESP8266 memory.
This usually occurs because client devices want to check whether or not the network has a connection to the internet.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
