### ISSUE TITLE
v2.1.0 menu font size not set correctly after clock screen

### ISSUE THREAD

**Issue by Daedelos** [spacehuhn/esp8266_deauther#961]
Pressing BUTTON_B on clock screen (large font) returns to prior screen but does not reset the font to the smaller size used on the menu. 
i.e. the menu is now displayed using the (too large) font of the clock display.

**Comment by spacehuhn** [comment]
Thanks for the fast error report. I pushed the necessary changes, please test if the error persits.

**Comment by Daedelos** [comment]
All sorted - many thanks :)
