### ISSUE TITLE
v2.1.0 - Station mac's not scrolling left/right

### ISSUE THREAD

**Issue by Daedelos** [spacehuhn/esp8266_deauther#962]
When displaying Stations the mac is not scrolled left & right in order to display the last hex digit that is off the right hand edge of the oled as in the prior release.

**Comment by tobozo** [comment]
Scrolling isn't part of the specs so it's not like it's missing, and another approach to "fix" this could be to use a larger display.

You can still use the serial console or the web console to get the full MAC string anyway :-)

**Comment by Daedelos** [comment]
The previous release (2.0.5/2.0.6) scrolled/moved the Station ssid & mac left right in order to display the full mac
e.g. Microsof:a1:b2:c3:d4 the 4 falls off the end of a 128x64 oled

In order to handle that the previous version moved Microsof:a1:b2:c3:d4 left then right to display the nibble off the screen,

The current version does not have this action. Has this action been removed?

**Comment by tobozo** [comment]
oops I hadn't noticed that, maybe @spacehuhn can make a statement about the disappearance of this feature ?

**Comment by spacehuhn** [comment]
It's not a feature, it's a big (never thought I would say it this way around). Will look into it later.

**Comment by spacehuhn** [comment]
Pushed something, please confirm if the scrolling works for you now 😃

**Comment by Daedelos** [comment]
Looks good - circular scrolling working well. Thanks again.
