### ISSUE TITLE
❗️esp8266 ver. 2.0.5 missing clients

### ISSUE THREAD

**Issue by Proofer3** [spacehuhn/esp8266_deauther#965]
Hi,

I just bought an NodeMCU esp8266 esp-12e WIFI Lolin Module V3 with CH340 chip, i succesfuly instaled the latest version of deauther program with arduino.

Then after i changed the name in the setings on the web from pwned to the name i liked more..  i reconnected and started trying how it works (on my own WIFI network). That is where i got a little confused, in this source video;

https://www.youtube.com/watch?v=oQQhBdCQOTM 

AT 3:17 it shows a "clients" list, in my case, the web version is totaly diffent and only has an option to derauth all devices, beacon and  random beacon. 

So here is my question.. how can i get to the clients list, i have tryed instaling an oldder version (1.2), guessing it would have the feature but no at 192.168.4.1 i get the same interface with no clients, i really want to try to deauther a specific user(for education purpuse, since i have a report on this in tech course lol) I did search the wiki and noticed you said it can be done just oneself has to do it..
Can you please tell me how, i would reall be gratefull if you do so. 😄

Thanks,
Best regards R.

**Comment by spacehuhn** [comment]
The stations/clients page was merged with the names and the access point page into the scan page.

**Comment by Proofer3** [comment]
Thank you, 
So if i understand correctly i must 
1.scan APS 
2.select my network
 3.scan stations
and then i can choose a user attack?
Funnt thing i get an error when i press scan stations

"ERROR: loading file: run?cmd=scan stations -t 15s -ch all"
What do you suggest i do?

I really  appreciate your help :)

**Comment by Proofer3** [comment]
Oh it works now, i forgot it disconnects 

Thaks for the help 🥇
