### ISSUE TITLE
user_interface.h

### ISSUE THREAD

**Issue by Raellbv** [spacehuhn/esp8266_deauther#966]
??  user_interface.h ??
i tray to uploud but missing the the file
===========================================================
Arduino:1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board:"Arduino Yún"

esp8266_deauther:9:30: error: user_interface.h: No such file or directory

compilation terminated.

exit status 1
user_interface.h: No such file or directory
============================================================

**Comment by spacehuhn** [comment]
# You have to select the right board under Tools -> Board as it is explained in the [wiki](https://github.com/spacehuhn/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide)

**Comment by Namya125** [comment]
In file included from C:\Users\Namya Priya\Documents\Arduino\libraries\uMQTTBroker/uMQTTBroker.h:4:0,

from C:\Users\Namya Priya\Documents\Arduino\uMQTTBrokerSampleOOFull\uMQTTBrokerSampleOOFull.ino:9:

C:\Users\Namya Priya\Documents\Arduino\libraries\uMQTTBroker/user_interface.h:37:2: error: #error LWIP_OPEN_SRC must be defined

 #error LWIP_OPEN_SRC must be defined

  ^
I am using esp32 as an mqtt  broker for which I am getting an error as above
how do I rectify this error.

**Comment by tobozo** [comment]
@Namya125 replace your esp32 by an esp8266 and the error should be fixed

**Comment by Namya125** [comment]
> @Namya125 replace your esp32 by an esp8266 and the error should be fixed

is there any other method to rectify this error?

**Comment by tobozo** [comment]
@Namya125 yes you can eventually use an [esp32 as a bridge to an esp8266](https://github.com/tobozo/M5Stack-ESP12-Shield)

**Comment by Namya125** [comment]
@tobozo thank you!! will try it.

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
