### ISSUE TITLE
There is line that longer than maximum casusing error in sourceInsight

### ISSUE THREAD

**Issue by cheng3100** [spacehuhn/esp8266_deauther#967]
When I open the language.h in sourceInsight 4.0, it turn out a error like this:
![default](https://user-images.githubusercontent.com/25582840/47251047-e55f2680-d45f-11e8-83ab-576626aa16f4.png)
It is because the “CLI_CHICKEN_OUTPUT” too long . And it seems may also lead to another bug. So split the line with colons.
Well, It is indeed a “chicken” when I finish :） 

![default](https://user-images.githubusercontent.com/25582840/47251078-aaa9be00-d460-11e8-96b9-f3a2a3c785e6.png)

**Comment by tobozo** [comment]
Closing this issue as merged, feel free to reopen if necessary.
