### ISSUE TITLE
AP selection

### ISSUE THREAD

**Issue by an0n47** [spacehuhn/esp8266_deauther#97]
i can't select more than one ap at a time...  plz help

**Comment by spacehuhn** [comment]
you need to update to the newest version.

**Comment by an0n47** [comment]
maximum packetrate for deauthentication , or best packet rate

**Comment by spacehuhn** [comment]
?

**Comment by an0n47** [comment]
packetrate option (deauthentication) in settings tab . default value is 10. what is the maximum value we can set . or best . thkz for the replay.
