### ISSUE TITLE
Just A Question

### ISSUE THREAD

**Issue by TecTom2003** [spacehuhn/esp8266_deauther#970]
Well I was wondering that if this is running on a 2.4 gh frequency as to “jam” WiFi networks, and since you can scan for stations and deauth specific devices. Does this also “jam” the Bluetooth frequency for the selected device? Thank you!

**Comment by digmorepaka** [comment]
bro sir read wiki sir this not jammer this deauth this send deauth packet sir it only work on wifi

**Comment by jLynx** [comment]
Read the wiki and FAQ before asking a question. Then you won't sound stupid
