### ISSUE TITLE
OLED SSIDs menu not working

### ISSUE THREAD

**Issue by OstenTV** [spacehuhn/esp8266_deauther#973]
I have a DSTRIKE v3.5 (the one with RGB LED), running Deauther v2.0.5.
The menu for selecting SSIDs doesn't open on the OLED interface. If I enable random mode from the WEB interface, I can enter the menu without any problem.

**Comment by elliot-holley** [comment]
Same problem here

**Comment by elliot-holley** [comment]
I have a feeling its something to do with something has to be actually in the menu to open it
just a guess

**Comment by elliot-holley** [comment]
I have a solve!

Go to web interface, type in whatever you like in 'SSID', In the 'Number' selection type '24' (or whatever amount you like) press save and then reboot! for some reason this does not get deleted when the board is rebooted

hopes this solves your problem!

**Comment by tobozo** [comment]
reminder : ssid must be between 8 ans 31 bytes (some unicode letters can use up to 3 bytes) otherwise WiFi won't work as intended

so you can't just type in *whatever you like* in 'SSID'

**Comment by elliot-holley** [comment]
oh

**Comment by OstenTV** [comment]
No.... Lemme explain. The menu won't open when the list is empty. If I go to the WEB interface and add an SSID, it works fine. It has nothing to do with the SSID being too long, as there are none.

**Comment by elliot-holley** [comment]
this is a feature?

**Comment by elliot-holley** [comment]
The problem Isn't really not being able to access the list when there are no SSIDs; the problem is that there dosen't appear to be any way to add a SSID to the list from the display/buttons alone.

**Comment by OstenTV** [comment]
You can add SSIDs from inside the SSIDs menu (at the bottom). But if you can't enter the menu, then there would be no way to add them, so you're kinda right. In the previous version, you were able to enter the menu while the list was empty.

**Comment by elliot-holley** [comment]
![cpthegoodoldays_796907061-0822cc1](https://user-images.githubusercontent.com/30124328/48221978-62a8f780-e38b-11e8-812f-96f954c49892.jpg)
Remember the good ol' days?

**Comment by elliot-holley** [comment]
Don't we all?

Anyway, back on to the main subject of this thread. An easy fix would be to go on to the web interface, just put a space in the SSID name, put the number of SSIDs as 1 and save. in my experience this does not get deleted when I reboot mine. I know it's not permanent, but it should work for the moment, until a proper fix is rolled out by someone with more experience than me in coding.

**Comment by elliot-holley** [comment]
I know that sounds lazy, but I have no experience with coding, apart from python.

**Comment by spacehuhn** [comment]
If you compile the latest version yourself, it should work. 
Might not have been in version 2.0.5. Release of v2.1 is coming soon, so don't worry ;)

**Comment by elliot-holley** [comment]
:)

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
