### ISSUE TITLE
Getting compile error:Please upgrade to ArduinoJson 5!

### ISSUE THREAD

**Issue by ghost** [spacehuhn/esp8266_deauther#974]
I already have ArduinoJson 5 installed!

**Comment by spacehuhn** [comment]
So what you're saying is, that the compiler is lying when it says that you have a newer/older version of ArduinoJson installed?

**Comment by KerbalFun123** [comment]
Yes.

**Comment by jLynx** [comment]
@spacehuhn I think his computer is lying as its trying to take over the world 1 fake upgrade message at a time. Its ok I believe you @KerbalFun123 
![image](https://user-images.githubusercontent.com/4393979/47812587-b32dbd00-ddad-11e8-93cc-bd557aed70c3.png)

**Comment by tobozo** [comment]
Closing this issue as too hilarious, feel free to reopen if necessary.
