### ISSUE TITLE
Is it possible to target specific devices on a network instead of them all?

### ISSUE THREAD

**Issue by RottenDirector** [spacehuhn/esp8266_deauther#977]
Title says it all

**Comment by spacehuhn** [comment]
yes

**Comment by RottenDirector** [comment]
> yes

How?

**Comment by killergeek** [comment]
![mao_rtfm_vectorize_by_cmenghi](https://user-images.githubusercontent.com/7829787/48072327-8bd75580-e1dc-11e8-9297-28d099a10b16.png)
https://github.com/spacehuhn/esp8266_deauther/wiki

**Comment by spacehuhn** [comment]
You scan for stations and select one, or add a device to the name list.

**Comment by jLynx** [comment]
Yes.

**Comment by guoqiyun** [comment]
It seems this was removed from recent versions for some reason. I flashed my board to test it on my mobile. I obviously would not want to target an entire network!
![deauth select removed 2018-11-24](https://user-images.githubusercontent.com/26774814/48969074-7f833300-eff9-11e8-8840-e5a112a48bb9.jpg)

**Comment by spacehuhn** [comment]
Scan for stations and select one, or add a device to the name list.

**Comment by forseenink3238** [comment]
Just capture a WiFi handshake then you will get mac address. Use the mac address to add a device.

**Comment by spacehuhn** [comment]
No need to capture any handshakes... just scan for stations.
