### ISSUE TITLE
Spam WOL packets

### ISSUE THREAD

**Issue by Hammad1029** [spacehuhn/esp8266_deauther#98]
Just like spamming deauth packets, is it possible to spam WOL(wake on lan) packets? add it please # #

**Comment by joneroy** [comment]
@Hammad1029 

It's complicated feature "Spam WOL packets"

**Comment by spacehuhn** [comment]
How should you send wake on lan packets without knowing the mac of the target?

**Comment by Hammad1029** [comment]
by scanning the ap? scanning the ap currently and going on the clients does reveal the client address.

**Comment by spacehuhn** [comment]
yes, avtive devices! ...devices which doens't care about WOL packets you send them.

**Comment by spacehuhn** [comment]
You can't scan for sleeping devices. You'd need to preset the MACs and at this point you'd probably have physical access and don't need to send these packets. I don't see the use for this project.

**Comment by N0vaPixel** [comment]
You're probably talking about "wake on wireless lan"
+ Like @spacehuhn said you need to know your targets
+ WOL packets are often protected
+ Like WOL, to use WOWLAN technology you must be connected to an AP.
Sorry but we can't do anything
Thanks for helping us to find new ideas :)
