### ISSUE TITLE
v2.1.0 bug Settings will not load 

### ISSUE THREAD

**Issue by elliot-holley** [spacehuhn/esp8266_deauther#983]
After the 2.1.0 update (Yay updates!) the settings menu in the web interface will not load. for some reason the serial monitor is responding to any command with intricate streams of gibberish; for instance, I type in 'sysinfo' and the board responds with '⸮⸮⸮⸮⸮⸮⸮⸮⸮z⸮⸮⸮⸮v'. Bizzare. I managed to get the screen to work by changing the A-config tab. Any Ideas?

**Comment by tobozo** [comment]
Closing this issue as using the wrong baud rate in the console isn't a bug, feel free to reopen if necessary.
