### ISSUE TITLE
Concatenates spaces in SSIDs when doing beacon attack

### ISSUE THREAD

**Issue by Cra1gTucker** [spacehuhn/esp8266_deauther#985]
I'm using the deauther on an ESP8266-DevKitC board bought from Espressif official Taobao store.
When sending fake beacon frames the device adds space characters to the SSID.
For example an SSID called "foobar" with WPA in ssid.json should look like
```
["foobar      ​      ​     ",true,6]
```
I've noticed the third element 6 indicates the number of real characters in the SSID, however when sending out beacons the SSID seen on Wi-Fi clients is still `foobar      ​      ​      `with all the extra space characters. It seems that the third element gets ignored when attacking.
I think this could be a bug. Thx for reading.

**Comment by Cra1gTucker** [comment]
Could I ask that if there is a way to just get rid of the blank characters, like if I only want to create one fake AP with the same name?

**Comment by spacehuhn** [comment]
If you're running the latest version (2.1.0), it should do exactly that if you add a single SSID.  
In case you need the .bin files, I'll release them soon.

**Comment by Cra1gTucker** [comment]
Great, that's something I want! Thx!
