### ISSUE TITLE
ESP8266Flasher PROBLEM 

### ISSUE THREAD

**Issue by Keys545** [spacehuhn/esp8266_deauther#986]
**Hello when i try to flash my ESP8266 wit firmware deauther_2.1.0_1mb

i got every time Waiting MAC

log:

Note:Detect serial port changed.

Note:Auto MAP serial port.Port-->COM5

Note:Serial port connected.

Note:Begin find ESP8266.

CAN SOMEONE HELP ?**

**Comment by forseenink3238** [comment]
Go to device manager if using windows and check what port is it and check that the drivers are installed for the specific usb to serial chip.

**Comment by MartieTheSmartie** [comment]
Mine is also waiting for mac, drivers installed...

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.
