### ISSUE TITLE
Typo at usage

### ISSUE THREAD

**Issue by Aaron2550** [spacehuhn/esp8266_deauther#987]
"If you don't see a pwned network, fash the ESP8266 again. See installation for more." `flash` has a typo

->> [https://github.com/spacehuhn/esp8266_deauther/wiki/Web](https://github.com/spacehuhn/esp8266_deauther/wiki/Web)

**Comment by tobozo** [comment]
@Aaron2550 thanks for reporting this, the typo has been corrected

**Comment by Aaron2550** [comment]
@tobozo Theres another one, let me just screenshot it...

**Comment by Aaron2550** [comment]
see [https://drive.google.com/file/d/1eQCHS9lby5uOQDAd3MMkpU2dnfbgnHov/view?usp=sharing](https://drive.google.com/file/d/1eQCHS9lby5uOQDAd3MMkpU2dnfbgnHov/view?usp=sharing)
