### ISSUE TITLE
.bin Releases for flashing with esp8266flasher

### ISSUE THREAD

**Issue by tpmodding** [spacehuhn/esp8266_deauther#99]
Hey guys,

some users are to lazy/stupid to read the readme then they are starting to spam with issues...
So here is a solution for them:
you need two things:
1. ESP8266Flasher
2.the esp8266deauther precompiled binarys

Quick Tut:
I use this with NodeMCU and this settings:
<img width="395" alt="bildschirmfoto 2017-03-07 um 19 05 53" src="https://cloud.githubusercontent.com/assets/17259976/23671193/a9ff717a-036a-11e7-8ecf-ce9fa58a0a2d.png">

If you click upload you can see the path to the .bin where the flash starts...
<img width="930" alt="bildschirmfoto 2017-03-07 um 19 07 30" src="https://cloud.githubusercontent.com/assets/17259976/23671243/c9bb520e-036a-11e7-9a3a-29438ca72db5.png">

then start esp8266flasher and select the .bin
<img width="994" alt="bildschirmfoto 2017-03-07 um 19 10 54" src="https://cloud.githubusercontent.com/assets/17259976/23671464/9f1568b8-036b-11e7-938f-654c5fe411b2.png">

click flash and wait :)
<img width="526" alt="bildschirmfoto 2017-03-07 um 19 13 50" src="https://cloud.githubusercontent.com/assets/17259976/23671483/aff5637c-036b-11e7-9777-b71981b3a3c0.png">

Here is a actuall bin from testing branch, if you want to test...

[esp8266_deauther-testing.bin.zip](https://github.com/spacehuhn/esp8266_deauther/files/825371/esp8266_deauther-testing.bin.zip)

you could tag them with a version number and upload it at as release here
https://github.com/spacehuhn/esp8266_deauther/releases

greetings TP

**Comment by spacehuhn** [comment]
Yes I think we're at a point where this is badly needed! Thanks for the advice.

**Comment by spacehuhn** [comment]
Also solves the 512kb problem. I just create 2 bin files.

**Comment by Splodgie** [comment]
Last comment, Goodbye.

**Comment by N0vaPixel** [comment]
@tpmodding Nice flashing alternative ! Thx

> Last comment, Goodbye.

#32 
Love theres guys like @Splodgie who think that we are their employees. We don't owe you anything.
It's time for you to make things yourself 😄  
So goodbye too

**Comment by spacehuhn** [comment]
WTF I don't understand these people. He deleted every of his posts. Whole conversations here doesn't make sense anymore. This is ridiculous.

**Comment by chinahk** [comment]
saying people lazy stupid for asking question is insult he help me very muc to get program load working he send me here helpme all time.

**Comment by spacehuhn** [comment]
Nobody said he is stupid. This gone a bit off topic here, I think we can close this.

**Comment by FirstPure** [comment]
What a bummer If it was not for Splodgie I would have gave up ages ago, I watched a indian YT video got no help until he offered to walk me through it god did I ask he some questions must have been 50 or more. 
I came here and found he's gone I wonder why, tpmodding  lazy/stupid, N0vaPixel links his post #32  We don't owe you anything.  WTF I don't understand these people. you dont understand anybody but your self.
(at least I have his EMail).
Why dont you make this private so none of us stupid peiople bother you.

**Comment by tpmodding** [comment]
if you have problems, i help you, i show it you, i can explain it you, and if nothing helps, i can connect to your pc via teamviewer and help, if you have problems....

but most of the issues was " 'wifi_send_pkt_freedom' was not declared" that means that those people ar to lazy to do anything and read....the readme shows you step by step what to do...if you follow those steps you DONT get this error...if you have other problems, you are welcome to ask for support...don't get me wrong...i'm even not a coder...but i am able to read first everything, try it, if it dont work, to search in the issues or google, and if then nothing works or ask for support...

they added a new feature, which was explained in the readme what you have to do after those changes...but nobody reads them and say "new testing branch dont work"....no infos why, what he has done, which hardware nothing... and my message was not for a special user or something else...

**Comment by FirstPure** [comment]
I think thats called Back Peddling M8.

**Comment by tpmodding** [comment]
oh no, sure not! its still a solution for lazy/stupid ones who dont want to read the readme and open issues! but enough said now...

**Comment by spacehuhn** [comment]
@FirstPure you, like many others, miss the point that this is no forum. no arduino forum and no espressif support. And this project is not about explaining everyone on this world how the basics of microcontrollers work. We help as much as we can, but most people don't even read the readme correctly or search for similar issues. Also most poeple don't even give us the information needed to get or solve their problem. We don't need to help you, we use our free time to do this project and don't get paid for this! And to comment things like this on an issue where we are clearly helping to make the installation process easier for everyone is very ignorant.

I get that you 're offended by @tpmodding statement, but he has his point. This is not what open source projects and github is for. Get in our position first before blaming us. We are providing more help and a way better readme as most projects. Sorry that it's to complicated for you.
