### ISSUE TITLE
Connection drops on Wifi deauther

### ISSUE THREAD

**Issue by don1406** [spacehuhn/esp8266_deauther#995]
Hi,

I have recently bought a WIFI deauther (USB version), when i connect to it, it is going ok.
I ping the deauther, to see if it is going down or not.
I want to scan a network, or change from the tab "Scan" to "SSID" for example, then i get no ping and only request time out in my terminal, and the deauther doenst respond anymore. 

I have already flashed the deauther 2 times, but still same problem. i used verison 2.0.5

Does anyone know if it is the board or something ?

**Comment by forseenink3238** [comment]
It was happening to me yesterday and my version was 2.0.5 so I flashed it with the new version 2.1.0 before posting an issue

**Comment by don1406** [comment]
If you suggesting that i have to wait a year or so, no thats not an option. Maybe i can try flash it with version 2.1.0. Where did you get the 2.1.0 release ?

**Comment by forseenink3238** [comment]
No not that

**Comment by forseenink3238** [comment]
Should i send iy

**Comment by don1406** [comment]
Hi, 
Thank you for being so helpfull. I have flashed the board with version 2.10.
Hoever, i get allot of error: cant ....script.json errors.. 
Am i the only one ?

**Comment by forseenink3238** [comment]
No it happens to me too

**Comment by forseenink3238** [comment]
can you help me in my issue please?

**Comment by don1406** [comment]
Wich issue ?
