### ISSUE TITLE
Setting the mac of deauther's AP doesn't work

### ISSUE THREAD

**Issue by Daedelos** [spacehuhn/esp8266_deauther#998]
Using the serial interface, issuing 
set macap 00:1d:aa:50:e7:88
on the command line sets the mac of deauther's softAP to the supplied value (confirmed by issuing "get macap")

However this supplied mac value is not used by deauther's  softAP. Scanning for AP's from another device shows the deauther board is still using the esp8266's burnt in (default) mac for its AP and not the 00:1d:aa:50:e7:88 requested.

**Comment by tobozo** [comment]
Closing this issue as rebooting solved it, feel free to reopen if necessary.
