### ISSUE TITLE
no libraries

### ISSUE THREAD

**Issue by russianhackerman** [spacehuhn/esp8266_deauther#999]
cant load url in manual. esp8266 found nothing
![default](https://user-images.githubusercontent.com/38893261/49566767-7583fd00-f934-11e8-97ed-29e573156668.JPG)
![default](https://user-images.githubusercontent.com/38893261/49566768-7583fd00-f934-11e8-92fd-45f1d906730f.JPG)

**Comment by tobozo** [comment]
since you're installing a SDK, and a SDK is not a library, better look in the *boards manager* instead of the library manager.

![image](https://user-images.githubusercontent.com/1893754/49569528-79b01a80-f934-11e8-9ea2-10983f827fbb.png)
